#pragma once
#ifndef QT6ZIG_LIBQT6C_H
#define QT6ZIG_LIBQT6C_H

#include "../src/qtlibc.h"

#include "../src/libqabstractvideobuffer.h"
#include "../src/libqaudio.h"
#include "../src/libqaudiobuffer.h"
#include "../src/libqaudiobufferinput.h"
#include "../src/libqaudiobufferoutput.h"
#include "../src/libqaudiodecoder.h"
#include "../src/libqaudiodevice.h"
#include "../src/libqaudioformat.h"
#include "../src/libqaudioinput.h"
#include "../src/libqaudiooutput.h"
#include "../src/libqaudiosink.h"
#include "../src/libqaudiosource.h"
#include "../src/libqcamera.h"
#include "../src/libqcameradevice.h"
#include "../src/libqcapturablewindow.h"
#include "../src/libqimagecapture.h"
#include "../src/libqmediacapturesession.h"
#include "../src/libqmediadevices.h"
#include "../src/libqmediaformat.h"
#include "../src/libqmediametadata.h"
#include "../src/libqmediaplayer.h"
#include "../src/libqmediarecorder.h"
#include "../src/libqmediatimerange.h"
#include "../src/libqscreencapture.h"
#include "../src/libqsoundeffect.h"
#include "../src/libqtaudio.h"
#include "../src/libqtmultimedia-config.h"
#include "../src/libqtmultimediaexports.h"
#include "../src/libqtmultimediaglobal.h"
#include "../src/libqtmultimediaversion.h"
#include "../src/libqtvideo.h"
#include "../src/libqvideoframe.h"
#include "../src/libqvideoframeformat.h"
#include "../src/libqvideoframeinput.h"
#include "../src/libqvideosink.h"
#include "../src/libqwavedecoder.h"
#include "../src/libqwindowcapture.h"

#endif
