#pragma once
#ifndef QSTRING_H_C_LIB
#define QSTRING_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAnyStringView QAnyStringView;
typedef struct QByteArrayView QByteArrayView;
typedef struct QChar QChar;
typedef struct QRegularExpression QRegularExpression;
typedef struct QRegularExpressionMatch QRegularExpressionMatch;
typedef struct QStringView QStringView;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QString* QString_new();
QString* QString_new2(const QChar* unicode);
QString* QString_new3(QChar* c);
QString* QString_new4(ptrdiff_t size, QChar* c);
QString* QString_new5(QLatin1StringView latin1);
QString* QString_new6(QStringView* sv);
QString* QString_new7(const libqt_string param1);
QString* QString_new8(const char* ch);
QString* QString_new9(const libqt_string a);
QString* QString_new10(ptrdiff_t size, int param2);
QString* QString_new11(const QChar* unicode, ptrdiff_t size);
void QString_OperatorAssign(QString* self, QChar* c);
void QString_OperatorAssign2(QString* self, const libqt_string param1);
void QString_OperatorAssign3(QString* self, QLatin1StringView latin1);
void QString_Swap(QString* self, libqt_string other);
ptrdiff_t QString_MaxSize();
ptrdiff_t QString_Size(const QString* self);
ptrdiff_t QString_Count(const QString* self);
ptrdiff_t QString_Length(const QString* self);
bool QString_IsEmpty(const QString* self);
void QString_Resize(QString* self, ptrdiff_t size);
void QString_Resize2(QString* self, ptrdiff_t size, QChar* fillChar);
void QString_ResizeForOverwrite(QString* self, ptrdiff_t size);
libqt_string QString_Fill(QString* self, QChar* c);
void QString_Truncate(QString* self, ptrdiff_t pos);
void QString_Chop(QString* self, ptrdiff_t n);
libqt_string QString_Slice(QString* self, ptrdiff_t pos);
libqt_string QString_Slice2(QString* self, ptrdiff_t pos, ptrdiff_t n);
ptrdiff_t QString_Capacity(const QString* self);
void QString_Reserve(QString* self, ptrdiff_t size);
void QString_Squeeze(QString* self);
const QChar* QString_Unicode(const QString* self);
QChar* QString_Data(QString* self);
const QChar* QString_Data2(const QString* self);
const QChar* QString_ConstData(const QString* self);
void QString_Detach(QString* self);
bool QString_IsDetached(const QString* self);
bool QString_IsSharedWith(const QString* self, const libqt_string other);
void QString_Clear(QString* self);
QChar* QString_At(const QString* self, ptrdiff_t i);
QChar* QString_OperatorSubscript(const QString* self, ptrdiff_t i);
QChar* QString_OperatorSubscript2(QString* self, ptrdiff_t i);
QChar* QString_Front(const QString* self);
QChar* QString_Front2(QString* self);
QChar* QString_Back(const QString* self);
QChar* QString_Back2(QString* self);
libqt_string QString_Arg(const QString* self, long long a);
libqt_string QString_Arg2(const QString* self, unsigned long long a);
libqt_string QString_Arg3(const QString* self, long a);
libqt_string QString_Arg4(const QString* self, unsigned long a);
libqt_string QString_Arg5(const QString* self, int a);
libqt_string QString_Arg6(const QString* self, unsigned int a);
libqt_string QString_Arg7(const QString* self, int16_t a);
libqt_string QString_Arg8(const QString* self, uint16_t a);
libqt_string QString_Arg9(const QString* self, double a);
libqt_string QString_Arg10(const QString* self, char a);
libqt_string QString_Arg11(const QString* self, QChar* a);
libqt_string QString_Arg12(const QString* self, const libqt_string a);
libqt_string QString_Arg13(const QString* self, QStringView* a);
libqt_string QString_Arg14(const QString* self, QLatin1StringView a);
libqt_string QString_Asprintf(const char* format, ... );
ptrdiff_t QString_IndexOf(const QString* self, QChar* c);
ptrdiff_t QString_IndexOf2(const QString* self, QLatin1StringView s);
ptrdiff_t QString_IndexOf3(const QString* self, const libqt_string s);
ptrdiff_t QString_IndexOf4(const QString* self, QStringView* s);
ptrdiff_t QString_LastIndexOf(const QString* self, QChar* c);
ptrdiff_t QString_LastIndexOf2(const QString* self, QChar* c, ptrdiff_t from);
ptrdiff_t QString_LastIndexOf3(const QString* self, QLatin1StringView s);
ptrdiff_t QString_LastIndexOf4(const QString* self, QLatin1StringView s, ptrdiff_t from);
ptrdiff_t QString_LastIndexOf5(const QString* self, const libqt_string s);
ptrdiff_t QString_LastIndexOf6(const QString* self, const libqt_string s, ptrdiff_t from);
ptrdiff_t QString_LastIndexOf7(const QString* self, QStringView* s);
ptrdiff_t QString_LastIndexOf8(const QString* self, QStringView* s, ptrdiff_t from);
bool QString_Contains(const QString* self, QChar* c);
bool QString_Contains2(const QString* self, const libqt_string s);
bool QString_Contains3(const QString* self, QLatin1StringView s);
bool QString_Contains4(const QString* self, QStringView* s);
ptrdiff_t QString_Count2(const QString* self, QChar* c);
ptrdiff_t QString_Count3(const QString* self, const libqt_string s);
ptrdiff_t QString_Count4(const QString* self, QStringView* s);
ptrdiff_t QString_IndexOf5(const QString* self, const QRegularExpression* re);
ptrdiff_t QString_LastIndexOf9(const QString* self, const QRegularExpression* re, ptrdiff_t from);
bool QString_Contains5(const QString* self, const QRegularExpression* re);
ptrdiff_t QString_Count5(const QString* self, const QRegularExpression* re);
libqt_string QString_Section(const QString* self, QChar* sep, ptrdiff_t start);
libqt_string QString_Section2(const QString* self, const libqt_string in_sep, ptrdiff_t start);
libqt_string QString_Section3(const QString* self, const QRegularExpression* re, ptrdiff_t start);
libqt_string QString_Left(const QString* self, ptrdiff_t n);
libqt_string QString_Right(const QString* self, ptrdiff_t n);
libqt_string QString_Mid(const QString* self, ptrdiff_t position);
libqt_string QString_First(const QString* self, ptrdiff_t n);
libqt_string QString_Last(const QString* self, ptrdiff_t n);
libqt_string QString_Sliced(const QString* self, ptrdiff_t pos);
libqt_string QString_Sliced2(const QString* self, ptrdiff_t pos, ptrdiff_t n);
libqt_string QString_Chopped(const QString* self, ptrdiff_t n);
bool QString_StartsWith(const QString* self, const libqt_string s);
bool QString_StartsWith2(const QString* self, QStringView* s);
bool QString_StartsWith3(const QString* self, QLatin1StringView s);
bool QString_StartsWith4(const QString* self, QChar* c);
bool QString_EndsWith(const QString* self, const libqt_string s);
bool QString_EndsWith2(const QString* self, QStringView* s);
bool QString_EndsWith3(const QString* self, QLatin1StringView s);
bool QString_EndsWith4(const QString* self, QChar* c);
bool QString_IsUpper(const QString* self);
bool QString_IsLower(const QString* self);
libqt_string QString_LeftJustified(const QString* self, ptrdiff_t width);
libqt_string QString_RightJustified(const QString* self, ptrdiff_t width);
libqt_string QString_ToLower(const QString* self);
libqt_string QString_ToUpper(const QString* self);
libqt_string QString_ToCaseFolded(const QString* self);
libqt_string QString_Trimmed(const QString* self);
libqt_string QString_Simplified(const QString* self);
libqt_string QString_ToHtmlEscaped(const QString* self);
libqt_string QString_Insert(QString* self, ptrdiff_t i, QChar* c);
libqt_string QString_Insert2(QString* self, ptrdiff_t i, const QChar* uc, ptrdiff_t lenVal);
libqt_string QString_Insert3(QString* self, ptrdiff_t i, const libqt_string s);
libqt_string QString_Insert4(QString* self, ptrdiff_t i, QStringView* v);
libqt_string QString_Insert5(QString* self, ptrdiff_t i, QLatin1StringView s);
libqt_string QString_Insert6(QString* self, ptrdiff_t i, QUtf8StringView s);
libqt_string QString_Append(QString* self, QChar* c);
libqt_string QString_Append2(QString* self, const QChar* uc, ptrdiff_t lenVal);
libqt_string QString_Append3(QString* self, const libqt_string s);
libqt_string QString_Append4(QString* self, QStringView* v);
libqt_string QString_Append5(QString* self, QLatin1StringView s);
libqt_string QString_Append6(QString* self, QUtf8StringView s);
libqt_string QString_Prepend(QString* self, QChar* c);
libqt_string QString_Prepend2(QString* self, const QChar* uc, ptrdiff_t lenVal);
libqt_string QString_Prepend3(QString* self, const libqt_string s);
libqt_string QString_Prepend4(QString* self, QStringView* v);
libqt_string QString_Prepend5(QString* self, QLatin1StringView s);
libqt_string QString_Prepend6(QString* self, QUtf8StringView s);
libqt_string QString_Assign(QString* self, libqt_string s);
libqt_string QString_Assign2(QString* self, ptrdiff_t n, QChar* c);
libqt_string QString_OperatorPlusAssign(QString* self, QChar* c);
libqt_string QString_OperatorPlusAssign2(QString* self, const libqt_string s);
libqt_string QString_OperatorPlusAssign3(QString* self, QStringView* v);
libqt_string QString_OperatorPlusAssign4(QString* self, QLatin1StringView s);
libqt_string QString_OperatorPlusAssign5(QString* self, QUtf8StringView s);
libqt_string QString_Remove(QString* self, ptrdiff_t i, ptrdiff_t lenVal);
libqt_string QString_Remove2(QString* self, QChar* c);
libqt_string QString_Remove3(QString* self, QLatin1StringView s);
libqt_string QString_Remove4(QString* self, const libqt_string s);
libqt_string QString_RemoveAt(QString* self, ptrdiff_t pos);
libqt_string QString_RemoveFirst(QString* self);
libqt_string QString_RemoveLast(QString* self);
libqt_string QString_Replace(QString* self, ptrdiff_t i, ptrdiff_t lenVal, QChar* after);
libqt_string QString_Replace2(QString* self, ptrdiff_t i, ptrdiff_t lenVal, const QChar* s, ptrdiff_t slen);
libqt_string QString_Replace3(QString* self, ptrdiff_t i, ptrdiff_t lenVal, const libqt_string after);
libqt_string QString_Replace4(QString* self, QChar* before, QChar* after);
libqt_string QString_Replace5(QString* self, const QChar* before, ptrdiff_t blen, const QChar* after, ptrdiff_t alen);
libqt_string QString_Replace6(QString* self, QLatin1StringView before, QLatin1StringView after);
libqt_string QString_Replace7(QString* self, QLatin1StringView before, const libqt_string after);
libqt_string QString_Replace8(QString* self, const libqt_string before, QLatin1StringView after);
libqt_string QString_Replace9(QString* self, const libqt_string before, const libqt_string after);
libqt_string QString_Replace10(QString* self, QChar* c, const libqt_string after);
libqt_string QString_Replace11(QString* self, QChar* c, QLatin1StringView after);
libqt_string QString_Replace12(QString* self, const QRegularExpression* re, const libqt_string after);
libqt_string QString_Remove5(QString* self, const QRegularExpression* re);
libqt_list QString_Split(const QString* self, const libqt_string sep);
libqt_list QString_Split2(const QString* self, QChar* sep);
libqt_list QString_Split3(const QString* self, const QRegularExpression* sep);
libqt_string QString_Normalized(const QString* self, int mode);
libqt_string QString_Repeated(const QString* self, ptrdiff_t times);
const uint16_t* QString_Utf16(const QString* self);
libqt_string QString_ToLatin1(const QString* self);
libqt_string QString_ToUtf8(const QString* self);
libqt_string QString_ToLocal8Bit(const QString* self);
libqt_list QString_ToUcs4(const QString* self);
libqt_string QString_FromLatin1(QByteArrayView* ba);
libqt_string QString_FromLatin12(const char* str, ptrdiff_t size);
libqt_string QString_FromUtf8(QByteArrayView* utf8);
libqt_string QString_FromUtf82(const char* utf8, ptrdiff_t size);
libqt_string QString_FromLocal8Bit(QByteArrayView* ba);
libqt_string QString_FromLocal8Bit2(const char* str, ptrdiff_t size);
libqt_string QString_FromRawData(const QChar* param1, ptrdiff_t size);
libqt_string QString_FromUtf162(const uint16_t* str);
libqt_string QString_FromUcs42(const unsigned int* str);
libqt_string QString_SetRawData(QString* self, const QChar* unicode, ptrdiff_t size);
libqt_string QString_SetUnicode(QString* self, const QChar* unicode, ptrdiff_t size);
libqt_string QString_SetUtf16(QString* self, const uint16_t* utf16, ptrdiff_t size);
int QString_Compare(const QString* self, const libqt_string s);
int QString_Compare2(const QString* self, QLatin1StringView other);
int QString_Compare3(const QString* self, QStringView* s);
int QString_Compare4(const QString* self, QChar* ch);
int QString_Compare5(const libqt_string s1, const libqt_string s2);
int QString_Compare6(const libqt_string s1, QLatin1StringView s2);
int QString_Compare7(QLatin1StringView s1, const libqt_string s2);
int QString_Compare8(const libqt_string s1, QStringView* s2);
int QString_Compare9(QStringView* s1, const libqt_string s2);
int QString_LocaleAwareCompare(const QString* self, const libqt_string s);
int QString_LocaleAwareCompare2(const QString* self, QStringView* s);
int QString_LocaleAwareCompare3(const libqt_string s1, const libqt_string s2);
int QString_LocaleAwareCompare4(QStringView* s1, QStringView* s2);
int16_t QString_ToShort(const QString* self);
uint16_t QString_ToUShort(const QString* self);
int QString_ToInt(const QString* self);
unsigned int QString_ToUInt(const QString* self);
long QString_ToLong(const QString* self);
unsigned long QString_ToULong(const QString* self);
long long QString_ToLongLong(const QString* self);
unsigned long long QString_ToULongLong(const QString* self);
float QString_ToFloat(const QString* self);
double QString_ToDouble(const QString* self);
libqt_string QString_SetNum(QString* self, int16_t param1);
libqt_string QString_SetNum2(QString* self, uint16_t param1);
libqt_string QString_SetNum3(QString* self, int param1);
libqt_string QString_SetNum4(QString* self, unsigned int param1);
libqt_string QString_SetNum5(QString* self, long param1);
libqt_string QString_SetNum6(QString* self, unsigned long param1);
libqt_string QString_SetNum7(QString* self, long long param1);
libqt_string QString_SetNum8(QString* self, unsigned long long param1);
libqt_string QString_SetNum9(QString* self, float param1);
libqt_string QString_SetNum10(QString* self, double param1);
libqt_string QString_Number(int param1);
libqt_string QString_Number2(unsigned int param1);
libqt_string QString_Number3(long param1);
libqt_string QString_Number4(unsigned long param1);
libqt_string QString_Number5(long long param1);
libqt_string QString_Number6(unsigned long long param1);
libqt_string QString_Number7(double param1);
void QString_OperatorAssign4(QString* self, const char* ch);
void QString_OperatorAssign5(QString* self, const libqt_string a);
libqt_string QString_Prepend7(QString* self, const char* s);
libqt_string QString_Prepend8(QString* self, const libqt_string s);
libqt_string QString_Append7(QString* self, const char* s);
libqt_string QString_Append8(QString* self, const libqt_string s);
libqt_string QString_Insert7(QString* self, ptrdiff_t i, const char* s);
libqt_string QString_Insert8(QString* self, ptrdiff_t i, const libqt_string s);
libqt_string QString_OperatorPlusAssign6(QString* self, const char* s);
libqt_string QString_OperatorPlusAssign7(QString* self, const libqt_string s);
QChar** QString_Begin(QString* self);
const QChar** QString_Begin2(const QString* self);
const QChar** QString_Cbegin(const QString* self);
const QChar** QString_ConstBegin(const QString* self);
QChar** QString_End(QString* self);
const QChar** QString_End2(const QString* self);
const QChar** QString_Cend(const QString* self);
const QChar** QString_ConstEnd(const QString* self);
std::reverse_iterator<QChar *> QString_Rbegin(QString* self);
std::reverse_iterator<QChar *> QString_Rend(QString* self);
std::reverse_iterator<const QChar *> QString_Rbegin2(const QString* self);
std::reverse_iterator<const QChar *> QString_Rend2(const QString* self);
std::reverse_iterator<const QChar *> QString_Crbegin(const QString* self);
std::reverse_iterator<const QChar *> QString_Crend(const QString* self);
void QString_PushBack(QString* self, QChar* c);
void QString_PushBack2(QString* self, const libqt_string s);
void QString_PushFront(QString* self, QChar* c);
void QString_PushFront2(QString* self, const libqt_string s);
void QString_ShrinkToFit(QString* self);
QChar** QString_Erase(QString* self, const QChar** first, const QChar** last);
QChar** QString_Erase2(QString* self, const QChar** it);
ptrdiff_t QString_MaxSize2(const QString* self);
libqt_string QString_FromStdWString(const std::wstring* s);
std::wstring QString_ToStdWString(const QString* self);
libqt_string QString_FromStdU16String(const std::u16string* s);
std::u16string QString_ToStdU16String(const QString* self);
libqt_string QString_FromStdU32String(const std::u32string* s);
std::u32string QString_ToStdU32String(const QString* self);
std::u16string_view QString_OperatorbasicStringView(const QString* self);
bool QString_IsNull(const QString* self);
bool QString_IsRightToLeft(const QString* self);
bool QString_IsValidUtf16(const QString* self);
libqt_string QString_Fill2(QString* self, QChar* c, ptrdiff_t size);
libqt_string QString_Arg22(const QString* self, long long a, int fieldwidth);
libqt_string QString_Arg32(const QString* self, long long a, int fieldwidth, int base);
libqt_string QString_Arg42(const QString* self, long long a, int fieldwidth, int base, QChar* fillChar);
libqt_string QString_Arg23(const QString* self, unsigned long long a, int fieldwidth);
libqt_string QString_Arg33(const QString* self, unsigned long long a, int fieldwidth, int base);
libqt_string QString_Arg43(const QString* self, unsigned long long a, int fieldwidth, int base, QChar* fillChar);
libqt_string QString_Arg24(const QString* self, long a, int fieldwidth);
libqt_string QString_Arg34(const QString* self, long a, int fieldwidth, int base);
libqt_string QString_Arg44(const QString* self, long a, int fieldwidth, int base, QChar* fillChar);
libqt_string QString_Arg25(const QString* self, unsigned long a, int fieldwidth);
libqt_string QString_Arg35(const QString* self, unsigned long a, int fieldwidth, int base);
libqt_string QString_Arg45(const QString* self, unsigned long a, int fieldwidth, int base, QChar* fillChar);
libqt_string QString_Arg26(const QString* self, int a, int fieldWidth);
libqt_string QString_Arg36(const QString* self, int a, int fieldWidth, int base);
libqt_string QString_Arg46(const QString* self, int a, int fieldWidth, int base, QChar* fillChar);
libqt_string QString_Arg27(const QString* self, unsigned int a, int fieldWidth);
libqt_string QString_Arg37(const QString* self, unsigned int a, int fieldWidth, int base);
libqt_string QString_Arg47(const QString* self, unsigned int a, int fieldWidth, int base, QChar* fillChar);
libqt_string QString_Arg28(const QString* self, int16_t a, int fieldWidth);
libqt_string QString_Arg38(const QString* self, int16_t a, int fieldWidth, int base);
libqt_string QString_Arg48(const QString* self, int16_t a, int fieldWidth, int base, QChar* fillChar);
libqt_string QString_Arg29(const QString* self, uint16_t a, int fieldWidth);
libqt_string QString_Arg39(const QString* self, uint16_t a, int fieldWidth, int base);
libqt_string QString_Arg49(const QString* self, uint16_t a, int fieldWidth, int base, QChar* fillChar);
libqt_string QString_Arg210(const QString* self, double a, int fieldWidth);
libqt_string QString_Arg310(const QString* self, double a, int fieldWidth, char format);
libqt_string QString_Arg410(const QString* self, double a, int fieldWidth, char format, int precision);
libqt_string QString_Arg52(const QString* self, double a, int fieldWidth, char format, int precision, QChar* fillChar);
libqt_string QString_Arg211(const QString* self, char a, int fieldWidth);
libqt_string QString_Arg311(const QString* self, char a, int fieldWidth, QChar* fillChar);
libqt_string QString_Arg212(const QString* self, QChar* a, int fieldWidth);
libqt_string QString_Arg312(const QString* self, QChar* a, int fieldWidth, QChar* fillChar);
libqt_string QString_Arg213(const QString* self, const libqt_string a, int fieldWidth);
libqt_string QString_Arg313(const QString* self, const libqt_string a, int fieldWidth, QChar* fillChar);
libqt_string QString_Arg214(const QString* self, QStringView* a, int fieldWidth);
libqt_string QString_Arg314(const QString* self, QStringView* a, int fieldWidth, QChar* fillChar);
libqt_string QString_Arg215(const QString* self, QLatin1StringView a, int fieldWidth);
libqt_string QString_Arg315(const QString* self, QLatin1StringView a, int fieldWidth, QChar* fillChar);
ptrdiff_t QString_IndexOf22(const QString* self, QChar* c, ptrdiff_t from);
ptrdiff_t QString_IndexOf32(const QString* self, QChar* c, ptrdiff_t from, int cs);
ptrdiff_t QString_IndexOf23(const QString* self, QLatin1StringView s, ptrdiff_t from);
ptrdiff_t QString_IndexOf33(const QString* self, QLatin1StringView s, ptrdiff_t from, int cs);
ptrdiff_t QString_IndexOf24(const QString* self, const libqt_string s, ptrdiff_t from);
ptrdiff_t QString_IndexOf34(const QString* self, const libqt_string s, ptrdiff_t from, int cs);
ptrdiff_t QString_IndexOf25(const QString* self, QStringView* s, ptrdiff_t from);
ptrdiff_t QString_IndexOf35(const QString* self, QStringView* s, ptrdiff_t from, int cs);
ptrdiff_t QString_LastIndexOf22(const QString* self, QChar* c, int cs);
ptrdiff_t QString_LastIndexOf32(const QString* self, QChar* c, ptrdiff_t from, int cs);
ptrdiff_t QString_LastIndexOf23(const QString* self, QLatin1StringView s, int cs);
ptrdiff_t QString_LastIndexOf33(const QString* self, QLatin1StringView s, ptrdiff_t from, int cs);
ptrdiff_t QString_LastIndexOf24(const QString* self, const libqt_string s, int cs);
ptrdiff_t QString_LastIndexOf34(const QString* self, const libqt_string s, ptrdiff_t from, int cs);
ptrdiff_t QString_LastIndexOf25(const QString* self, QStringView* s, int cs);
ptrdiff_t QString_LastIndexOf35(const QString* self, QStringView* s, ptrdiff_t from, int cs);
bool QString_Contains22(const QString* self, QChar* c, int cs);
bool QString_Contains23(const QString* self, const libqt_string s, int cs);
bool QString_Contains24(const QString* self, QLatin1StringView s, int cs);
bool QString_Contains25(const QString* self, QStringView* s, int cs);
ptrdiff_t QString_Count22(const QString* self, QChar* c, int cs);
ptrdiff_t QString_Count23(const QString* self, const libqt_string s, int cs);
ptrdiff_t QString_Count24(const QString* self, QStringView* s, int cs);
ptrdiff_t QString_IndexOf26(const QString* self, const QRegularExpression* re, ptrdiff_t from);
ptrdiff_t QString_IndexOf36(const QString* self, const QRegularExpression* re, ptrdiff_t from, QRegularExpressionMatch* rmatch);
ptrdiff_t QString_LastIndexOf36(const QString* self, const QRegularExpression* re, ptrdiff_t from, QRegularExpressionMatch* rmatch);
bool QString_Contains26(const QString* self, const QRegularExpression* re, QRegularExpressionMatch* rmatch);
libqt_string QString_Section32(const QString* self, QChar* sep, ptrdiff_t start, ptrdiff_t end);
libqt_string QString_Section4(const QString* self, QChar* sep, ptrdiff_t start, ptrdiff_t end, int flags);
libqt_string QString_Section33(const QString* self, const libqt_string in_sep, ptrdiff_t start, ptrdiff_t end);
libqt_string QString_Section42(const QString* self, const libqt_string in_sep, ptrdiff_t start, ptrdiff_t end, int flags);
libqt_string QString_Section34(const QString* self, const QRegularExpression* re, ptrdiff_t start, ptrdiff_t end);
libqt_string QString_Section43(const QString* self, const QRegularExpression* re, ptrdiff_t start, ptrdiff_t end, int flags);
libqt_string QString_Mid2(const QString* self, ptrdiff_t position, ptrdiff_t n);
bool QString_StartsWith22(const QString* self, const libqt_string s, int cs);
bool QString_StartsWith23(const QString* self, QStringView* s, int cs);
bool QString_StartsWith24(const QString* self, QLatin1StringView s, int cs);
bool QString_StartsWith25(const QString* self, QChar* c, int cs);
bool QString_EndsWith22(const QString* self, const libqt_string s, int cs);
bool QString_EndsWith23(const QString* self, QStringView* s, int cs);
bool QString_EndsWith24(const QString* self, QLatin1StringView s, int cs);
bool QString_EndsWith25(const QString* self, QChar* c, int cs);
libqt_string QString_LeftJustified2(const QString* self, ptrdiff_t width, QChar* fill);
libqt_string QString_LeftJustified3(const QString* self, ptrdiff_t width, QChar* fill, bool trunc);
libqt_string QString_RightJustified2(const QString* self, ptrdiff_t width, QChar* fill);
libqt_string QString_RightJustified3(const QString* self, ptrdiff_t width, QChar* fill, bool trunc);
libqt_string QString_Remove22(QString* self, QChar* c, int cs);
libqt_string QString_Remove23(QString* self, QLatin1StringView s, int cs);
libqt_string QString_Remove24(QString* self, const libqt_string s, int cs);
libqt_string QString_Replace32(QString* self, QChar* before, QChar* after, int cs);
libqt_string QString_Replace52(QString* self, const QChar* before, ptrdiff_t blen, const QChar* after, ptrdiff_t alen, int cs);
libqt_string QString_Replace33(QString* self, QLatin1StringView before, QLatin1StringView after, int cs);
libqt_string QString_Replace34(QString* self, QLatin1StringView before, const libqt_string after, int cs);
libqt_string QString_Replace35(QString* self, const libqt_string before, QLatin1StringView after, int cs);
libqt_string QString_Replace36(QString* self, const libqt_string before, const libqt_string after, int cs);
libqt_string QString_Replace37(QString* self, QChar* c, const libqt_string after, int cs);
libqt_string QString_Replace38(QString* self, QChar* c, QLatin1StringView after, int cs);
libqt_list QString_Split22(const QString* self, const libqt_string sep, int behavior);
libqt_list QString_Split32(const QString* self, const libqt_string sep, int behavior, int cs);
libqt_list QString_Split23(const QString* self, QChar* sep, int behavior);
libqt_list QString_Split33(const QString* self, QChar* sep, int behavior, int cs);
libqt_list QString_Split24(const QString* self, const QRegularExpression* sep, int behavior);
libqt_string QString_Normalized2(const QString* self, int mode, int version);
libqt_string QString_FromUtf1623(const uint16_t* str, ptrdiff_t size);
libqt_string QString_FromUcs423(const unsigned int* str, ptrdiff_t size);
int QString_Compare22(const QString* self, const libqt_string s, int cs);
int QString_Compare23(const QString* self, QLatin1StringView other, int cs);
int QString_Compare24(const QString* self, QStringView* s, int cs);
int QString_Compare25(const QString* self, QChar* ch, int cs);
int QString_Compare32(const libqt_string s1, const libqt_string s2, int cs);
int QString_Compare33(const libqt_string s1, QLatin1StringView s2, int cs);
int QString_Compare34(QLatin1StringView s1, const libqt_string s2, int cs);
int QString_Compare35(const libqt_string s1, QStringView* s2, int cs);
int QString_Compare36(QStringView* s1, const libqt_string s2, int cs);
int16_t QString_ToShort1(const QString* self, bool* ok);
int16_t QString_ToShort2(const QString* self, bool* ok, int base);
uint16_t QString_ToUShort1(const QString* self, bool* ok);
uint16_t QString_ToUShort2(const QString* self, bool* ok, int base);
int QString_ToInt1(const QString* self, bool* ok);
int QString_ToInt2(const QString* self, bool* ok, int base);
unsigned int QString_ToUInt1(const QString* self, bool* ok);
unsigned int QString_ToUInt2(const QString* self, bool* ok, int base);
long QString_ToLong1(const QString* self, bool* ok);
long QString_ToLong2(const QString* self, bool* ok, int base);
unsigned long QString_ToULong1(const QString* self, bool* ok);
unsigned long QString_ToULong2(const QString* self, bool* ok, int base);
long long QString_ToLongLong1(const QString* self, bool* ok);
long long QString_ToLongLong2(const QString* self, bool* ok, int base);
unsigned long long QString_ToULongLong1(const QString* self, bool* ok);
unsigned long long QString_ToULongLong2(const QString* self, bool* ok, int base);
float QString_ToFloat1(const QString* self, bool* ok);
double QString_ToDouble1(const QString* self, bool* ok);
libqt_string QString_SetNum22(QString* self, int16_t param1, int base);
libqt_string QString_SetNum23(QString* self, uint16_t param1, int base);
libqt_string QString_SetNum24(QString* self, int param1, int base);
libqt_string QString_SetNum25(QString* self, unsigned int param1, int base);
libqt_string QString_SetNum26(QString* self, long param1, int base);
libqt_string QString_SetNum27(QString* self, unsigned long param1, int base);
libqt_string QString_SetNum28(QString* self, long long param1, int base);
libqt_string QString_SetNum29(QString* self, unsigned long long param1, int base);
libqt_string QString_SetNum210(QString* self, float param1, char format);
libqt_string QString_SetNum32(QString* self, float param1, char format, int precision);
libqt_string QString_SetNum211(QString* self, double param1, char format);
libqt_string QString_SetNum33(QString* self, double param1, char format, int precision);
libqt_string QString_Number22(int param1, int base);
libqt_string QString_Number23(unsigned int param1, int base);
libqt_string QString_Number24(long param1, int base);
libqt_string QString_Number25(unsigned long param1, int base);
libqt_string QString_Number26(long long param1, int base);
libqt_string QString_Number27(unsigned long long param1, int base);
libqt_string QString_Number28(double param1, char format);
libqt_string QString_Number32(double param1, char format, int precision);
void QString_Delete(QString* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
