#pragma once
#ifndef QABSTRACTITEMMODEL_H_C_LIB
#define QABSTRACTITEMMODEL_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractListModel QAbstractListModel;
typedef struct QAbstractTableModel QAbstractTableModel;
typedef struct QDataStream QDataStream;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QModelRoleData QModelRoleData;
typedef struct QModelRoleDataSpan QModelRoleDataSpan;
typedef struct QObject QObject;
typedef struct QPersistentModelIndex QPersistentModelIndex;
typedef struct QSize QSize;
typedef struct QVariant QVariant;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QModelRoleData* QModelRoleData_new(int role);
int QModelRoleData_Role(const QModelRoleData* self);
QVariant* QModelRoleData_Data(QModelRoleData* self);
const QVariant* QModelRoleData_Data2(const QModelRoleData* self);
void QModelRoleData_ClearData(QModelRoleData* self);
void QModelRoleData_OperatorAssign(QModelRoleData* self, const QModelRoleData* param1);
void QModelRoleData_Delete(QModelRoleData* self);

QModelRoleDataSpan* QModelRoleDataSpan_new(const QModelRoleDataSpan* other);
QModelRoleDataSpan* QModelRoleDataSpan_new2(QModelRoleDataSpan* other);
QModelRoleDataSpan* QModelRoleDataSpan_new3();
QModelRoleDataSpan* QModelRoleDataSpan_new4(QModelRoleData* modelRoleData);
QModelRoleDataSpan* QModelRoleDataSpan_new5(QModelRoleData* modelRoleData, ptrdiff_t lenVal);
QModelRoleDataSpan* QModelRoleDataSpan_new6(const QModelRoleDataSpan* param1);
void QModelRoleDataSpan_CopyAssign(QModelRoleDataSpan* self, QModelRoleDataSpan* other);
void QModelRoleDataSpan_MoveAssign(QModelRoleDataSpan* self, QModelRoleDataSpan* other);
ptrdiff_t QModelRoleDataSpan_Size(const QModelRoleDataSpan* self);
ptrdiff_t QModelRoleDataSpan_Length(const QModelRoleDataSpan* self);
QModelRoleData* QModelRoleDataSpan_Data(const QModelRoleDataSpan* self);
QModelRoleData* QModelRoleDataSpan_Begin(const QModelRoleDataSpan* self);
QModelRoleData* QModelRoleDataSpan_End(const QModelRoleDataSpan* self);
QModelRoleData* QModelRoleDataSpan_OperatorSubscript(const QModelRoleDataSpan* self, ptrdiff_t index);
QVariant* QModelRoleDataSpan_DataForRole(const QModelRoleDataSpan* self, int role);
void QModelRoleDataSpan_Delete(QModelRoleDataSpan* self);

QModelIndex* QModelIndex_new(const QModelIndex* other);
QModelIndex* QModelIndex_new2(QModelIndex* other);
QModelIndex* QModelIndex_new3();
QModelIndex* QModelIndex_new4(const QModelIndex* param1);
void QModelIndex_CopyAssign(QModelIndex* self, QModelIndex* other);
void QModelIndex_MoveAssign(QModelIndex* self, QModelIndex* other);
int QModelIndex_Row(const QModelIndex* self);
int QModelIndex_Column(const QModelIndex* self);
uintptr_t QModelIndex_InternalId(const QModelIndex* self);
void* QModelIndex_InternalPointer(const QModelIndex* self);
const void* QModelIndex_ConstInternalPointer(const QModelIndex* self);
QModelIndex* QModelIndex_Parent(const QModelIndex* self);
QModelIndex* QModelIndex_Sibling(const QModelIndex* self, int row, int column);
QModelIndex* QModelIndex_SiblingAtColumn(const QModelIndex* self, int column);
QModelIndex* QModelIndex_SiblingAtRow(const QModelIndex* self, int row);
QVariant* QModelIndex_Data(const QModelIndex* self);
void QModelIndex_MultiData(const QModelIndex* self, QModelRoleDataSpan* roleDataSpan);
int QModelIndex_Flags(const QModelIndex* self);
const QAbstractItemModel* QModelIndex_Model(const QModelIndex* self);
bool QModelIndex_IsValid(const QModelIndex* self);
QVariant* QModelIndex_Data1(const QModelIndex* self, int role);
void QModelIndex_Delete(QModelIndex* self);

QPersistentModelIndex* QPersistentModelIndex_new();
QPersistentModelIndex* QPersistentModelIndex_new2(const QModelIndex* index);
QPersistentModelIndex* QPersistentModelIndex_new3(const QPersistentModelIndex* other);
void QPersistentModelIndex_OperatorAssign(QPersistentModelIndex* self, const QPersistentModelIndex* other);
void QPersistentModelIndex_Swap(QPersistentModelIndex* self, QPersistentModelIndex* other);
void QPersistentModelIndex_OperatorAssign2(QPersistentModelIndex* self, const QModelIndex* other);
QModelIndex* QPersistentModelIndex_OperatorQModelIndex(const QPersistentModelIndex* self);
int QPersistentModelIndex_Row(const QPersistentModelIndex* self);
int QPersistentModelIndex_Column(const QPersistentModelIndex* self);
void* QPersistentModelIndex_InternalPointer(const QPersistentModelIndex* self);
const void* QPersistentModelIndex_ConstInternalPointer(const QPersistentModelIndex* self);
uintptr_t QPersistentModelIndex_InternalId(const QPersistentModelIndex* self);
QModelIndex* QPersistentModelIndex_Parent(const QPersistentModelIndex* self);
QModelIndex* QPersistentModelIndex_Sibling(const QPersistentModelIndex* self, int row, int column);
QVariant* QPersistentModelIndex_Data(const QPersistentModelIndex* self);
void QPersistentModelIndex_MultiData(const QPersistentModelIndex* self, QModelRoleDataSpan* roleDataSpan);
int QPersistentModelIndex_Flags(const QPersistentModelIndex* self);
const QAbstractItemModel* QPersistentModelIndex_Model(const QPersistentModelIndex* self);
bool QPersistentModelIndex_IsValid(const QPersistentModelIndex* self);
QVariant* QPersistentModelIndex_Data1(const QPersistentModelIndex* self, int role);
void QPersistentModelIndex_Delete(QPersistentModelIndex* self);

QAbstractItemModel* QAbstractItemModel_new();
QAbstractItemModel* QAbstractItemModel_new2(QObject* parent);
libqt_string QAbstractItemModel_Tr(const char* s);
bool QAbstractItemModel_HasIndex(const QAbstractItemModel* self, int row, int column);
QModelIndex* QAbstractItemModel_Index(const QAbstractItemModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* QAbstractItemModel_Parent(const QAbstractItemModel* self, const QModelIndex* child);
QModelIndex* QAbstractItemModel_Sibling(const QAbstractItemModel* self, int row, int column, const QModelIndex* idx);
int QAbstractItemModel_RowCount(const QAbstractItemModel* self, const QModelIndex* parent);
int QAbstractItemModel_ColumnCount(const QAbstractItemModel* self, const QModelIndex* parent);
bool QAbstractItemModel_HasChildren(const QAbstractItemModel* self, const QModelIndex* parent);
QVariant* QAbstractItemModel_Data(const QAbstractItemModel* self, const QModelIndex* index, int role);
bool QAbstractItemModel_SetData(QAbstractItemModel* self, const QModelIndex* index, const QVariant* value, int role);
QVariant* QAbstractItemModel_HeaderData(const QAbstractItemModel* self, int section, int orientation, int role);
bool QAbstractItemModel_SetHeaderData(QAbstractItemModel* self, int section, int orientation, const QVariant* value, int role);
libqt_map QAbstractItemModel_ItemData(const QAbstractItemModel* self, const QModelIndex* index);
bool QAbstractItemModel_SetItemData(QAbstractItemModel* self, const QModelIndex* index, const libqt_map roles);
bool QAbstractItemModel_ClearItemData(QAbstractItemModel* self, const QModelIndex* index);
libqt_list QAbstractItemModel_MimeTypes(const QAbstractItemModel* self);
QMimeData* QAbstractItemModel_MimeData(const QAbstractItemModel* self, const libqt_list indexes);
bool QAbstractItemModel_CanDropMimeData(const QAbstractItemModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
bool QAbstractItemModel_DropMimeData(QAbstractItemModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
int QAbstractItemModel_SupportedDropActions(const QAbstractItemModel* self);
int QAbstractItemModel_SupportedDragActions(const QAbstractItemModel* self);
bool QAbstractItemModel_InsertRows(QAbstractItemModel* self, int row, int count, const QModelIndex* parent);
bool QAbstractItemModel_InsertColumns(QAbstractItemModel* self, int column, int count, const QModelIndex* parent);
bool QAbstractItemModel_RemoveRows(QAbstractItemModel* self, int row, int count, const QModelIndex* parent);
bool QAbstractItemModel_RemoveColumns(QAbstractItemModel* self, int column, int count, const QModelIndex* parent);
bool QAbstractItemModel_MoveRows(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_MoveColumns(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_InsertRow(QAbstractItemModel* self, int row);
bool QAbstractItemModel_InsertColumn(QAbstractItemModel* self, int column);
bool QAbstractItemModel_RemoveRow(QAbstractItemModel* self, int row);
bool QAbstractItemModel_RemoveColumn(QAbstractItemModel* self, int column);
bool QAbstractItemModel_MoveRow(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceRow, const QModelIndex* destinationParent, int destinationChild);
bool QAbstractItemModel_MoveColumn(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceColumn, const QModelIndex* destinationParent, int destinationChild);
void QAbstractItemModel_FetchMore(QAbstractItemModel* self, const QModelIndex* parent);
bool QAbstractItemModel_CanFetchMore(const QAbstractItemModel* self, const QModelIndex* parent);
int QAbstractItemModel_Flags(const QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_Sort(QAbstractItemModel* self, int column, int order);
QModelIndex* QAbstractItemModel_Buddy(const QAbstractItemModel* self, const QModelIndex* index);
libqt_list QAbstractItemModel_Match(const QAbstractItemModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
QSize* QAbstractItemModel_Span(const QAbstractItemModel* self, const QModelIndex* index);
libqt_map QAbstractItemModel_RoleNames(const QAbstractItemModel* self);
bool QAbstractItemModel_CheckIndex(const QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_MultiData(const QAbstractItemModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void QAbstractItemModel_DataChanged(QAbstractItemModel* self, const QModelIndex* topLeft, const QModelIndex* bottomRight);
void QAbstractItemModel_Connect_DataChanged(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_HeaderDataChanged(QAbstractItemModel* self, int orientation, int first, int last);
void QAbstractItemModel_Connect_HeaderDataChanged(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_LayoutChanged(QAbstractItemModel* self);
void QAbstractItemModel_Connect_LayoutChanged(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_LayoutAboutToBeChanged(QAbstractItemModel* self);
void QAbstractItemModel_Connect_LayoutAboutToBeChanged(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_Submit(QAbstractItemModel* self);
void QAbstractItemModel_Revert(QAbstractItemModel* self);
void QAbstractItemModel_ResetInternalData(QAbstractItemModel* self);
libqt_string QAbstractItemModel_Tr2(const char* s, const char* c);
libqt_string QAbstractItemModel_Tr3(const char* s, const char* c, int n);
bool QAbstractItemModel_HasIndex3(const QAbstractItemModel* self, int row, int column, const QModelIndex* parent);
bool QAbstractItemModel_InsertRow2(QAbstractItemModel* self, int row, const QModelIndex* parent);
bool QAbstractItemModel_InsertColumn2(QAbstractItemModel* self, int column, const QModelIndex* parent);
bool QAbstractItemModel_RemoveRow2(QAbstractItemModel* self, int row, const QModelIndex* parent);
bool QAbstractItemModel_RemoveColumn2(QAbstractItemModel* self, int column, const QModelIndex* parent);
bool QAbstractItemModel_CheckIndex2(const QAbstractItemModel* self, const QModelIndex* index, int options);
void QAbstractItemModel_DataChanged3(QAbstractItemModel* self, const QModelIndex* topLeft, const QModelIndex* bottomRight, const libqt_list roles);
void QAbstractItemModel_Connect_DataChanged3(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_LayoutChanged1(QAbstractItemModel* self, const libqt_list parents);
void QAbstractItemModel_Connect_LayoutChanged1(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_LayoutChanged2(QAbstractItemModel* self, const libqt_list parents, int hint);
void QAbstractItemModel_Connect_LayoutChanged2(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_LayoutAboutToBeChanged1(QAbstractItemModel* self, const libqt_list parents);
void QAbstractItemModel_Connect_LayoutAboutToBeChanged1(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_LayoutAboutToBeChanged2(QAbstractItemModel* self, const libqt_list parents, int hint);
void QAbstractItemModel_Connect_LayoutAboutToBeChanged2(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_OnIndex(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseIndex(const QAbstractItemModel* self, int row, int column, const QModelIndex* parent);
void QAbstractItemModel_OnParent(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseParent(const QAbstractItemModel* self, const QModelIndex* child);
void QAbstractItemModel_OnSibling(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseSibling(const QAbstractItemModel* self, int row, int column, const QModelIndex* idx);
void QAbstractItemModel_OnRowCount(const QAbstractItemModel* self, intptr_t slot);
int QAbstractItemModel_QBaseRowCount(const QAbstractItemModel* self, const QModelIndex* parent);
void QAbstractItemModel_OnColumnCount(const QAbstractItemModel* self, intptr_t slot);
int QAbstractItemModel_QBaseColumnCount(const QAbstractItemModel* self, const QModelIndex* parent);
void QAbstractItemModel_OnHasChildren(const QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseHasChildren(const QAbstractItemModel* self, const QModelIndex* parent);
void QAbstractItemModel_OnData(const QAbstractItemModel* self, intptr_t slot);
QVariant* QAbstractItemModel_QBaseData(const QAbstractItemModel* self, const QModelIndex* index, int role);
void QAbstractItemModel_OnSetData(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseSetData(QAbstractItemModel* self, const QModelIndex* index, const QVariant* value, int role);
void QAbstractItemModel_OnHeaderData(const QAbstractItemModel* self, intptr_t slot);
QVariant* QAbstractItemModel_QBaseHeaderData(const QAbstractItemModel* self, int section, int orientation, int role);
void QAbstractItemModel_OnSetHeaderData(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseSetHeaderData(QAbstractItemModel* self, int section, int orientation, const QVariant* value, int role);
void QAbstractItemModel_OnItemData(const QAbstractItemModel* self, intptr_t slot);
libqt_map QAbstractItemModel_QBaseItemData(const QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_OnSetItemData(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseSetItemData(QAbstractItemModel* self, const QModelIndex* index, const libqt_map roles);
void QAbstractItemModel_OnClearItemData(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseClearItemData(QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_OnMimeTypes(const QAbstractItemModel* self, intptr_t slot);
libqt_list QAbstractItemModel_QBaseMimeTypes(const QAbstractItemModel* self);
void QAbstractItemModel_OnMimeData(const QAbstractItemModel* self, intptr_t slot);
QMimeData* QAbstractItemModel_QBaseMimeData(const QAbstractItemModel* self, const libqt_list indexes);
void QAbstractItemModel_OnCanDropMimeData(const QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseCanDropMimeData(const QAbstractItemModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void QAbstractItemModel_OnDropMimeData(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseDropMimeData(QAbstractItemModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void QAbstractItemModel_OnSupportedDropActions(const QAbstractItemModel* self, intptr_t slot);
int QAbstractItemModel_QBaseSupportedDropActions(const QAbstractItemModel* self);
void QAbstractItemModel_OnSupportedDragActions(const QAbstractItemModel* self, intptr_t slot);
int QAbstractItemModel_QBaseSupportedDragActions(const QAbstractItemModel* self);
void QAbstractItemModel_OnInsertRows(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseInsertRows(QAbstractItemModel* self, int row, int count, const QModelIndex* parent);
void QAbstractItemModel_OnInsertColumns(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseInsertColumns(QAbstractItemModel* self, int column, int count, const QModelIndex* parent);
void QAbstractItemModel_OnRemoveRows(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseRemoveRows(QAbstractItemModel* self, int row, int count, const QModelIndex* parent);
void QAbstractItemModel_OnRemoveColumns(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseRemoveColumns(QAbstractItemModel* self, int column, int count, const QModelIndex* parent);
void QAbstractItemModel_OnMoveRows(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseMoveRows(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
void QAbstractItemModel_OnMoveColumns(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseMoveColumns(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void QAbstractItemModel_OnFetchMore(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseFetchMore(QAbstractItemModel* self, const QModelIndex* parent);
void QAbstractItemModel_OnCanFetchMore(const QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseCanFetchMore(const QAbstractItemModel* self, const QModelIndex* parent);
void QAbstractItemModel_OnFlags(const QAbstractItemModel* self, intptr_t slot);
int QAbstractItemModel_QBaseFlags(const QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_OnSort(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseSort(QAbstractItemModel* self, int column, int order);
void QAbstractItemModel_OnBuddy(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseBuddy(const QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_OnMatch(const QAbstractItemModel* self, intptr_t slot);
libqt_list QAbstractItemModel_QBaseMatch(const QAbstractItemModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
void QAbstractItemModel_OnSpan(const QAbstractItemModel* self, intptr_t slot);
QSize* QAbstractItemModel_QBaseSpan(const QAbstractItemModel* self, const QModelIndex* index);
void QAbstractItemModel_OnRoleNames(const QAbstractItemModel* self, intptr_t slot);
libqt_map QAbstractItemModel_QBaseRoleNames(const QAbstractItemModel* self);
void QAbstractItemModel_OnMultiData(const QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseMultiData(const QAbstractItemModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void QAbstractItemModel_OnSubmit(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseSubmit(QAbstractItemModel* self);
void QAbstractItemModel_OnRevert(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseRevert(QAbstractItemModel* self);
void QAbstractItemModel_OnResetInternalData(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseResetInternalData(QAbstractItemModel* self);
QModelIndex* QAbstractItemModel_CreateIndex(const QAbstractItemModel* self, int row, int column);
void QAbstractItemModel_OnCreateIndex(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseCreateIndex(const QAbstractItemModel* self, int row, int column);
QModelIndex* QAbstractItemModel_CreateIndex2(const QAbstractItemModel* self, int row, int column, uintptr_t id);
void QAbstractItemModel_OnCreateIndex2(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseCreateIndex2(const QAbstractItemModel* self, int row, int column, uintptr_t id);
void QAbstractItemModel_EncodeData(const QAbstractItemModel* self, const libqt_list indexes, QDataStream* stream);
void QAbstractItemModel_OnEncodeData(const QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEncodeData(const QAbstractItemModel* self, const libqt_list indexes, QDataStream* stream);
bool QAbstractItemModel_DecodeData(QAbstractItemModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void QAbstractItemModel_OnDecodeData(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseDecodeData(QAbstractItemModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void QAbstractItemModel_BeginInsertRows(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_OnBeginInsertRows(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseBeginInsertRows(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_EndInsertRows(QAbstractItemModel* self);
void QAbstractItemModel_OnEndInsertRows(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndInsertRows(QAbstractItemModel* self);
void QAbstractItemModel_BeginRemoveRows(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_OnBeginRemoveRows(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseBeginRemoveRows(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_EndRemoveRows(QAbstractItemModel* self);
void QAbstractItemModel_OnEndRemoveRows(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndRemoveRows(QAbstractItemModel* self);
bool QAbstractItemModel_BeginMoveRows(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void QAbstractItemModel_OnBeginMoveRows(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseBeginMoveRows(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void QAbstractItemModel_EndMoveRows(QAbstractItemModel* self);
void QAbstractItemModel_OnEndMoveRows(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndMoveRows(QAbstractItemModel* self);
void QAbstractItemModel_BeginInsertColumns(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_OnBeginInsertColumns(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseBeginInsertColumns(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_EndInsertColumns(QAbstractItemModel* self);
void QAbstractItemModel_OnEndInsertColumns(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndInsertColumns(QAbstractItemModel* self);
void QAbstractItemModel_BeginRemoveColumns(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_OnBeginRemoveColumns(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseBeginRemoveColumns(QAbstractItemModel* self, const QModelIndex* parent, int first, int last);
void QAbstractItemModel_EndRemoveColumns(QAbstractItemModel* self);
void QAbstractItemModel_OnEndRemoveColumns(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndRemoveColumns(QAbstractItemModel* self);
bool QAbstractItemModel_BeginMoveColumns(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void QAbstractItemModel_OnBeginMoveColumns(QAbstractItemModel* self, intptr_t slot);
bool QAbstractItemModel_QBaseBeginMoveColumns(QAbstractItemModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void QAbstractItemModel_EndMoveColumns(QAbstractItemModel* self);
void QAbstractItemModel_OnEndMoveColumns(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndMoveColumns(QAbstractItemModel* self);
void QAbstractItemModel_BeginResetModel(QAbstractItemModel* self);
void QAbstractItemModel_OnBeginResetModel(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseBeginResetModel(QAbstractItemModel* self);
void QAbstractItemModel_EndResetModel(QAbstractItemModel* self);
void QAbstractItemModel_OnEndResetModel(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseEndResetModel(QAbstractItemModel* self);
void QAbstractItemModel_ChangePersistentIndex(QAbstractItemModel* self, const QModelIndex* from, const QModelIndex* to);
void QAbstractItemModel_OnChangePersistentIndex(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseChangePersistentIndex(QAbstractItemModel* self, const QModelIndex* from, const QModelIndex* to);
void QAbstractItemModel_ChangePersistentIndexList(QAbstractItemModel* self, const libqt_list from, const libqt_list to);
void QAbstractItemModel_OnChangePersistentIndexList(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_QBaseChangePersistentIndexList(QAbstractItemModel* self, const libqt_list from, const libqt_list to);
libqt_list QAbstractItemModel_PersistentIndexList(const QAbstractItemModel* self);
void QAbstractItemModel_OnPersistentIndexList(const QAbstractItemModel* self, intptr_t slot);
libqt_list QAbstractItemModel_QBasePersistentIndexList(const QAbstractItemModel* self);
QModelIndex* QAbstractItemModel_CreateIndex3(const QAbstractItemModel* self, int row, int column, const void* data);
void QAbstractItemModel_OnCreateIndex3(const QAbstractItemModel* self, intptr_t slot);
QModelIndex* QAbstractItemModel_QBaseCreateIndex3(const QAbstractItemModel* self, int row, int column, const void* data);
void QAbstractItemModel_Connect_rowsAboutToBeInserted(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_rowsInserted(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_rowsAboutToBeRemoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_rowsRemoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_columnsAboutToBeInserted(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_columnsInserted(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_columnsAboutToBeRemoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_columnsRemoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_modelAboutToBeReset(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_modelReset(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_rowsAboutToBeMoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_rowsMoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_columnsAboutToBeMoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Connect_columnsMoved(QAbstractItemModel* self, intptr_t slot);
void QAbstractItemModel_Delete(QAbstractItemModel* self);

QAbstractTableModel* QAbstractTableModel_new();
QAbstractTableModel* QAbstractTableModel_new2(QObject* parent);
libqt_string QAbstractTableModel_Tr(const char* s);
QModelIndex* QAbstractTableModel_Index(const QAbstractTableModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* QAbstractTableModel_Sibling(const QAbstractTableModel* self, int row, int column, const QModelIndex* idx);
bool QAbstractTableModel_DropMimeData(QAbstractTableModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
int QAbstractTableModel_Flags(const QAbstractTableModel* self, const QModelIndex* index);
libqt_string QAbstractTableModel_Tr2(const char* s, const char* c);
libqt_string QAbstractTableModel_Tr3(const char* s, const char* c, int n);
void QAbstractTableModel_OnIndex(const QAbstractTableModel* self, intptr_t slot);
QModelIndex* QAbstractTableModel_QBaseIndex(const QAbstractTableModel* self, int row, int column, const QModelIndex* parent);
void QAbstractTableModel_OnSibling(const QAbstractTableModel* self, intptr_t slot);
QModelIndex* QAbstractTableModel_QBaseSibling(const QAbstractTableModel* self, int row, int column, const QModelIndex* idx);
void QAbstractTableModel_OnDropMimeData(QAbstractTableModel* self, intptr_t slot);
bool QAbstractTableModel_QBaseDropMimeData(QAbstractTableModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void QAbstractTableModel_OnFlags(const QAbstractTableModel* self, intptr_t slot);
int QAbstractTableModel_QBaseFlags(const QAbstractTableModel* self, const QModelIndex* index);
void QAbstractTableModel_Delete(QAbstractTableModel* self);

QAbstractListModel* QAbstractListModel_new();
QAbstractListModel* QAbstractListModel_new2(QObject* parent);
libqt_string QAbstractListModel_Tr(const char* s);
QModelIndex* QAbstractListModel_Index(const QAbstractListModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* QAbstractListModel_Sibling(const QAbstractListModel* self, int row, int column, const QModelIndex* idx);
bool QAbstractListModel_DropMimeData(QAbstractListModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
int QAbstractListModel_Flags(const QAbstractListModel* self, const QModelIndex* index);
libqt_string QAbstractListModel_Tr2(const char* s, const char* c);
libqt_string QAbstractListModel_Tr3(const char* s, const char* c, int n);
void QAbstractListModel_OnIndex(const QAbstractListModel* self, intptr_t slot);
QModelIndex* QAbstractListModel_QBaseIndex(const QAbstractListModel* self, int row, int column, const QModelIndex* parent);
void QAbstractListModel_OnSibling(const QAbstractListModel* self, intptr_t slot);
QModelIndex* QAbstractListModel_QBaseSibling(const QAbstractListModel* self, int row, int column, const QModelIndex* idx);
void QAbstractListModel_OnDropMimeData(QAbstractListModel* self, intptr_t slot);
bool QAbstractListModel_QBaseDropMimeData(QAbstractListModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void QAbstractListModel_OnFlags(const QAbstractListModel* self, intptr_t slot);
int QAbstractListModel_QBaseFlags(const QAbstractListModel* self, const QModelIndex* index);
void QAbstractListModel_Delete(QAbstractListModel* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
