#pragma once
#ifndef QGRAPHICSITEM_H_C_LIB
#define QGRAPHICSITEM_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractGraphicsShapeItem QAbstractGraphicsShapeItem;
typedef struct QBrush QBrush;
typedef struct QColor QColor;
typedef struct QCursor QCursor;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QGraphicsEffect QGraphicsEffect;
typedef struct QGraphicsEllipseItem QGraphicsEllipseItem;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsItemGroup QGraphicsItemGroup;
typedef struct QGraphicsLineItem QGraphicsLineItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsPathItem QGraphicsPathItem;
typedef struct QGraphicsPixmapItem QGraphicsPixmapItem;
typedef struct QGraphicsPolygonItem QGraphicsPolygonItem;
typedef struct QGraphicsRectItem QGraphicsRectItem;
typedef struct QGraphicsScene QGraphicsScene;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsSimpleTextItem QGraphicsSimpleTextItem;
typedef struct QGraphicsTextItem QGraphicsTextItem;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineF QLineF;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPen QPen;
typedef struct QPixmap QPixmap;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QRegion QRegion;
typedef struct QSize QSize;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTextCursor QTextCursor;
typedef struct QTextDocument QTextDocument;
typedef struct QTransform QTransform;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif




QGraphicsItem* QGraphicsItem_new();
QGraphicsItem* QGraphicsItem_new2(QGraphicsItem* parent);
QGraphicsScene* QGraphicsItem_Scene(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_ParentItem(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_TopLevelItem(const QGraphicsItem* self);
QGraphicsObject* QGraphicsItem_ParentObject(const QGraphicsItem* self);
QGraphicsWidget* QGraphicsItem_ParentWidget(const QGraphicsItem* self);
QGraphicsWidget* QGraphicsItem_TopLevelWidget(const QGraphicsItem* self);
QGraphicsWidget* QGraphicsItem_Window(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_Panel(const QGraphicsItem* self);
void QGraphicsItem_SetParentItem(QGraphicsItem* self, QGraphicsItem* parent);
libqt_list QGraphicsItem_ChildItems(const QGraphicsItem* self);
bool QGraphicsItem_IsWidget(const QGraphicsItem* self);
bool QGraphicsItem_IsWindow(const QGraphicsItem* self);
bool QGraphicsItem_IsPanel(const QGraphicsItem* self);
QGraphicsObject* QGraphicsItem_ToGraphicsObject(QGraphicsItem* self);
const QGraphicsObject* QGraphicsItem_ToGraphicsObject2(const QGraphicsItem* self);
QGraphicsItemGroup* QGraphicsItem_Group(const QGraphicsItem* self);
void QGraphicsItem_SetGroup(QGraphicsItem* self, QGraphicsItemGroup* group);
int QGraphicsItem_Flags(const QGraphicsItem* self);
void QGraphicsItem_SetFlag(QGraphicsItem* self, int flag);
void QGraphicsItem_SetFlags(QGraphicsItem* self, int flags);
int QGraphicsItem_CacheMode(const QGraphicsItem* self);
void QGraphicsItem_SetCacheMode(QGraphicsItem* self, int mode);
int QGraphicsItem_PanelModality(const QGraphicsItem* self);
void QGraphicsItem_SetPanelModality(QGraphicsItem* self, int panelModality);
bool QGraphicsItem_IsBlockedByModalPanel(const QGraphicsItem* self);
libqt_string QGraphicsItem_ToolTip(const QGraphicsItem* self);
void QGraphicsItem_SetToolTip(QGraphicsItem* self, const libqt_string toolTip);
QCursor* QGraphicsItem_Cursor(const QGraphicsItem* self);
void QGraphicsItem_SetCursor(QGraphicsItem* self, const QCursor* cursor);
bool QGraphicsItem_HasCursor(const QGraphicsItem* self);
void QGraphicsItem_UnsetCursor(QGraphicsItem* self);
bool QGraphicsItem_IsVisible(const QGraphicsItem* self);
bool QGraphicsItem_IsVisibleTo(const QGraphicsItem* self, const QGraphicsItem* parent);
void QGraphicsItem_SetVisible(QGraphicsItem* self, bool visible);
void QGraphicsItem_Hide(QGraphicsItem* self);
void QGraphicsItem_Show(QGraphicsItem* self);
bool QGraphicsItem_IsEnabled(const QGraphicsItem* self);
void QGraphicsItem_SetEnabled(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_IsSelected(const QGraphicsItem* self);
void QGraphicsItem_SetSelected(QGraphicsItem* self, bool selected);
bool QGraphicsItem_AcceptDrops(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptDrops(QGraphicsItem* self, bool on);
double QGraphicsItem_Opacity(const QGraphicsItem* self);
double QGraphicsItem_EffectiveOpacity(const QGraphicsItem* self);
void QGraphicsItem_SetOpacity(QGraphicsItem* self, double opacity);
QGraphicsEffect* QGraphicsItem_GraphicsEffect(const QGraphicsItem* self);
void QGraphicsItem_SetGraphicsEffect(QGraphicsItem* self, QGraphicsEffect* effect);
int QGraphicsItem_AcceptedMouseButtons(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptedMouseButtons(QGraphicsItem* self, int buttons);
bool QGraphicsItem_AcceptHoverEvents(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptHoverEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_AcceptTouchEvents(const QGraphicsItem* self);
void QGraphicsItem_SetAcceptTouchEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_FiltersChildEvents(const QGraphicsItem* self);
void QGraphicsItem_SetFiltersChildEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_HandlesChildEvents(const QGraphicsItem* self);
void QGraphicsItem_SetHandlesChildEvents(QGraphicsItem* self, bool enabled);
bool QGraphicsItem_IsActive(const QGraphicsItem* self);
void QGraphicsItem_SetActive(QGraphicsItem* self, bool active);
bool QGraphicsItem_HasFocus(const QGraphicsItem* self);
void QGraphicsItem_SetFocus(QGraphicsItem* self);
void QGraphicsItem_ClearFocus(QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_FocusProxy(const QGraphicsItem* self);
void QGraphicsItem_SetFocusProxy(QGraphicsItem* self, QGraphicsItem* item);
QGraphicsItem* QGraphicsItem_FocusItem(const QGraphicsItem* self);
QGraphicsItem* QGraphicsItem_FocusScopeItem(const QGraphicsItem* self);
void QGraphicsItem_GrabMouse(QGraphicsItem* self);
void QGraphicsItem_UngrabMouse(QGraphicsItem* self);
void QGraphicsItem_GrabKeyboard(QGraphicsItem* self);
void QGraphicsItem_UngrabKeyboard(QGraphicsItem* self);
QPointF* QGraphicsItem_Pos(const QGraphicsItem* self);
double QGraphicsItem_X(const QGraphicsItem* self);
void QGraphicsItem_SetX(QGraphicsItem* self, double x);
double QGraphicsItem_Y(const QGraphicsItem* self);
void QGraphicsItem_SetY(QGraphicsItem* self, double y);
QPointF* QGraphicsItem_ScenePos(const QGraphicsItem* self);
void QGraphicsItem_SetPos(QGraphicsItem* self, const QPointF* pos);
void QGraphicsItem_SetPos2(QGraphicsItem* self, double x, double y);
void QGraphicsItem_MoveBy(QGraphicsItem* self, double dx, double dy);
void QGraphicsItem_EnsureVisible(QGraphicsItem* self);
void QGraphicsItem_EnsureVisible2(QGraphicsItem* self, double x, double y, double w, double h);
QTransform* QGraphicsItem_Transform(const QGraphicsItem* self);
QTransform* QGraphicsItem_SceneTransform(const QGraphicsItem* self);
QTransform* QGraphicsItem_DeviceTransform(const QGraphicsItem* self, const QTransform* viewportTransform);
QTransform* QGraphicsItem_ItemTransform(const QGraphicsItem* self, const QGraphicsItem* other);
void QGraphicsItem_SetTransform(QGraphicsItem* self, const QTransform* matrix);
void QGraphicsItem_ResetTransform(QGraphicsItem* self);
void QGraphicsItem_SetRotation(QGraphicsItem* self, double angle);
double QGraphicsItem_Rotation(const QGraphicsItem* self);
void QGraphicsItem_SetScale(QGraphicsItem* self, double scale);
double QGraphicsItem_Scale(const QGraphicsItem* self);
libqt_list QGraphicsItem_Transformations(const QGraphicsItem* self);
void QGraphicsItem_SetTransformations(QGraphicsItem* self, const libqt_list transformations);
QPointF* QGraphicsItem_TransformOriginPoint(const QGraphicsItem* self);
void QGraphicsItem_SetTransformOriginPoint(QGraphicsItem* self, const QPointF* origin);
void QGraphicsItem_SetTransformOriginPoint2(QGraphicsItem* self, double ax, double ay);
void QGraphicsItem_Advance(QGraphicsItem* self, int phase);
double QGraphicsItem_ZValue(const QGraphicsItem* self);
void QGraphicsItem_SetZValue(QGraphicsItem* self, double z);
void QGraphicsItem_StackBefore(QGraphicsItem* self, const QGraphicsItem* sibling);
QRectF* QGraphicsItem_BoundingRect(const QGraphicsItem* self);
QRectF* QGraphicsItem_ChildrenBoundingRect(const QGraphicsItem* self);
QRectF* QGraphicsItem_SceneBoundingRect(const QGraphicsItem* self);
QPainterPath* QGraphicsItem_Shape(const QGraphicsItem* self);
bool QGraphicsItem_IsClipped(const QGraphicsItem* self);
QPainterPath* QGraphicsItem_ClipPath(const QGraphicsItem* self);
bool QGraphicsItem_Contains(const QGraphicsItem* self, const QPointF* point);
bool QGraphicsItem_CollidesWithItem(const QGraphicsItem* self, const QGraphicsItem* other, int mode);
bool QGraphicsItem_CollidesWithPath(const QGraphicsItem* self, const QPainterPath* path, int mode);
libqt_list QGraphicsItem_CollidingItems(const QGraphicsItem* self);
bool QGraphicsItem_IsObscured(const QGraphicsItem* self);
bool QGraphicsItem_IsObscured2(const QGraphicsItem* self, double x, double y, double w, double h);
bool QGraphicsItem_IsObscuredBy(const QGraphicsItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsItem_OpaqueArea(const QGraphicsItem* self);
QRegion* QGraphicsItem_BoundingRegion(const QGraphicsItem* self, const QTransform* itemToDeviceTransform);
double QGraphicsItem_BoundingRegionGranularity(const QGraphicsItem* self);
void QGraphicsItem_SetBoundingRegionGranularity(QGraphicsItem* self, double granularity);
void QGraphicsItem_Paint(QGraphicsItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsItem_Update(QGraphicsItem* self);
void QGraphicsItem_Update2(QGraphicsItem* self, double x, double y, double width, double height);
void QGraphicsItem_Scroll(QGraphicsItem* self, double dx, double dy);
QPointF* QGraphicsItem_MapToItem(const QGraphicsItem* self, const QGraphicsItem* item, const QPointF* point);
QPointF* QGraphicsItem_MapToParent(const QGraphicsItem* self, const QPointF* point);
QPointF* QGraphicsItem_MapToScene(const QGraphicsItem* self, const QPointF* point);
QRectF* QGraphicsItem_MapRectToItem(const QGraphicsItem* self, const QGraphicsItem* item, const QRectF* rect);
QRectF* QGraphicsItem_MapRectToParent(const QGraphicsItem* self, const QRectF* rect);
QRectF* QGraphicsItem_MapRectToScene(const QGraphicsItem* self, const QRectF* rect);
QPainterPath* QGraphicsItem_MapToItem4(const QGraphicsItem* self, const QGraphicsItem* item, const QPainterPath* path);
QPainterPath* QGraphicsItem_MapToParent4(const QGraphicsItem* self, const QPainterPath* path);
QPainterPath* QGraphicsItem_MapToScene4(const QGraphicsItem* self, const QPainterPath* path);
QPointF* QGraphicsItem_MapFromItem(const QGraphicsItem* self, const QGraphicsItem* item, const QPointF* point);
QPointF* QGraphicsItem_MapFromParent(const QGraphicsItem* self, const QPointF* point);
QPointF* QGraphicsItem_MapFromScene(const QGraphicsItem* self, const QPointF* point);
QRectF* QGraphicsItem_MapRectFromItem(const QGraphicsItem* self, const QGraphicsItem* item, const QRectF* rect);
QRectF* QGraphicsItem_MapRectFromParent(const QGraphicsItem* self, const QRectF* rect);
QRectF* QGraphicsItem_MapRectFromScene(const QGraphicsItem* self, const QRectF* rect);
QPainterPath* QGraphicsItem_MapFromItem4(const QGraphicsItem* self, const QGraphicsItem* item, const QPainterPath* path);
QPainterPath* QGraphicsItem_MapFromParent4(const QGraphicsItem* self, const QPainterPath* path);
QPainterPath* QGraphicsItem_MapFromScene4(const QGraphicsItem* self, const QPainterPath* path);
QPointF* QGraphicsItem_MapToItem5(const QGraphicsItem* self, const QGraphicsItem* item, double x, double y);
QPointF* QGraphicsItem_MapToParent5(const QGraphicsItem* self, double x, double y);
QPointF* QGraphicsItem_MapToScene5(const QGraphicsItem* self, double x, double y);
QRectF* QGraphicsItem_MapRectToItem2(const QGraphicsItem* self, const QGraphicsItem* item, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectToParent2(const QGraphicsItem* self, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectToScene2(const QGraphicsItem* self, double x, double y, double w, double h);
QPointF* QGraphicsItem_MapFromItem5(const QGraphicsItem* self, const QGraphicsItem* item, double x, double y);
QPointF* QGraphicsItem_MapFromParent5(const QGraphicsItem* self, double x, double y);
QPointF* QGraphicsItem_MapFromScene5(const QGraphicsItem* self, double x, double y);
QRectF* QGraphicsItem_MapRectFromItem2(const QGraphicsItem* self, const QGraphicsItem* item, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectFromParent2(const QGraphicsItem* self, double x, double y, double w, double h);
QRectF* QGraphicsItem_MapRectFromScene2(const QGraphicsItem* self, double x, double y, double w, double h);
bool QGraphicsItem_IsAncestorOf(const QGraphicsItem* self, const QGraphicsItem* child);
QGraphicsItem* QGraphicsItem_CommonAncestorItem(const QGraphicsItem* self, const QGraphicsItem* other);
bool QGraphicsItem_IsUnderMouse(const QGraphicsItem* self);
QVariant* QGraphicsItem_Data(const QGraphicsItem* self, int key);
void QGraphicsItem_SetData(QGraphicsItem* self, int key, const QVariant* value);
int QGraphicsItem_InputMethodHints(const QGraphicsItem* self);
void QGraphicsItem_SetInputMethodHints(QGraphicsItem* self, int hints);
int QGraphicsItem_Type(const QGraphicsItem* self);
void QGraphicsItem_InstallSceneEventFilter(QGraphicsItem* self, QGraphicsItem* filterItem);
void QGraphicsItem_RemoveSceneEventFilter(QGraphicsItem* self, QGraphicsItem* filterItem);
bool QGraphicsItem_SceneEventFilter(QGraphicsItem* self, QGraphicsItem* watched, QEvent* event);
bool QGraphicsItem_SceneEvent(QGraphicsItem* self, QEvent* event);
void QGraphicsItem_ContextMenuEvent(QGraphicsItem* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsItem_DragEnterEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_DragLeaveEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_DragMoveEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_DropEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_FocusInEvent(QGraphicsItem* self, QFocusEvent* event);
void QGraphicsItem_FocusOutEvent(QGraphicsItem* self, QFocusEvent* event);
void QGraphicsItem_HoverEnterEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_HoverMoveEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_HoverLeaveEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_KeyPressEvent(QGraphicsItem* self, QKeyEvent* event);
void QGraphicsItem_KeyReleaseEvent(QGraphicsItem* self, QKeyEvent* event);
void QGraphicsItem_MousePressEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_MouseMoveEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_MouseReleaseEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_MouseDoubleClickEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_WheelEvent(QGraphicsItem* self, QGraphicsSceneWheelEvent* event);
void QGraphicsItem_InputMethodEvent(QGraphicsItem* self, QInputMethodEvent* event);
QVariant* QGraphicsItem_InputMethodQuery(const QGraphicsItem* self, int query);
QVariant* QGraphicsItem_ItemChange(QGraphicsItem* self, int change, const QVariant* value);
bool QGraphicsItem_SupportsExtension(const QGraphicsItem* self, int extension);
void QGraphicsItem_SetExtension(QGraphicsItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsItem_Extension(const QGraphicsItem* self, const QVariant* variant);
void QGraphicsItem_SetFlag2(QGraphicsItem* self, int flag, bool enabled);
void QGraphicsItem_SetCacheMode2(QGraphicsItem* self, int mode, const QSize* cacheSize);
bool QGraphicsItem_IsBlockedByModalPanel1(const QGraphicsItem* self, QGraphicsItem** blockingPanel);
void QGraphicsItem_SetFocus1(QGraphicsItem* self, int focusReason);
void QGraphicsItem_EnsureVisible1(QGraphicsItem* self, const QRectF* rect);
void QGraphicsItem_EnsureVisible22(QGraphicsItem* self, const QRectF* rect, int xmargin);
void QGraphicsItem_EnsureVisible3(QGraphicsItem* self, const QRectF* rect, int xmargin, int ymargin);
void QGraphicsItem_EnsureVisible5(QGraphicsItem* self, double x, double y, double w, double h, int xmargin);
void QGraphicsItem_EnsureVisible6(QGraphicsItem* self, double x, double y, double w, double h, int xmargin, int ymargin);
QTransform* QGraphicsItem_ItemTransform2(const QGraphicsItem* self, const QGraphicsItem* other, bool* ok);
void QGraphicsItem_SetTransform2(QGraphicsItem* self, const QTransform* matrix, bool combine);
libqt_list QGraphicsItem_CollidingItems1(const QGraphicsItem* self, int mode);
bool QGraphicsItem_IsObscured1(const QGraphicsItem* self, const QRectF* rect);
void QGraphicsItem_Update1(QGraphicsItem* self, const QRectF* rect);
void QGraphicsItem_Scroll3(QGraphicsItem* self, double dx, double dy, const QRectF* rect);
void QGraphicsItem_OnAdvance(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseAdvance(QGraphicsItem* self, int phase);
void QGraphicsItem_OnBoundingRect(const QGraphicsItem* self, intptr_t slot);
QRectF* QGraphicsItem_QBaseBoundingRect(const QGraphicsItem* self);
void QGraphicsItem_OnShape(const QGraphicsItem* self, intptr_t slot);
QPainterPath* QGraphicsItem_QBaseShape(const QGraphicsItem* self);
void QGraphicsItem_OnContains(const QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseContains(const QGraphicsItem* self, const QPointF* point);
void QGraphicsItem_OnCollidesWithItem(const QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseCollidesWithItem(const QGraphicsItem* self, const QGraphicsItem* other, int mode);
void QGraphicsItem_OnCollidesWithPath(const QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseCollidesWithPath(const QGraphicsItem* self, const QPainterPath* path, int mode);
void QGraphicsItem_OnIsObscuredBy(const QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseIsObscuredBy(const QGraphicsItem* self, const QGraphicsItem* item);
void QGraphicsItem_OnOpaqueArea(const QGraphicsItem* self, intptr_t slot);
QPainterPath* QGraphicsItem_QBaseOpaqueArea(const QGraphicsItem* self);
void QGraphicsItem_OnPaint(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBasePaint(QGraphicsItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsItem_OnType(const QGraphicsItem* self, intptr_t slot);
int QGraphicsItem_QBaseType(const QGraphicsItem* self);
void QGraphicsItem_OnSceneEventFilter(QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseSceneEventFilter(QGraphicsItem* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsItem_OnSceneEvent(QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseSceneEvent(QGraphicsItem* self, QEvent* event);
void QGraphicsItem_OnContextMenuEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseContextMenuEvent(QGraphicsItem* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsItem_OnDragEnterEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseDragEnterEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_OnDragLeaveEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseDragLeaveEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_OnDragMoveEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseDragMoveEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_OnDropEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseDropEvent(QGraphicsItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsItem_OnFocusInEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseFocusInEvent(QGraphicsItem* self, QFocusEvent* event);
void QGraphicsItem_OnFocusOutEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseFocusOutEvent(QGraphicsItem* self, QFocusEvent* event);
void QGraphicsItem_OnHoverEnterEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseHoverEnterEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_OnHoverMoveEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseHoverMoveEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_OnHoverLeaveEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseHoverLeaveEvent(QGraphicsItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsItem_OnKeyPressEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseKeyPressEvent(QGraphicsItem* self, QKeyEvent* event);
void QGraphicsItem_OnKeyReleaseEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseKeyReleaseEvent(QGraphicsItem* self, QKeyEvent* event);
void QGraphicsItem_OnMousePressEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseMousePressEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_OnMouseMoveEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseMouseMoveEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_OnMouseReleaseEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseMouseReleaseEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_OnMouseDoubleClickEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseMouseDoubleClickEvent(QGraphicsItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsItem_OnWheelEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseWheelEvent(QGraphicsItem* self, QGraphicsSceneWheelEvent* event);
void QGraphicsItem_OnInputMethodEvent(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseInputMethodEvent(QGraphicsItem* self, QInputMethodEvent* event);
void QGraphicsItem_OnInputMethodQuery(const QGraphicsItem* self, intptr_t slot);
QVariant* QGraphicsItem_QBaseInputMethodQuery(const QGraphicsItem* self, int query);
void QGraphicsItem_OnItemChange(QGraphicsItem* self, intptr_t slot);
QVariant* QGraphicsItem_QBaseItemChange(QGraphicsItem* self, int change, const QVariant* value);
void QGraphicsItem_OnSupportsExtension(const QGraphicsItem* self, intptr_t slot);
bool QGraphicsItem_QBaseSupportsExtension(const QGraphicsItem* self, int extension);
void QGraphicsItem_OnSetExtension(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseSetExtension(QGraphicsItem* self, int extension, const QVariant* variant);
void QGraphicsItem_OnExtension(const QGraphicsItem* self, intptr_t slot);
QVariant* QGraphicsItem_QBaseExtension(const QGraphicsItem* self, const QVariant* variant);
void QGraphicsItem_UpdateMicroFocus(QGraphicsItem* self);
void QGraphicsItem_OnUpdateMicroFocus(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseUpdateMicroFocus(QGraphicsItem* self);
void QGraphicsItem_AddToIndex(QGraphicsItem* self);
void QGraphicsItem_OnAddToIndex(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseAddToIndex(QGraphicsItem* self);
void QGraphicsItem_RemoveFromIndex(QGraphicsItem* self);
void QGraphicsItem_OnRemoveFromIndex(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBaseRemoveFromIndex(QGraphicsItem* self);
void QGraphicsItem_PrepareGeometryChange(QGraphicsItem* self);
void QGraphicsItem_OnPrepareGeometryChange(QGraphicsItem* self, intptr_t slot);
void QGraphicsItem_QBasePrepareGeometryChange(QGraphicsItem* self);
void QGraphicsItem_Delete(QGraphicsItem* self);

QGraphicsObject* QGraphicsObject_new();
QGraphicsObject* QGraphicsObject_new2(QGraphicsItem* parent);
libqt_string QGraphicsObject_Tr(const char* s);
void QGraphicsObject_GrabGesture(QGraphicsObject* self, int typeVal);
void QGraphicsObject_UngrabGesture(QGraphicsObject* self, int typeVal);
void QGraphicsObject_ParentChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_ParentChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_OpacityChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_OpacityChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_VisibleChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_VisibleChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_EnabledChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_EnabledChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_XChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_XChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_YChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_YChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_ZChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_ZChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_RotationChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_RotationChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_ScaleChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_ScaleChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_ChildrenChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_ChildrenChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_WidthChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_WidthChanged(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_HeightChanged(QGraphicsObject* self);
void QGraphicsObject_Connect_HeightChanged(QGraphicsObject* self, intptr_t slot);
bool QGraphicsObject_Event(QGraphicsObject* self, QEvent* ev);
libqt_string QGraphicsObject_Tr2(const char* s, const char* c);
libqt_string QGraphicsObject_Tr3(const char* s, const char* c, int n);
void QGraphicsObject_GrabGesture2(QGraphicsObject* self, int typeVal, int flags);
void QGraphicsObject_OnEvent(QGraphicsObject* self, intptr_t slot);
bool QGraphicsObject_QBaseEvent(QGraphicsObject* self, QEvent* ev);
void QGraphicsObject_UpdateMicroFocus(QGraphicsObject* self);
void QGraphicsObject_OnUpdateMicroFocus(QGraphicsObject* self, intptr_t slot);
void QGraphicsObject_QBaseUpdateMicroFocus(QGraphicsObject* self);
void QGraphicsObject_Delete(QGraphicsObject* self);

QAbstractGraphicsShapeItem* QAbstractGraphicsShapeItem_new();
QAbstractGraphicsShapeItem* QAbstractGraphicsShapeItem_new2(QGraphicsItem* parent);
QPen* QAbstractGraphicsShapeItem_Pen(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_SetPen(QAbstractGraphicsShapeItem* self, const QPen* pen);
QBrush* QAbstractGraphicsShapeItem_Brush(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_SetBrush(QAbstractGraphicsShapeItem* self, const QBrush* brush);
bool QAbstractGraphicsShapeItem_IsObscuredBy(const QAbstractGraphicsShapeItem* self, const QGraphicsItem* item);
QPainterPath* QAbstractGraphicsShapeItem_OpaqueArea(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_OnIsObscuredBy(const QAbstractGraphicsShapeItem* self, intptr_t slot);
bool QAbstractGraphicsShapeItem_QBaseIsObscuredBy(const QAbstractGraphicsShapeItem* self, const QGraphicsItem* item);
void QAbstractGraphicsShapeItem_OnOpaqueArea(const QAbstractGraphicsShapeItem* self, intptr_t slot);
QPainterPath* QAbstractGraphicsShapeItem_QBaseOpaqueArea(const QAbstractGraphicsShapeItem* self);
void QAbstractGraphicsShapeItem_Delete(QAbstractGraphicsShapeItem* self);

QGraphicsPathItem* QGraphicsPathItem_new();
QGraphicsPathItem* QGraphicsPathItem_new2(const QPainterPath* path);
QGraphicsPathItem* QGraphicsPathItem_new3(QGraphicsItem* parent);
QGraphicsPathItem* QGraphicsPathItem_new4(const QPainterPath* path, QGraphicsItem* parent);
QPainterPath* QGraphicsPathItem_Path(const QGraphicsPathItem* self);
void QGraphicsPathItem_SetPath(QGraphicsPathItem* self, const QPainterPath* path);
QRectF* QGraphicsPathItem_BoundingRect(const QGraphicsPathItem* self);
QPainterPath* QGraphicsPathItem_Shape(const QGraphicsPathItem* self);
bool QGraphicsPathItem_Contains(const QGraphicsPathItem* self, const QPointF* point);
void QGraphicsPathItem_Paint(QGraphicsPathItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsPathItem_IsObscuredBy(const QGraphicsPathItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsPathItem_OpaqueArea(const QGraphicsPathItem* self);
int QGraphicsPathItem_Type(const QGraphicsPathItem* self);
bool QGraphicsPathItem_SupportsExtension(const QGraphicsPathItem* self, int extension);
void QGraphicsPathItem_SetExtension(QGraphicsPathItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsPathItem_Extension(const QGraphicsPathItem* self, const QVariant* variant);
void QGraphicsPathItem_OnBoundingRect(const QGraphicsPathItem* self, intptr_t slot);
QRectF* QGraphicsPathItem_QBaseBoundingRect(const QGraphicsPathItem* self);
void QGraphicsPathItem_OnShape(const QGraphicsPathItem* self, intptr_t slot);
QPainterPath* QGraphicsPathItem_QBaseShape(const QGraphicsPathItem* self);
void QGraphicsPathItem_OnContains(const QGraphicsPathItem* self, intptr_t slot);
bool QGraphicsPathItem_QBaseContains(const QGraphicsPathItem* self, const QPointF* point);
void QGraphicsPathItem_OnPaint(QGraphicsPathItem* self, intptr_t slot);
void QGraphicsPathItem_QBasePaint(QGraphicsPathItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsPathItem_OnIsObscuredBy(const QGraphicsPathItem* self, intptr_t slot);
bool QGraphicsPathItem_QBaseIsObscuredBy(const QGraphicsPathItem* self, const QGraphicsItem* item);
void QGraphicsPathItem_OnOpaqueArea(const QGraphicsPathItem* self, intptr_t slot);
QPainterPath* QGraphicsPathItem_QBaseOpaqueArea(const QGraphicsPathItem* self);
void QGraphicsPathItem_OnType(const QGraphicsPathItem* self, intptr_t slot);
int QGraphicsPathItem_QBaseType(const QGraphicsPathItem* self);
void QGraphicsPathItem_OnSupportsExtension(const QGraphicsPathItem* self, intptr_t slot);
bool QGraphicsPathItem_QBaseSupportsExtension(const QGraphicsPathItem* self, int extension);
void QGraphicsPathItem_OnSetExtension(QGraphicsPathItem* self, intptr_t slot);
void QGraphicsPathItem_QBaseSetExtension(QGraphicsPathItem* self, int extension, const QVariant* variant);
void QGraphicsPathItem_OnExtension(const QGraphicsPathItem* self, intptr_t slot);
QVariant* QGraphicsPathItem_QBaseExtension(const QGraphicsPathItem* self, const QVariant* variant);
void QGraphicsPathItem_Delete(QGraphicsPathItem* self);

QGraphicsRectItem* QGraphicsRectItem_new();
QGraphicsRectItem* QGraphicsRectItem_new2(const QRectF* rect);
QGraphicsRectItem* QGraphicsRectItem_new3(double x, double y, double w, double h);
QGraphicsRectItem* QGraphicsRectItem_new4(QGraphicsItem* parent);
QGraphicsRectItem* QGraphicsRectItem_new5(const QRectF* rect, QGraphicsItem* parent);
QGraphicsRectItem* QGraphicsRectItem_new6(double x, double y, double w, double h, QGraphicsItem* parent);
QRectF* QGraphicsRectItem_Rect(const QGraphicsRectItem* self);
void QGraphicsRectItem_SetRect(QGraphicsRectItem* self, const QRectF* rect);
void QGraphicsRectItem_SetRect2(QGraphicsRectItem* self, double x, double y, double w, double h);
QRectF* QGraphicsRectItem_BoundingRect(const QGraphicsRectItem* self);
QPainterPath* QGraphicsRectItem_Shape(const QGraphicsRectItem* self);
bool QGraphicsRectItem_Contains(const QGraphicsRectItem* self, const QPointF* point);
void QGraphicsRectItem_Paint(QGraphicsRectItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsRectItem_IsObscuredBy(const QGraphicsRectItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsRectItem_OpaqueArea(const QGraphicsRectItem* self);
int QGraphicsRectItem_Type(const QGraphicsRectItem* self);
bool QGraphicsRectItem_SupportsExtension(const QGraphicsRectItem* self, int extension);
void QGraphicsRectItem_SetExtension(QGraphicsRectItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsRectItem_Extension(const QGraphicsRectItem* self, const QVariant* variant);
void QGraphicsRectItem_OnBoundingRect(const QGraphicsRectItem* self, intptr_t slot);
QRectF* QGraphicsRectItem_QBaseBoundingRect(const QGraphicsRectItem* self);
void QGraphicsRectItem_OnShape(const QGraphicsRectItem* self, intptr_t slot);
QPainterPath* QGraphicsRectItem_QBaseShape(const QGraphicsRectItem* self);
void QGraphicsRectItem_OnContains(const QGraphicsRectItem* self, intptr_t slot);
bool QGraphicsRectItem_QBaseContains(const QGraphicsRectItem* self, const QPointF* point);
void QGraphicsRectItem_OnPaint(QGraphicsRectItem* self, intptr_t slot);
void QGraphicsRectItem_QBasePaint(QGraphicsRectItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsRectItem_OnIsObscuredBy(const QGraphicsRectItem* self, intptr_t slot);
bool QGraphicsRectItem_QBaseIsObscuredBy(const QGraphicsRectItem* self, const QGraphicsItem* item);
void QGraphicsRectItem_OnOpaqueArea(const QGraphicsRectItem* self, intptr_t slot);
QPainterPath* QGraphicsRectItem_QBaseOpaqueArea(const QGraphicsRectItem* self);
void QGraphicsRectItem_OnType(const QGraphicsRectItem* self, intptr_t slot);
int QGraphicsRectItem_QBaseType(const QGraphicsRectItem* self);
void QGraphicsRectItem_OnSupportsExtension(const QGraphicsRectItem* self, intptr_t slot);
bool QGraphicsRectItem_QBaseSupportsExtension(const QGraphicsRectItem* self, int extension);
void QGraphicsRectItem_OnSetExtension(QGraphicsRectItem* self, intptr_t slot);
void QGraphicsRectItem_QBaseSetExtension(QGraphicsRectItem* self, int extension, const QVariant* variant);
void QGraphicsRectItem_OnExtension(const QGraphicsRectItem* self, intptr_t slot);
QVariant* QGraphicsRectItem_QBaseExtension(const QGraphicsRectItem* self, const QVariant* variant);
void QGraphicsRectItem_Delete(QGraphicsRectItem* self);

QGraphicsEllipseItem* QGraphicsEllipseItem_new();
QGraphicsEllipseItem* QGraphicsEllipseItem_new2(const QRectF* rect);
QGraphicsEllipseItem* QGraphicsEllipseItem_new3(double x, double y, double w, double h);
QGraphicsEllipseItem* QGraphicsEllipseItem_new4(QGraphicsItem* parent);
QGraphicsEllipseItem* QGraphicsEllipseItem_new5(const QRectF* rect, QGraphicsItem* parent);
QGraphicsEllipseItem* QGraphicsEllipseItem_new6(double x, double y, double w, double h, QGraphicsItem* parent);
QRectF* QGraphicsEllipseItem_Rect(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_SetRect(QGraphicsEllipseItem* self, const QRectF* rect);
void QGraphicsEllipseItem_SetRect2(QGraphicsEllipseItem* self, double x, double y, double w, double h);
int QGraphicsEllipseItem_StartAngle(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_SetStartAngle(QGraphicsEllipseItem* self, int angle);
int QGraphicsEllipseItem_SpanAngle(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_SetSpanAngle(QGraphicsEllipseItem* self, int angle);
QRectF* QGraphicsEllipseItem_BoundingRect(const QGraphicsEllipseItem* self);
QPainterPath* QGraphicsEllipseItem_Shape(const QGraphicsEllipseItem* self);
bool QGraphicsEllipseItem_Contains(const QGraphicsEllipseItem* self, const QPointF* point);
void QGraphicsEllipseItem_Paint(QGraphicsEllipseItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsEllipseItem_IsObscuredBy(const QGraphicsEllipseItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsEllipseItem_OpaqueArea(const QGraphicsEllipseItem* self);
int QGraphicsEllipseItem_Type(const QGraphicsEllipseItem* self);
bool QGraphicsEllipseItem_SupportsExtension(const QGraphicsEllipseItem* self, int extension);
void QGraphicsEllipseItem_SetExtension(QGraphicsEllipseItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsEllipseItem_Extension(const QGraphicsEllipseItem* self, const QVariant* variant);
void QGraphicsEllipseItem_OnBoundingRect(const QGraphicsEllipseItem* self, intptr_t slot);
QRectF* QGraphicsEllipseItem_QBaseBoundingRect(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_OnShape(const QGraphicsEllipseItem* self, intptr_t slot);
QPainterPath* QGraphicsEllipseItem_QBaseShape(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_OnContains(const QGraphicsEllipseItem* self, intptr_t slot);
bool QGraphicsEllipseItem_QBaseContains(const QGraphicsEllipseItem* self, const QPointF* point);
void QGraphicsEllipseItem_OnPaint(QGraphicsEllipseItem* self, intptr_t slot);
void QGraphicsEllipseItem_QBasePaint(QGraphicsEllipseItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsEllipseItem_OnIsObscuredBy(const QGraphicsEllipseItem* self, intptr_t slot);
bool QGraphicsEllipseItem_QBaseIsObscuredBy(const QGraphicsEllipseItem* self, const QGraphicsItem* item);
void QGraphicsEllipseItem_OnOpaqueArea(const QGraphicsEllipseItem* self, intptr_t slot);
QPainterPath* QGraphicsEllipseItem_QBaseOpaqueArea(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_OnType(const QGraphicsEllipseItem* self, intptr_t slot);
int QGraphicsEllipseItem_QBaseType(const QGraphicsEllipseItem* self);
void QGraphicsEllipseItem_OnSupportsExtension(const QGraphicsEllipseItem* self, intptr_t slot);
bool QGraphicsEllipseItem_QBaseSupportsExtension(const QGraphicsEllipseItem* self, int extension);
void QGraphicsEllipseItem_OnSetExtension(QGraphicsEllipseItem* self, intptr_t slot);
void QGraphicsEllipseItem_QBaseSetExtension(QGraphicsEllipseItem* self, int extension, const QVariant* variant);
void QGraphicsEllipseItem_OnExtension(const QGraphicsEllipseItem* self, intptr_t slot);
QVariant* QGraphicsEllipseItem_QBaseExtension(const QGraphicsEllipseItem* self, const QVariant* variant);
void QGraphicsEllipseItem_Delete(QGraphicsEllipseItem* self);

QGraphicsPolygonItem* QGraphicsPolygonItem_new();
QGraphicsPolygonItem* QGraphicsPolygonItem_new2(QGraphicsItem* parent);
int QGraphicsPolygonItem_FillRule(const QGraphicsPolygonItem* self);
void QGraphicsPolygonItem_SetFillRule(QGraphicsPolygonItem* self, int rule);
QRectF* QGraphicsPolygonItem_BoundingRect(const QGraphicsPolygonItem* self);
QPainterPath* QGraphicsPolygonItem_Shape(const QGraphicsPolygonItem* self);
bool QGraphicsPolygonItem_Contains(const QGraphicsPolygonItem* self, const QPointF* point);
void QGraphicsPolygonItem_Paint(QGraphicsPolygonItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsPolygonItem_IsObscuredBy(const QGraphicsPolygonItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsPolygonItem_OpaqueArea(const QGraphicsPolygonItem* self);
int QGraphicsPolygonItem_Type(const QGraphicsPolygonItem* self);
bool QGraphicsPolygonItem_SupportsExtension(const QGraphicsPolygonItem* self, int extension);
void QGraphicsPolygonItem_SetExtension(QGraphicsPolygonItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsPolygonItem_Extension(const QGraphicsPolygonItem* self, const QVariant* variant);
void QGraphicsPolygonItem_OnBoundingRect(const QGraphicsPolygonItem* self, intptr_t slot);
QRectF* QGraphicsPolygonItem_QBaseBoundingRect(const QGraphicsPolygonItem* self);
void QGraphicsPolygonItem_OnShape(const QGraphicsPolygonItem* self, intptr_t slot);
QPainterPath* QGraphicsPolygonItem_QBaseShape(const QGraphicsPolygonItem* self);
void QGraphicsPolygonItem_OnContains(const QGraphicsPolygonItem* self, intptr_t slot);
bool QGraphicsPolygonItem_QBaseContains(const QGraphicsPolygonItem* self, const QPointF* point);
void QGraphicsPolygonItem_OnPaint(QGraphicsPolygonItem* self, intptr_t slot);
void QGraphicsPolygonItem_QBasePaint(QGraphicsPolygonItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsPolygonItem_OnIsObscuredBy(const QGraphicsPolygonItem* self, intptr_t slot);
bool QGraphicsPolygonItem_QBaseIsObscuredBy(const QGraphicsPolygonItem* self, const QGraphicsItem* item);
void QGraphicsPolygonItem_OnOpaqueArea(const QGraphicsPolygonItem* self, intptr_t slot);
QPainterPath* QGraphicsPolygonItem_QBaseOpaqueArea(const QGraphicsPolygonItem* self);
void QGraphicsPolygonItem_OnType(const QGraphicsPolygonItem* self, intptr_t slot);
int QGraphicsPolygonItem_QBaseType(const QGraphicsPolygonItem* self);
void QGraphicsPolygonItem_OnSupportsExtension(const QGraphicsPolygonItem* self, intptr_t slot);
bool QGraphicsPolygonItem_QBaseSupportsExtension(const QGraphicsPolygonItem* self, int extension);
void QGraphicsPolygonItem_OnSetExtension(QGraphicsPolygonItem* self, intptr_t slot);
void QGraphicsPolygonItem_QBaseSetExtension(QGraphicsPolygonItem* self, int extension, const QVariant* variant);
void QGraphicsPolygonItem_OnExtension(const QGraphicsPolygonItem* self, intptr_t slot);
QVariant* QGraphicsPolygonItem_QBaseExtension(const QGraphicsPolygonItem* self, const QVariant* variant);
void QGraphicsPolygonItem_Delete(QGraphicsPolygonItem* self);

QGraphicsLineItem* QGraphicsLineItem_new();
QGraphicsLineItem* QGraphicsLineItem_new2(const QLineF* line);
QGraphicsLineItem* QGraphicsLineItem_new3(double x1, double y1, double x2, double y2);
QGraphicsLineItem* QGraphicsLineItem_new4(QGraphicsItem* parent);
QGraphicsLineItem* QGraphicsLineItem_new5(const QLineF* line, QGraphicsItem* parent);
QGraphicsLineItem* QGraphicsLineItem_new6(double x1, double y1, double x2, double y2, QGraphicsItem* parent);
QPen* QGraphicsLineItem_Pen(const QGraphicsLineItem* self);
void QGraphicsLineItem_SetPen(QGraphicsLineItem* self, const QPen* pen);
QLineF* QGraphicsLineItem_Line(const QGraphicsLineItem* self);
void QGraphicsLineItem_SetLine(QGraphicsLineItem* self, const QLineF* line);
void QGraphicsLineItem_SetLine2(QGraphicsLineItem* self, double x1, double y1, double x2, double y2);
QRectF* QGraphicsLineItem_BoundingRect(const QGraphicsLineItem* self);
QPainterPath* QGraphicsLineItem_Shape(const QGraphicsLineItem* self);
bool QGraphicsLineItem_Contains(const QGraphicsLineItem* self, const QPointF* point);
void QGraphicsLineItem_Paint(QGraphicsLineItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsLineItem_IsObscuredBy(const QGraphicsLineItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsLineItem_OpaqueArea(const QGraphicsLineItem* self);
int QGraphicsLineItem_Type(const QGraphicsLineItem* self);
bool QGraphicsLineItem_SupportsExtension(const QGraphicsLineItem* self, int extension);
void QGraphicsLineItem_SetExtension(QGraphicsLineItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsLineItem_Extension(const QGraphicsLineItem* self, const QVariant* variant);
void QGraphicsLineItem_OnBoundingRect(const QGraphicsLineItem* self, intptr_t slot);
QRectF* QGraphicsLineItem_QBaseBoundingRect(const QGraphicsLineItem* self);
void QGraphicsLineItem_OnShape(const QGraphicsLineItem* self, intptr_t slot);
QPainterPath* QGraphicsLineItem_QBaseShape(const QGraphicsLineItem* self);
void QGraphicsLineItem_OnContains(const QGraphicsLineItem* self, intptr_t slot);
bool QGraphicsLineItem_QBaseContains(const QGraphicsLineItem* self, const QPointF* point);
void QGraphicsLineItem_OnPaint(QGraphicsLineItem* self, intptr_t slot);
void QGraphicsLineItem_QBasePaint(QGraphicsLineItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsLineItem_OnIsObscuredBy(const QGraphicsLineItem* self, intptr_t slot);
bool QGraphicsLineItem_QBaseIsObscuredBy(const QGraphicsLineItem* self, const QGraphicsItem* item);
void QGraphicsLineItem_OnOpaqueArea(const QGraphicsLineItem* self, intptr_t slot);
QPainterPath* QGraphicsLineItem_QBaseOpaqueArea(const QGraphicsLineItem* self);
void QGraphicsLineItem_OnType(const QGraphicsLineItem* self, intptr_t slot);
int QGraphicsLineItem_QBaseType(const QGraphicsLineItem* self);
void QGraphicsLineItem_OnSupportsExtension(const QGraphicsLineItem* self, intptr_t slot);
bool QGraphicsLineItem_QBaseSupportsExtension(const QGraphicsLineItem* self, int extension);
void QGraphicsLineItem_OnSetExtension(QGraphicsLineItem* self, intptr_t slot);
void QGraphicsLineItem_QBaseSetExtension(QGraphicsLineItem* self, int extension, const QVariant* variant);
void QGraphicsLineItem_OnExtension(const QGraphicsLineItem* self, intptr_t slot);
QVariant* QGraphicsLineItem_QBaseExtension(const QGraphicsLineItem* self, const QVariant* variant);
void QGraphicsLineItem_Delete(QGraphicsLineItem* self);

QGraphicsPixmapItem* QGraphicsPixmapItem_new();
QGraphicsPixmapItem* QGraphicsPixmapItem_new2(const QPixmap* pixmap);
QGraphicsPixmapItem* QGraphicsPixmapItem_new3(QGraphicsItem* parent);
QGraphicsPixmapItem* QGraphicsPixmapItem_new4(const QPixmap* pixmap, QGraphicsItem* parent);
QPixmap* QGraphicsPixmapItem_Pixmap(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetPixmap(QGraphicsPixmapItem* self, const QPixmap* pixmap);
int QGraphicsPixmapItem_TransformationMode(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetTransformationMode(QGraphicsPixmapItem* self, int mode);
QPointF* QGraphicsPixmapItem_Offset(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetOffset(QGraphicsPixmapItem* self, const QPointF* offset);
void QGraphicsPixmapItem_SetOffset2(QGraphicsPixmapItem* self, double x, double y);
QRectF* QGraphicsPixmapItem_BoundingRect(const QGraphicsPixmapItem* self);
QPainterPath* QGraphicsPixmapItem_Shape(const QGraphicsPixmapItem* self);
bool QGraphicsPixmapItem_Contains(const QGraphicsPixmapItem* self, const QPointF* point);
void QGraphicsPixmapItem_Paint(QGraphicsPixmapItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsPixmapItem_IsObscuredBy(const QGraphicsPixmapItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsPixmapItem_OpaqueArea(const QGraphicsPixmapItem* self);
int QGraphicsPixmapItem_Type(const QGraphicsPixmapItem* self);
int QGraphicsPixmapItem_ShapeMode(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_SetShapeMode(QGraphicsPixmapItem* self, int mode);
bool QGraphicsPixmapItem_SupportsExtension(const QGraphicsPixmapItem* self, int extension);
void QGraphicsPixmapItem_SetExtension(QGraphicsPixmapItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsPixmapItem_Extension(const QGraphicsPixmapItem* self, const QVariant* variant);
void QGraphicsPixmapItem_OnBoundingRect(const QGraphicsPixmapItem* self, intptr_t slot);
QRectF* QGraphicsPixmapItem_QBaseBoundingRect(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_OnShape(const QGraphicsPixmapItem* self, intptr_t slot);
QPainterPath* QGraphicsPixmapItem_QBaseShape(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_OnContains(const QGraphicsPixmapItem* self, intptr_t slot);
bool QGraphicsPixmapItem_QBaseContains(const QGraphicsPixmapItem* self, const QPointF* point);
void QGraphicsPixmapItem_OnPaint(QGraphicsPixmapItem* self, intptr_t slot);
void QGraphicsPixmapItem_QBasePaint(QGraphicsPixmapItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsPixmapItem_OnIsObscuredBy(const QGraphicsPixmapItem* self, intptr_t slot);
bool QGraphicsPixmapItem_QBaseIsObscuredBy(const QGraphicsPixmapItem* self, const QGraphicsItem* item);
void QGraphicsPixmapItem_OnOpaqueArea(const QGraphicsPixmapItem* self, intptr_t slot);
QPainterPath* QGraphicsPixmapItem_QBaseOpaqueArea(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_OnType(const QGraphicsPixmapItem* self, intptr_t slot);
int QGraphicsPixmapItem_QBaseType(const QGraphicsPixmapItem* self);
void QGraphicsPixmapItem_OnSupportsExtension(const QGraphicsPixmapItem* self, intptr_t slot);
bool QGraphicsPixmapItem_QBaseSupportsExtension(const QGraphicsPixmapItem* self, int extension);
void QGraphicsPixmapItem_OnSetExtension(QGraphicsPixmapItem* self, intptr_t slot);
void QGraphicsPixmapItem_QBaseSetExtension(QGraphicsPixmapItem* self, int extension, const QVariant* variant);
void QGraphicsPixmapItem_OnExtension(const QGraphicsPixmapItem* self, intptr_t slot);
QVariant* QGraphicsPixmapItem_QBaseExtension(const QGraphicsPixmapItem* self, const QVariant* variant);
void QGraphicsPixmapItem_Delete(QGraphicsPixmapItem* self);

QGraphicsTextItem* QGraphicsTextItem_new();
QGraphicsTextItem* QGraphicsTextItem_new2(const libqt_string text);
QGraphicsTextItem* QGraphicsTextItem_new3(QGraphicsItem* parent);
QGraphicsTextItem* QGraphicsTextItem_new4(const libqt_string text, QGraphicsItem* parent);
libqt_string QGraphicsTextItem_Tr(const char* s);
libqt_string QGraphicsTextItem_ToHtml(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetHtml(QGraphicsTextItem* self, const libqt_string html);
libqt_string QGraphicsTextItem_ToPlainText(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetPlainText(QGraphicsTextItem* self, const libqt_string text);
QFont* QGraphicsTextItem_Font(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetFont(QGraphicsTextItem* self, const QFont* font);
void QGraphicsTextItem_SetDefaultTextColor(QGraphicsTextItem* self, const QColor* c);
QColor* QGraphicsTextItem_DefaultTextColor(const QGraphicsTextItem* self);
QRectF* QGraphicsTextItem_BoundingRect(const QGraphicsTextItem* self);
QPainterPath* QGraphicsTextItem_Shape(const QGraphicsTextItem* self);
bool QGraphicsTextItem_Contains(const QGraphicsTextItem* self, const QPointF* point);
void QGraphicsTextItem_Paint(QGraphicsTextItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsTextItem_IsObscuredBy(const QGraphicsTextItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsTextItem_OpaqueArea(const QGraphicsTextItem* self);
int QGraphicsTextItem_Type(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTextWidth(QGraphicsTextItem* self, double width);
double QGraphicsTextItem_TextWidth(const QGraphicsTextItem* self);
void QGraphicsTextItem_AdjustSize(QGraphicsTextItem* self);
void QGraphicsTextItem_SetDocument(QGraphicsTextItem* self, QTextDocument* document);
QTextDocument* QGraphicsTextItem_Document(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTextInteractionFlags(QGraphicsTextItem* self, int flags);
int QGraphicsTextItem_TextInteractionFlags(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTabChangesFocus(QGraphicsTextItem* self, bool b);
bool QGraphicsTextItem_TabChangesFocus(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetOpenExternalLinks(QGraphicsTextItem* self, bool open);
bool QGraphicsTextItem_OpenExternalLinks(const QGraphicsTextItem* self);
void QGraphicsTextItem_SetTextCursor(QGraphicsTextItem* self, const QTextCursor* cursor);
QTextCursor* QGraphicsTextItem_TextCursor(const QGraphicsTextItem* self);
void QGraphicsTextItem_LinkActivated(QGraphicsTextItem* self, const libqt_string param1);
void QGraphicsTextItem_Connect_LinkActivated(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_LinkHovered(QGraphicsTextItem* self, const libqt_string param1);
void QGraphicsTextItem_Connect_LinkHovered(QGraphicsTextItem* self, intptr_t slot);
bool QGraphicsTextItem_SceneEvent(QGraphicsTextItem* self, QEvent* event);
void QGraphicsTextItem_MousePressEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_MouseMoveEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_MouseReleaseEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_MouseDoubleClickEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_ContextMenuEvent(QGraphicsTextItem* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsTextItem_KeyPressEvent(QGraphicsTextItem* self, QKeyEvent* event);
void QGraphicsTextItem_KeyReleaseEvent(QGraphicsTextItem* self, QKeyEvent* event);
void QGraphicsTextItem_FocusInEvent(QGraphicsTextItem* self, QFocusEvent* event);
void QGraphicsTextItem_FocusOutEvent(QGraphicsTextItem* self, QFocusEvent* event);
void QGraphicsTextItem_DragEnterEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_DragLeaveEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_DragMoveEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_DropEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_InputMethodEvent(QGraphicsTextItem* self, QInputMethodEvent* event);
void QGraphicsTextItem_HoverEnterEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_HoverMoveEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_HoverLeaveEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
QVariant* QGraphicsTextItem_InputMethodQuery(const QGraphicsTextItem* self, int query);
bool QGraphicsTextItem_SupportsExtension(const QGraphicsTextItem* self, int extension);
void QGraphicsTextItem_SetExtension(QGraphicsTextItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsTextItem_Extension(const QGraphicsTextItem* self, const QVariant* variant);
libqt_string QGraphicsTextItem_Tr2(const char* s, const char* c);
libqt_string QGraphicsTextItem_Tr3(const char* s, const char* c, int n);
void QGraphicsTextItem_OnBoundingRect(const QGraphicsTextItem* self, intptr_t slot);
QRectF* QGraphicsTextItem_QBaseBoundingRect(const QGraphicsTextItem* self);
void QGraphicsTextItem_OnShape(const QGraphicsTextItem* self, intptr_t slot);
QPainterPath* QGraphicsTextItem_QBaseShape(const QGraphicsTextItem* self);
void QGraphicsTextItem_OnContains(const QGraphicsTextItem* self, intptr_t slot);
bool QGraphicsTextItem_QBaseContains(const QGraphicsTextItem* self, const QPointF* point);
void QGraphicsTextItem_OnPaint(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBasePaint(QGraphicsTextItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsTextItem_OnIsObscuredBy(const QGraphicsTextItem* self, intptr_t slot);
bool QGraphicsTextItem_QBaseIsObscuredBy(const QGraphicsTextItem* self, const QGraphicsItem* item);
void QGraphicsTextItem_OnOpaqueArea(const QGraphicsTextItem* self, intptr_t slot);
QPainterPath* QGraphicsTextItem_QBaseOpaqueArea(const QGraphicsTextItem* self);
void QGraphicsTextItem_OnType(const QGraphicsTextItem* self, intptr_t slot);
int QGraphicsTextItem_QBaseType(const QGraphicsTextItem* self);
void QGraphicsTextItem_OnSceneEvent(QGraphicsTextItem* self, intptr_t slot);
bool QGraphicsTextItem_QBaseSceneEvent(QGraphicsTextItem* self, QEvent* event);
void QGraphicsTextItem_OnMousePressEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseMousePressEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_OnMouseMoveEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseMouseMoveEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_OnMouseReleaseEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseMouseReleaseEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_OnMouseDoubleClickEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseMouseDoubleClickEvent(QGraphicsTextItem* self, QGraphicsSceneMouseEvent* event);
void QGraphicsTextItem_OnContextMenuEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseContextMenuEvent(QGraphicsTextItem* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsTextItem_OnKeyPressEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseKeyPressEvent(QGraphicsTextItem* self, QKeyEvent* event);
void QGraphicsTextItem_OnKeyReleaseEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseKeyReleaseEvent(QGraphicsTextItem* self, QKeyEvent* event);
void QGraphicsTextItem_OnFocusInEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseFocusInEvent(QGraphicsTextItem* self, QFocusEvent* event);
void QGraphicsTextItem_OnFocusOutEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseFocusOutEvent(QGraphicsTextItem* self, QFocusEvent* event);
void QGraphicsTextItem_OnDragEnterEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseDragEnterEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_OnDragLeaveEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseDragLeaveEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_OnDragMoveEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseDragMoveEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_OnDropEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseDropEvent(QGraphicsTextItem* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsTextItem_OnInputMethodEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseInputMethodEvent(QGraphicsTextItem* self, QInputMethodEvent* event);
void QGraphicsTextItem_OnHoverEnterEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseHoverEnterEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_OnHoverMoveEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseHoverMoveEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_OnHoverLeaveEvent(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseHoverLeaveEvent(QGraphicsTextItem* self, QGraphicsSceneHoverEvent* event);
void QGraphicsTextItem_OnInputMethodQuery(const QGraphicsTextItem* self, intptr_t slot);
QVariant* QGraphicsTextItem_QBaseInputMethodQuery(const QGraphicsTextItem* self, int query);
void QGraphicsTextItem_OnSupportsExtension(const QGraphicsTextItem* self, intptr_t slot);
bool QGraphicsTextItem_QBaseSupportsExtension(const QGraphicsTextItem* self, int extension);
void QGraphicsTextItem_OnSetExtension(QGraphicsTextItem* self, intptr_t slot);
void QGraphicsTextItem_QBaseSetExtension(QGraphicsTextItem* self, int extension, const QVariant* variant);
void QGraphicsTextItem_OnExtension(const QGraphicsTextItem* self, intptr_t slot);
QVariant* QGraphicsTextItem_QBaseExtension(const QGraphicsTextItem* self, const QVariant* variant);
void QGraphicsTextItem_Delete(QGraphicsTextItem* self);

QGraphicsSimpleTextItem* QGraphicsSimpleTextItem_new();
QGraphicsSimpleTextItem* QGraphicsSimpleTextItem_new2(const libqt_string text);
QGraphicsSimpleTextItem* QGraphicsSimpleTextItem_new3(QGraphicsItem* parent);
QGraphicsSimpleTextItem* QGraphicsSimpleTextItem_new4(const libqt_string text, QGraphicsItem* parent);
void QGraphicsSimpleTextItem_SetText(QGraphicsSimpleTextItem* self, const libqt_string text);
libqt_string QGraphicsSimpleTextItem_Text(const QGraphicsSimpleTextItem* self);
void QGraphicsSimpleTextItem_SetFont(QGraphicsSimpleTextItem* self, const QFont* font);
QFont* QGraphicsSimpleTextItem_Font(const QGraphicsSimpleTextItem* self);
QRectF* QGraphicsSimpleTextItem_BoundingRect(const QGraphicsSimpleTextItem* self);
QPainterPath* QGraphicsSimpleTextItem_Shape(const QGraphicsSimpleTextItem* self);
bool QGraphicsSimpleTextItem_Contains(const QGraphicsSimpleTextItem* self, const QPointF* point);
void QGraphicsSimpleTextItem_Paint(QGraphicsSimpleTextItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsSimpleTextItem_IsObscuredBy(const QGraphicsSimpleTextItem* self, const QGraphicsItem* item);
QPainterPath* QGraphicsSimpleTextItem_OpaqueArea(const QGraphicsSimpleTextItem* self);
int QGraphicsSimpleTextItem_Type(const QGraphicsSimpleTextItem* self);
bool QGraphicsSimpleTextItem_SupportsExtension(const QGraphicsSimpleTextItem* self, int extension);
void QGraphicsSimpleTextItem_SetExtension(QGraphicsSimpleTextItem* self, int extension, const QVariant* variant);
QVariant* QGraphicsSimpleTextItem_Extension(const QGraphicsSimpleTextItem* self, const QVariant* variant);
void QGraphicsSimpleTextItem_OnBoundingRect(const QGraphicsSimpleTextItem* self, intptr_t slot);
QRectF* QGraphicsSimpleTextItem_QBaseBoundingRect(const QGraphicsSimpleTextItem* self);
void QGraphicsSimpleTextItem_OnShape(const QGraphicsSimpleTextItem* self, intptr_t slot);
QPainterPath* QGraphicsSimpleTextItem_QBaseShape(const QGraphicsSimpleTextItem* self);
void QGraphicsSimpleTextItem_OnContains(const QGraphicsSimpleTextItem* self, intptr_t slot);
bool QGraphicsSimpleTextItem_QBaseContains(const QGraphicsSimpleTextItem* self, const QPointF* point);
void QGraphicsSimpleTextItem_OnPaint(QGraphicsSimpleTextItem* self, intptr_t slot);
void QGraphicsSimpleTextItem_QBasePaint(QGraphicsSimpleTextItem* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsSimpleTextItem_OnIsObscuredBy(const QGraphicsSimpleTextItem* self, intptr_t slot);
bool QGraphicsSimpleTextItem_QBaseIsObscuredBy(const QGraphicsSimpleTextItem* self, const QGraphicsItem* item);
void QGraphicsSimpleTextItem_OnOpaqueArea(const QGraphicsSimpleTextItem* self, intptr_t slot);
QPainterPath* QGraphicsSimpleTextItem_QBaseOpaqueArea(const QGraphicsSimpleTextItem* self);
void QGraphicsSimpleTextItem_OnType(const QGraphicsSimpleTextItem* self, intptr_t slot);
int QGraphicsSimpleTextItem_QBaseType(const QGraphicsSimpleTextItem* self);
void QGraphicsSimpleTextItem_OnSupportsExtension(const QGraphicsSimpleTextItem* self, intptr_t slot);
bool QGraphicsSimpleTextItem_QBaseSupportsExtension(const QGraphicsSimpleTextItem* self, int extension);
void QGraphicsSimpleTextItem_OnSetExtension(QGraphicsSimpleTextItem* self, intptr_t slot);
void QGraphicsSimpleTextItem_QBaseSetExtension(QGraphicsSimpleTextItem* self, int extension, const QVariant* variant);
void QGraphicsSimpleTextItem_OnExtension(const QGraphicsSimpleTextItem* self, intptr_t slot);
QVariant* QGraphicsSimpleTextItem_QBaseExtension(const QGraphicsSimpleTextItem* self, const QVariant* variant);
void QGraphicsSimpleTextItem_Delete(QGraphicsSimpleTextItem* self);

QGraphicsItemGroup* QGraphicsItemGroup_new();
QGraphicsItemGroup* QGraphicsItemGroup_new2(QGraphicsItem* parent);
void QGraphicsItemGroup_AddToGroup(QGraphicsItemGroup* self, QGraphicsItem* item);
void QGraphicsItemGroup_RemoveFromGroup(QGraphicsItemGroup* self, QGraphicsItem* item);
QRectF* QGraphicsItemGroup_BoundingRect(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_Paint(QGraphicsItemGroup* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
bool QGraphicsItemGroup_IsObscuredBy(const QGraphicsItemGroup* self, const QGraphicsItem* item);
QPainterPath* QGraphicsItemGroup_OpaqueArea(const QGraphicsItemGroup* self);
int QGraphicsItemGroup_Type(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_OnBoundingRect(const QGraphicsItemGroup* self, intptr_t slot);
QRectF* QGraphicsItemGroup_QBaseBoundingRect(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_OnPaint(QGraphicsItemGroup* self, intptr_t slot);
void QGraphicsItemGroup_QBasePaint(QGraphicsItemGroup* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsItemGroup_OnIsObscuredBy(const QGraphicsItemGroup* self, intptr_t slot);
bool QGraphicsItemGroup_QBaseIsObscuredBy(const QGraphicsItemGroup* self, const QGraphicsItem* item);
void QGraphicsItemGroup_OnOpaqueArea(const QGraphicsItemGroup* self, intptr_t slot);
QPainterPath* QGraphicsItemGroup_QBaseOpaqueArea(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_OnType(const QGraphicsItemGroup* self, intptr_t slot);
int QGraphicsItemGroup_QBaseType(const QGraphicsItemGroup* self);
void QGraphicsItemGroup_Delete(QGraphicsItemGroup* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
