// THIS FILE IS AUTOMATICALLY GENERATED
// Root module for qt6zig - re-exports all Qt binding types and enums

pub const C = @import("qtzig");

// Qt Core
pub const qcoreevent = @import("src/libqcoreevent.zig").qevent;
pub const qtimerevent = @import("src/libqcoreevent.zig").qtimerevent;
pub const qchildevent = @import("src/libqcoreevent.zig").qchildevent;
pub const qdynamicpropertychangeevent = @import("src/libqcoreevent.zig").qdynamicpropertychangeevent;
pub const qcoreapplication = @import("src/libqcoreapplication.zig").qcoreapplication;
pub const qdir = @import("src/libqdir.zig").qdir;
pub const qeventloop = @import("src/libqeventloop.zig").qeventloop;
pub const qeventlooplocker = @import("src/libqeventloop.zig").qeventlooplocker;
pub const qgenericargument = @import("src/libqobjectdefs.zig").qgenericargument;
pub const qgenericreturnargument = @import("src/libqobjectdefs.zig").qgenericreturnargument;
pub const qinternal = @import("src/libqnamespace.zig").qinternal;
pub const qitemselection = @import("src/libqitemselectionmodel.zig").qitemselection;
pub const qitemselectionmodel = @import("src/libqitemselectionmodel.zig").qitemselectionmodel;
pub const qitemselectionrange = @import("src/libqitemselectionmodel.zig").qitemselectionrange;
pub const qkeycombination = @import("src/libqnamespace.zig").qkeycombination;
pub const qkeysequence = @import("src/libqkeysequence.zig").qkeysequence;
pub const qmetamethodargument = @import("src/libqobjectdefs.zig").qmetamethodargument;
pub const qmetamethodreturnargument = @import("src/libqobjectdefs.zig").qmetamethodreturnargument;
pub const qmetaobject = @import("src/libqobjectdefs.zig").qmetaobject;
pub const qmetaobject__connection = @import("src/libqobjectdefs.zig").qmetaobject__connection;
pub const qmetaobject__data = @import("src/libqobjectdefs.zig").qmetaobject__data;
pub const qmetaobject__superdata = @import("src/libqobjectdefs.zig").qmetaobject__superdata;
pub const qobject = @import("src/libqobject.zig").qobject;
pub const qobjectdata = @import("src/libqobject.zig").qobjectdata;
pub const qsignalblocker = @import("src/libqobject.zig").qsignalblocker;
pub const qtimer = @import("src/libqtimer.zig").qtimer;

// Qt Core enums
pub const qcoreevent_enums = @import("src/libqcoreevent.zig").enums;
pub const qcoreapplication_enums = @import("src/libqcoreapplication.zig").enums;
pub const qdir_enums = @import("src/libqdir.zig").enums;
pub const qeventloop_enums = @import("src/libqeventloop.zig").enums;
pub const qiodevicebase_enums = @import("src/libqiodevicebase.zig").enums;
pub const qitemselectionmodel_enums = @import("src/libqitemselectionmodel.zig").enums;
pub const qkeysequence_enums = @import("src/libqkeysequence.zig").enums;
pub const qnamespace_enums = @import("src/libqnamespace.zig").enums;
pub const qobject_enums = @import("src/libqobject.zig").enums;
pub const qobjectdefs_enums = @import("src/libqobjectdefs.zig").enums;

// Qt GUI
pub const qcolor = @import("src/libqcolor.zig").qcolor;
pub const qeventpoint = @import("src/libqeventpoint.zig").qeventpoint;
pub const qfont = @import("src/libqfont.zig").qfont;
pub const qfont__tag = @import("src/libqfont.zig").qfont__tag;
pub const qguiapplication = @import("src/libqguiapplication.zig").qguiapplication;
pub const qicon = @import("src/libqicon.zig").qicon;
pub const qimage = @import("src/libqimage.zig").qimage;
pub const qinputdevice = @import("src/libqinputdevice.zig").qinputdevice;
pub const qiodevicebase = @import("src/libqiodevicebase.zig").qiodevicebase;
pub const qpaintdevice = @import("src/libqpaintdevice.zig").qpaintdevice;
pub const qpalette = @import("src/libqpalette.zig").qpalette;
pub const qpixmap = @import("src/libqpixmap.zig").qpixmap;
pub const qpointingdevice = @import("src/libqpointingdevice.zig").qpointingdevice;
pub const qpointingdeviceuniqueid = @import("src/libqpointingdevice.zig").qpointingdeviceuniqueid;

// Qt GUI enums
pub const qcolor_enums = @import("src/libqcolor.zig").enums;
pub const qevent_enums = @import("src/libqevent.zig").enums;
pub const qeventpoint_enums = @import("src/libqeventpoint.zig").enums;
pub const qfont_enums = @import("src/libqfont.zig").enums;
pub const qicon_enums = @import("src/libqicon.zig").enums;
pub const qimage_enums = @import("src/libqimage.zig").enums;
pub const qinputdevice_enums = @import("src/libqinputdevice.zig").enums;
pub const qpaintdevice_enums = @import("src/libqpaintdevice.zig").enums;
pub const qpalette_enums = @import("src/libqpalette.zig").enums;
pub const qpointingdevice_enums = @import("src/libqpointingdevice.zig").enums;
pub const qvalidator_enums = @import("src/libqvalidator.zig").enums;

// Qt GUI events
pub const qactionevent = @import("src/libqevent.zig").qactionevent;
pub const qapplicationstatechangeevent = @import("src/libqevent.zig").qapplicationstatechangeevent;
pub const qchildwindowevent = @import("src/libqevent.zig").qchildwindowevent;
pub const qcloseevent = @import("src/libqevent.zig").qcloseevent;
pub const qcontextmenuevent = @import("src/libqevent.zig").qcontextmenuevent;
pub const qdragenterevent = @import("src/libqevent.zig").qdragenterevent;
pub const qdragleaveevent = @import("src/libqevent.zig").qdragleaveevent;
pub const qdragmoveevent = @import("src/libqevent.zig").qdragmoveevent;
pub const qdropevent = @import("src/libqevent.zig").qdropevent;
pub const qenterevent = @import("src/libqevent.zig").qenterevent;
pub const qexposeevent = @import("src/libqevent.zig").qexposeevent;
pub const qfileopenevent = @import("src/libqevent.zig").qfileopenevent;
pub const qfocusevent = @import("src/libqevent.zig").qfocusevent;
pub const qhelpevent = @import("src/libqevent.zig").qhelpevent;
pub const qhideevent = @import("src/libqevent.zig").qhideevent;
pub const qhoverevent = @import("src/libqevent.zig").qhoverevent;
pub const qicondragevent = @import("src/libqevent.zig").qicondragevent;
pub const qinputevent = @import("src/libqevent.zig").qinputevent;
pub const qinputmethodevent = @import("src/libqevent.zig").qinputmethodevent;
pub const qinputmethodevent__attribute = @import("src/libqevent.zig").qinputmethodevent__attribute;
pub const qinputmethodqueryevent = @import("src/libqevent.zig").qinputmethodqueryevent;
pub const qkeyevent = @import("src/libqevent.zig").qkeyevent;
pub const qmouseevent = @import("src/libqevent.zig").qmouseevent;
pub const qmoveevent = @import("src/libqevent.zig").qmoveevent;
pub const qnativegestureevent = @import("src/libqevent.zig").qnativegestureevent;
pub const qpaintevent = @import("src/libqevent.zig").qpaintevent;
pub const qplatformsurfaceevent = @import("src/libqevent.zig").qplatformsurfaceevent;
pub const qpointerevent = @import("src/libqevent.zig").qpointerevent;
pub const qresizeevent = @import("src/libqevent.zig").qresizeevent;
pub const qscreenorientationchangeevent = @import("src/libqevent.zig").qscreenorientationchangeevent;
pub const qscrollevent = @import("src/libqevent.zig").qscrollevent;
pub const qscrollprepareevent = @import("src/libqevent.zig").qscrollprepareevent;
pub const qshortcutevent = @import("src/libqevent.zig").qshortcutevent;
pub const qshowevent = @import("src/libqevent.zig").qshowevent;
pub const qsinglepointevent = @import("src/libqevent.zig").qsinglepointevent;
pub const qstatustipevent = @import("src/libqevent.zig").qstatustipevent;
pub const qtabletevent = @import("src/libqevent.zig").qtabletevent;
pub const qtoolbarchangeevent = @import("src/libqevent.zig").qtoolbarchangeevent;
pub const qtouchevent = @import("src/libqevent.zig").qtouchevent;
pub const qwhatsthisclickedevent = @import("src/libqevent.zig").qwhatsthisclickedevent;
pub const qwheelevent = @import("src/libqevent.zig").qwheelevent;
pub const qwindowstatechangeevent = @import("src/libqevent.zig").qwindowstatechangeevent;

// Qt GUI validators
pub const qdoublevalidator = @import("src/libqvalidator.zig").qdoublevalidator;
pub const qintvalidator = @import("src/libqvalidator.zig").qintvalidator;
pub const qregularexpressionvalidator = @import("src/libqvalidator.zig").qregularexpressionvalidator;
pub const qvalidator = @import("src/libqvalidator.zig").qvalidator;

// Qt Widgets
pub const qabstractbutton = @import("src/libqabstractbutton.zig").qabstractbutton;
pub const qabstractitemdelegate = @import("src/libqabstractitemdelegate.zig").qabstractitemdelegate;
pub const qabstractitemview = @import("src/libqabstractitemview.zig").qabstractitemview;
pub const qabstractscrollarea = @import("src/libqabstractscrollarea.zig").qabstractscrollarea;
pub const qabstractspinbox = @import("src/libqabstractspinbox.zig").qabstractspinbox;
pub const qaction = @import("src/libqaction.zig").qaction;
pub const qapplication = @import("src/libqapplication.zig").qapplication;
pub const qboxlayout = @import("src/libqboxlayout.zig").qboxlayout;
pub const qhboxlayout = @import("src/libqboxlayout.zig").qhboxlayout;
pub const qvboxlayout = @import("src/libqboxlayout.zig").qvboxlayout;
pub const qcheckbox = @import("src/libqcheckbox.zig").qcheckbox;
pub const qcombobox = @import("src/libqcombobox.zig").qcombobox;
pub const qdialog = @import("src/libqdialog.zig").qdialog;
pub const qfiledialog = @import("src/libqfiledialog.zig").qfiledialog;
pub const qframe = @import("src/libqframe.zig").qframe;
pub const qgridlayout = @import("src/libqgridlayout.zig").qgridlayout;
pub const qlabel = @import("src/libqlabel.zig").qlabel;
pub const qlayout = @import("src/libqlayout.zig").qlayout;
pub const qlineedit = @import("src/libqlineedit.zig").qlineedit;
pub const qmessagebox = @import("src/libqmessagebox.zig").qmessagebox;
pub const qprogressbar = @import("src/libqprogressbar.zig").qprogressbar;
pub const qpushbutton = @import("src/libqpushbutton.zig").qpushbutton;
pub const qscrollarea = @import("src/libqscrollarea.zig").qscrollarea;
pub const qsizepolicy = @import("src/libqsizepolicy.zig").qsizepolicy;
pub const qdoublespinbox = @import("src/libqspinbox.zig").qdoublespinbox;
pub const qspinbox = @import("src/libqspinbox.zig").qspinbox;
pub const qsplitter = @import("src/libqsplitter.zig").qsplitter;
pub const qsplitterhandle = @import("src/libqsplitter.zig").qsplitterhandle;
pub const qstackedwidget = @import("src/libqstackedwidget.zig").qstackedwidget;
pub const qtablewidget = @import("src/libqtablewidget.zig").qtablewidget;
pub const qtablewidgetitem = @import("src/libqtablewidget.zig").qtablewidgetitem;
pub const qtablewidgetselectionrange = @import("src/libqtablewidget.zig").qtablewidgetselectionrange;
pub const qabstractundoitem = @import("src/libqtextdocument.zig").qabstractundoitem;
pub const qtextblockformat = @import("src/libqtextformat.zig").qtextblockformat;
pub const qtextcharformat = @import("src/libqtextformat.zig").qtextcharformat;
pub const qtextcursor = @import("src/libqtextcursor.zig").qtextcursor;
pub const qtextdocument = @import("src/libqtextdocument.zig").qtextdocument;
pub const qtextedit = @import("src/libqtextedit.zig").qtextedit;
pub const qtextedit__extraselection = @import("src/libqtextedit.zig").qtextedit__extraselection;
pub const qtextformat = @import("src/libqtextformat.zig").qtextformat;
pub const qtextframeformat = @import("src/libqtextformat.zig").qtextframeformat;
pub const qtextimageformat = @import("src/libqtextformat.zig").qtextimageformat;
pub const qtextlength = @import("src/libqtextformat.zig").qtextlength;
pub const qtextlistformat = @import("src/libqtextformat.zig").qtextlistformat;
pub const qtextoption = @import("src/libqtextoption.zig").qtextoption;
pub const qtextoption__tab = @import("src/libqtextoption.zig").qtextoption__tab;
pub const qtexttablecellformat = @import("src/libqtextformat.zig").qtexttablecellformat;
pub const qtexttableformat = @import("src/libqtextformat.zig").qtexttableformat;
pub const qwidget = @import("src/libqwidget.zig").qwidget;
pub const qwidgetdata = @import("src/libqwidget.zig").qwidgetdata;
pub const qwidgetaction = @import("src/libqwidgetaction.zig").qwidgetaction;

// Qt Widget enums
pub const qabstractitemdelegate_enums = @import("src/libqabstractitemdelegate.zig").enums;
pub const qabstractitemview_enums = @import("src/libqabstractitemview.zig").enums;
pub const qabstractscrollarea_enums = @import("src/libqabstractscrollarea.zig").enums;
pub const qabstractspinbox_enums = @import("src/libqabstractspinbox.zig").enums;
pub const qaction_enums = @import("src/libqaction.zig").enums;
pub const qboxlayout_enums = @import("src/libqboxlayout.zig").enums;
pub const qcombobox_enums = @import("src/libqcombobox.zig").enums;
pub const qdialog_enums = @import("src/libqdialog.zig").enums;
pub const qfiledialog_enums = @import("src/libqfiledialog.zig").enums;
pub const qframe_enums = @import("src/libqframe.zig").enums;
pub const qlayout_enums = @import("src/libqlayout.zig").enums;
pub const qlineedit_enums = @import("src/libqlineedit.zig").enums;
pub const qmessagebox_enums = @import("src/libqmessagebox.zig").enums;
pub const qprogressbar_enums = @import("src/libqprogressbar.zig").enums;
pub const qsizepolicy_enums = @import("src/libqsizepolicy.zig").enums;
pub const qtablewidget_enums = @import("src/libqtablewidget.zig").enums;
pub const qtextcursor_enums = @import("src/libqtextcursor.zig").enums;
pub const qtextdocument_enums = @import("src/libqtextdocument.zig").enums;
pub const qtextedit_enums = @import("src/libqtextedit.zig").enums;
pub const qtextformat_enums = @import("src/libqtextformat.zig").enums;
pub const qtextoption_enums = @import("src/libqtextoption.zig").enums;
pub const qwidget_enums = @import("src/libqwidget.zig").enums;

// Additional types needed by mpod viewer
pub const qcursor = @import("src/libqcursor.zig").qcursor;
pub const qscrollbar = @import("src/libqscrollbar.zig").qscrollbar;
pub const qabstractslider = @import("src/libqabstractslider.zig").qabstractslider;

// Painting and printing
pub const qpainter = @import("src/libqpainter.zig").qpainter;
pub const qprinter = @import("src/printsupport/libqprinter.zig").qprinter;

// QPoint/QPointF accessors (no generated wrapper in src/)
const qtc = @import("qt6c");
pub const qpoint = struct {
    pub fn X(self: ?*anyopaque) i32 {
        return qtc.QPoint_X(@ptrCast(self));
    }
    pub fn Y(self: ?*anyopaque) i32 {
        return qtc.QPoint_Y(@ptrCast(self));
    }
};
pub const qpointf = struct {
    pub fn X(self: ?*anyopaque) f64 {
        return qtc.QPointF_X(@ptrCast(self));
    }
    pub fn Y(self: ?*anyopaque) f64 {
        return qtc.QPointF_Y(@ptrCast(self));
    }
};

// Platform plugin registration - must be called before QApplication.New()
pub fn registerPlatformPlugins() void {
    qtc.qt6zig_register_platform_plugins();
}
