// THIS FILE IS AUTOMATICALLY GENERATED
// Root module for qt6zig - re-exports all Qt binding types and enums

pub const C = @import("qtzig");

// Qt Core
pub const qcoreevent = @import("src/libqcoreevent.zig").qevent;
pub const qtimerevent = @import("src/libqcoreevent.zig").qtimerevent;
pub const qchildevent = @import("src/libqcoreevent.zig").qchildevent;
pub const qdynamicpropertychangeevent = @import("src/libqcoreevent.zig").qdynamicpropertychangeevent;
pub const qcoreapplication = @import("src/libqcoreapplication.zig").qcoreapplication;

// Qt Core enums
pub const qcoreevent_enums = @import("src/libqcoreevent.zig").enums;
pub const qnamespace_enums = @import("src/libqnamespace.zig").enums;
pub const qobjectdefs_enums = @import("src/libqobjectdefs.zig").enums;
pub const qkeysequence_enums = @import("src/libqkeysequence.zig").enums;
pub const qeventloop_enums = @import("src/libqeventloop.zig").enums;

// Qt GUI
pub const qguiapplication = @import("src/libqguiapplication.zig").qguiapplication;
pub const qpaintdevice_enums = @import("src/libqpaintdevice.zig").enums;
pub const qpalette_enums = @import("src/libqpalette.zig").enums;

// Qt Widgets
pub const qabstractbutton = @import("src/libqabstractbutton.zig").qabstractbutton;
pub const qapplication = @import("src/libqapplication.zig").qapplication;
pub const qpushbutton = @import("src/libqpushbutton.zig").qpushbutton;
pub const qwidget = @import("src/libqwidget.zig").qwidget;
pub const qwidgetaction = @import("src/libqwidgetaction.zig").qwidgetaction;

// Qt Widget enums
pub const qwidget_enums = @import("src/libqwidget.zig").enums;
pub const qsizepolicy_enums = @import("src/libqsizepolicy.zig").enums;
pub const qaction_enums = @import("src/libqaction.zig").enums;

// Platform plugin registration - must be called before QApplication.New()
const qtc = @import("qt6c");
pub fn registerPlatformPlugins() void {
    qtc.qt6zig_register_platform_plugins();
}
