#pragma once
#ifndef QOPENGLFUNCTIONS_4_1_CORE_H_C_LIB
#define QOPENGLFUNCTIONS_4_1_CORE_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_4_1_Core QOpenGLFunctions_4_1_Core;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_4_1_Core* QOpenGLFunctions_4_1_Core_new();
bool QOpenGLFunctions_4_1_Core_InitializeOpenGLFunctions(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlViewport(QOpenGLFunctions_4_1_Core* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlDepthRange(QOpenGLFunctions_4_1_Core* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_4_1_Core_GlIsEnabled(QOpenGLFunctions_4_1_Core* self, uint32_t cap);
void QOpenGLFunctions_4_1_Core_GlGetTexLevelParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetTexLevelParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_4_1_Core_GlGetTexParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetTexParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_4_1_Core_GlGetTexImage(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_4_1_Core_GlGetString(QOpenGLFunctions_4_1_Core* self, uint32_t name);
void QOpenGLFunctions_4_1_Core_GlGetIntegerv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetFloatv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, float* params);
void QOpenGLFunctions_4_1_Core_GlGetDoublev(QOpenGLFunctions_4_1_Core* self, uint32_t pname, double* params);
void QOpenGLFunctions_4_1_Core_GlGetBooleanv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_4_1_Core_GlReadPixels(QOpenGLFunctions_4_1_Core* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_4_1_Core_GlReadBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlPixelStorei(QOpenGLFunctions_4_1_Core* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_4_1_Core_GlPixelStoref(QOpenGLFunctions_4_1_Core* self, uint32_t pname, float param);
void QOpenGLFunctions_4_1_Core_GlDepthFunc(QOpenGLFunctions_4_1_Core* self, uint32_t func);
void QOpenGLFunctions_4_1_Core_GlStencilOp(QOpenGLFunctions_4_1_Core* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_4_1_Core_GlStencilFunc(QOpenGLFunctions_4_1_Core* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_4_1_Core_GlLogicOp(QOpenGLFunctions_4_1_Core* self, uint32_t opcode);
void QOpenGLFunctions_4_1_Core_GlBlendFunc(QOpenGLFunctions_4_1_Core* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_4_1_Core_GlFlush(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlFinish(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlEnable(QOpenGLFunctions_4_1_Core* self, uint32_t cap);
void QOpenGLFunctions_4_1_Core_GlDisable(QOpenGLFunctions_4_1_Core* self, uint32_t cap);
void QOpenGLFunctions_4_1_Core_GlDepthMask(QOpenGLFunctions_4_1_Core* self, unsigned char flag);
void QOpenGLFunctions_4_1_Core_GlColorMask(QOpenGLFunctions_4_1_Core* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_4_1_Core_GlStencilMask(QOpenGLFunctions_4_1_Core* self, uint32_t mask);
void QOpenGLFunctions_4_1_Core_GlClearDepth(QOpenGLFunctions_4_1_Core* self, double depth);
void QOpenGLFunctions_4_1_Core_GlClearStencil(QOpenGLFunctions_4_1_Core* self, int32_t s);
void QOpenGLFunctions_4_1_Core_GlClearColor(QOpenGLFunctions_4_1_Core* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_4_1_Core_GlClear(QOpenGLFunctions_4_1_Core* self, uint32_t mask);
void QOpenGLFunctions_4_1_Core_GlDrawBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlTexImage2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_4_1_Core_GlTexImage1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_4_1_Core_GlTexParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_4_1_Core_GlTexParameteri(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_4_1_Core_GlTexParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_4_1_Core_GlTexParameterf(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_4_1_Core_GlScissor(QOpenGLFunctions_4_1_Core* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlPolygonMode(QOpenGLFunctions_4_1_Core* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlPointSize(QOpenGLFunctions_4_1_Core* self, float size);
void QOpenGLFunctions_4_1_Core_GlLineWidth(QOpenGLFunctions_4_1_Core* self, float width);
void QOpenGLFunctions_4_1_Core_GlHint(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlFrontFace(QOpenGLFunctions_4_1_Core* self, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlCullFace(QOpenGLFunctions_4_1_Core* self, uint32_t mode);
unsigned char QOpenGLFunctions_4_1_Core_GlIsTexture(QOpenGLFunctions_4_1_Core* self, uint32_t texture);
void QOpenGLFunctions_4_1_Core_GlGenTextures(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* textures);
void QOpenGLFunctions_4_1_Core_GlDeleteTextures(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* textures);
void QOpenGLFunctions_4_1_Core_GlBindTexture(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t texture);
void QOpenGLFunctions_4_1_Core_GlTexSubImage2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_4_1_Core_GlTexSubImage1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_4_1_Core_GlCopyTexSubImage2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlCopyTexSubImage1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_4_1_Core_GlCopyTexImage2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border);
void QOpenGLFunctions_4_1_Core_GlCopyTexImage1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t border);
void QOpenGLFunctions_4_1_Core_GlPolygonOffset(QOpenGLFunctions_4_1_Core* self, float factor, float units);
void QOpenGLFunctions_4_1_Core_GlDrawElements(QOpenGLFunctions_4_1_Core* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_4_1_Core_GlDrawArrays(QOpenGLFunctions_4_1_Core* self, uint32_t mode, int32_t first, int32_t count);
void QOpenGLFunctions_4_1_Core_GlCopyTexSubImage3D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlTexSubImage3D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_4_1_Core_GlTexImage3D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_4_1_Core_GlDrawRangeElements(QOpenGLFunctions_4_1_Core* self, uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_4_1_Core_GlBlendEquation(QOpenGLFunctions_4_1_Core* self, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlBlendColor(QOpenGLFunctions_4_1_Core* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_4_1_Core_GlGetCompressedTexImage(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, void* img);
void QOpenGLFunctions_4_1_Core_GlCompressedTexSubImage1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_4_1_Core_GlCompressedTexSubImage2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_4_1_Core_GlCompressedTexSubImage3D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_4_1_Core_GlCompressedTexImage1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_4_1_Core_GlCompressedTexImage2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_4_1_Core_GlCompressedTexImage3D(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_4_1_Core_GlSampleCoverage(QOpenGLFunctions_4_1_Core* self, float value, unsigned char invert);
void QOpenGLFunctions_4_1_Core_GlActiveTexture(QOpenGLFunctions_4_1_Core* self, uint32_t texture);
void QOpenGLFunctions_4_1_Core_GlPointParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_4_1_Core_GlPointParameteri(QOpenGLFunctions_4_1_Core* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_4_1_Core_GlPointParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, const float* params);
void QOpenGLFunctions_4_1_Core_GlPointParameterf(QOpenGLFunctions_4_1_Core* self, uint32_t pname, float param);
void QOpenGLFunctions_4_1_Core_GlMultiDrawElements(QOpenGLFunctions_4_1_Core* self, uint32_t mode, const int32_t* count, uint32_t typeVal, const void** indices, int32_t drawcount);
void QOpenGLFunctions_4_1_Core_GlMultiDrawArrays(QOpenGLFunctions_4_1_Core* self, uint32_t mode, const int32_t* first, const int32_t* count, int32_t drawcount);
void QOpenGLFunctions_4_1_Core_GlBlendFuncSeparate(QOpenGLFunctions_4_1_Core* self, uint32_t sfactorRGB, uint32_t dfactorRGB, uint32_t sfactorAlpha, uint32_t dfactorAlpha);
void QOpenGLFunctions_4_1_Core_GlGetBufferPointerv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, void** params);
void QOpenGLFunctions_4_1_Core_GlGetBufferParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int32_t* params);
unsigned char QOpenGLFunctions_4_1_Core_GlUnmapBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target);
void* QOpenGLFunctions_4_1_Core_GlMapBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t access);
void QOpenGLFunctions_4_1_Core_GlGetBufferSubData(QOpenGLFunctions_4_1_Core* self, uint32_t target, int64_t offset, int64_t size, void* data);
void QOpenGLFunctions_4_1_Core_GlBufferSubData(QOpenGLFunctions_4_1_Core* self, uint32_t target, int64_t offset, int64_t size, const void* data);
void QOpenGLFunctions_4_1_Core_GlBufferData(QOpenGLFunctions_4_1_Core* self, uint32_t target, int64_t size, const void* data, uint32_t usage);
unsigned char QOpenGLFunctions_4_1_Core_GlIsBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t buffer);
void QOpenGLFunctions_4_1_Core_GlGenBuffers(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* buffers);
void QOpenGLFunctions_4_1_Core_GlDeleteBuffers(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* buffers);
void QOpenGLFunctions_4_1_Core_GlBindBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t buffer);
void QOpenGLFunctions_4_1_Core_GlGetQueryObjectuiv(QOpenGLFunctions_4_1_Core* self, uint32_t id, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetQueryObjectiv(QOpenGLFunctions_4_1_Core* self, uint32_t id, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetQueryiv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlEndQuery(QOpenGLFunctions_4_1_Core* self, uint32_t target);
void QOpenGLFunctions_4_1_Core_GlBeginQuery(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t id);
unsigned char QOpenGLFunctions_4_1_Core_GlIsQuery(QOpenGLFunctions_4_1_Core* self, uint32_t id);
void QOpenGLFunctions_4_1_Core_GlDeleteQueries(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* ids);
void QOpenGLFunctions_4_1_Core_GlGenQueries(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* ids);
void QOpenGLFunctions_4_1_Core_GlVertexAttribPointer(QOpenGLFunctions_4_1_Core* self, uint32_t index, int32_t size, uint32_t typeVal, unsigned char normalized, int32_t stride, const void* pointer);
void QOpenGLFunctions_4_1_Core_GlValidateProgram(QOpenGLFunctions_4_1_Core* self, uint32_t program);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix4fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix3fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix2fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniform4iv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform3iv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform2iv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform1iv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform4fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniform3fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniform2fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniform1fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniform4i(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t v0, int32_t v1, int32_t v2, int32_t v3);
void QOpenGLFunctions_4_1_Core_GlUniform3i(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t v0, int32_t v1, int32_t v2);
void QOpenGLFunctions_4_1_Core_GlUniform2i(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t v0, int32_t v1);
void QOpenGLFunctions_4_1_Core_GlUniform1i(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t v0);
void QOpenGLFunctions_4_1_Core_GlUniform4f(QOpenGLFunctions_4_1_Core* self, int32_t location, float v0, float v1, float v2, float v3);
void QOpenGLFunctions_4_1_Core_GlUniform3f(QOpenGLFunctions_4_1_Core* self, int32_t location, float v0, float v1, float v2);
void QOpenGLFunctions_4_1_Core_GlUniform2f(QOpenGLFunctions_4_1_Core* self, int32_t location, float v0, float v1);
void QOpenGLFunctions_4_1_Core_GlUniform1f(QOpenGLFunctions_4_1_Core* self, int32_t location, float v0);
void QOpenGLFunctions_4_1_Core_GlUseProgram(QOpenGLFunctions_4_1_Core* self, uint32_t program);
void QOpenGLFunctions_4_1_Core_GlShaderSource(QOpenGLFunctions_4_1_Core* self, uint32_t shader, int32_t count, const GLchar** stringVal, const int32_t* length);
void QOpenGLFunctions_4_1_Core_GlLinkProgram(QOpenGLFunctions_4_1_Core* self, uint32_t program);
unsigned char QOpenGLFunctions_4_1_Core_GlIsShader(QOpenGLFunctions_4_1_Core* self, uint32_t shader);
unsigned char QOpenGLFunctions_4_1_Core_GlIsProgram(QOpenGLFunctions_4_1_Core* self, uint32_t program);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribPointerv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, void** pointer);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribfv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, float* params);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribdv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, double* params);
void QOpenGLFunctions_4_1_Core_GlGetUniformiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetUniformfv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, float* params);
int32_t QOpenGLFunctions_4_1_Core_GlGetUniformLocation(QOpenGLFunctions_4_1_Core* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlGetShaderSource(QOpenGLFunctions_4_1_Core* self, uint32_t shader, int32_t bufSize, int32_t* length, GLchar* source);
void QOpenGLFunctions_4_1_Core_GlGetShaderInfoLog(QOpenGLFunctions_4_1_Core* self, uint32_t shader, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_4_1_Core_GlGetShaderiv(QOpenGLFunctions_4_1_Core* self, uint32_t shader, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetProgramInfoLog(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_4_1_Core_GlGetProgramiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t pname, int32_t* params);
int32_t QOpenGLFunctions_4_1_Core_GlGetAttribLocation(QOpenGLFunctions_4_1_Core* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlGetAttachedShaders(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t maxCount, int32_t* count, uint32_t* obj);
void QOpenGLFunctions_4_1_Core_GlEnableVertexAttribArray(QOpenGLFunctions_4_1_Core* self, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlDisableVertexAttribArray(QOpenGLFunctions_4_1_Core* self, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlDetachShader(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shader);
void QOpenGLFunctions_4_1_Core_GlDeleteShader(QOpenGLFunctions_4_1_Core* self, uint32_t shader);
void QOpenGLFunctions_4_1_Core_GlDeleteProgram(QOpenGLFunctions_4_1_Core* self, uint32_t program);
uint32_t QOpenGLFunctions_4_1_Core_GlCreateShader(QOpenGLFunctions_4_1_Core* self, uint32_t typeVal);
uint32_t QOpenGLFunctions_4_1_Core_GlCreateProgram(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlCompileShader(QOpenGLFunctions_4_1_Core* self, uint32_t shader);
void QOpenGLFunctions_4_1_Core_GlBindAttribLocation(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t index, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlAttachShader(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shader);
void QOpenGLFunctions_4_1_Core_GlStencilMaskSeparate(QOpenGLFunctions_4_1_Core* self, uint32_t face, uint32_t mask);
void QOpenGLFunctions_4_1_Core_GlStencilFuncSeparate(QOpenGLFunctions_4_1_Core* self, uint32_t face, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_4_1_Core_GlStencilOpSeparate(QOpenGLFunctions_4_1_Core* self, uint32_t face, uint32_t sfail, uint32_t dpfail, uint32_t dppass);
void QOpenGLFunctions_4_1_Core_GlBlendEquationSeparate(QOpenGLFunctions_4_1_Core* self, uint32_t modeRGB, uint32_t modeAlpha);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix4x3fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix3x4fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix4x2fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix2x4fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix3x2fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix2x3fv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
unsigned char QOpenGLFunctions_4_1_Core_GlIsVertexArray(QOpenGLFunctions_4_1_Core* self, uint32_t array);
void QOpenGLFunctions_4_1_Core_GlGenVertexArrays(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* arrays);
void QOpenGLFunctions_4_1_Core_GlDeleteVertexArrays(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* arrays);
void QOpenGLFunctions_4_1_Core_GlBindVertexArray(QOpenGLFunctions_4_1_Core* self, uint32_t array);
void QOpenGLFunctions_4_1_Core_GlFlushMappedBufferRange(QOpenGLFunctions_4_1_Core* self, uint32_t target, int64_t offset, int64_t length);
void* QOpenGLFunctions_4_1_Core_GlMapBufferRange(QOpenGLFunctions_4_1_Core* self, uint32_t target, int64_t offset, int64_t length, uint32_t access);
void QOpenGLFunctions_4_1_Core_GlFramebufferTextureLayer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t texture, int32_t level, int32_t layer);
void QOpenGLFunctions_4_1_Core_GlRenderbufferStorageMultisample(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t samples, uint32_t internalformat, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlBlitFramebuffer(QOpenGLFunctions_4_1_Core* self, int32_t srcX0, int32_t srcY0, int32_t srcX1, int32_t srcY1, int32_t dstX0, int32_t dstY0, int32_t dstX1, int32_t dstY1, uint32_t mask, uint32_t filter);
void QOpenGLFunctions_4_1_Core_GlGenerateMipmap(QOpenGLFunctions_4_1_Core* self, uint32_t target);
void QOpenGLFunctions_4_1_Core_GlGetFramebufferAttachmentParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlFramebufferRenderbuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t renderbuffertarget, uint32_t renderbuffer);
void QOpenGLFunctions_4_1_Core_GlFramebufferTexture3D(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level, int32_t zoffset);
void QOpenGLFunctions_4_1_Core_GlFramebufferTexture2D(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level);
void QOpenGLFunctions_4_1_Core_GlFramebufferTexture1D(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level);
void QOpenGLFunctions_4_1_Core_GlGenFramebuffers(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* framebuffers);
void QOpenGLFunctions_4_1_Core_GlDeleteFramebuffers(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* framebuffers);
void QOpenGLFunctions_4_1_Core_GlBindFramebuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t framebuffer);
unsigned char QOpenGLFunctions_4_1_Core_GlIsFramebuffer(QOpenGLFunctions_4_1_Core* self, uint32_t framebuffer);
void QOpenGLFunctions_4_1_Core_GlGetRenderbufferParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlRenderbufferStorage(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlGenRenderbuffers(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* renderbuffers);
void QOpenGLFunctions_4_1_Core_GlDeleteRenderbuffers(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* renderbuffers);
void QOpenGLFunctions_4_1_Core_GlBindRenderbuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t renderbuffer);
unsigned char QOpenGLFunctions_4_1_Core_GlIsRenderbuffer(QOpenGLFunctions_4_1_Core* self, uint32_t renderbuffer);
const uint8_t* QOpenGLFunctions_4_1_Core_GlGetStringi(QOpenGLFunctions_4_1_Core* self, uint32_t name, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlClearBufferfi(QOpenGLFunctions_4_1_Core* self, uint32_t buffer, int32_t drawbuffer, float depth, int32_t stencil);
void QOpenGLFunctions_4_1_Core_GlClearBufferfv(QOpenGLFunctions_4_1_Core* self, uint32_t buffer, int32_t drawbuffer, const float* value);
void QOpenGLFunctions_4_1_Core_GlClearBufferuiv(QOpenGLFunctions_4_1_Core* self, uint32_t buffer, int32_t drawbuffer, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlClearBufferiv(QOpenGLFunctions_4_1_Core* self, uint32_t buffer, int32_t drawbuffer, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlGetTexParameterIuiv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetTexParameterIiv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlTexParameterIuiv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, const uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlTexParameterIiv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_4_1_Core_GlUniform4uiv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform3uiv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform2uiv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform1uiv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlUniform4ui(QOpenGLFunctions_4_1_Core* self, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3);
void QOpenGLFunctions_4_1_Core_GlUniform3ui(QOpenGLFunctions_4_1_Core* self, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2);
void QOpenGLFunctions_4_1_Core_GlUniform2ui(QOpenGLFunctions_4_1_Core* self, int32_t location, uint32_t v0, uint32_t v1);
void QOpenGLFunctions_4_1_Core_GlUniform1ui(QOpenGLFunctions_4_1_Core* self, int32_t location, uint32_t v0);
int32_t QOpenGLFunctions_4_1_Core_GlGetFragDataLocation(QOpenGLFunctions_4_1_Core* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlBindFragDataLocation(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t color, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlGetUniformuiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribIuiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribIiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlVertexAttribIPointer(QOpenGLFunctions_4_1_Core* self, uint32_t index, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_4_1_Core_GlEndConditionalRender(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlBeginConditionalRender(QOpenGLFunctions_4_1_Core* self, uint32_t id, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlClampColor(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t clamp);
void QOpenGLFunctions_4_1_Core_GlTransformFeedbackVaryings(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t count, const GLchar** varyings, uint32_t bufferMode);
void QOpenGLFunctions_4_1_Core_GlBindBufferBase(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, uint32_t buffer);
void QOpenGLFunctions_4_1_Core_GlBindBufferRange(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, uint32_t buffer, int64_t offset, int64_t size);
void QOpenGLFunctions_4_1_Core_GlEndTransformFeedback(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlBeginTransformFeedback(QOpenGLFunctions_4_1_Core* self, uint32_t primitiveMode);
unsigned char QOpenGLFunctions_4_1_Core_GlIsEnabledi(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlDisablei(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlEnablei(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlGetIntegeriV(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, int32_t* data);
void QOpenGLFunctions_4_1_Core_GlGetBooleaniV(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, unsigned char* data);
void QOpenGLFunctions_4_1_Core_GlColorMaski(QOpenGLFunctions_4_1_Core* self, uint32_t index, unsigned char r, unsigned char g, unsigned char b, unsigned char a);
void QOpenGLFunctions_4_1_Core_GlCopyBufferSubData(QOpenGLFunctions_4_1_Core* self, uint32_t readTarget, uint32_t writeTarget, int64_t readOffset, int64_t writeOffset, int64_t size);
void QOpenGLFunctions_4_1_Core_GlUniformBlockBinding(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t uniformBlockIndex, uint32_t uniformBlockBinding);
void QOpenGLFunctions_4_1_Core_GlGetActiveUniformBlockName(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t uniformBlockIndex, int32_t bufSize, int32_t* length, GLchar* uniformBlockName);
void QOpenGLFunctions_4_1_Core_GlGetActiveUniformBlockiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t uniformBlockIndex, uint32_t pname, int32_t* params);
uint32_t QOpenGLFunctions_4_1_Core_GlGetUniformBlockIndex(QOpenGLFunctions_4_1_Core* self, uint32_t program, const GLchar* uniformBlockName);
void QOpenGLFunctions_4_1_Core_GlGetActiveUniformName(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t uniformIndex, int32_t bufSize, int32_t* length, GLchar* uniformName);
void QOpenGLFunctions_4_1_Core_GlGetActiveUniformsiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t uniformCount, const uint32_t* uniformIndices, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetUniformIndices(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t uniformCount, const GLchar** uniformNames, uint32_t* uniformIndices);
void QOpenGLFunctions_4_1_Core_GlPrimitiveRestartIndex(QOpenGLFunctions_4_1_Core* self, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlTexBuffer(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t internalformat, uint32_t buffer);
void QOpenGLFunctions_4_1_Core_GlDrawElementsInstanced(QOpenGLFunctions_4_1_Core* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices, int32_t instancecount);
void QOpenGLFunctions_4_1_Core_GlDrawArraysInstanced(QOpenGLFunctions_4_1_Core* self, uint32_t mode, int32_t first, int32_t count, int32_t instancecount);
void QOpenGLFunctions_4_1_Core_GlSampleMaski(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t mask);
void QOpenGLFunctions_4_1_Core_GlGetMultisamplefv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, uint32_t index, float* val);
void QOpenGLFunctions_4_1_Core_GlTexImage3DMultisample(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t samples, int32_t internalformat, int32_t width, int32_t height, int32_t depth, unsigned char fixedsamplelocations);
void QOpenGLFunctions_4_1_Core_GlTexImage2DMultisample(QOpenGLFunctions_4_1_Core* self, uint32_t target, int32_t samples, int32_t internalformat, int32_t width, int32_t height, unsigned char fixedsamplelocations);
void QOpenGLFunctions_4_1_Core_GlGetInteger64v(QOpenGLFunctions_4_1_Core* self, uint32_t pname, int64_t* params);
void QOpenGLFunctions_4_1_Core_GlProvokingVertex(QOpenGLFunctions_4_1_Core* self, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlMultiDrawElementsBaseVertex(QOpenGLFunctions_4_1_Core* self, uint32_t mode, const int32_t* count, uint32_t typeVal, const void** indices, int32_t drawcount, const int32_t* basevertex);
void QOpenGLFunctions_4_1_Core_GlDrawElementsInstancedBaseVertex(QOpenGLFunctions_4_1_Core* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices, int32_t instancecount, int32_t basevertex);
void QOpenGLFunctions_4_1_Core_GlDrawRangeElementsBaseVertex(QOpenGLFunctions_4_1_Core* self, uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t typeVal, const void* indices, int32_t basevertex);
void QOpenGLFunctions_4_1_Core_GlDrawElementsBaseVertex(QOpenGLFunctions_4_1_Core* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices, int32_t basevertex);
void QOpenGLFunctions_4_1_Core_GlFramebufferTexture(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t attachment, uint32_t texture, int32_t level);
void QOpenGLFunctions_4_1_Core_GlGetBufferParameteri64v(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t pname, int64_t* params);
void QOpenGLFunctions_4_1_Core_GlGetInteger64iV(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, int64_t* data);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP4uiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP4ui(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, uint32_t value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP3uiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP3ui(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, uint32_t value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP2uiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP2ui(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, uint32_t value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP1uiv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlVertexAttribP1ui(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t typeVal, unsigned char normalized, uint32_t value);
void QOpenGLFunctions_4_1_Core_GlGetQueryObjectui64v(QOpenGLFunctions_4_1_Core* self, uint32_t id, uint32_t pname, uint64_t* params);
void QOpenGLFunctions_4_1_Core_GlGetQueryObjecti64v(QOpenGLFunctions_4_1_Core* self, uint32_t id, uint32_t pname, int64_t* params);
void QOpenGLFunctions_4_1_Core_GlQueryCounter(QOpenGLFunctions_4_1_Core* self, uint32_t id, uint32_t target);
void QOpenGLFunctions_4_1_Core_GlGetSamplerParameterIuiv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetSamplerParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, float* params);
void QOpenGLFunctions_4_1_Core_GlGetSamplerParameterIiv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlGetSamplerParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlSamplerParameterIuiv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, const uint32_t* param);
void QOpenGLFunctions_4_1_Core_GlSamplerParameterIiv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, const int32_t* param);
void QOpenGLFunctions_4_1_Core_GlSamplerParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, const float* param);
void QOpenGLFunctions_4_1_Core_GlSamplerParameterf(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, float param);
void QOpenGLFunctions_4_1_Core_GlSamplerParameteriv(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, const int32_t* param);
void QOpenGLFunctions_4_1_Core_GlSamplerParameteri(QOpenGLFunctions_4_1_Core* self, uint32_t sampler, uint32_t pname, int32_t param);
void QOpenGLFunctions_4_1_Core_GlBindSampler(QOpenGLFunctions_4_1_Core* self, uint32_t unit, uint32_t sampler);
unsigned char QOpenGLFunctions_4_1_Core_GlIsSampler(QOpenGLFunctions_4_1_Core* self, uint32_t sampler);
void QOpenGLFunctions_4_1_Core_GlDeleteSamplers(QOpenGLFunctions_4_1_Core* self, int32_t count, const uint32_t* samplers);
void QOpenGLFunctions_4_1_Core_GlGenSamplers(QOpenGLFunctions_4_1_Core* self, int32_t count, uint32_t* samplers);
int32_t QOpenGLFunctions_4_1_Core_GlGetFragDataIndex(QOpenGLFunctions_4_1_Core* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlBindFragDataLocationIndexed(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t colorNumber, uint32_t index, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlVertexAttribDivisor(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t divisor);
void QOpenGLFunctions_4_1_Core_GlGetQueryIndexediv(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, uint32_t pname, int32_t* params);
void QOpenGLFunctions_4_1_Core_GlEndQueryIndexed(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_4_1_Core_GlBeginQueryIndexed(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, uint32_t id);
void QOpenGLFunctions_4_1_Core_GlDrawTransformFeedbackStream(QOpenGLFunctions_4_1_Core* self, uint32_t mode, uint32_t id, uint32_t stream);
void QOpenGLFunctions_4_1_Core_GlDrawTransformFeedback(QOpenGLFunctions_4_1_Core* self, uint32_t mode, uint32_t id);
void QOpenGLFunctions_4_1_Core_GlResumeTransformFeedback(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_GlPauseTransformFeedback(QOpenGLFunctions_4_1_Core* self);
unsigned char QOpenGLFunctions_4_1_Core_GlIsTransformFeedback(QOpenGLFunctions_4_1_Core* self, uint32_t id);
void QOpenGLFunctions_4_1_Core_GlGenTransformFeedbacks(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* ids);
void QOpenGLFunctions_4_1_Core_GlDeleteTransformFeedbacks(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* ids);
void QOpenGLFunctions_4_1_Core_GlBindTransformFeedback(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t id);
void QOpenGLFunctions_4_1_Core_GlPatchParameterfv(QOpenGLFunctions_4_1_Core* self, uint32_t pname, const float* values);
void QOpenGLFunctions_4_1_Core_GlPatchParameteri(QOpenGLFunctions_4_1_Core* self, uint32_t pname, int32_t value);
void QOpenGLFunctions_4_1_Core_GlGetProgramStageiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shadertype, uint32_t pname, int32_t* values);
void QOpenGLFunctions_4_1_Core_GlGetUniformSubroutineuiv(QOpenGLFunctions_4_1_Core* self, uint32_t shadertype, int32_t location, uint32_t* params);
void QOpenGLFunctions_4_1_Core_GlUniformSubroutinesuiv(QOpenGLFunctions_4_1_Core* self, uint32_t shadertype, int32_t count, const uint32_t* indices);
void QOpenGLFunctions_4_1_Core_GlGetActiveSubroutineName(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shadertype, uint32_t index, int32_t bufsize, int32_t* length, GLchar* name);
void QOpenGLFunctions_4_1_Core_GlGetActiveSubroutineUniformName(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shadertype, uint32_t index, int32_t bufsize, int32_t* length, GLchar* name);
void QOpenGLFunctions_4_1_Core_GlGetActiveSubroutineUniformiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shadertype, uint32_t index, uint32_t pname, int32_t* values);
uint32_t QOpenGLFunctions_4_1_Core_GlGetSubroutineIndex(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shadertype, const GLchar* name);
int32_t QOpenGLFunctions_4_1_Core_GlGetSubroutineUniformLocation(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t shadertype, const GLchar* name);
void QOpenGLFunctions_4_1_Core_GlGetUniformdv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, double* params);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix4x3dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix4x2dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix3x4dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix3x2dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix2x4dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix2x3dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix4dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix3dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniformMatrix2dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniform4dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniform3dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniform2dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniform1dv(QOpenGLFunctions_4_1_Core* self, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlUniform4d(QOpenGLFunctions_4_1_Core* self, int32_t location, double x, double y, double z, double w);
void QOpenGLFunctions_4_1_Core_GlUniform3d(QOpenGLFunctions_4_1_Core* self, int32_t location, double x, double y, double z);
void QOpenGLFunctions_4_1_Core_GlUniform2d(QOpenGLFunctions_4_1_Core* self, int32_t location, double x, double y);
void QOpenGLFunctions_4_1_Core_GlUniform1d(QOpenGLFunctions_4_1_Core* self, int32_t location, double x);
void QOpenGLFunctions_4_1_Core_GlDrawElementsIndirect(QOpenGLFunctions_4_1_Core* self, uint32_t mode, uint32_t typeVal, const void* indirect);
void QOpenGLFunctions_4_1_Core_GlDrawArraysIndirect(QOpenGLFunctions_4_1_Core* self, uint32_t mode, const void* indirect);
void QOpenGLFunctions_4_1_Core_GlBlendFuncSeparatei(QOpenGLFunctions_4_1_Core* self, uint32_t buf, uint32_t srcRGB, uint32_t dstRGB, uint32_t srcAlpha, uint32_t dstAlpha);
void QOpenGLFunctions_4_1_Core_GlBlendFunci(QOpenGLFunctions_4_1_Core* self, uint32_t buf, uint32_t src, uint32_t dst);
void QOpenGLFunctions_4_1_Core_GlBlendEquationSeparatei(QOpenGLFunctions_4_1_Core* self, uint32_t buf, uint32_t modeRGB, uint32_t modeAlpha);
void QOpenGLFunctions_4_1_Core_GlBlendEquationi(QOpenGLFunctions_4_1_Core* self, uint32_t buf, uint32_t mode);
void QOpenGLFunctions_4_1_Core_GlMinSampleShading(QOpenGLFunctions_4_1_Core* self, float value);
void QOpenGLFunctions_4_1_Core_GlGetDoubleiV(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, double* data);
void QOpenGLFunctions_4_1_Core_GlGetFloatiV(QOpenGLFunctions_4_1_Core* self, uint32_t target, uint32_t index, float* data);
void QOpenGLFunctions_4_1_Core_GlDepthRangeIndexed(QOpenGLFunctions_4_1_Core* self, uint32_t index, double n, double f);
void QOpenGLFunctions_4_1_Core_GlDepthRangeArrayv(QOpenGLFunctions_4_1_Core* self, uint32_t first, int32_t count, const double* v);
void QOpenGLFunctions_4_1_Core_GlScissorIndexedv(QOpenGLFunctions_4_1_Core* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_4_1_Core_GlScissorIndexed(QOpenGLFunctions_4_1_Core* self, uint32_t index, int32_t left, int32_t bottom, int32_t width, int32_t height);
void QOpenGLFunctions_4_1_Core_GlScissorArrayv(QOpenGLFunctions_4_1_Core* self, uint32_t first, int32_t count, const int32_t* v);
void QOpenGLFunctions_4_1_Core_GlViewportIndexedfv(QOpenGLFunctions_4_1_Core* self, uint32_t index, const float* v);
void QOpenGLFunctions_4_1_Core_GlViewportIndexedf(QOpenGLFunctions_4_1_Core* self, uint32_t index, float x, float y, float w, float h);
void QOpenGLFunctions_4_1_Core_GlViewportArrayv(QOpenGLFunctions_4_1_Core* self, uint32_t first, int32_t count, const float* v);
void QOpenGLFunctions_4_1_Core_GlGetVertexAttribLdv(QOpenGLFunctions_4_1_Core* self, uint32_t index, uint32_t pname, double* params);
void QOpenGLFunctions_4_1_Core_GlVertexAttribLPointer(QOpenGLFunctions_4_1_Core* self, uint32_t index, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL4dv(QOpenGLFunctions_4_1_Core* self, uint32_t index, const double* v);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL3dv(QOpenGLFunctions_4_1_Core* self, uint32_t index, const double* v);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL2dv(QOpenGLFunctions_4_1_Core* self, uint32_t index, const double* v);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL1dv(QOpenGLFunctions_4_1_Core* self, uint32_t index, const double* v);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL4d(QOpenGLFunctions_4_1_Core* self, uint32_t index, double x, double y, double z, double w);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL3d(QOpenGLFunctions_4_1_Core* self, uint32_t index, double x, double y, double z);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL2d(QOpenGLFunctions_4_1_Core* self, uint32_t index, double x, double y);
void QOpenGLFunctions_4_1_Core_GlVertexAttribL1d(QOpenGLFunctions_4_1_Core* self, uint32_t index, double x);
void QOpenGLFunctions_4_1_Core_GlGetProgramPipelineInfoLog(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_4_1_Core_GlValidateProgramPipeline(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix4x3dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix3x4dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix4x2dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix2x4dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix3x2dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix2x3dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix4x3fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix3x4fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix4x2fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix2x4fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix3x2fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix2x3fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix4dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix3dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix2dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix4fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix3fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniformMatrix2fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4uiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4ui(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4d(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, double v0, double v1, double v2, double v3);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4f(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, float v0, float v1, float v2, float v3);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4iv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform4i(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t v0, int32_t v1, int32_t v2, int32_t v3);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3uiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3ui(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3d(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, double v0, double v1, double v2);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3f(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, float v0, float v1, float v2);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3iv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform3i(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t v0, int32_t v1, int32_t v2);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2uiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2ui(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, uint32_t v0, uint32_t v1);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2d(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, double v0, double v1);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2f(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, float v0, float v1);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2iv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform2i(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t v0, int32_t v1);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1uiv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1ui(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, uint32_t v0);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1dv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const double* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1d(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, double v0);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1fv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1f(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, float v0);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1iv(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_4_1_Core_GlProgramUniform1i(QOpenGLFunctions_4_1_Core* self, uint32_t program, int32_t location, int32_t v0);
void QOpenGLFunctions_4_1_Core_GlGetProgramPipelineiv(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline, uint32_t pname, int32_t* params);
unsigned char QOpenGLFunctions_4_1_Core_GlIsProgramPipeline(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline);
void QOpenGLFunctions_4_1_Core_GlGenProgramPipelines(QOpenGLFunctions_4_1_Core* self, int32_t n, uint32_t* pipelines);
void QOpenGLFunctions_4_1_Core_GlDeleteProgramPipelines(QOpenGLFunctions_4_1_Core* self, int32_t n, const uint32_t* pipelines);
void QOpenGLFunctions_4_1_Core_GlBindProgramPipeline(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline);
uint32_t QOpenGLFunctions_4_1_Core_GlCreateShaderProgramv(QOpenGLFunctions_4_1_Core* self, uint32_t typeVal, int32_t count, const GLchar** strings);
void QOpenGLFunctions_4_1_Core_GlActiveShaderProgram(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline, uint32_t program);
void QOpenGLFunctions_4_1_Core_GlUseProgramStages(QOpenGLFunctions_4_1_Core* self, uint32_t pipeline, uint32_t stages, uint32_t program);
void QOpenGLFunctions_4_1_Core_GlProgramParameteri(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t pname, int32_t value);
void QOpenGLFunctions_4_1_Core_GlProgramBinary(QOpenGLFunctions_4_1_Core* self, uint32_t program, uint32_t binaryFormat, const void* binary, int32_t length);
void QOpenGLFunctions_4_1_Core_GlClearDepthf(QOpenGLFunctions_4_1_Core* self, float dd);
void QOpenGLFunctions_4_1_Core_GlDepthRangef(QOpenGLFunctions_4_1_Core* self, float n, float f);
void QOpenGLFunctions_4_1_Core_GlGetShaderPrecisionFormat(QOpenGLFunctions_4_1_Core* self, uint32_t shadertype, uint32_t precisiontype, int32_t* range, int32_t* precision);
void QOpenGLFunctions_4_1_Core_GlShaderBinary(QOpenGLFunctions_4_1_Core* self, int32_t count, const uint32_t* shaders, uint32_t binaryformat, const void* binary, int32_t length);
void QOpenGLFunctions_4_1_Core_GlReleaseShaderCompiler(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_OnInitializeOpenGLFunctions(QOpenGLFunctions_4_1_Core* self, intptr_t slot);
bool QOpenGLFunctions_4_1_Core_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_4_1_Core* self);
void QOpenGLFunctions_4_1_Core_Delete(QOpenGLFunctions_4_1_Core* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
