#pragma once
#ifndef QOPENGLFUNCTIONS_1_5_H_C_LIB
#define QOPENGLFUNCTIONS_1_5_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_1_5 QOpenGLFunctions_1_5;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_1_5* QOpenGLFunctions_1_5_new();
bool QOpenGLFunctions_1_5_InitializeOpenGLFunctions(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlViewport(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_5_GlDepthRange(QOpenGLFunctions_1_5* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_1_5_GlIsEnabled(QOpenGLFunctions_1_5* self, uint32_t cap);
void QOpenGLFunctions_1_5_GlGetTexLevelParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetTexLevelParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetTexParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetTexParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetTexImage(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_1_5_GlGetString(QOpenGLFunctions_1_5* self, uint32_t name);
void QOpenGLFunctions_1_5_GlGetIntegerv(QOpenGLFunctions_1_5* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetFloatv(QOpenGLFunctions_1_5* self, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetDoublev(QOpenGLFunctions_1_5* self, uint32_t pname, double* params);
void QOpenGLFunctions_1_5_GlGetBooleanv(QOpenGLFunctions_1_5* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_1_5_GlReadPixels(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_1_5_GlReadBuffer(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlPixelStorei(QOpenGLFunctions_1_5* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlPixelStoref(QOpenGLFunctions_1_5* self, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlDepthFunc(QOpenGLFunctions_1_5* self, uint32_t func);
void QOpenGLFunctions_1_5_GlStencilOp(QOpenGLFunctions_1_5* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_1_5_GlStencilFunc(QOpenGLFunctions_1_5* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_1_5_GlLogicOp(QOpenGLFunctions_1_5* self, uint32_t opcode);
void QOpenGLFunctions_1_5_GlBlendFunc(QOpenGLFunctions_1_5* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_1_5_GlFlush(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlFinish(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlEnable(QOpenGLFunctions_1_5* self, uint32_t cap);
void QOpenGLFunctions_1_5_GlDisable(QOpenGLFunctions_1_5* self, uint32_t cap);
void QOpenGLFunctions_1_5_GlDepthMask(QOpenGLFunctions_1_5* self, unsigned char flag);
void QOpenGLFunctions_1_5_GlColorMask(QOpenGLFunctions_1_5* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_1_5_GlStencilMask(QOpenGLFunctions_1_5* self, uint32_t mask);
void QOpenGLFunctions_1_5_GlClearDepth(QOpenGLFunctions_1_5* self, double depth);
void QOpenGLFunctions_1_5_GlClearStencil(QOpenGLFunctions_1_5* self, int32_t s);
void QOpenGLFunctions_1_5_GlClearColor(QOpenGLFunctions_1_5* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_5_GlClear(QOpenGLFunctions_1_5* self, uint32_t mask);
void QOpenGLFunctions_1_5_GlDrawBuffer(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlTexImage2D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlTexImage1D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlTexParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlTexParameteri(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlTexParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlTexParameterf(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlScissor(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_5_GlPolygonMode(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_5_GlPointSize(QOpenGLFunctions_1_5* self, float size);
void QOpenGLFunctions_1_5_GlLineWidth(QOpenGLFunctions_1_5* self, float width);
void QOpenGLFunctions_1_5_GlHint(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_1_5_GlFrontFace(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlCullFace(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlIndexubv(QOpenGLFunctions_1_5* self, const uint8_t* c);
void QOpenGLFunctions_1_5_GlIndexub(QOpenGLFunctions_1_5* self, uint8_t c);
unsigned char QOpenGLFunctions_1_5_GlIsTexture(QOpenGLFunctions_1_5* self, uint32_t texture);
void QOpenGLFunctions_1_5_GlGenTextures(QOpenGLFunctions_1_5* self, int32_t n, uint32_t* textures);
void QOpenGLFunctions_1_5_GlDeleteTextures(QOpenGLFunctions_1_5* self, int32_t n, const uint32_t* textures);
void QOpenGLFunctions_1_5_GlBindTexture(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t texture);
void QOpenGLFunctions_1_5_GlTexSubImage2D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlTexSubImage1D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlCopyTexSubImage2D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_5_GlCopyTexSubImage1D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_5_GlCopyTexImage2D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border);
void QOpenGLFunctions_1_5_GlCopyTexImage1D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t border);
void QOpenGLFunctions_1_5_GlPolygonOffset(QOpenGLFunctions_1_5* self, float factor, float units);
void QOpenGLFunctions_1_5_GlGetPointerv(QOpenGLFunctions_1_5* self, uint32_t pname, void** params);
void QOpenGLFunctions_1_5_GlDrawElements(QOpenGLFunctions_1_5* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_1_5_GlDrawArrays(QOpenGLFunctions_1_5* self, uint32_t mode, int32_t first, int32_t count);
void QOpenGLFunctions_1_5_GlCopyTexSubImage3D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_5_GlTexSubImage3D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlTexImage3D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlDrawRangeElements(QOpenGLFunctions_1_5* self, uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_1_5_GlBlendEquation(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlBlendColor(QOpenGLFunctions_1_5* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_5_GlGetCompressedTexImage(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, void* img);
void QOpenGLFunctions_1_5_GlCompressedTexSubImage1D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_5_GlCompressedTexSubImage2D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_5_GlCompressedTexSubImage3D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_5_GlCompressedTexImage1D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_5_GlCompressedTexImage2D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_5_GlCompressedTexImage3D(QOpenGLFunctions_1_5* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_5_GlSampleCoverage(QOpenGLFunctions_1_5* self, float value, unsigned char invert);
void QOpenGLFunctions_1_5_GlActiveTexture(QOpenGLFunctions_1_5* self, uint32_t texture);
void QOpenGLFunctions_1_5_GlPointParameteriv(QOpenGLFunctions_1_5* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlPointParameteri(QOpenGLFunctions_1_5* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlPointParameterfv(QOpenGLFunctions_1_5* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlPointParameterf(QOpenGLFunctions_1_5* self, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlMultiDrawElements(QOpenGLFunctions_1_5* self, uint32_t mode, const int32_t* count, uint32_t typeVal, const void** indices, int32_t drawcount);
void QOpenGLFunctions_1_5_GlMultiDrawArrays(QOpenGLFunctions_1_5* self, uint32_t mode, const int32_t* first, const int32_t* count, int32_t drawcount);
void QOpenGLFunctions_1_5_GlBlendFuncSeparate(QOpenGLFunctions_1_5* self, uint32_t sfactorRGB, uint32_t dfactorRGB, uint32_t sfactorAlpha, uint32_t dfactorAlpha);
void QOpenGLFunctions_1_5_GlGetBufferPointerv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, void** params);
void QOpenGLFunctions_1_5_GlGetBufferParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
unsigned char QOpenGLFunctions_1_5_GlUnmapBuffer(QOpenGLFunctions_1_5* self, uint32_t target);
void* QOpenGLFunctions_1_5_GlMapBuffer(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t access);
void QOpenGLFunctions_1_5_GlGetBufferSubData(QOpenGLFunctions_1_5* self, uint32_t target, int64_t offset, int64_t size, void* data);
void QOpenGLFunctions_1_5_GlBufferSubData(QOpenGLFunctions_1_5* self, uint32_t target, int64_t offset, int64_t size, const void* data);
void QOpenGLFunctions_1_5_GlBufferData(QOpenGLFunctions_1_5* self, uint32_t target, int64_t size, const void* data, uint32_t usage);
unsigned char QOpenGLFunctions_1_5_GlIsBuffer(QOpenGLFunctions_1_5* self, uint32_t buffer);
void QOpenGLFunctions_1_5_GlGenBuffers(QOpenGLFunctions_1_5* self, int32_t n, uint32_t* buffers);
void QOpenGLFunctions_1_5_GlDeleteBuffers(QOpenGLFunctions_1_5* self, int32_t n, const uint32_t* buffers);
void QOpenGLFunctions_1_5_GlBindBuffer(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t buffer);
void QOpenGLFunctions_1_5_GlGetQueryObjectuiv(QOpenGLFunctions_1_5* self, uint32_t id, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_1_5_GlGetQueryObjectiv(QOpenGLFunctions_1_5* self, uint32_t id, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetQueryiv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlEndQuery(QOpenGLFunctions_1_5* self, uint32_t target);
void QOpenGLFunctions_1_5_GlBeginQuery(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t id);
unsigned char QOpenGLFunctions_1_5_GlIsQuery(QOpenGLFunctions_1_5* self, uint32_t id);
void QOpenGLFunctions_1_5_GlDeleteQueries(QOpenGLFunctions_1_5* self, int32_t n, const uint32_t* ids);
void QOpenGLFunctions_1_5_GlGenQueries(QOpenGLFunctions_1_5* self, int32_t n, uint32_t* ids);
void QOpenGLFunctions_1_5_GlTranslatef(QOpenGLFunctions_1_5* self, float x, float y, float z);
void QOpenGLFunctions_1_5_GlTranslated(QOpenGLFunctions_1_5* self, double x, double y, double z);
void QOpenGLFunctions_1_5_GlScalef(QOpenGLFunctions_1_5* self, float x, float y, float z);
void QOpenGLFunctions_1_5_GlScaled(QOpenGLFunctions_1_5* self, double x, double y, double z);
void QOpenGLFunctions_1_5_GlRotatef(QOpenGLFunctions_1_5* self, float angle, float x, float y, float z);
void QOpenGLFunctions_1_5_GlRotated(QOpenGLFunctions_1_5* self, double angle, double x, double y, double z);
void QOpenGLFunctions_1_5_GlPushMatrix(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlPopMatrix(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlOrtho(QOpenGLFunctions_1_5* self, double left, double right, double bottom, double top, double zNear, double zFar);
void QOpenGLFunctions_1_5_GlMultMatrixd(QOpenGLFunctions_1_5* self, const double* m);
void QOpenGLFunctions_1_5_GlMultMatrixf(QOpenGLFunctions_1_5* self, const float* m);
void QOpenGLFunctions_1_5_GlMatrixMode(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlLoadMatrixd(QOpenGLFunctions_1_5* self, const double* m);
void QOpenGLFunctions_1_5_GlLoadMatrixf(QOpenGLFunctions_1_5* self, const float* m);
void QOpenGLFunctions_1_5_GlLoadIdentity(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlFrustum(QOpenGLFunctions_1_5* self, double left, double right, double bottom, double top, double zNear, double zFar);
unsigned char QOpenGLFunctions_1_5_GlIsList(QOpenGLFunctions_1_5* self, uint32_t list);
void QOpenGLFunctions_1_5_GlGetTexGeniv(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetTexGenfv(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetTexGendv(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, double* params);
void QOpenGLFunctions_1_5_GlGetTexEnviv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetTexEnvfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetPolygonStipple(QOpenGLFunctions_1_5* self, uint8_t* mask);
void QOpenGLFunctions_1_5_GlGetPixelMapusv(QOpenGLFunctions_1_5* self, uint32_t mapVal, uint16_t* values);
void QOpenGLFunctions_1_5_GlGetPixelMapuiv(QOpenGLFunctions_1_5* self, uint32_t mapVal, uint32_t* values);
void QOpenGLFunctions_1_5_GlGetPixelMapfv(QOpenGLFunctions_1_5* self, uint32_t mapVal, float* values);
void QOpenGLFunctions_1_5_GlGetMaterialiv(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetMaterialfv(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetMapiv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t query, int32_t* v);
void QOpenGLFunctions_1_5_GlGetMapfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t query, float* v);
void QOpenGLFunctions_1_5_GlGetMapdv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t query, double* v);
void QOpenGLFunctions_1_5_GlGetLightiv(QOpenGLFunctions_1_5* self, uint32_t light, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetLightfv(QOpenGLFunctions_1_5* self, uint32_t light, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetClipPlane(QOpenGLFunctions_1_5* self, uint32_t plane, double* equation);
void QOpenGLFunctions_1_5_GlDrawPixels(QOpenGLFunctions_1_5* self, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_5_GlCopyPixels(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t typeVal);
void QOpenGLFunctions_1_5_GlPixelMapusv(QOpenGLFunctions_1_5* self, uint32_t mapVal, int32_t mapsize, const uint16_t* values);
void QOpenGLFunctions_1_5_GlPixelMapuiv(QOpenGLFunctions_1_5* self, uint32_t mapVal, int32_t mapsize, const uint32_t* values);
void QOpenGLFunctions_1_5_GlPixelMapfv(QOpenGLFunctions_1_5* self, uint32_t mapVal, int32_t mapsize, const float* values);
void QOpenGLFunctions_1_5_GlPixelTransferi(QOpenGLFunctions_1_5* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlPixelTransferf(QOpenGLFunctions_1_5* self, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlPixelZoom(QOpenGLFunctions_1_5* self, float xfactor, float yfactor);
void QOpenGLFunctions_1_5_GlAlphaFunc(QOpenGLFunctions_1_5* self, uint32_t func, float ref);
void QOpenGLFunctions_1_5_GlEvalPoint2(QOpenGLFunctions_1_5* self, int32_t i, int32_t j);
void QOpenGLFunctions_1_5_GlEvalMesh2(QOpenGLFunctions_1_5* self, uint32_t mode, int32_t i1Val, int32_t i2Val, int32_t j1, int32_t j2);
void QOpenGLFunctions_1_5_GlEvalPoint1(QOpenGLFunctions_1_5* self, int32_t i);
void QOpenGLFunctions_1_5_GlEvalMesh1(QOpenGLFunctions_1_5* self, uint32_t mode, int32_t i1Val, int32_t i2Val);
void QOpenGLFunctions_1_5_GlEvalCoord2fv(QOpenGLFunctions_1_5* self, const float* u);
void QOpenGLFunctions_1_5_GlEvalCoord2f(QOpenGLFunctions_1_5* self, float u, float v);
void QOpenGLFunctions_1_5_GlEvalCoord2dv(QOpenGLFunctions_1_5* self, const double* u);
void QOpenGLFunctions_1_5_GlEvalCoord2d(QOpenGLFunctions_1_5* self, double u, double v);
void QOpenGLFunctions_1_5_GlEvalCoord1fv(QOpenGLFunctions_1_5* self, const float* u);
void QOpenGLFunctions_1_5_GlEvalCoord1f(QOpenGLFunctions_1_5* self, float u);
void QOpenGLFunctions_1_5_GlEvalCoord1dv(QOpenGLFunctions_1_5* self, const double* u);
void QOpenGLFunctions_1_5_GlEvalCoord1d(QOpenGLFunctions_1_5* self, double u);
void QOpenGLFunctions_1_5_GlMapGrid2f(QOpenGLFunctions_1_5* self, int32_t un, float u1Val, float u2Val, int32_t vn, float v1, float v2);
void QOpenGLFunctions_1_5_GlMapGrid2d(QOpenGLFunctions_1_5* self, int32_t un, double u1Val, double u2Val, int32_t vn, double v1, double v2);
void QOpenGLFunctions_1_5_GlMapGrid1f(QOpenGLFunctions_1_5* self, int32_t un, float u1Val, float u2Val);
void QOpenGLFunctions_1_5_GlMapGrid1d(QOpenGLFunctions_1_5* self, int32_t un, double u1Val, double u2Val);
void QOpenGLFunctions_1_5_GlMap2f(QOpenGLFunctions_1_5* self, uint32_t target, float u1Val, float u2Val, int32_t ustride, int32_t uorder, float v1, float v2, int32_t vstride, int32_t vorder, const float* points);
void QOpenGLFunctions_1_5_GlMap2d(QOpenGLFunctions_1_5* self, uint32_t target, double u1Val, double u2Val, int32_t ustride, int32_t uorder, double v1, double v2, int32_t vstride, int32_t vorder, const double* points);
void QOpenGLFunctions_1_5_GlMap1f(QOpenGLFunctions_1_5* self, uint32_t target, float u1Val, float u2Val, int32_t stride, int32_t order, const float* points);
void QOpenGLFunctions_1_5_GlMap1d(QOpenGLFunctions_1_5* self, uint32_t target, double u1Val, double u2Val, int32_t stride, int32_t order, const double* points);
void QOpenGLFunctions_1_5_GlPushAttrib(QOpenGLFunctions_1_5* self, uint32_t mask);
void QOpenGLFunctions_1_5_GlPopAttrib(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlAccum(QOpenGLFunctions_1_5* self, uint32_t op, float value);
void QOpenGLFunctions_1_5_GlIndexMask(QOpenGLFunctions_1_5* self, uint32_t mask);
void QOpenGLFunctions_1_5_GlClearIndex(QOpenGLFunctions_1_5* self, float c);
void QOpenGLFunctions_1_5_GlClearAccum(QOpenGLFunctions_1_5* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_5_GlPushName(QOpenGLFunctions_1_5* self, uint32_t name);
void QOpenGLFunctions_1_5_GlPopName(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlPassThrough(QOpenGLFunctions_1_5* self, float token);
void QOpenGLFunctions_1_5_GlLoadName(QOpenGLFunctions_1_5* self, uint32_t name);
void QOpenGLFunctions_1_5_GlInitNames(QOpenGLFunctions_1_5* self);
int32_t QOpenGLFunctions_1_5_GlRenderMode(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlSelectBuffer(QOpenGLFunctions_1_5* self, int32_t size, uint32_t* buffer);
void QOpenGLFunctions_1_5_GlFeedbackBuffer(QOpenGLFunctions_1_5* self, int32_t size, uint32_t typeVal, float* buffer);
void QOpenGLFunctions_1_5_GlTexGeniv(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlTexGeni(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlTexGenfv(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlTexGenf(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlTexGendv(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, const double* params);
void QOpenGLFunctions_1_5_GlTexGend(QOpenGLFunctions_1_5* self, uint32_t coord, uint32_t pname, double param);
void QOpenGLFunctions_1_5_GlTexEnviv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlTexEnvi(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlTexEnvfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlTexEnvf(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlShadeModel(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlPolygonStipple(QOpenGLFunctions_1_5* self, const uint8_t* mask);
void QOpenGLFunctions_1_5_GlMaterialiv(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlMateriali(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlMaterialfv(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlMaterialf(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlLineStipple(QOpenGLFunctions_1_5* self, int32_t factor, uint16_t pattern);
void QOpenGLFunctions_1_5_GlLightModeliv(QOpenGLFunctions_1_5* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlLightModeli(QOpenGLFunctions_1_5* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlLightModelfv(QOpenGLFunctions_1_5* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlLightModelf(QOpenGLFunctions_1_5* self, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlLightiv(QOpenGLFunctions_1_5* self, uint32_t light, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlLighti(QOpenGLFunctions_1_5* self, uint32_t light, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlLightfv(QOpenGLFunctions_1_5* self, uint32_t light, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlLightf(QOpenGLFunctions_1_5* self, uint32_t light, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlFogiv(QOpenGLFunctions_1_5* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlFogi(QOpenGLFunctions_1_5* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_5_GlFogfv(QOpenGLFunctions_1_5* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlFogf(QOpenGLFunctions_1_5* self, uint32_t pname, float param);
void QOpenGLFunctions_1_5_GlColorMaterial(QOpenGLFunctions_1_5* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_5_GlClipPlane(QOpenGLFunctions_1_5* self, uint32_t plane, const double* equation);
void QOpenGLFunctions_1_5_GlVertex4sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlVertex4s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_5_GlVertex4iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlVertex4i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_5_GlVertex4fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlVertex4f(QOpenGLFunctions_1_5* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_5_GlVertex4dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlVertex4d(QOpenGLFunctions_1_5* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_5_GlVertex3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlVertex3s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_5_GlVertex3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlVertex3i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_5_GlVertex3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlVertex3f(QOpenGLFunctions_1_5* self, float x, float y, float z);
void QOpenGLFunctions_1_5_GlVertex3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlVertex3d(QOpenGLFunctions_1_5* self, double x, double y, double z);
void QOpenGLFunctions_1_5_GlVertex2sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlVertex2s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_5_GlVertex2iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlVertex2i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_5_GlVertex2fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlVertex2f(QOpenGLFunctions_1_5* self, float x, float y);
void QOpenGLFunctions_1_5_GlVertex2dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlVertex2d(QOpenGLFunctions_1_5* self, double x, double y);
void QOpenGLFunctions_1_5_GlTexCoord4sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlTexCoord4s(QOpenGLFunctions_1_5* self, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_1_5_GlTexCoord4iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlTexCoord4i(QOpenGLFunctions_1_5* self, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_1_5_GlTexCoord4fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlTexCoord4f(QOpenGLFunctions_1_5* self, float s, float t, float r, float q);
void QOpenGLFunctions_1_5_GlTexCoord4dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlTexCoord4d(QOpenGLFunctions_1_5* self, double s, double t, double r, double q);
void QOpenGLFunctions_1_5_GlTexCoord3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlTexCoord3s(QOpenGLFunctions_1_5* self, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_1_5_GlTexCoord3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlTexCoord3i(QOpenGLFunctions_1_5* self, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_1_5_GlTexCoord3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlTexCoord3f(QOpenGLFunctions_1_5* self, float s, float t, float r);
void QOpenGLFunctions_1_5_GlTexCoord3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlTexCoord3d(QOpenGLFunctions_1_5* self, double s, double t, double r);
void QOpenGLFunctions_1_5_GlTexCoord2sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlTexCoord2s(QOpenGLFunctions_1_5* self, int16_t s, int16_t t);
void QOpenGLFunctions_1_5_GlTexCoord2iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlTexCoord2i(QOpenGLFunctions_1_5* self, int32_t s, int32_t t);
void QOpenGLFunctions_1_5_GlTexCoord2fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlTexCoord2f(QOpenGLFunctions_1_5* self, float s, float t);
void QOpenGLFunctions_1_5_GlTexCoord2dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlTexCoord2d(QOpenGLFunctions_1_5* self, double s, double t);
void QOpenGLFunctions_1_5_GlTexCoord1sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlTexCoord1s(QOpenGLFunctions_1_5* self, int16_t s);
void QOpenGLFunctions_1_5_GlTexCoord1iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlTexCoord1i(QOpenGLFunctions_1_5* self, int32_t s);
void QOpenGLFunctions_1_5_GlTexCoord1fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlTexCoord1f(QOpenGLFunctions_1_5* self, float s);
void QOpenGLFunctions_1_5_GlTexCoord1dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlTexCoord1d(QOpenGLFunctions_1_5* self, double s);
void QOpenGLFunctions_1_5_GlRectsv(QOpenGLFunctions_1_5* self, const int16_t* v1, const int16_t* v2);
void QOpenGLFunctions_1_5_GlRects(QOpenGLFunctions_1_5* self, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void QOpenGLFunctions_1_5_GlRectiv(QOpenGLFunctions_1_5* self, const int32_t* v1, const int32_t* v2);
void QOpenGLFunctions_1_5_GlRecti(QOpenGLFunctions_1_5* self, int32_t x1, int32_t y1, int32_t x2, int32_t y2);
void QOpenGLFunctions_1_5_GlRectfv(QOpenGLFunctions_1_5* self, const float* v1, const float* v2);
void QOpenGLFunctions_1_5_GlRectf(QOpenGLFunctions_1_5* self, float x1, float y1, float x2, float y2);
void QOpenGLFunctions_1_5_GlRectdv(QOpenGLFunctions_1_5* self, const double* v1, const double* v2);
void QOpenGLFunctions_1_5_GlRectd(QOpenGLFunctions_1_5* self, double x1, double y1, double x2, double y2);
void QOpenGLFunctions_1_5_GlRasterPos4sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlRasterPos4s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_5_GlRasterPos4iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlRasterPos4i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_5_GlRasterPos4fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlRasterPos4f(QOpenGLFunctions_1_5* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_5_GlRasterPos4dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlRasterPos4d(QOpenGLFunctions_1_5* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_5_GlRasterPos3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlRasterPos3s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_5_GlRasterPos3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlRasterPos3i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_5_GlRasterPos3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlRasterPos3f(QOpenGLFunctions_1_5* self, float x, float y, float z);
void QOpenGLFunctions_1_5_GlRasterPos3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlRasterPos3d(QOpenGLFunctions_1_5* self, double x, double y, double z);
void QOpenGLFunctions_1_5_GlRasterPos2sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlRasterPos2s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_5_GlRasterPos2iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlRasterPos2i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_5_GlRasterPos2fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlRasterPos2f(QOpenGLFunctions_1_5* self, float x, float y);
void QOpenGLFunctions_1_5_GlRasterPos2dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlRasterPos2d(QOpenGLFunctions_1_5* self, double x, double y);
void QOpenGLFunctions_1_5_GlNormal3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlNormal3s(QOpenGLFunctions_1_5* self, int16_t nx, int16_t ny, int16_t nz);
void QOpenGLFunctions_1_5_GlNormal3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlNormal3i(QOpenGLFunctions_1_5* self, int32_t nx, int32_t ny, int32_t nz);
void QOpenGLFunctions_1_5_GlNormal3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlNormal3f(QOpenGLFunctions_1_5* self, float nx, float ny, float nz);
void QOpenGLFunctions_1_5_GlNormal3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlNormal3d(QOpenGLFunctions_1_5* self, double nx, double ny, double nz);
void QOpenGLFunctions_1_5_GlNormal3bv(QOpenGLFunctions_1_5* self, const signed char* v);
void QOpenGLFunctions_1_5_GlNormal3b(QOpenGLFunctions_1_5* self, signed char nx, signed char ny, signed char nz);
void QOpenGLFunctions_1_5_GlIndexsv(QOpenGLFunctions_1_5* self, const int16_t* c);
void QOpenGLFunctions_1_5_GlIndexs(QOpenGLFunctions_1_5* self, int16_t c);
void QOpenGLFunctions_1_5_GlIndexiv(QOpenGLFunctions_1_5* self, const int32_t* c);
void QOpenGLFunctions_1_5_GlIndexi(QOpenGLFunctions_1_5* self, int32_t c);
void QOpenGLFunctions_1_5_GlIndexfv(QOpenGLFunctions_1_5* self, const float* c);
void QOpenGLFunctions_1_5_GlIndexf(QOpenGLFunctions_1_5* self, float c);
void QOpenGLFunctions_1_5_GlIndexdv(QOpenGLFunctions_1_5* self, const double* c);
void QOpenGLFunctions_1_5_GlIndexd(QOpenGLFunctions_1_5* self, double c);
void QOpenGLFunctions_1_5_GlEnd(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlEdgeFlagv(QOpenGLFunctions_1_5* self, const unsigned char* flag);
void QOpenGLFunctions_1_5_GlEdgeFlag(QOpenGLFunctions_1_5* self, unsigned char flag);
void QOpenGLFunctions_1_5_GlColor4usv(QOpenGLFunctions_1_5* self, const uint16_t* v);
void QOpenGLFunctions_1_5_GlColor4us(QOpenGLFunctions_1_5* self, uint16_t red, uint16_t green, uint16_t blue, uint16_t alpha);
void QOpenGLFunctions_1_5_GlColor4uiv(QOpenGLFunctions_1_5* self, const uint32_t* v);
void QOpenGLFunctions_1_5_GlColor4ui(QOpenGLFunctions_1_5* self, uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha);
void QOpenGLFunctions_1_5_GlColor4ubv(QOpenGLFunctions_1_5* self, const uint8_t* v);
void QOpenGLFunctions_1_5_GlColor4ub(QOpenGLFunctions_1_5* self, uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha);
void QOpenGLFunctions_1_5_GlColor4sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlColor4s(QOpenGLFunctions_1_5* self, int16_t red, int16_t green, int16_t blue, int16_t alpha);
void QOpenGLFunctions_1_5_GlColor4iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlColor4i(QOpenGLFunctions_1_5* self, int32_t red, int32_t green, int32_t blue, int32_t alpha);
void QOpenGLFunctions_1_5_GlColor4fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlColor4f(QOpenGLFunctions_1_5* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_5_GlColor4dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlColor4d(QOpenGLFunctions_1_5* self, double red, double green, double blue, double alpha);
void QOpenGLFunctions_1_5_GlColor4bv(QOpenGLFunctions_1_5* self, const signed char* v);
void QOpenGLFunctions_1_5_GlColor4b(QOpenGLFunctions_1_5* self, signed char red, signed char green, signed char blue, signed char alpha);
void QOpenGLFunctions_1_5_GlColor3usv(QOpenGLFunctions_1_5* self, const uint16_t* v);
void QOpenGLFunctions_1_5_GlColor3us(QOpenGLFunctions_1_5* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_1_5_GlColor3uiv(QOpenGLFunctions_1_5* self, const uint32_t* v);
void QOpenGLFunctions_1_5_GlColor3ui(QOpenGLFunctions_1_5* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_1_5_GlColor3ubv(QOpenGLFunctions_1_5* self, const uint8_t* v);
void QOpenGLFunctions_1_5_GlColor3ub(QOpenGLFunctions_1_5* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_1_5_GlColor3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlColor3s(QOpenGLFunctions_1_5* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_1_5_GlColor3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlColor3i(QOpenGLFunctions_1_5* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_1_5_GlColor3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlColor3f(QOpenGLFunctions_1_5* self, float red, float green, float blue);
void QOpenGLFunctions_1_5_GlColor3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlColor3d(QOpenGLFunctions_1_5* self, double red, double green, double blue);
void QOpenGLFunctions_1_5_GlColor3bv(QOpenGLFunctions_1_5* self, const signed char* v);
void QOpenGLFunctions_1_5_GlColor3b(QOpenGLFunctions_1_5* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_1_5_GlBitmap(QOpenGLFunctions_1_5* self, int32_t width, int32_t height, float xorig, float yorig, float xmove, float ymove, const uint8_t* bitmap);
void QOpenGLFunctions_1_5_GlBegin(QOpenGLFunctions_1_5* self, uint32_t mode);
void QOpenGLFunctions_1_5_GlListBase(QOpenGLFunctions_1_5* self, uint32_t base);
uint32_t QOpenGLFunctions_1_5_GlGenLists(QOpenGLFunctions_1_5* self, int32_t range);
void QOpenGLFunctions_1_5_GlDeleteLists(QOpenGLFunctions_1_5* self, uint32_t list, int32_t range);
void QOpenGLFunctions_1_5_GlCallLists(QOpenGLFunctions_1_5* self, int32_t n, uint32_t typeVal, const void* lists);
void QOpenGLFunctions_1_5_GlCallList(QOpenGLFunctions_1_5* self, uint32_t list);
void QOpenGLFunctions_1_5_GlEndList(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlNewList(QOpenGLFunctions_1_5* self, uint32_t list, uint32_t mode);
void QOpenGLFunctions_1_5_GlPushClientAttrib(QOpenGLFunctions_1_5* self, uint32_t mask);
void QOpenGLFunctions_1_5_GlPopClientAttrib(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_GlPrioritizeTextures(QOpenGLFunctions_1_5* self, int32_t n, const uint32_t* textures, const float* priorities);
unsigned char QOpenGLFunctions_1_5_GlAreTexturesResident(QOpenGLFunctions_1_5* self, int32_t n, const uint32_t* textures, unsigned char* residences);
void QOpenGLFunctions_1_5_GlVertexPointer(QOpenGLFunctions_1_5* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlTexCoordPointer(QOpenGLFunctions_1_5* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlNormalPointer(QOpenGLFunctions_1_5* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlInterleavedArrays(QOpenGLFunctions_1_5* self, uint32_t format, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlIndexPointer(QOpenGLFunctions_1_5* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlEnableClientState(QOpenGLFunctions_1_5* self, uint32_t array);
void QOpenGLFunctions_1_5_GlEdgeFlagPointer(QOpenGLFunctions_1_5* self, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlDisableClientState(QOpenGLFunctions_1_5* self, uint32_t array);
void QOpenGLFunctions_1_5_GlColorPointer(QOpenGLFunctions_1_5* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlArrayElement(QOpenGLFunctions_1_5* self, int32_t i);
void QOpenGLFunctions_1_5_GlResetMinmax(QOpenGLFunctions_1_5* self, uint32_t target);
void QOpenGLFunctions_1_5_GlResetHistogram(QOpenGLFunctions_1_5* self, uint32_t target);
void QOpenGLFunctions_1_5_GlMinmax(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_1_5_GlHistogram(QOpenGLFunctions_1_5* self, uint32_t target, int32_t width, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_1_5_GlGetMinmaxParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetMinmaxParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetMinmax(QOpenGLFunctions_1_5* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_1_5_GlGetHistogramParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetHistogramParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetHistogram(QOpenGLFunctions_1_5* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_1_5_GlSeparableFilter2D(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* row, const void* column);
void QOpenGLFunctions_1_5_GlGetSeparableFilter(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t format, uint32_t typeVal, void* row, void* column, void* span);
void QOpenGLFunctions_1_5_GlGetConvolutionParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetConvolutionParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetConvolutionFilter(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t format, uint32_t typeVal, void* image);
void QOpenGLFunctions_1_5_GlCopyConvolutionFilter2D(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_5_GlCopyConvolutionFilter1D(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_5_GlConvolutionParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlConvolutionParameteri(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t params);
void QOpenGLFunctions_1_5_GlConvolutionParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlConvolutionParameterf(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float params);
void QOpenGLFunctions_1_5_GlConvolutionFilter2D(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_1_5_GlConvolutionFilter1D(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_1_5_GlCopyColorSubTable(QOpenGLFunctions_1_5* self, uint32_t target, int32_t start, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_5_GlColorSubTable(QOpenGLFunctions_1_5* self, uint32_t target, int32_t start, int32_t count, uint32_t format, uint32_t typeVal, const void* data);
void QOpenGLFunctions_1_5_GlGetColorTableParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_5_GlGetColorTableParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_5_GlGetColorTable(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t format, uint32_t typeVal, void* table);
void QOpenGLFunctions_1_5_GlCopyColorTable(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_5_GlColorTableParameteriv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_5_GlColorTableParameterfv(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_5_GlColorTable(QOpenGLFunctions_1_5* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* table);
void QOpenGLFunctions_1_5_GlMultTransposeMatrixd(QOpenGLFunctions_1_5* self, const double* m);
void QOpenGLFunctions_1_5_GlMultTransposeMatrixf(QOpenGLFunctions_1_5* self, const float* m);
void QOpenGLFunctions_1_5_GlLoadTransposeMatrixd(QOpenGLFunctions_1_5* self, const double* m);
void QOpenGLFunctions_1_5_GlLoadTransposeMatrixf(QOpenGLFunctions_1_5* self, const float* m);
void QOpenGLFunctions_1_5_GlMultiTexCoord4sv(QOpenGLFunctions_1_5* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord4s(QOpenGLFunctions_1_5* self, uint32_t target, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_1_5_GlMultiTexCoord4iv(QOpenGLFunctions_1_5* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord4i(QOpenGLFunctions_1_5* self, uint32_t target, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_1_5_GlMultiTexCoord4fv(QOpenGLFunctions_1_5* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord4f(QOpenGLFunctions_1_5* self, uint32_t target, float s, float t, float r, float q);
void QOpenGLFunctions_1_5_GlMultiTexCoord4dv(QOpenGLFunctions_1_5* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord4d(QOpenGLFunctions_1_5* self, uint32_t target, double s, double t, double r, double q);
void QOpenGLFunctions_1_5_GlMultiTexCoord3sv(QOpenGLFunctions_1_5* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord3s(QOpenGLFunctions_1_5* self, uint32_t target, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_1_5_GlMultiTexCoord3iv(QOpenGLFunctions_1_5* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord3i(QOpenGLFunctions_1_5* self, uint32_t target, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_1_5_GlMultiTexCoord3fv(QOpenGLFunctions_1_5* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord3f(QOpenGLFunctions_1_5* self, uint32_t target, float s, float t, float r);
void QOpenGLFunctions_1_5_GlMultiTexCoord3dv(QOpenGLFunctions_1_5* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord3d(QOpenGLFunctions_1_5* self, uint32_t target, double s, double t, double r);
void QOpenGLFunctions_1_5_GlMultiTexCoord2sv(QOpenGLFunctions_1_5* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord2s(QOpenGLFunctions_1_5* self, uint32_t target, int16_t s, int16_t t);
void QOpenGLFunctions_1_5_GlMultiTexCoord2iv(QOpenGLFunctions_1_5* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord2i(QOpenGLFunctions_1_5* self, uint32_t target, int32_t s, int32_t t);
void QOpenGLFunctions_1_5_GlMultiTexCoord2fv(QOpenGLFunctions_1_5* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord2f(QOpenGLFunctions_1_5* self, uint32_t target, float s, float t);
void QOpenGLFunctions_1_5_GlMultiTexCoord2dv(QOpenGLFunctions_1_5* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord2d(QOpenGLFunctions_1_5* self, uint32_t target, double s, double t);
void QOpenGLFunctions_1_5_GlMultiTexCoord1sv(QOpenGLFunctions_1_5* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord1s(QOpenGLFunctions_1_5* self, uint32_t target, int16_t s);
void QOpenGLFunctions_1_5_GlMultiTexCoord1iv(QOpenGLFunctions_1_5* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord1i(QOpenGLFunctions_1_5* self, uint32_t target, int32_t s);
void QOpenGLFunctions_1_5_GlMultiTexCoord1fv(QOpenGLFunctions_1_5* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord1f(QOpenGLFunctions_1_5* self, uint32_t target, float s);
void QOpenGLFunctions_1_5_GlMultiTexCoord1dv(QOpenGLFunctions_1_5* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_5_GlMultiTexCoord1d(QOpenGLFunctions_1_5* self, uint32_t target, double s);
void QOpenGLFunctions_1_5_GlClientActiveTexture(QOpenGLFunctions_1_5* self, uint32_t texture);
void QOpenGLFunctions_1_5_GlWindowPos3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlWindowPos3s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_5_GlWindowPos3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlWindowPos3i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_5_GlWindowPos3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlWindowPos3f(QOpenGLFunctions_1_5* self, float x, float y, float z);
void QOpenGLFunctions_1_5_GlWindowPos3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlWindowPos3d(QOpenGLFunctions_1_5* self, double x, double y, double z);
void QOpenGLFunctions_1_5_GlWindowPos2sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlWindowPos2s(QOpenGLFunctions_1_5* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_5_GlWindowPos2iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlWindowPos2i(QOpenGLFunctions_1_5* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_5_GlWindowPos2fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlWindowPos2f(QOpenGLFunctions_1_5* self, float x, float y);
void QOpenGLFunctions_1_5_GlWindowPos2dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlWindowPos2d(QOpenGLFunctions_1_5* self, double x, double y);
void QOpenGLFunctions_1_5_GlSecondaryColorPointer(QOpenGLFunctions_1_5* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlSecondaryColor3usv(QOpenGLFunctions_1_5* self, const uint16_t* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3us(QOpenGLFunctions_1_5* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3uiv(QOpenGLFunctions_1_5* self, const uint32_t* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3ui(QOpenGLFunctions_1_5* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3ubv(QOpenGLFunctions_1_5* self, const uint8_t* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3ub(QOpenGLFunctions_1_5* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3sv(QOpenGLFunctions_1_5* self, const int16_t* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3s(QOpenGLFunctions_1_5* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3iv(QOpenGLFunctions_1_5* self, const int32_t* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3i(QOpenGLFunctions_1_5* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3fv(QOpenGLFunctions_1_5* self, const float* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3f(QOpenGLFunctions_1_5* self, float red, float green, float blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3dv(QOpenGLFunctions_1_5* self, const double* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3d(QOpenGLFunctions_1_5* self, double red, double green, double blue);
void QOpenGLFunctions_1_5_GlSecondaryColor3bv(QOpenGLFunctions_1_5* self, const signed char* v);
void QOpenGLFunctions_1_5_GlSecondaryColor3b(QOpenGLFunctions_1_5* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_1_5_GlFogCoordPointer(QOpenGLFunctions_1_5* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_5_GlFogCoorddv(QOpenGLFunctions_1_5* self, const double* coord);
void QOpenGLFunctions_1_5_GlFogCoordd(QOpenGLFunctions_1_5* self, double coord);
void QOpenGLFunctions_1_5_GlFogCoordfv(QOpenGLFunctions_1_5* self, const float* coord);
void QOpenGLFunctions_1_5_GlFogCoordf(QOpenGLFunctions_1_5* self, float coord);
void QOpenGLFunctions_1_5_OnInitializeOpenGLFunctions(QOpenGLFunctions_1_5* self, intptr_t slot);
bool QOpenGLFunctions_1_5_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_1_5* self);
void QOpenGLFunctions_1_5_Delete(QOpenGLFunctions_1_5* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
