#pragma once
#ifndef QOPENGLFUNCTIONS_1_3_H_C_LIB
#define QOPENGLFUNCTIONS_1_3_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_1_3 QOpenGLFunctions_1_3;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_1_3* QOpenGLFunctions_1_3_new();
bool QOpenGLFunctions_1_3_InitializeOpenGLFunctions(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlViewport(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_3_GlDepthRange(QOpenGLFunctions_1_3* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_1_3_GlIsEnabled(QOpenGLFunctions_1_3* self, uint32_t cap);
void QOpenGLFunctions_1_3_GlGetTexLevelParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetTexLevelParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetTexParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetTexParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetTexImage(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_1_3_GlGetString(QOpenGLFunctions_1_3* self, uint32_t name);
void QOpenGLFunctions_1_3_GlGetIntegerv(QOpenGLFunctions_1_3* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetFloatv(QOpenGLFunctions_1_3* self, uint32_t pname, float* params);
GL QOpenGLFunctions_1_3_GlGetError(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlGetDoublev(QOpenGLFunctions_1_3* self, uint32_t pname, double* params);
void QOpenGLFunctions_1_3_GlGetBooleanv(QOpenGLFunctions_1_3* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_1_3_GlReadPixels(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_1_3_GlReadBuffer(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlPixelStorei(QOpenGLFunctions_1_3* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlPixelStoref(QOpenGLFunctions_1_3* self, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlDepthFunc(QOpenGLFunctions_1_3* self, uint32_t func);
void QOpenGLFunctions_1_3_GlStencilOp(QOpenGLFunctions_1_3* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_1_3_GlStencilFunc(QOpenGLFunctions_1_3* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_1_3_GlLogicOp(QOpenGLFunctions_1_3* self, uint32_t opcode);
void QOpenGLFunctions_1_3_GlBlendFunc(QOpenGLFunctions_1_3* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_1_3_GlFlush(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlFinish(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlEnable(QOpenGLFunctions_1_3* self, uint32_t cap);
void QOpenGLFunctions_1_3_GlDisable(QOpenGLFunctions_1_3* self, uint32_t cap);
void QOpenGLFunctions_1_3_GlDepthMask(QOpenGLFunctions_1_3* self, unsigned char flag);
void QOpenGLFunctions_1_3_GlColorMask(QOpenGLFunctions_1_3* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_1_3_GlStencilMask(QOpenGLFunctions_1_3* self, uint32_t mask);
void QOpenGLFunctions_1_3_GlClearDepth(QOpenGLFunctions_1_3* self, double depth);
void QOpenGLFunctions_1_3_GlClearStencil(QOpenGLFunctions_1_3* self, int32_t s);
void QOpenGLFunctions_1_3_GlClearColor(QOpenGLFunctions_1_3* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_3_GlClear(QOpenGLFunctions_1_3* self, uint32_t mask);
void QOpenGLFunctions_1_3_GlDrawBuffer(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlTexImage2D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlTexImage1D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlTexParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlTexParameteri(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlTexParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlTexParameterf(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlScissor(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_3_GlPolygonMode(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_3_GlPointSize(QOpenGLFunctions_1_3* self, float size);
void QOpenGLFunctions_1_3_GlLineWidth(QOpenGLFunctions_1_3* self, float width);
void QOpenGLFunctions_1_3_GlHint(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_1_3_GlFrontFace(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlCullFace(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlIndexubv(QOpenGLFunctions_1_3* self, const uint8_t* c);
void QOpenGLFunctions_1_3_GlIndexub(QOpenGLFunctions_1_3* self, uint8_t c);
unsigned char QOpenGLFunctions_1_3_GlIsTexture(QOpenGLFunctions_1_3* self, uint32_t texture);
void QOpenGLFunctions_1_3_GlGenTextures(QOpenGLFunctions_1_3* self, int32_t n, uint32_t* textures);
void QOpenGLFunctions_1_3_GlDeleteTextures(QOpenGLFunctions_1_3* self, int32_t n, const uint32_t* textures);
void QOpenGLFunctions_1_3_GlBindTexture(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t texture);
void QOpenGLFunctions_1_3_GlTexSubImage2D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlTexSubImage1D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlCopyTexSubImage2D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_3_GlCopyTexSubImage1D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_3_GlCopyTexImage2D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border);
void QOpenGLFunctions_1_3_GlCopyTexImage1D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t border);
void QOpenGLFunctions_1_3_GlPolygonOffset(QOpenGLFunctions_1_3* self, float factor, float units);
void QOpenGLFunctions_1_3_GlGetPointerv(QOpenGLFunctions_1_3* self, uint32_t pname, void** params);
void QOpenGLFunctions_1_3_GlDrawElements(QOpenGLFunctions_1_3* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_1_3_GlDrawArrays(QOpenGLFunctions_1_3* self, uint32_t mode, int32_t first, int32_t count);
void QOpenGLFunctions_1_3_GlCopyTexSubImage3D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_3_GlTexSubImage3D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlTexImage3D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlDrawRangeElements(QOpenGLFunctions_1_3* self, uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_1_3_GlBlendEquation(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlBlendColor(QOpenGLFunctions_1_3* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_3_GlGetCompressedTexImage(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, void* img);
void QOpenGLFunctions_1_3_GlCompressedTexSubImage1D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_3_GlCompressedTexSubImage2D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_3_GlCompressedTexSubImage3D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_3_GlCompressedTexImage1D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_3_GlCompressedTexImage2D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_3_GlCompressedTexImage3D(QOpenGLFunctions_1_3* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_1_3_GlSampleCoverage(QOpenGLFunctions_1_3* self, float value, unsigned char invert);
void QOpenGLFunctions_1_3_GlActiveTexture(QOpenGLFunctions_1_3* self, uint32_t texture);
void QOpenGLFunctions_1_3_GlTranslatef(QOpenGLFunctions_1_3* self, float x, float y, float z);
void QOpenGLFunctions_1_3_GlTranslated(QOpenGLFunctions_1_3* self, double x, double y, double z);
void QOpenGLFunctions_1_3_GlScalef(QOpenGLFunctions_1_3* self, float x, float y, float z);
void QOpenGLFunctions_1_3_GlScaled(QOpenGLFunctions_1_3* self, double x, double y, double z);
void QOpenGLFunctions_1_3_GlRotatef(QOpenGLFunctions_1_3* self, float angle, float x, float y, float z);
void QOpenGLFunctions_1_3_GlRotated(QOpenGLFunctions_1_3* self, double angle, double x, double y, double z);
void QOpenGLFunctions_1_3_GlPushMatrix(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlPopMatrix(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlOrtho(QOpenGLFunctions_1_3* self, double left, double right, double bottom, double top, double zNear, double zFar);
void QOpenGLFunctions_1_3_GlMultMatrixd(QOpenGLFunctions_1_3* self, const double* m);
void QOpenGLFunctions_1_3_GlMultMatrixf(QOpenGLFunctions_1_3* self, const float* m);
void QOpenGLFunctions_1_3_GlMatrixMode(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlLoadMatrixd(QOpenGLFunctions_1_3* self, const double* m);
void QOpenGLFunctions_1_3_GlLoadMatrixf(QOpenGLFunctions_1_3* self, const float* m);
void QOpenGLFunctions_1_3_GlLoadIdentity(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlFrustum(QOpenGLFunctions_1_3* self, double left, double right, double bottom, double top, double zNear, double zFar);
unsigned char QOpenGLFunctions_1_3_GlIsList(QOpenGLFunctions_1_3* self, uint32_t list);
void QOpenGLFunctions_1_3_GlGetTexGeniv(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetTexGenfv(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetTexGendv(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, double* params);
void QOpenGLFunctions_1_3_GlGetTexEnviv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetTexEnvfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetPolygonStipple(QOpenGLFunctions_1_3* self, uint8_t* mask);
void QOpenGLFunctions_1_3_GlGetPixelMapusv(QOpenGLFunctions_1_3* self, uint32_t mapVal, uint16_t* values);
void QOpenGLFunctions_1_3_GlGetPixelMapuiv(QOpenGLFunctions_1_3* self, uint32_t mapVal, uint32_t* values);
void QOpenGLFunctions_1_3_GlGetPixelMapfv(QOpenGLFunctions_1_3* self, uint32_t mapVal, float* values);
void QOpenGLFunctions_1_3_GlGetMaterialiv(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetMaterialfv(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetMapiv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t query, int32_t* v);
void QOpenGLFunctions_1_3_GlGetMapfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t query, float* v);
void QOpenGLFunctions_1_3_GlGetMapdv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t query, double* v);
void QOpenGLFunctions_1_3_GlGetLightiv(QOpenGLFunctions_1_3* self, uint32_t light, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetLightfv(QOpenGLFunctions_1_3* self, uint32_t light, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetClipPlane(QOpenGLFunctions_1_3* self, uint32_t plane, double* equation);
void QOpenGLFunctions_1_3_GlDrawPixels(QOpenGLFunctions_1_3* self, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_3_GlCopyPixels(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t typeVal);
void QOpenGLFunctions_1_3_GlPixelMapusv(QOpenGLFunctions_1_3* self, uint32_t mapVal, int32_t mapsize, const uint16_t* values);
void QOpenGLFunctions_1_3_GlPixelMapuiv(QOpenGLFunctions_1_3* self, uint32_t mapVal, int32_t mapsize, const uint32_t* values);
void QOpenGLFunctions_1_3_GlPixelMapfv(QOpenGLFunctions_1_3* self, uint32_t mapVal, int32_t mapsize, const float* values);
void QOpenGLFunctions_1_3_GlPixelTransferi(QOpenGLFunctions_1_3* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlPixelTransferf(QOpenGLFunctions_1_3* self, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlPixelZoom(QOpenGLFunctions_1_3* self, float xfactor, float yfactor);
void QOpenGLFunctions_1_3_GlAlphaFunc(QOpenGLFunctions_1_3* self, uint32_t func, float ref);
void QOpenGLFunctions_1_3_GlEvalPoint2(QOpenGLFunctions_1_3* self, int32_t i, int32_t j);
void QOpenGLFunctions_1_3_GlEvalMesh2(QOpenGLFunctions_1_3* self, uint32_t mode, int32_t i1Val, int32_t i2Val, int32_t j1, int32_t j2);
void QOpenGLFunctions_1_3_GlEvalPoint1(QOpenGLFunctions_1_3* self, int32_t i);
void QOpenGLFunctions_1_3_GlEvalMesh1(QOpenGLFunctions_1_3* self, uint32_t mode, int32_t i1Val, int32_t i2Val);
void QOpenGLFunctions_1_3_GlEvalCoord2fv(QOpenGLFunctions_1_3* self, const float* u);
void QOpenGLFunctions_1_3_GlEvalCoord2f(QOpenGLFunctions_1_3* self, float u, float v);
void QOpenGLFunctions_1_3_GlEvalCoord2dv(QOpenGLFunctions_1_3* self, const double* u);
void QOpenGLFunctions_1_3_GlEvalCoord2d(QOpenGLFunctions_1_3* self, double u, double v);
void QOpenGLFunctions_1_3_GlEvalCoord1fv(QOpenGLFunctions_1_3* self, const float* u);
void QOpenGLFunctions_1_3_GlEvalCoord1f(QOpenGLFunctions_1_3* self, float u);
void QOpenGLFunctions_1_3_GlEvalCoord1dv(QOpenGLFunctions_1_3* self, const double* u);
void QOpenGLFunctions_1_3_GlEvalCoord1d(QOpenGLFunctions_1_3* self, double u);
void QOpenGLFunctions_1_3_GlMapGrid2f(QOpenGLFunctions_1_3* self, int32_t un, float u1Val, float u2Val, int32_t vn, float v1, float v2);
void QOpenGLFunctions_1_3_GlMapGrid2d(QOpenGLFunctions_1_3* self, int32_t un, double u1Val, double u2Val, int32_t vn, double v1, double v2);
void QOpenGLFunctions_1_3_GlMapGrid1f(QOpenGLFunctions_1_3* self, int32_t un, float u1Val, float u2Val);
void QOpenGLFunctions_1_3_GlMapGrid1d(QOpenGLFunctions_1_3* self, int32_t un, double u1Val, double u2Val);
void QOpenGLFunctions_1_3_GlMap2f(QOpenGLFunctions_1_3* self, uint32_t target, float u1Val, float u2Val, int32_t ustride, int32_t uorder, float v1, float v2, int32_t vstride, int32_t vorder, const float* points);
void QOpenGLFunctions_1_3_GlMap2d(QOpenGLFunctions_1_3* self, uint32_t target, double u1Val, double u2Val, int32_t ustride, int32_t uorder, double v1, double v2, int32_t vstride, int32_t vorder, const double* points);
void QOpenGLFunctions_1_3_GlMap1f(QOpenGLFunctions_1_3* self, uint32_t target, float u1Val, float u2Val, int32_t stride, int32_t order, const float* points);
void QOpenGLFunctions_1_3_GlMap1d(QOpenGLFunctions_1_3* self, uint32_t target, double u1Val, double u2Val, int32_t stride, int32_t order, const double* points);
void QOpenGLFunctions_1_3_GlPushAttrib(QOpenGLFunctions_1_3* self, uint32_t mask);
void QOpenGLFunctions_1_3_GlPopAttrib(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlAccum(QOpenGLFunctions_1_3* self, uint32_t op, float value);
void QOpenGLFunctions_1_3_GlIndexMask(QOpenGLFunctions_1_3* self, uint32_t mask);
void QOpenGLFunctions_1_3_GlClearIndex(QOpenGLFunctions_1_3* self, float c);
void QOpenGLFunctions_1_3_GlClearAccum(QOpenGLFunctions_1_3* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_3_GlPushName(QOpenGLFunctions_1_3* self, uint32_t name);
void QOpenGLFunctions_1_3_GlPopName(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlPassThrough(QOpenGLFunctions_1_3* self, float token);
void QOpenGLFunctions_1_3_GlLoadName(QOpenGLFunctions_1_3* self, uint32_t name);
void QOpenGLFunctions_1_3_GlInitNames(QOpenGLFunctions_1_3* self);
int32_t QOpenGLFunctions_1_3_GlRenderMode(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlSelectBuffer(QOpenGLFunctions_1_3* self, int32_t size, uint32_t* buffer);
void QOpenGLFunctions_1_3_GlFeedbackBuffer(QOpenGLFunctions_1_3* self, int32_t size, uint32_t typeVal, float* buffer);
void QOpenGLFunctions_1_3_GlTexGeniv(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlTexGeni(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlTexGenfv(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlTexGenf(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlTexGendv(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, const double* params);
void QOpenGLFunctions_1_3_GlTexGend(QOpenGLFunctions_1_3* self, uint32_t coord, uint32_t pname, double param);
void QOpenGLFunctions_1_3_GlTexEnviv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlTexEnvi(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlTexEnvfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlTexEnvf(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlShadeModel(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlPolygonStipple(QOpenGLFunctions_1_3* self, const uint8_t* mask);
void QOpenGLFunctions_1_3_GlMaterialiv(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlMateriali(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlMaterialfv(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlMaterialf(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlLineStipple(QOpenGLFunctions_1_3* self, int32_t factor, uint16_t pattern);
void QOpenGLFunctions_1_3_GlLightModeliv(QOpenGLFunctions_1_3* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlLightModeli(QOpenGLFunctions_1_3* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlLightModelfv(QOpenGLFunctions_1_3* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlLightModelf(QOpenGLFunctions_1_3* self, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlLightiv(QOpenGLFunctions_1_3* self, uint32_t light, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlLighti(QOpenGLFunctions_1_3* self, uint32_t light, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlLightfv(QOpenGLFunctions_1_3* self, uint32_t light, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlLightf(QOpenGLFunctions_1_3* self, uint32_t light, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlFogiv(QOpenGLFunctions_1_3* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlFogi(QOpenGLFunctions_1_3* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_3_GlFogfv(QOpenGLFunctions_1_3* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlFogf(QOpenGLFunctions_1_3* self, uint32_t pname, float param);
void QOpenGLFunctions_1_3_GlColorMaterial(QOpenGLFunctions_1_3* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_3_GlClipPlane(QOpenGLFunctions_1_3* self, uint32_t plane, const double* equation);
void QOpenGLFunctions_1_3_GlVertex4sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlVertex4s(QOpenGLFunctions_1_3* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_3_GlVertex4iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlVertex4i(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_3_GlVertex4fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlVertex4f(QOpenGLFunctions_1_3* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_3_GlVertex4dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlVertex4d(QOpenGLFunctions_1_3* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_3_GlVertex3sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlVertex3s(QOpenGLFunctions_1_3* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_3_GlVertex3iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlVertex3i(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_3_GlVertex3fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlVertex3f(QOpenGLFunctions_1_3* self, float x, float y, float z);
void QOpenGLFunctions_1_3_GlVertex3dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlVertex3d(QOpenGLFunctions_1_3* self, double x, double y, double z);
void QOpenGLFunctions_1_3_GlVertex2sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlVertex2s(QOpenGLFunctions_1_3* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_3_GlVertex2iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlVertex2i(QOpenGLFunctions_1_3* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_3_GlVertex2fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlVertex2f(QOpenGLFunctions_1_3* self, float x, float y);
void QOpenGLFunctions_1_3_GlVertex2dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlVertex2d(QOpenGLFunctions_1_3* self, double x, double y);
void QOpenGLFunctions_1_3_GlTexCoord4sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlTexCoord4s(QOpenGLFunctions_1_3* self, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_1_3_GlTexCoord4iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlTexCoord4i(QOpenGLFunctions_1_3* self, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_1_3_GlTexCoord4fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlTexCoord4f(QOpenGLFunctions_1_3* self, float s, float t, float r, float q);
void QOpenGLFunctions_1_3_GlTexCoord4dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlTexCoord4d(QOpenGLFunctions_1_3* self, double s, double t, double r, double q);
void QOpenGLFunctions_1_3_GlTexCoord3sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlTexCoord3s(QOpenGLFunctions_1_3* self, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_1_3_GlTexCoord3iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlTexCoord3i(QOpenGLFunctions_1_3* self, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_1_3_GlTexCoord3fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlTexCoord3f(QOpenGLFunctions_1_3* self, float s, float t, float r);
void QOpenGLFunctions_1_3_GlTexCoord3dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlTexCoord3d(QOpenGLFunctions_1_3* self, double s, double t, double r);
void QOpenGLFunctions_1_3_GlTexCoord2sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlTexCoord2s(QOpenGLFunctions_1_3* self, int16_t s, int16_t t);
void QOpenGLFunctions_1_3_GlTexCoord2iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlTexCoord2i(QOpenGLFunctions_1_3* self, int32_t s, int32_t t);
void QOpenGLFunctions_1_3_GlTexCoord2fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlTexCoord2f(QOpenGLFunctions_1_3* self, float s, float t);
void QOpenGLFunctions_1_3_GlTexCoord2dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlTexCoord2d(QOpenGLFunctions_1_3* self, double s, double t);
void QOpenGLFunctions_1_3_GlTexCoord1sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlTexCoord1s(QOpenGLFunctions_1_3* self, int16_t s);
void QOpenGLFunctions_1_3_GlTexCoord1iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlTexCoord1i(QOpenGLFunctions_1_3* self, int32_t s);
void QOpenGLFunctions_1_3_GlTexCoord1fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlTexCoord1f(QOpenGLFunctions_1_3* self, float s);
void QOpenGLFunctions_1_3_GlTexCoord1dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlTexCoord1d(QOpenGLFunctions_1_3* self, double s);
void QOpenGLFunctions_1_3_GlRectsv(QOpenGLFunctions_1_3* self, const int16_t* v1, const int16_t* v2);
void QOpenGLFunctions_1_3_GlRects(QOpenGLFunctions_1_3* self, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void QOpenGLFunctions_1_3_GlRectiv(QOpenGLFunctions_1_3* self, const int32_t* v1, const int32_t* v2);
void QOpenGLFunctions_1_3_GlRecti(QOpenGLFunctions_1_3* self, int32_t x1, int32_t y1, int32_t x2, int32_t y2);
void QOpenGLFunctions_1_3_GlRectfv(QOpenGLFunctions_1_3* self, const float* v1, const float* v2);
void QOpenGLFunctions_1_3_GlRectf(QOpenGLFunctions_1_3* self, float x1, float y1, float x2, float y2);
void QOpenGLFunctions_1_3_GlRectdv(QOpenGLFunctions_1_3* self, const double* v1, const double* v2);
void QOpenGLFunctions_1_3_GlRectd(QOpenGLFunctions_1_3* self, double x1, double y1, double x2, double y2);
void QOpenGLFunctions_1_3_GlRasterPos4sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlRasterPos4s(QOpenGLFunctions_1_3* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_3_GlRasterPos4iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlRasterPos4i(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_3_GlRasterPos4fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlRasterPos4f(QOpenGLFunctions_1_3* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_3_GlRasterPos4dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlRasterPos4d(QOpenGLFunctions_1_3* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_3_GlRasterPos3sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlRasterPos3s(QOpenGLFunctions_1_3* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_3_GlRasterPos3iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlRasterPos3i(QOpenGLFunctions_1_3* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_3_GlRasterPos3fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlRasterPos3f(QOpenGLFunctions_1_3* self, float x, float y, float z);
void QOpenGLFunctions_1_3_GlRasterPos3dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlRasterPos3d(QOpenGLFunctions_1_3* self, double x, double y, double z);
void QOpenGLFunctions_1_3_GlRasterPos2sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlRasterPos2s(QOpenGLFunctions_1_3* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_3_GlRasterPos2iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlRasterPos2i(QOpenGLFunctions_1_3* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_3_GlRasterPos2fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlRasterPos2f(QOpenGLFunctions_1_3* self, float x, float y);
void QOpenGLFunctions_1_3_GlRasterPos2dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlRasterPos2d(QOpenGLFunctions_1_3* self, double x, double y);
void QOpenGLFunctions_1_3_GlNormal3sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlNormal3s(QOpenGLFunctions_1_3* self, int16_t nx, int16_t ny, int16_t nz);
void QOpenGLFunctions_1_3_GlNormal3iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlNormal3i(QOpenGLFunctions_1_3* self, int32_t nx, int32_t ny, int32_t nz);
void QOpenGLFunctions_1_3_GlNormal3fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlNormal3f(QOpenGLFunctions_1_3* self, float nx, float ny, float nz);
void QOpenGLFunctions_1_3_GlNormal3dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlNormal3d(QOpenGLFunctions_1_3* self, double nx, double ny, double nz);
void QOpenGLFunctions_1_3_GlNormal3bv(QOpenGLFunctions_1_3* self, const signed char* v);
void QOpenGLFunctions_1_3_GlNormal3b(QOpenGLFunctions_1_3* self, signed char nx, signed char ny, signed char nz);
void QOpenGLFunctions_1_3_GlIndexsv(QOpenGLFunctions_1_3* self, const int16_t* c);
void QOpenGLFunctions_1_3_GlIndexs(QOpenGLFunctions_1_3* self, int16_t c);
void QOpenGLFunctions_1_3_GlIndexiv(QOpenGLFunctions_1_3* self, const int32_t* c);
void QOpenGLFunctions_1_3_GlIndexi(QOpenGLFunctions_1_3* self, int32_t c);
void QOpenGLFunctions_1_3_GlIndexfv(QOpenGLFunctions_1_3* self, const float* c);
void QOpenGLFunctions_1_3_GlIndexf(QOpenGLFunctions_1_3* self, float c);
void QOpenGLFunctions_1_3_GlIndexdv(QOpenGLFunctions_1_3* self, const double* c);
void QOpenGLFunctions_1_3_GlIndexd(QOpenGLFunctions_1_3* self, double c);
void QOpenGLFunctions_1_3_GlEnd(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlEdgeFlagv(QOpenGLFunctions_1_3* self, const unsigned char* flag);
void QOpenGLFunctions_1_3_GlEdgeFlag(QOpenGLFunctions_1_3* self, unsigned char flag);
void QOpenGLFunctions_1_3_GlColor4usv(QOpenGLFunctions_1_3* self, const uint16_t* v);
void QOpenGLFunctions_1_3_GlColor4us(QOpenGLFunctions_1_3* self, uint16_t red, uint16_t green, uint16_t blue, uint16_t alpha);
void QOpenGLFunctions_1_3_GlColor4uiv(QOpenGLFunctions_1_3* self, const uint32_t* v);
void QOpenGLFunctions_1_3_GlColor4ui(QOpenGLFunctions_1_3* self, uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha);
void QOpenGLFunctions_1_3_GlColor4ubv(QOpenGLFunctions_1_3* self, const uint8_t* v);
void QOpenGLFunctions_1_3_GlColor4ub(QOpenGLFunctions_1_3* self, uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha);
void QOpenGLFunctions_1_3_GlColor4sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlColor4s(QOpenGLFunctions_1_3* self, int16_t red, int16_t green, int16_t blue, int16_t alpha);
void QOpenGLFunctions_1_3_GlColor4iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlColor4i(QOpenGLFunctions_1_3* self, int32_t red, int32_t green, int32_t blue, int32_t alpha);
void QOpenGLFunctions_1_3_GlColor4fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlColor4f(QOpenGLFunctions_1_3* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_3_GlColor4dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlColor4d(QOpenGLFunctions_1_3* self, double red, double green, double blue, double alpha);
void QOpenGLFunctions_1_3_GlColor4bv(QOpenGLFunctions_1_3* self, const signed char* v);
void QOpenGLFunctions_1_3_GlColor4b(QOpenGLFunctions_1_3* self, signed char red, signed char green, signed char blue, signed char alpha);
void QOpenGLFunctions_1_3_GlColor3usv(QOpenGLFunctions_1_3* self, const uint16_t* v);
void QOpenGLFunctions_1_3_GlColor3us(QOpenGLFunctions_1_3* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_1_3_GlColor3uiv(QOpenGLFunctions_1_3* self, const uint32_t* v);
void QOpenGLFunctions_1_3_GlColor3ui(QOpenGLFunctions_1_3* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_1_3_GlColor3ubv(QOpenGLFunctions_1_3* self, const uint8_t* v);
void QOpenGLFunctions_1_3_GlColor3ub(QOpenGLFunctions_1_3* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_1_3_GlColor3sv(QOpenGLFunctions_1_3* self, const int16_t* v);
void QOpenGLFunctions_1_3_GlColor3s(QOpenGLFunctions_1_3* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_1_3_GlColor3iv(QOpenGLFunctions_1_3* self, const int32_t* v);
void QOpenGLFunctions_1_3_GlColor3i(QOpenGLFunctions_1_3* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_1_3_GlColor3fv(QOpenGLFunctions_1_3* self, const float* v);
void QOpenGLFunctions_1_3_GlColor3f(QOpenGLFunctions_1_3* self, float red, float green, float blue);
void QOpenGLFunctions_1_3_GlColor3dv(QOpenGLFunctions_1_3* self, const double* v);
void QOpenGLFunctions_1_3_GlColor3d(QOpenGLFunctions_1_3* self, double red, double green, double blue);
void QOpenGLFunctions_1_3_GlColor3bv(QOpenGLFunctions_1_3* self, const signed char* v);
void QOpenGLFunctions_1_3_GlColor3b(QOpenGLFunctions_1_3* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_1_3_GlBitmap(QOpenGLFunctions_1_3* self, int32_t width, int32_t height, float xorig, float yorig, float xmove, float ymove, const uint8_t* bitmap);
void QOpenGLFunctions_1_3_GlBegin(QOpenGLFunctions_1_3* self, uint32_t mode);
void QOpenGLFunctions_1_3_GlListBase(QOpenGLFunctions_1_3* self, uint32_t base);
uint32_t QOpenGLFunctions_1_3_GlGenLists(QOpenGLFunctions_1_3* self, int32_t range);
void QOpenGLFunctions_1_3_GlDeleteLists(QOpenGLFunctions_1_3* self, uint32_t list, int32_t range);
void QOpenGLFunctions_1_3_GlCallLists(QOpenGLFunctions_1_3* self, int32_t n, uint32_t typeVal, const void* lists);
void QOpenGLFunctions_1_3_GlCallList(QOpenGLFunctions_1_3* self, uint32_t list);
void QOpenGLFunctions_1_3_GlEndList(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlNewList(QOpenGLFunctions_1_3* self, uint32_t list, uint32_t mode);
void QOpenGLFunctions_1_3_GlPushClientAttrib(QOpenGLFunctions_1_3* self, uint32_t mask);
void QOpenGLFunctions_1_3_GlPopClientAttrib(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_GlPrioritizeTextures(QOpenGLFunctions_1_3* self, int32_t n, const uint32_t* textures, const float* priorities);
unsigned char QOpenGLFunctions_1_3_GlAreTexturesResident(QOpenGLFunctions_1_3* self, int32_t n, const uint32_t* textures, unsigned char* residences);
void QOpenGLFunctions_1_3_GlVertexPointer(QOpenGLFunctions_1_3* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlTexCoordPointer(QOpenGLFunctions_1_3* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlNormalPointer(QOpenGLFunctions_1_3* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlInterleavedArrays(QOpenGLFunctions_1_3* self, uint32_t format, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlIndexPointer(QOpenGLFunctions_1_3* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlEnableClientState(QOpenGLFunctions_1_3* self, uint32_t array);
void QOpenGLFunctions_1_3_GlEdgeFlagPointer(QOpenGLFunctions_1_3* self, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlDisableClientState(QOpenGLFunctions_1_3* self, uint32_t array);
void QOpenGLFunctions_1_3_GlColorPointer(QOpenGLFunctions_1_3* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_3_GlArrayElement(QOpenGLFunctions_1_3* self, int32_t i);
void QOpenGLFunctions_1_3_GlResetMinmax(QOpenGLFunctions_1_3* self, uint32_t target);
void QOpenGLFunctions_1_3_GlResetHistogram(QOpenGLFunctions_1_3* self, uint32_t target);
void QOpenGLFunctions_1_3_GlMinmax(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_1_3_GlHistogram(QOpenGLFunctions_1_3* self, uint32_t target, int32_t width, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_1_3_GlGetMinmaxParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetMinmaxParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetMinmax(QOpenGLFunctions_1_3* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_1_3_GlGetHistogramParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetHistogramParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetHistogram(QOpenGLFunctions_1_3* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_1_3_GlSeparableFilter2D(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* row, const void* column);
void QOpenGLFunctions_1_3_GlGetSeparableFilter(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t format, uint32_t typeVal, void* row, void* column, void* span);
void QOpenGLFunctions_1_3_GlGetConvolutionParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetConvolutionParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetConvolutionFilter(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t format, uint32_t typeVal, void* image);
void QOpenGLFunctions_1_3_GlCopyConvolutionFilter2D(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_3_GlCopyConvolutionFilter1D(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_3_GlConvolutionParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlConvolutionParameteri(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t params);
void QOpenGLFunctions_1_3_GlConvolutionParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlConvolutionParameterf(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float params);
void QOpenGLFunctions_1_3_GlConvolutionFilter2D(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_1_3_GlConvolutionFilter1D(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_1_3_GlCopyColorSubTable(QOpenGLFunctions_1_3* self, uint32_t target, int32_t start, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_3_GlColorSubTable(QOpenGLFunctions_1_3* self, uint32_t target, int32_t start, int32_t count, uint32_t format, uint32_t typeVal, const void* data);
void QOpenGLFunctions_1_3_GlGetColorTableParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_3_GlGetColorTableParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_3_GlGetColorTable(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t format, uint32_t typeVal, void* table);
void QOpenGLFunctions_1_3_GlCopyColorTable(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_3_GlColorTableParameteriv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_3_GlColorTableParameterfv(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_3_GlColorTable(QOpenGLFunctions_1_3* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* table);
void QOpenGLFunctions_1_3_GlMultTransposeMatrixd(QOpenGLFunctions_1_3* self, const double* m);
void QOpenGLFunctions_1_3_GlMultTransposeMatrixf(QOpenGLFunctions_1_3* self, const float* m);
void QOpenGLFunctions_1_3_GlLoadTransposeMatrixd(QOpenGLFunctions_1_3* self, const double* m);
void QOpenGLFunctions_1_3_GlLoadTransposeMatrixf(QOpenGLFunctions_1_3* self, const float* m);
void QOpenGLFunctions_1_3_GlMultiTexCoord4sv(QOpenGLFunctions_1_3* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord4s(QOpenGLFunctions_1_3* self, uint32_t target, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_1_3_GlMultiTexCoord4iv(QOpenGLFunctions_1_3* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord4i(QOpenGLFunctions_1_3* self, uint32_t target, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_1_3_GlMultiTexCoord4fv(QOpenGLFunctions_1_3* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord4f(QOpenGLFunctions_1_3* self, uint32_t target, float s, float t, float r, float q);
void QOpenGLFunctions_1_3_GlMultiTexCoord4dv(QOpenGLFunctions_1_3* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord4d(QOpenGLFunctions_1_3* self, uint32_t target, double s, double t, double r, double q);
void QOpenGLFunctions_1_3_GlMultiTexCoord3sv(QOpenGLFunctions_1_3* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord3s(QOpenGLFunctions_1_3* self, uint32_t target, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_1_3_GlMultiTexCoord3iv(QOpenGLFunctions_1_3* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord3i(QOpenGLFunctions_1_3* self, uint32_t target, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_1_3_GlMultiTexCoord3fv(QOpenGLFunctions_1_3* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord3f(QOpenGLFunctions_1_3* self, uint32_t target, float s, float t, float r);
void QOpenGLFunctions_1_3_GlMultiTexCoord3dv(QOpenGLFunctions_1_3* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord3d(QOpenGLFunctions_1_3* self, uint32_t target, double s, double t, double r);
void QOpenGLFunctions_1_3_GlMultiTexCoord2sv(QOpenGLFunctions_1_3* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord2s(QOpenGLFunctions_1_3* self, uint32_t target, int16_t s, int16_t t);
void QOpenGLFunctions_1_3_GlMultiTexCoord2iv(QOpenGLFunctions_1_3* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord2i(QOpenGLFunctions_1_3* self, uint32_t target, int32_t s, int32_t t);
void QOpenGLFunctions_1_3_GlMultiTexCoord2fv(QOpenGLFunctions_1_3* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord2f(QOpenGLFunctions_1_3* self, uint32_t target, float s, float t);
void QOpenGLFunctions_1_3_GlMultiTexCoord2dv(QOpenGLFunctions_1_3* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord2d(QOpenGLFunctions_1_3* self, uint32_t target, double s, double t);
void QOpenGLFunctions_1_3_GlMultiTexCoord1sv(QOpenGLFunctions_1_3* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord1s(QOpenGLFunctions_1_3* self, uint32_t target, int16_t s);
void QOpenGLFunctions_1_3_GlMultiTexCoord1iv(QOpenGLFunctions_1_3* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord1i(QOpenGLFunctions_1_3* self, uint32_t target, int32_t s);
void QOpenGLFunctions_1_3_GlMultiTexCoord1fv(QOpenGLFunctions_1_3* self, uint32_t target, const float* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord1f(QOpenGLFunctions_1_3* self, uint32_t target, float s);
void QOpenGLFunctions_1_3_GlMultiTexCoord1dv(QOpenGLFunctions_1_3* self, uint32_t target, const double* v);
void QOpenGLFunctions_1_3_GlMultiTexCoord1d(QOpenGLFunctions_1_3* self, uint32_t target, double s);
void QOpenGLFunctions_1_3_GlClientActiveTexture(QOpenGLFunctions_1_3* self, uint32_t texture);
void QOpenGLFunctions_1_3_OnInitializeOpenGLFunctions(QOpenGLFunctions_1_3* self, intptr_t slot);
bool QOpenGLFunctions_1_3_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_1_3* self);
void QOpenGLFunctions_1_3_Delete(QOpenGLFunctions_1_3* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
