#pragma once
#ifndef QOPENGLFUNCTIONS_1_0_H_C_LIB
#define QOPENGLFUNCTIONS_1_0_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_1_0 QOpenGLFunctions_1_0;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_1_0* QOpenGLFunctions_1_0_new();
bool QOpenGLFunctions_1_0_InitializeOpenGLFunctions(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlViewport(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_0_GlDepthRange(QOpenGLFunctions_1_0* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_1_0_GlIsEnabled(QOpenGLFunctions_1_0* self, uint32_t cap);
void QOpenGLFunctions_1_0_GlGetTexLevelParameteriv(QOpenGLFunctions_1_0* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetTexLevelParameterfv(QOpenGLFunctions_1_0* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetTexParameteriv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetTexParameterfv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetTexImage(QOpenGLFunctions_1_0* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_1_0_GlGetString(QOpenGLFunctions_1_0* self, uint32_t name);
void QOpenGLFunctions_1_0_GlGetIntegerv(QOpenGLFunctions_1_0* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetFloatv(QOpenGLFunctions_1_0* self, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetDoublev(QOpenGLFunctions_1_0* self, uint32_t pname, double* params);
void QOpenGLFunctions_1_0_GlGetBooleanv(QOpenGLFunctions_1_0* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_1_0_GlReadPixels(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_1_0_GlReadBuffer(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlPixelStorei(QOpenGLFunctions_1_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlPixelStoref(QOpenGLFunctions_1_0* self, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlDepthFunc(QOpenGLFunctions_1_0* self, uint32_t func);
void QOpenGLFunctions_1_0_GlStencilOp(QOpenGLFunctions_1_0* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_1_0_GlStencilFunc(QOpenGLFunctions_1_0* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_1_0_GlLogicOp(QOpenGLFunctions_1_0* self, uint32_t opcode);
void QOpenGLFunctions_1_0_GlBlendFunc(QOpenGLFunctions_1_0* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_1_0_GlFlush(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlFinish(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlEnable(QOpenGLFunctions_1_0* self, uint32_t cap);
void QOpenGLFunctions_1_0_GlDisable(QOpenGLFunctions_1_0* self, uint32_t cap);
void QOpenGLFunctions_1_0_GlDepthMask(QOpenGLFunctions_1_0* self, unsigned char flag);
void QOpenGLFunctions_1_0_GlColorMask(QOpenGLFunctions_1_0* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_1_0_GlStencilMask(QOpenGLFunctions_1_0* self, uint32_t mask);
void QOpenGLFunctions_1_0_GlClearDepth(QOpenGLFunctions_1_0* self, double depth);
void QOpenGLFunctions_1_0_GlClearStencil(QOpenGLFunctions_1_0* self, int32_t s);
void QOpenGLFunctions_1_0_GlClearColor(QOpenGLFunctions_1_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_0_GlClear(QOpenGLFunctions_1_0* self, uint32_t mask);
void QOpenGLFunctions_1_0_GlDrawBuffer(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlTexImage2D(QOpenGLFunctions_1_0* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_0_GlTexImage1D(QOpenGLFunctions_1_0* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_0_GlTexParameteriv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlTexParameteri(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlTexParameterfv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlTexParameterf(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlScissor(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_0_GlPolygonMode(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_0_GlPointSize(QOpenGLFunctions_1_0* self, float size);
void QOpenGLFunctions_1_0_GlLineWidth(QOpenGLFunctions_1_0* self, float width);
void QOpenGLFunctions_1_0_GlHint(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_1_0_GlFrontFace(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlCullFace(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlTranslatef(QOpenGLFunctions_1_0* self, float x, float y, float z);
void QOpenGLFunctions_1_0_GlTranslated(QOpenGLFunctions_1_0* self, double x, double y, double z);
void QOpenGLFunctions_1_0_GlScalef(QOpenGLFunctions_1_0* self, float x, float y, float z);
void QOpenGLFunctions_1_0_GlScaled(QOpenGLFunctions_1_0* self, double x, double y, double z);
void QOpenGLFunctions_1_0_GlRotatef(QOpenGLFunctions_1_0* self, float angle, float x, float y, float z);
void QOpenGLFunctions_1_0_GlRotated(QOpenGLFunctions_1_0* self, double angle, double x, double y, double z);
void QOpenGLFunctions_1_0_GlPushMatrix(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlPopMatrix(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlOrtho(QOpenGLFunctions_1_0* self, double left, double right, double bottom, double top, double zNear, double zFar);
void QOpenGLFunctions_1_0_GlMultMatrixd(QOpenGLFunctions_1_0* self, const double* m);
void QOpenGLFunctions_1_0_GlMultMatrixf(QOpenGLFunctions_1_0* self, const float* m);
void QOpenGLFunctions_1_0_GlMatrixMode(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlLoadMatrixd(QOpenGLFunctions_1_0* self, const double* m);
void QOpenGLFunctions_1_0_GlLoadMatrixf(QOpenGLFunctions_1_0* self, const float* m);
void QOpenGLFunctions_1_0_GlLoadIdentity(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlFrustum(QOpenGLFunctions_1_0* self, double left, double right, double bottom, double top, double zNear, double zFar);
unsigned char QOpenGLFunctions_1_0_GlIsList(QOpenGLFunctions_1_0* self, uint32_t list);
void QOpenGLFunctions_1_0_GlGetTexGeniv(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetTexGenfv(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetTexGendv(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, double* params);
void QOpenGLFunctions_1_0_GlGetTexEnviv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetTexEnvfv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetPolygonStipple(QOpenGLFunctions_1_0* self, uint8_t* mask);
void QOpenGLFunctions_1_0_GlGetPixelMapusv(QOpenGLFunctions_1_0* self, uint32_t mapVal, uint16_t* values);
void QOpenGLFunctions_1_0_GlGetPixelMapuiv(QOpenGLFunctions_1_0* self, uint32_t mapVal, uint32_t* values);
void QOpenGLFunctions_1_0_GlGetPixelMapfv(QOpenGLFunctions_1_0* self, uint32_t mapVal, float* values);
void QOpenGLFunctions_1_0_GlGetMaterialiv(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetMaterialfv(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetMapiv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t query, int32_t* v);
void QOpenGLFunctions_1_0_GlGetMapfv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t query, float* v);
void QOpenGLFunctions_1_0_GlGetMapdv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t query, double* v);
void QOpenGLFunctions_1_0_GlGetLightiv(QOpenGLFunctions_1_0* self, uint32_t light, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_0_GlGetLightfv(QOpenGLFunctions_1_0* self, uint32_t light, uint32_t pname, float* params);
void QOpenGLFunctions_1_0_GlGetClipPlane(QOpenGLFunctions_1_0* self, uint32_t plane, double* equation);
void QOpenGLFunctions_1_0_GlDrawPixels(QOpenGLFunctions_1_0* self, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_0_GlCopyPixels(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t typeVal);
void QOpenGLFunctions_1_0_GlPixelMapusv(QOpenGLFunctions_1_0* self, uint32_t mapVal, int32_t mapsize, const uint16_t* values);
void QOpenGLFunctions_1_0_GlPixelMapuiv(QOpenGLFunctions_1_0* self, uint32_t mapVal, int32_t mapsize, const uint32_t* values);
void QOpenGLFunctions_1_0_GlPixelMapfv(QOpenGLFunctions_1_0* self, uint32_t mapVal, int32_t mapsize, const float* values);
void QOpenGLFunctions_1_0_GlPixelTransferi(QOpenGLFunctions_1_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlPixelTransferf(QOpenGLFunctions_1_0* self, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlPixelZoom(QOpenGLFunctions_1_0* self, float xfactor, float yfactor);
void QOpenGLFunctions_1_0_GlAlphaFunc(QOpenGLFunctions_1_0* self, uint32_t func, float ref);
void QOpenGLFunctions_1_0_GlEvalPoint2(QOpenGLFunctions_1_0* self, int32_t i, int32_t j);
void QOpenGLFunctions_1_0_GlEvalMesh2(QOpenGLFunctions_1_0* self, uint32_t mode, int32_t i1Val, int32_t i2Val, int32_t j1, int32_t j2);
void QOpenGLFunctions_1_0_GlEvalPoint1(QOpenGLFunctions_1_0* self, int32_t i);
void QOpenGLFunctions_1_0_GlEvalMesh1(QOpenGLFunctions_1_0* self, uint32_t mode, int32_t i1Val, int32_t i2Val);
void QOpenGLFunctions_1_0_GlEvalCoord2fv(QOpenGLFunctions_1_0* self, const float* u);
void QOpenGLFunctions_1_0_GlEvalCoord2f(QOpenGLFunctions_1_0* self, float u, float v);
void QOpenGLFunctions_1_0_GlEvalCoord2dv(QOpenGLFunctions_1_0* self, const double* u);
void QOpenGLFunctions_1_0_GlEvalCoord2d(QOpenGLFunctions_1_0* self, double u, double v);
void QOpenGLFunctions_1_0_GlEvalCoord1fv(QOpenGLFunctions_1_0* self, const float* u);
void QOpenGLFunctions_1_0_GlEvalCoord1f(QOpenGLFunctions_1_0* self, float u);
void QOpenGLFunctions_1_0_GlEvalCoord1dv(QOpenGLFunctions_1_0* self, const double* u);
void QOpenGLFunctions_1_0_GlEvalCoord1d(QOpenGLFunctions_1_0* self, double u);
void QOpenGLFunctions_1_0_GlMapGrid2f(QOpenGLFunctions_1_0* self, int32_t un, float u1Val, float u2Val, int32_t vn, float v1, float v2);
void QOpenGLFunctions_1_0_GlMapGrid2d(QOpenGLFunctions_1_0* self, int32_t un, double u1Val, double u2Val, int32_t vn, double v1, double v2);
void QOpenGLFunctions_1_0_GlMapGrid1f(QOpenGLFunctions_1_0* self, int32_t un, float u1Val, float u2Val);
void QOpenGLFunctions_1_0_GlMapGrid1d(QOpenGLFunctions_1_0* self, int32_t un, double u1Val, double u2Val);
void QOpenGLFunctions_1_0_GlMap2f(QOpenGLFunctions_1_0* self, uint32_t target, float u1Val, float u2Val, int32_t ustride, int32_t uorder, float v1, float v2, int32_t vstride, int32_t vorder, const float* points);
void QOpenGLFunctions_1_0_GlMap2d(QOpenGLFunctions_1_0* self, uint32_t target, double u1Val, double u2Val, int32_t ustride, int32_t uorder, double v1, double v2, int32_t vstride, int32_t vorder, const double* points);
void QOpenGLFunctions_1_0_GlMap1f(QOpenGLFunctions_1_0* self, uint32_t target, float u1Val, float u2Val, int32_t stride, int32_t order, const float* points);
void QOpenGLFunctions_1_0_GlMap1d(QOpenGLFunctions_1_0* self, uint32_t target, double u1Val, double u2Val, int32_t stride, int32_t order, const double* points);
void QOpenGLFunctions_1_0_GlPushAttrib(QOpenGLFunctions_1_0* self, uint32_t mask);
void QOpenGLFunctions_1_0_GlPopAttrib(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlAccum(QOpenGLFunctions_1_0* self, uint32_t op, float value);
void QOpenGLFunctions_1_0_GlIndexMask(QOpenGLFunctions_1_0* self, uint32_t mask);
void QOpenGLFunctions_1_0_GlClearIndex(QOpenGLFunctions_1_0* self, float c);
void QOpenGLFunctions_1_0_GlClearAccum(QOpenGLFunctions_1_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_0_GlPushName(QOpenGLFunctions_1_0* self, uint32_t name);
void QOpenGLFunctions_1_0_GlPopName(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlPassThrough(QOpenGLFunctions_1_0* self, float token);
void QOpenGLFunctions_1_0_GlLoadName(QOpenGLFunctions_1_0* self, uint32_t name);
void QOpenGLFunctions_1_0_GlInitNames(QOpenGLFunctions_1_0* self);
int32_t QOpenGLFunctions_1_0_GlRenderMode(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlSelectBuffer(QOpenGLFunctions_1_0* self, int32_t size, uint32_t* buffer);
void QOpenGLFunctions_1_0_GlFeedbackBuffer(QOpenGLFunctions_1_0* self, int32_t size, uint32_t typeVal, float* buffer);
void QOpenGLFunctions_1_0_GlTexGeniv(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlTexGeni(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlTexGenfv(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlTexGenf(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlTexGendv(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, const double* params);
void QOpenGLFunctions_1_0_GlTexGend(QOpenGLFunctions_1_0* self, uint32_t coord, uint32_t pname, double param);
void QOpenGLFunctions_1_0_GlTexEnviv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlTexEnvi(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlTexEnvfv(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlTexEnvf(QOpenGLFunctions_1_0* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlShadeModel(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlPolygonStipple(QOpenGLFunctions_1_0* self, const uint8_t* mask);
void QOpenGLFunctions_1_0_GlMaterialiv(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlMateriali(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlMaterialfv(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlMaterialf(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlLineStipple(QOpenGLFunctions_1_0* self, int32_t factor, uint16_t pattern);
void QOpenGLFunctions_1_0_GlLightModeliv(QOpenGLFunctions_1_0* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlLightModeli(QOpenGLFunctions_1_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlLightModelfv(QOpenGLFunctions_1_0* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlLightModelf(QOpenGLFunctions_1_0* self, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlLightiv(QOpenGLFunctions_1_0* self, uint32_t light, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlLighti(QOpenGLFunctions_1_0* self, uint32_t light, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlLightfv(QOpenGLFunctions_1_0* self, uint32_t light, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlLightf(QOpenGLFunctions_1_0* self, uint32_t light, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlFogiv(QOpenGLFunctions_1_0* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_0_GlFogi(QOpenGLFunctions_1_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_0_GlFogfv(QOpenGLFunctions_1_0* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_0_GlFogf(QOpenGLFunctions_1_0* self, uint32_t pname, float param);
void QOpenGLFunctions_1_0_GlColorMaterial(QOpenGLFunctions_1_0* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_0_GlClipPlane(QOpenGLFunctions_1_0* self, uint32_t plane, const double* equation);
void QOpenGLFunctions_1_0_GlVertex4sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlVertex4s(QOpenGLFunctions_1_0* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_0_GlVertex4iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlVertex4i(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_0_GlVertex4fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlVertex4f(QOpenGLFunctions_1_0* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_0_GlVertex4dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlVertex4d(QOpenGLFunctions_1_0* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_0_GlVertex3sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlVertex3s(QOpenGLFunctions_1_0* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_0_GlVertex3iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlVertex3i(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_0_GlVertex3fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlVertex3f(QOpenGLFunctions_1_0* self, float x, float y, float z);
void QOpenGLFunctions_1_0_GlVertex3dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlVertex3d(QOpenGLFunctions_1_0* self, double x, double y, double z);
void QOpenGLFunctions_1_0_GlVertex2sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlVertex2s(QOpenGLFunctions_1_0* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_0_GlVertex2iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlVertex2i(QOpenGLFunctions_1_0* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_0_GlVertex2fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlVertex2f(QOpenGLFunctions_1_0* self, float x, float y);
void QOpenGLFunctions_1_0_GlVertex2dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlVertex2d(QOpenGLFunctions_1_0* self, double x, double y);
void QOpenGLFunctions_1_0_GlTexCoord4sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlTexCoord4s(QOpenGLFunctions_1_0* self, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_1_0_GlTexCoord4iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlTexCoord4i(QOpenGLFunctions_1_0* self, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_1_0_GlTexCoord4fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlTexCoord4f(QOpenGLFunctions_1_0* self, float s, float t, float r, float q);
void QOpenGLFunctions_1_0_GlTexCoord4dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlTexCoord4d(QOpenGLFunctions_1_0* self, double s, double t, double r, double q);
void QOpenGLFunctions_1_0_GlTexCoord3sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlTexCoord3s(QOpenGLFunctions_1_0* self, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_1_0_GlTexCoord3iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlTexCoord3i(QOpenGLFunctions_1_0* self, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_1_0_GlTexCoord3fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlTexCoord3f(QOpenGLFunctions_1_0* self, float s, float t, float r);
void QOpenGLFunctions_1_0_GlTexCoord3dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlTexCoord3d(QOpenGLFunctions_1_0* self, double s, double t, double r);
void QOpenGLFunctions_1_0_GlTexCoord2sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlTexCoord2s(QOpenGLFunctions_1_0* self, int16_t s, int16_t t);
void QOpenGLFunctions_1_0_GlTexCoord2iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlTexCoord2i(QOpenGLFunctions_1_0* self, int32_t s, int32_t t);
void QOpenGLFunctions_1_0_GlTexCoord2fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlTexCoord2f(QOpenGLFunctions_1_0* self, float s, float t);
void QOpenGLFunctions_1_0_GlTexCoord2dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlTexCoord2d(QOpenGLFunctions_1_0* self, double s, double t);
void QOpenGLFunctions_1_0_GlTexCoord1sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlTexCoord1s(QOpenGLFunctions_1_0* self, int16_t s);
void QOpenGLFunctions_1_0_GlTexCoord1iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlTexCoord1i(QOpenGLFunctions_1_0* self, int32_t s);
void QOpenGLFunctions_1_0_GlTexCoord1fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlTexCoord1f(QOpenGLFunctions_1_0* self, float s);
void QOpenGLFunctions_1_0_GlTexCoord1dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlTexCoord1d(QOpenGLFunctions_1_0* self, double s);
void QOpenGLFunctions_1_0_GlRectsv(QOpenGLFunctions_1_0* self, const int16_t* v1, const int16_t* v2);
void QOpenGLFunctions_1_0_GlRects(QOpenGLFunctions_1_0* self, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void QOpenGLFunctions_1_0_GlRectiv(QOpenGLFunctions_1_0* self, const int32_t* v1, const int32_t* v2);
void QOpenGLFunctions_1_0_GlRecti(QOpenGLFunctions_1_0* self, int32_t x1, int32_t y1, int32_t x2, int32_t y2);
void QOpenGLFunctions_1_0_GlRectfv(QOpenGLFunctions_1_0* self, const float* v1, const float* v2);
void QOpenGLFunctions_1_0_GlRectf(QOpenGLFunctions_1_0* self, float x1, float y1, float x2, float y2);
void QOpenGLFunctions_1_0_GlRectdv(QOpenGLFunctions_1_0* self, const double* v1, const double* v2);
void QOpenGLFunctions_1_0_GlRectd(QOpenGLFunctions_1_0* self, double x1, double y1, double x2, double y2);
void QOpenGLFunctions_1_0_GlRasterPos4sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlRasterPos4s(QOpenGLFunctions_1_0* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_0_GlRasterPos4iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlRasterPos4i(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_0_GlRasterPos4fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlRasterPos4f(QOpenGLFunctions_1_0* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_0_GlRasterPos4dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlRasterPos4d(QOpenGLFunctions_1_0* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_0_GlRasterPos3sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlRasterPos3s(QOpenGLFunctions_1_0* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_0_GlRasterPos3iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlRasterPos3i(QOpenGLFunctions_1_0* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_0_GlRasterPos3fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlRasterPos3f(QOpenGLFunctions_1_0* self, float x, float y, float z);
void QOpenGLFunctions_1_0_GlRasterPos3dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlRasterPos3d(QOpenGLFunctions_1_0* self, double x, double y, double z);
void QOpenGLFunctions_1_0_GlRasterPos2sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlRasterPos2s(QOpenGLFunctions_1_0* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_0_GlRasterPos2iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlRasterPos2i(QOpenGLFunctions_1_0* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_0_GlRasterPos2fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlRasterPos2f(QOpenGLFunctions_1_0* self, float x, float y);
void QOpenGLFunctions_1_0_GlRasterPos2dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlRasterPos2d(QOpenGLFunctions_1_0* self, double x, double y);
void QOpenGLFunctions_1_0_GlNormal3sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlNormal3s(QOpenGLFunctions_1_0* self, int16_t nx, int16_t ny, int16_t nz);
void QOpenGLFunctions_1_0_GlNormal3iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlNormal3i(QOpenGLFunctions_1_0* self, int32_t nx, int32_t ny, int32_t nz);
void QOpenGLFunctions_1_0_GlNormal3fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlNormal3f(QOpenGLFunctions_1_0* self, float nx, float ny, float nz);
void QOpenGLFunctions_1_0_GlNormal3dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlNormal3d(QOpenGLFunctions_1_0* self, double nx, double ny, double nz);
void QOpenGLFunctions_1_0_GlNormal3bv(QOpenGLFunctions_1_0* self, const signed char* v);
void QOpenGLFunctions_1_0_GlNormal3b(QOpenGLFunctions_1_0* self, signed char nx, signed char ny, signed char nz);
void QOpenGLFunctions_1_0_GlIndexsv(QOpenGLFunctions_1_0* self, const int16_t* c);
void QOpenGLFunctions_1_0_GlIndexs(QOpenGLFunctions_1_0* self, int16_t c);
void QOpenGLFunctions_1_0_GlIndexiv(QOpenGLFunctions_1_0* self, const int32_t* c);
void QOpenGLFunctions_1_0_GlIndexi(QOpenGLFunctions_1_0* self, int32_t c);
void QOpenGLFunctions_1_0_GlIndexfv(QOpenGLFunctions_1_0* self, const float* c);
void QOpenGLFunctions_1_0_GlIndexf(QOpenGLFunctions_1_0* self, float c);
void QOpenGLFunctions_1_0_GlIndexdv(QOpenGLFunctions_1_0* self, const double* c);
void QOpenGLFunctions_1_0_GlIndexd(QOpenGLFunctions_1_0* self, double c);
void QOpenGLFunctions_1_0_GlEnd(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlEdgeFlagv(QOpenGLFunctions_1_0* self, const unsigned char* flag);
void QOpenGLFunctions_1_0_GlEdgeFlag(QOpenGLFunctions_1_0* self, unsigned char flag);
void QOpenGLFunctions_1_0_GlColor4usv(QOpenGLFunctions_1_0* self, const uint16_t* v);
void QOpenGLFunctions_1_0_GlColor4us(QOpenGLFunctions_1_0* self, uint16_t red, uint16_t green, uint16_t blue, uint16_t alpha);
void QOpenGLFunctions_1_0_GlColor4uiv(QOpenGLFunctions_1_0* self, const uint32_t* v);
void QOpenGLFunctions_1_0_GlColor4ui(QOpenGLFunctions_1_0* self, uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha);
void QOpenGLFunctions_1_0_GlColor4ubv(QOpenGLFunctions_1_0* self, const uint8_t* v);
void QOpenGLFunctions_1_0_GlColor4ub(QOpenGLFunctions_1_0* self, uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha);
void QOpenGLFunctions_1_0_GlColor4sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlColor4s(QOpenGLFunctions_1_0* self, int16_t red, int16_t green, int16_t blue, int16_t alpha);
void QOpenGLFunctions_1_0_GlColor4iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlColor4i(QOpenGLFunctions_1_0* self, int32_t red, int32_t green, int32_t blue, int32_t alpha);
void QOpenGLFunctions_1_0_GlColor4fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlColor4f(QOpenGLFunctions_1_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_0_GlColor4dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlColor4d(QOpenGLFunctions_1_0* self, double red, double green, double blue, double alpha);
void QOpenGLFunctions_1_0_GlColor4bv(QOpenGLFunctions_1_0* self, const signed char* v);
void QOpenGLFunctions_1_0_GlColor4b(QOpenGLFunctions_1_0* self, signed char red, signed char green, signed char blue, signed char alpha);
void QOpenGLFunctions_1_0_GlColor3usv(QOpenGLFunctions_1_0* self, const uint16_t* v);
void QOpenGLFunctions_1_0_GlColor3us(QOpenGLFunctions_1_0* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_1_0_GlColor3uiv(QOpenGLFunctions_1_0* self, const uint32_t* v);
void QOpenGLFunctions_1_0_GlColor3ui(QOpenGLFunctions_1_0* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_1_0_GlColor3ubv(QOpenGLFunctions_1_0* self, const uint8_t* v);
void QOpenGLFunctions_1_0_GlColor3ub(QOpenGLFunctions_1_0* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_1_0_GlColor3sv(QOpenGLFunctions_1_0* self, const int16_t* v);
void QOpenGLFunctions_1_0_GlColor3s(QOpenGLFunctions_1_0* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_1_0_GlColor3iv(QOpenGLFunctions_1_0* self, const int32_t* v);
void QOpenGLFunctions_1_0_GlColor3i(QOpenGLFunctions_1_0* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_1_0_GlColor3fv(QOpenGLFunctions_1_0* self, const float* v);
void QOpenGLFunctions_1_0_GlColor3f(QOpenGLFunctions_1_0* self, float red, float green, float blue);
void QOpenGLFunctions_1_0_GlColor3dv(QOpenGLFunctions_1_0* self, const double* v);
void QOpenGLFunctions_1_0_GlColor3d(QOpenGLFunctions_1_0* self, double red, double green, double blue);
void QOpenGLFunctions_1_0_GlColor3bv(QOpenGLFunctions_1_0* self, const signed char* v);
void QOpenGLFunctions_1_0_GlColor3b(QOpenGLFunctions_1_0* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_1_0_GlBitmap(QOpenGLFunctions_1_0* self, int32_t width, int32_t height, float xorig, float yorig, float xmove, float ymove, const uint8_t* bitmap);
void QOpenGLFunctions_1_0_GlBegin(QOpenGLFunctions_1_0* self, uint32_t mode);
void QOpenGLFunctions_1_0_GlListBase(QOpenGLFunctions_1_0* self, uint32_t base);
uint32_t QOpenGLFunctions_1_0_GlGenLists(QOpenGLFunctions_1_0* self, int32_t range);
void QOpenGLFunctions_1_0_GlDeleteLists(QOpenGLFunctions_1_0* self, uint32_t list, int32_t range);
void QOpenGLFunctions_1_0_GlCallLists(QOpenGLFunctions_1_0* self, int32_t n, uint32_t typeVal, const void* lists);
void QOpenGLFunctions_1_0_GlCallList(QOpenGLFunctions_1_0* self, uint32_t list);
void QOpenGLFunctions_1_0_GlEndList(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_GlNewList(QOpenGLFunctions_1_0* self, uint32_t list, uint32_t mode);
void QOpenGLFunctions_1_0_OnInitializeOpenGLFunctions(QOpenGLFunctions_1_0* self, intptr_t slot);
bool QOpenGLFunctions_1_0_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_1_0* self);
void QOpenGLFunctions_1_0_Delete(QOpenGLFunctions_1_0* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
