#pragma once
#ifndef QOPENGLFUNCTIONS_2_1_H_C_LIB
#define QOPENGLFUNCTIONS_2_1_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_2_1 QOpenGLFunctions_2_1;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_2_1* QOpenGLFunctions_2_1_new();
bool QOpenGLFunctions_2_1_InitializeOpenGLFunctions(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlViewport(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_2_1_GlDepthRange(QOpenGLFunctions_2_1* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_2_1_GlIsEnabled(QOpenGLFunctions_2_1* self, uint32_t cap);
void QOpenGLFunctions_2_1_GlGetTexLevelParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetTexLevelParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetTexParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetTexParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetTexImage(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_2_1_GlGetString(QOpenGLFunctions_2_1* self, uint32_t name);
void QOpenGLFunctions_2_1_GlGetIntegerv(QOpenGLFunctions_2_1* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetFloatv(QOpenGLFunctions_2_1* self, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetDoublev(QOpenGLFunctions_2_1* self, uint32_t pname, double* params);
void QOpenGLFunctions_2_1_GlGetBooleanv(QOpenGLFunctions_2_1* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_2_1_GlReadPixels(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_2_1_GlReadBuffer(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlPixelStorei(QOpenGLFunctions_2_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlPixelStoref(QOpenGLFunctions_2_1* self, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlDepthFunc(QOpenGLFunctions_2_1* self, uint32_t func);
void QOpenGLFunctions_2_1_GlStencilOp(QOpenGLFunctions_2_1* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_2_1_GlStencilFunc(QOpenGLFunctions_2_1* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_2_1_GlLogicOp(QOpenGLFunctions_2_1* self, uint32_t opcode);
void QOpenGLFunctions_2_1_GlBlendFunc(QOpenGLFunctions_2_1* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_2_1_GlFlush(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlFinish(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlEnable(QOpenGLFunctions_2_1* self, uint32_t cap);
void QOpenGLFunctions_2_1_GlDisable(QOpenGLFunctions_2_1* self, uint32_t cap);
void QOpenGLFunctions_2_1_GlDepthMask(QOpenGLFunctions_2_1* self, unsigned char flag);
void QOpenGLFunctions_2_1_GlColorMask(QOpenGLFunctions_2_1* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_2_1_GlStencilMask(QOpenGLFunctions_2_1* self, uint32_t mask);
void QOpenGLFunctions_2_1_GlClearDepth(QOpenGLFunctions_2_1* self, double depth);
void QOpenGLFunctions_2_1_GlClearStencil(QOpenGLFunctions_2_1* self, int32_t s);
void QOpenGLFunctions_2_1_GlClearColor(QOpenGLFunctions_2_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_2_1_GlClear(QOpenGLFunctions_2_1* self, uint32_t mask);
void QOpenGLFunctions_2_1_GlDrawBuffer(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlTexImage2D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlTexImage1D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlTexParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlTexParameteri(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlTexParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlTexParameterf(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlScissor(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_2_1_GlPolygonMode(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_2_1_GlPointSize(QOpenGLFunctions_2_1* self, float size);
void QOpenGLFunctions_2_1_GlLineWidth(QOpenGLFunctions_2_1* self, float width);
void QOpenGLFunctions_2_1_GlHint(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_2_1_GlFrontFace(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlCullFace(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlIndexubv(QOpenGLFunctions_2_1* self, const uint8_t* c);
void QOpenGLFunctions_2_1_GlIndexub(QOpenGLFunctions_2_1* self, uint8_t c);
unsigned char QOpenGLFunctions_2_1_GlIsTexture(QOpenGLFunctions_2_1* self, uint32_t texture);
void QOpenGLFunctions_2_1_GlGenTextures(QOpenGLFunctions_2_1* self, int32_t n, uint32_t* textures);
void QOpenGLFunctions_2_1_GlDeleteTextures(QOpenGLFunctions_2_1* self, int32_t n, const uint32_t* textures);
void QOpenGLFunctions_2_1_GlBindTexture(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t texture);
void QOpenGLFunctions_2_1_GlTexSubImage2D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlTexSubImage1D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlCopyTexSubImage2D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_2_1_GlCopyTexSubImage1D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_2_1_GlCopyTexImage2D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border);
void QOpenGLFunctions_2_1_GlCopyTexImage1D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t border);
void QOpenGLFunctions_2_1_GlPolygonOffset(QOpenGLFunctions_2_1* self, float factor, float units);
void QOpenGLFunctions_2_1_GlGetPointerv(QOpenGLFunctions_2_1* self, uint32_t pname, void** params);
void QOpenGLFunctions_2_1_GlDrawElements(QOpenGLFunctions_2_1* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_2_1_GlDrawArrays(QOpenGLFunctions_2_1* self, uint32_t mode, int32_t first, int32_t count);
void QOpenGLFunctions_2_1_GlCopyTexSubImage3D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_2_1_GlTexSubImage3D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlTexImage3D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlDrawRangeElements(QOpenGLFunctions_2_1* self, uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_2_1_GlBlendEquation(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlBlendColor(QOpenGLFunctions_2_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_2_1_GlGetCompressedTexImage(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, void* img);
void QOpenGLFunctions_2_1_GlCompressedTexSubImage1D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_2_1_GlCompressedTexSubImage2D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_2_1_GlCompressedTexSubImage3D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_2_1_GlCompressedTexImage1D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_2_1_GlCompressedTexImage2D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_2_1_GlCompressedTexImage3D(QOpenGLFunctions_2_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_2_1_GlSampleCoverage(QOpenGLFunctions_2_1* self, float value, unsigned char invert);
void QOpenGLFunctions_2_1_GlActiveTexture(QOpenGLFunctions_2_1* self, uint32_t texture);
void QOpenGLFunctions_2_1_GlPointParameteriv(QOpenGLFunctions_2_1* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlPointParameteri(QOpenGLFunctions_2_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlPointParameterfv(QOpenGLFunctions_2_1* self, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlPointParameterf(QOpenGLFunctions_2_1* self, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlMultiDrawElements(QOpenGLFunctions_2_1* self, uint32_t mode, const int32_t* count, uint32_t typeVal, const void** indices, int32_t drawcount);
void QOpenGLFunctions_2_1_GlMultiDrawArrays(QOpenGLFunctions_2_1* self, uint32_t mode, const int32_t* first, const int32_t* count, int32_t drawcount);
void QOpenGLFunctions_2_1_GlBlendFuncSeparate(QOpenGLFunctions_2_1* self, uint32_t sfactorRGB, uint32_t dfactorRGB, uint32_t sfactorAlpha, uint32_t dfactorAlpha);
void QOpenGLFunctions_2_1_GlGetBufferPointerv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, void** params);
void QOpenGLFunctions_2_1_GlGetBufferParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
unsigned char QOpenGLFunctions_2_1_GlUnmapBuffer(QOpenGLFunctions_2_1* self, uint32_t target);
void* QOpenGLFunctions_2_1_GlMapBuffer(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t access);
void QOpenGLFunctions_2_1_GlGetBufferSubData(QOpenGLFunctions_2_1* self, uint32_t target, int64_t offset, int64_t size, void* data);
void QOpenGLFunctions_2_1_GlBufferSubData(QOpenGLFunctions_2_1* self, uint32_t target, int64_t offset, int64_t size, const void* data);
void QOpenGLFunctions_2_1_GlBufferData(QOpenGLFunctions_2_1* self, uint32_t target, int64_t size, const void* data, uint32_t usage);
unsigned char QOpenGLFunctions_2_1_GlIsBuffer(QOpenGLFunctions_2_1* self, uint32_t buffer);
void QOpenGLFunctions_2_1_GlGenBuffers(QOpenGLFunctions_2_1* self, int32_t n, uint32_t* buffers);
void QOpenGLFunctions_2_1_GlDeleteBuffers(QOpenGLFunctions_2_1* self, int32_t n, const uint32_t* buffers);
void QOpenGLFunctions_2_1_GlBindBuffer(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t buffer);
void QOpenGLFunctions_2_1_GlGetQueryObjectuiv(QOpenGLFunctions_2_1* self, uint32_t id, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_2_1_GlGetQueryObjectiv(QOpenGLFunctions_2_1* self, uint32_t id, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetQueryiv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlEndQuery(QOpenGLFunctions_2_1* self, uint32_t target);
void QOpenGLFunctions_2_1_GlBeginQuery(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t id);
unsigned char QOpenGLFunctions_2_1_GlIsQuery(QOpenGLFunctions_2_1* self, uint32_t id);
void QOpenGLFunctions_2_1_GlDeleteQueries(QOpenGLFunctions_2_1* self, int32_t n, const uint32_t* ids);
void QOpenGLFunctions_2_1_GlGenQueries(QOpenGLFunctions_2_1* self, int32_t n, uint32_t* ids);
void QOpenGLFunctions_2_1_GlVertexAttribPointer(QOpenGLFunctions_2_1* self, uint32_t index, int32_t size, uint32_t typeVal, unsigned char normalized, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlValidateProgram(QOpenGLFunctions_2_1* self, uint32_t program);
void QOpenGLFunctions_2_1_GlUniformMatrix4fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix3fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix2fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniform4iv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_2_1_GlUniform3iv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_2_1_GlUniform2iv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_2_1_GlUniform1iv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_2_1_GlUniform4fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_2_1_GlUniform3fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_2_1_GlUniform2fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_2_1_GlUniform1fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_2_1_GlUniform4i(QOpenGLFunctions_2_1* self, int32_t location, int32_t v0, int32_t v1, int32_t v2, int32_t v3);
void QOpenGLFunctions_2_1_GlUniform3i(QOpenGLFunctions_2_1* self, int32_t location, int32_t v0, int32_t v1, int32_t v2);
void QOpenGLFunctions_2_1_GlUniform2i(QOpenGLFunctions_2_1* self, int32_t location, int32_t v0, int32_t v1);
void QOpenGLFunctions_2_1_GlUniform1i(QOpenGLFunctions_2_1* self, int32_t location, int32_t v0);
void QOpenGLFunctions_2_1_GlUniform4f(QOpenGLFunctions_2_1* self, int32_t location, float v0, float v1, float v2, float v3);
void QOpenGLFunctions_2_1_GlUniform3f(QOpenGLFunctions_2_1* self, int32_t location, float v0, float v1, float v2);
void QOpenGLFunctions_2_1_GlUniform2f(QOpenGLFunctions_2_1* self, int32_t location, float v0, float v1);
void QOpenGLFunctions_2_1_GlUniform1f(QOpenGLFunctions_2_1* self, int32_t location, float v0);
void QOpenGLFunctions_2_1_GlUseProgram(QOpenGLFunctions_2_1* self, uint32_t program);
void QOpenGLFunctions_2_1_GlShaderSource(QOpenGLFunctions_2_1* self, uint32_t shader, int32_t count, const GLchar** stringVal, const int32_t* length);
void QOpenGLFunctions_2_1_GlLinkProgram(QOpenGLFunctions_2_1* self, uint32_t program);
unsigned char QOpenGLFunctions_2_1_GlIsShader(QOpenGLFunctions_2_1* self, uint32_t shader);
unsigned char QOpenGLFunctions_2_1_GlIsProgram(QOpenGLFunctions_2_1* self, uint32_t program);
void QOpenGLFunctions_2_1_GlGetVertexAttribPointerv(QOpenGLFunctions_2_1* self, uint32_t index, uint32_t pname, void** pointer);
void QOpenGLFunctions_2_1_GlGetVertexAttribiv(QOpenGLFunctions_2_1* self, uint32_t index, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetVertexAttribfv(QOpenGLFunctions_2_1* self, uint32_t index, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetVertexAttribdv(QOpenGLFunctions_2_1* self, uint32_t index, uint32_t pname, double* params);
void QOpenGLFunctions_2_1_GlGetUniformiv(QOpenGLFunctions_2_1* self, uint32_t program, int32_t location, int32_t* params);
void QOpenGLFunctions_2_1_GlGetUniformfv(QOpenGLFunctions_2_1* self, uint32_t program, int32_t location, float* params);
int32_t QOpenGLFunctions_2_1_GlGetUniformLocation(QOpenGLFunctions_2_1* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_2_1_GlGetShaderSource(QOpenGLFunctions_2_1* self, uint32_t shader, int32_t bufSize, int32_t* length, GLchar* source);
void QOpenGLFunctions_2_1_GlGetShaderInfoLog(QOpenGLFunctions_2_1* self, uint32_t shader, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_2_1_GlGetShaderiv(QOpenGLFunctions_2_1* self, uint32_t shader, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetProgramInfoLog(QOpenGLFunctions_2_1* self, uint32_t program, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_2_1_GlGetProgramiv(QOpenGLFunctions_2_1* self, uint32_t program, uint32_t pname, int32_t* params);
int32_t QOpenGLFunctions_2_1_GlGetAttribLocation(QOpenGLFunctions_2_1* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_2_1_GlGetAttachedShaders(QOpenGLFunctions_2_1* self, uint32_t program, int32_t maxCount, int32_t* count, uint32_t* obj);
void QOpenGLFunctions_2_1_GlEnableVertexAttribArray(QOpenGLFunctions_2_1* self, uint32_t index);
void QOpenGLFunctions_2_1_GlDisableVertexAttribArray(QOpenGLFunctions_2_1* self, uint32_t index);
void QOpenGLFunctions_2_1_GlDetachShader(QOpenGLFunctions_2_1* self, uint32_t program, uint32_t shader);
void QOpenGLFunctions_2_1_GlDeleteShader(QOpenGLFunctions_2_1* self, uint32_t shader);
void QOpenGLFunctions_2_1_GlDeleteProgram(QOpenGLFunctions_2_1* self, uint32_t program);
uint32_t QOpenGLFunctions_2_1_GlCreateShader(QOpenGLFunctions_2_1* self, uint32_t typeVal);
uint32_t QOpenGLFunctions_2_1_GlCreateProgram(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlCompileShader(QOpenGLFunctions_2_1* self, uint32_t shader);
void QOpenGLFunctions_2_1_GlBindAttribLocation(QOpenGLFunctions_2_1* self, uint32_t program, uint32_t index, const GLchar* name);
void QOpenGLFunctions_2_1_GlAttachShader(QOpenGLFunctions_2_1* self, uint32_t program, uint32_t shader);
void QOpenGLFunctions_2_1_GlStencilMaskSeparate(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t mask);
void QOpenGLFunctions_2_1_GlStencilFuncSeparate(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_2_1_GlStencilOpSeparate(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t sfail, uint32_t dpfail, uint32_t dppass);
void QOpenGLFunctions_2_1_GlBlendEquationSeparate(QOpenGLFunctions_2_1* self, uint32_t modeRGB, uint32_t modeAlpha);
void QOpenGLFunctions_2_1_GlUniformMatrix4x3fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix3x4fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix4x2fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix2x4fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix3x2fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlUniformMatrix2x3fv(QOpenGLFunctions_2_1* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_2_1_GlTranslatef(QOpenGLFunctions_2_1* self, float x, float y, float z);
void QOpenGLFunctions_2_1_GlTranslated(QOpenGLFunctions_2_1* self, double x, double y, double z);
void QOpenGLFunctions_2_1_GlScalef(QOpenGLFunctions_2_1* self, float x, float y, float z);
void QOpenGLFunctions_2_1_GlScaled(QOpenGLFunctions_2_1* self, double x, double y, double z);
void QOpenGLFunctions_2_1_GlRotatef(QOpenGLFunctions_2_1* self, float angle, float x, float y, float z);
void QOpenGLFunctions_2_1_GlRotated(QOpenGLFunctions_2_1* self, double angle, double x, double y, double z);
void QOpenGLFunctions_2_1_GlPushMatrix(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlPopMatrix(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlOrtho(QOpenGLFunctions_2_1* self, double left, double right, double bottom, double top, double zNear, double zFar);
void QOpenGLFunctions_2_1_GlMultMatrixd(QOpenGLFunctions_2_1* self, const double* m);
void QOpenGLFunctions_2_1_GlMultMatrixf(QOpenGLFunctions_2_1* self, const float* m);
void QOpenGLFunctions_2_1_GlMatrixMode(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlLoadMatrixd(QOpenGLFunctions_2_1* self, const double* m);
void QOpenGLFunctions_2_1_GlLoadMatrixf(QOpenGLFunctions_2_1* self, const float* m);
void QOpenGLFunctions_2_1_GlLoadIdentity(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlFrustum(QOpenGLFunctions_2_1* self, double left, double right, double bottom, double top, double zNear, double zFar);
unsigned char QOpenGLFunctions_2_1_GlIsList(QOpenGLFunctions_2_1* self, uint32_t list);
void QOpenGLFunctions_2_1_GlGetTexGeniv(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetTexGenfv(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetTexGendv(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, double* params);
void QOpenGLFunctions_2_1_GlGetTexEnviv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetTexEnvfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetPolygonStipple(QOpenGLFunctions_2_1* self, uint8_t* mask);
void QOpenGLFunctions_2_1_GlGetPixelMapusv(QOpenGLFunctions_2_1* self, uint32_t mapVal, uint16_t* values);
void QOpenGLFunctions_2_1_GlGetPixelMapuiv(QOpenGLFunctions_2_1* self, uint32_t mapVal, uint32_t* values);
void QOpenGLFunctions_2_1_GlGetPixelMapfv(QOpenGLFunctions_2_1* self, uint32_t mapVal, float* values);
void QOpenGLFunctions_2_1_GlGetMaterialiv(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetMaterialfv(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetMapiv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t query, int32_t* v);
void QOpenGLFunctions_2_1_GlGetMapfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t query, float* v);
void QOpenGLFunctions_2_1_GlGetMapdv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t query, double* v);
void QOpenGLFunctions_2_1_GlGetLightiv(QOpenGLFunctions_2_1* self, uint32_t light, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetLightfv(QOpenGLFunctions_2_1* self, uint32_t light, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetClipPlane(QOpenGLFunctions_2_1* self, uint32_t plane, double* equation);
void QOpenGLFunctions_2_1_GlDrawPixels(QOpenGLFunctions_2_1* self, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_2_1_GlCopyPixels(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t typeVal);
void QOpenGLFunctions_2_1_GlPixelMapusv(QOpenGLFunctions_2_1* self, uint32_t mapVal, int32_t mapsize, const uint16_t* values);
void QOpenGLFunctions_2_1_GlPixelMapuiv(QOpenGLFunctions_2_1* self, uint32_t mapVal, int32_t mapsize, const uint32_t* values);
void QOpenGLFunctions_2_1_GlPixelMapfv(QOpenGLFunctions_2_1* self, uint32_t mapVal, int32_t mapsize, const float* values);
void QOpenGLFunctions_2_1_GlPixelTransferi(QOpenGLFunctions_2_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlPixelTransferf(QOpenGLFunctions_2_1* self, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlPixelZoom(QOpenGLFunctions_2_1* self, float xfactor, float yfactor);
void QOpenGLFunctions_2_1_GlAlphaFunc(QOpenGLFunctions_2_1* self, uint32_t func, float ref);
void QOpenGLFunctions_2_1_GlEvalPoint2(QOpenGLFunctions_2_1* self, int32_t i, int32_t j);
void QOpenGLFunctions_2_1_GlEvalMesh2(QOpenGLFunctions_2_1* self, uint32_t mode, int32_t i1Val, int32_t i2Val, int32_t j1, int32_t j2);
void QOpenGLFunctions_2_1_GlEvalPoint1(QOpenGLFunctions_2_1* self, int32_t i);
void QOpenGLFunctions_2_1_GlEvalMesh1(QOpenGLFunctions_2_1* self, uint32_t mode, int32_t i1Val, int32_t i2Val);
void QOpenGLFunctions_2_1_GlEvalCoord2fv(QOpenGLFunctions_2_1* self, const float* u);
void QOpenGLFunctions_2_1_GlEvalCoord2f(QOpenGLFunctions_2_1* self, float u, float v);
void QOpenGLFunctions_2_1_GlEvalCoord2dv(QOpenGLFunctions_2_1* self, const double* u);
void QOpenGLFunctions_2_1_GlEvalCoord2d(QOpenGLFunctions_2_1* self, double u, double v);
void QOpenGLFunctions_2_1_GlEvalCoord1fv(QOpenGLFunctions_2_1* self, const float* u);
void QOpenGLFunctions_2_1_GlEvalCoord1f(QOpenGLFunctions_2_1* self, float u);
void QOpenGLFunctions_2_1_GlEvalCoord1dv(QOpenGLFunctions_2_1* self, const double* u);
void QOpenGLFunctions_2_1_GlEvalCoord1d(QOpenGLFunctions_2_1* self, double u);
void QOpenGLFunctions_2_1_GlMapGrid2f(QOpenGLFunctions_2_1* self, int32_t un, float u1Val, float u2Val, int32_t vn, float v1, float v2);
void QOpenGLFunctions_2_1_GlMapGrid2d(QOpenGLFunctions_2_1* self, int32_t un, double u1Val, double u2Val, int32_t vn, double v1, double v2);
void QOpenGLFunctions_2_1_GlMapGrid1f(QOpenGLFunctions_2_1* self, int32_t un, float u1Val, float u2Val);
void QOpenGLFunctions_2_1_GlMapGrid1d(QOpenGLFunctions_2_1* self, int32_t un, double u1Val, double u2Val);
void QOpenGLFunctions_2_1_GlMap2f(QOpenGLFunctions_2_1* self, uint32_t target, float u1Val, float u2Val, int32_t ustride, int32_t uorder, float v1, float v2, int32_t vstride, int32_t vorder, const float* points);
void QOpenGLFunctions_2_1_GlMap2d(QOpenGLFunctions_2_1* self, uint32_t target, double u1Val, double u2Val, int32_t ustride, int32_t uorder, double v1, double v2, int32_t vstride, int32_t vorder, const double* points);
void QOpenGLFunctions_2_1_GlMap1f(QOpenGLFunctions_2_1* self, uint32_t target, float u1Val, float u2Val, int32_t stride, int32_t order, const float* points);
void QOpenGLFunctions_2_1_GlMap1d(QOpenGLFunctions_2_1* self, uint32_t target, double u1Val, double u2Val, int32_t stride, int32_t order, const double* points);
void QOpenGLFunctions_2_1_GlPushAttrib(QOpenGLFunctions_2_1* self, uint32_t mask);
void QOpenGLFunctions_2_1_GlPopAttrib(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlAccum(QOpenGLFunctions_2_1* self, uint32_t op, float value);
void QOpenGLFunctions_2_1_GlIndexMask(QOpenGLFunctions_2_1* self, uint32_t mask);
void QOpenGLFunctions_2_1_GlClearIndex(QOpenGLFunctions_2_1* self, float c);
void QOpenGLFunctions_2_1_GlClearAccum(QOpenGLFunctions_2_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_2_1_GlPushName(QOpenGLFunctions_2_1* self, uint32_t name);
void QOpenGLFunctions_2_1_GlPopName(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlPassThrough(QOpenGLFunctions_2_1* self, float token);
void QOpenGLFunctions_2_1_GlLoadName(QOpenGLFunctions_2_1* self, uint32_t name);
void QOpenGLFunctions_2_1_GlInitNames(QOpenGLFunctions_2_1* self);
int32_t QOpenGLFunctions_2_1_GlRenderMode(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlSelectBuffer(QOpenGLFunctions_2_1* self, int32_t size, uint32_t* buffer);
void QOpenGLFunctions_2_1_GlFeedbackBuffer(QOpenGLFunctions_2_1* self, int32_t size, uint32_t typeVal, float* buffer);
void QOpenGLFunctions_2_1_GlTexGeniv(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlTexGeni(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlTexGenfv(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlTexGenf(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlTexGendv(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, const double* params);
void QOpenGLFunctions_2_1_GlTexGend(QOpenGLFunctions_2_1* self, uint32_t coord, uint32_t pname, double param);
void QOpenGLFunctions_2_1_GlTexEnviv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlTexEnvi(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlTexEnvfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlTexEnvf(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlShadeModel(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlPolygonStipple(QOpenGLFunctions_2_1* self, const uint8_t* mask);
void QOpenGLFunctions_2_1_GlMaterialiv(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlMateriali(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlMaterialfv(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlMaterialf(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlLineStipple(QOpenGLFunctions_2_1* self, int32_t factor, uint16_t pattern);
void QOpenGLFunctions_2_1_GlLightModeliv(QOpenGLFunctions_2_1* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlLightModeli(QOpenGLFunctions_2_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlLightModelfv(QOpenGLFunctions_2_1* self, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlLightModelf(QOpenGLFunctions_2_1* self, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlLightiv(QOpenGLFunctions_2_1* self, uint32_t light, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlLighti(QOpenGLFunctions_2_1* self, uint32_t light, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlLightfv(QOpenGLFunctions_2_1* self, uint32_t light, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlLightf(QOpenGLFunctions_2_1* self, uint32_t light, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlFogiv(QOpenGLFunctions_2_1* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlFogi(QOpenGLFunctions_2_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_2_1_GlFogfv(QOpenGLFunctions_2_1* self, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlFogf(QOpenGLFunctions_2_1* self, uint32_t pname, float param);
void QOpenGLFunctions_2_1_GlColorMaterial(QOpenGLFunctions_2_1* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_2_1_GlClipPlane(QOpenGLFunctions_2_1* self, uint32_t plane, const double* equation);
void QOpenGLFunctions_2_1_GlVertex4sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertex4s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_2_1_GlVertex4iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlVertex4i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_2_1_GlVertex4fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlVertex4f(QOpenGLFunctions_2_1* self, float x, float y, float z, float w);
void QOpenGLFunctions_2_1_GlVertex4dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlVertex4d(QOpenGLFunctions_2_1* self, double x, double y, double z, double w);
void QOpenGLFunctions_2_1_GlVertex3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertex3s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_2_1_GlVertex3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlVertex3i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_2_1_GlVertex3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlVertex3f(QOpenGLFunctions_2_1* self, float x, float y, float z);
void QOpenGLFunctions_2_1_GlVertex3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlVertex3d(QOpenGLFunctions_2_1* self, double x, double y, double z);
void QOpenGLFunctions_2_1_GlVertex2sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertex2s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y);
void QOpenGLFunctions_2_1_GlVertex2iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlVertex2i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y);
void QOpenGLFunctions_2_1_GlVertex2fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlVertex2f(QOpenGLFunctions_2_1* self, float x, float y);
void QOpenGLFunctions_2_1_GlVertex2dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlVertex2d(QOpenGLFunctions_2_1* self, double x, double y);
void QOpenGLFunctions_2_1_GlTexCoord4sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlTexCoord4s(QOpenGLFunctions_2_1* self, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_2_1_GlTexCoord4iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlTexCoord4i(QOpenGLFunctions_2_1* self, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_2_1_GlTexCoord4fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlTexCoord4f(QOpenGLFunctions_2_1* self, float s, float t, float r, float q);
void QOpenGLFunctions_2_1_GlTexCoord4dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlTexCoord4d(QOpenGLFunctions_2_1* self, double s, double t, double r, double q);
void QOpenGLFunctions_2_1_GlTexCoord3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlTexCoord3s(QOpenGLFunctions_2_1* self, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_2_1_GlTexCoord3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlTexCoord3i(QOpenGLFunctions_2_1* self, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_2_1_GlTexCoord3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlTexCoord3f(QOpenGLFunctions_2_1* self, float s, float t, float r);
void QOpenGLFunctions_2_1_GlTexCoord3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlTexCoord3d(QOpenGLFunctions_2_1* self, double s, double t, double r);
void QOpenGLFunctions_2_1_GlTexCoord2sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlTexCoord2s(QOpenGLFunctions_2_1* self, int16_t s, int16_t t);
void QOpenGLFunctions_2_1_GlTexCoord2iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlTexCoord2i(QOpenGLFunctions_2_1* self, int32_t s, int32_t t);
void QOpenGLFunctions_2_1_GlTexCoord2fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlTexCoord2f(QOpenGLFunctions_2_1* self, float s, float t);
void QOpenGLFunctions_2_1_GlTexCoord2dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlTexCoord2d(QOpenGLFunctions_2_1* self, double s, double t);
void QOpenGLFunctions_2_1_GlTexCoord1sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlTexCoord1s(QOpenGLFunctions_2_1* self, int16_t s);
void QOpenGLFunctions_2_1_GlTexCoord1iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlTexCoord1i(QOpenGLFunctions_2_1* self, int32_t s);
void QOpenGLFunctions_2_1_GlTexCoord1fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlTexCoord1f(QOpenGLFunctions_2_1* self, float s);
void QOpenGLFunctions_2_1_GlTexCoord1dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlTexCoord1d(QOpenGLFunctions_2_1* self, double s);
void QOpenGLFunctions_2_1_GlRectsv(QOpenGLFunctions_2_1* self, const int16_t* v1, const int16_t* v2);
void QOpenGLFunctions_2_1_GlRects(QOpenGLFunctions_2_1* self, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void QOpenGLFunctions_2_1_GlRectiv(QOpenGLFunctions_2_1* self, const int32_t* v1, const int32_t* v2);
void QOpenGLFunctions_2_1_GlRecti(QOpenGLFunctions_2_1* self, int32_t x1, int32_t y1, int32_t x2, int32_t y2);
void QOpenGLFunctions_2_1_GlRectfv(QOpenGLFunctions_2_1* self, const float* v1, const float* v2);
void QOpenGLFunctions_2_1_GlRectf(QOpenGLFunctions_2_1* self, float x1, float y1, float x2, float y2);
void QOpenGLFunctions_2_1_GlRectdv(QOpenGLFunctions_2_1* self, const double* v1, const double* v2);
void QOpenGLFunctions_2_1_GlRectd(QOpenGLFunctions_2_1* self, double x1, double y1, double x2, double y2);
void QOpenGLFunctions_2_1_GlRasterPos4sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlRasterPos4s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_2_1_GlRasterPos4iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlRasterPos4i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_2_1_GlRasterPos4fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlRasterPos4f(QOpenGLFunctions_2_1* self, float x, float y, float z, float w);
void QOpenGLFunctions_2_1_GlRasterPos4dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlRasterPos4d(QOpenGLFunctions_2_1* self, double x, double y, double z, double w);
void QOpenGLFunctions_2_1_GlRasterPos3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlRasterPos3s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_2_1_GlRasterPos3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlRasterPos3i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_2_1_GlRasterPos3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlRasterPos3f(QOpenGLFunctions_2_1* self, float x, float y, float z);
void QOpenGLFunctions_2_1_GlRasterPos3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlRasterPos3d(QOpenGLFunctions_2_1* self, double x, double y, double z);
void QOpenGLFunctions_2_1_GlRasterPos2sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlRasterPos2s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y);
void QOpenGLFunctions_2_1_GlRasterPos2iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlRasterPos2i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y);
void QOpenGLFunctions_2_1_GlRasterPos2fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlRasterPos2f(QOpenGLFunctions_2_1* self, float x, float y);
void QOpenGLFunctions_2_1_GlRasterPos2dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlRasterPos2d(QOpenGLFunctions_2_1* self, double x, double y);
void QOpenGLFunctions_2_1_GlNormal3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlNormal3s(QOpenGLFunctions_2_1* self, int16_t nx, int16_t ny, int16_t nz);
void QOpenGLFunctions_2_1_GlNormal3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlNormal3i(QOpenGLFunctions_2_1* self, int32_t nx, int32_t ny, int32_t nz);
void QOpenGLFunctions_2_1_GlNormal3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlNormal3f(QOpenGLFunctions_2_1* self, float nx, float ny, float nz);
void QOpenGLFunctions_2_1_GlNormal3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlNormal3d(QOpenGLFunctions_2_1* self, double nx, double ny, double nz);
void QOpenGLFunctions_2_1_GlNormal3bv(QOpenGLFunctions_2_1* self, const signed char* v);
void QOpenGLFunctions_2_1_GlNormal3b(QOpenGLFunctions_2_1* self, signed char nx, signed char ny, signed char nz);
void QOpenGLFunctions_2_1_GlIndexsv(QOpenGLFunctions_2_1* self, const int16_t* c);
void QOpenGLFunctions_2_1_GlIndexs(QOpenGLFunctions_2_1* self, int16_t c);
void QOpenGLFunctions_2_1_GlIndexiv(QOpenGLFunctions_2_1* self, const int32_t* c);
void QOpenGLFunctions_2_1_GlIndexi(QOpenGLFunctions_2_1* self, int32_t c);
void QOpenGLFunctions_2_1_GlIndexfv(QOpenGLFunctions_2_1* self, const float* c);
void QOpenGLFunctions_2_1_GlIndexf(QOpenGLFunctions_2_1* self, float c);
void QOpenGLFunctions_2_1_GlIndexdv(QOpenGLFunctions_2_1* self, const double* c);
void QOpenGLFunctions_2_1_GlIndexd(QOpenGLFunctions_2_1* self, double c);
void QOpenGLFunctions_2_1_GlEnd(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlEdgeFlagv(QOpenGLFunctions_2_1* self, const unsigned char* flag);
void QOpenGLFunctions_2_1_GlEdgeFlag(QOpenGLFunctions_2_1* self, unsigned char flag);
void QOpenGLFunctions_2_1_GlColor4usv(QOpenGLFunctions_2_1* self, const uint16_t* v);
void QOpenGLFunctions_2_1_GlColor4us(QOpenGLFunctions_2_1* self, uint16_t red, uint16_t green, uint16_t blue, uint16_t alpha);
void QOpenGLFunctions_2_1_GlColor4uiv(QOpenGLFunctions_2_1* self, const uint32_t* v);
void QOpenGLFunctions_2_1_GlColor4ui(QOpenGLFunctions_2_1* self, uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha);
void QOpenGLFunctions_2_1_GlColor4ubv(QOpenGLFunctions_2_1* self, const uint8_t* v);
void QOpenGLFunctions_2_1_GlColor4ub(QOpenGLFunctions_2_1* self, uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha);
void QOpenGLFunctions_2_1_GlColor4sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlColor4s(QOpenGLFunctions_2_1* self, int16_t red, int16_t green, int16_t blue, int16_t alpha);
void QOpenGLFunctions_2_1_GlColor4iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlColor4i(QOpenGLFunctions_2_1* self, int32_t red, int32_t green, int32_t blue, int32_t alpha);
void QOpenGLFunctions_2_1_GlColor4fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlColor4f(QOpenGLFunctions_2_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_2_1_GlColor4dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlColor4d(QOpenGLFunctions_2_1* self, double red, double green, double blue, double alpha);
void QOpenGLFunctions_2_1_GlColor4bv(QOpenGLFunctions_2_1* self, const signed char* v);
void QOpenGLFunctions_2_1_GlColor4b(QOpenGLFunctions_2_1* self, signed char red, signed char green, signed char blue, signed char alpha);
void QOpenGLFunctions_2_1_GlColor3usv(QOpenGLFunctions_2_1* self, const uint16_t* v);
void QOpenGLFunctions_2_1_GlColor3us(QOpenGLFunctions_2_1* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_2_1_GlColor3uiv(QOpenGLFunctions_2_1* self, const uint32_t* v);
void QOpenGLFunctions_2_1_GlColor3ui(QOpenGLFunctions_2_1* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_2_1_GlColor3ubv(QOpenGLFunctions_2_1* self, const uint8_t* v);
void QOpenGLFunctions_2_1_GlColor3ub(QOpenGLFunctions_2_1* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_2_1_GlColor3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlColor3s(QOpenGLFunctions_2_1* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_2_1_GlColor3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlColor3i(QOpenGLFunctions_2_1* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_2_1_GlColor3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlColor3f(QOpenGLFunctions_2_1* self, float red, float green, float blue);
void QOpenGLFunctions_2_1_GlColor3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlColor3d(QOpenGLFunctions_2_1* self, double red, double green, double blue);
void QOpenGLFunctions_2_1_GlColor3bv(QOpenGLFunctions_2_1* self, const signed char* v);
void QOpenGLFunctions_2_1_GlColor3b(QOpenGLFunctions_2_1* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_2_1_GlBitmap(QOpenGLFunctions_2_1* self, int32_t width, int32_t height, float xorig, float yorig, float xmove, float ymove, const uint8_t* bitmap);
void QOpenGLFunctions_2_1_GlBegin(QOpenGLFunctions_2_1* self, uint32_t mode);
void QOpenGLFunctions_2_1_GlListBase(QOpenGLFunctions_2_1* self, uint32_t base);
uint32_t QOpenGLFunctions_2_1_GlGenLists(QOpenGLFunctions_2_1* self, int32_t range);
void QOpenGLFunctions_2_1_GlDeleteLists(QOpenGLFunctions_2_1* self, uint32_t list, int32_t range);
void QOpenGLFunctions_2_1_GlCallLists(QOpenGLFunctions_2_1* self, int32_t n, uint32_t typeVal, const void* lists);
void QOpenGLFunctions_2_1_GlCallList(QOpenGLFunctions_2_1* self, uint32_t list);
void QOpenGLFunctions_2_1_GlEndList(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlNewList(QOpenGLFunctions_2_1* self, uint32_t list, uint32_t mode);
void QOpenGLFunctions_2_1_GlPushClientAttrib(QOpenGLFunctions_2_1* self, uint32_t mask);
void QOpenGLFunctions_2_1_GlPopClientAttrib(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_GlPrioritizeTextures(QOpenGLFunctions_2_1* self, int32_t n, const uint32_t* textures, const float* priorities);
unsigned char QOpenGLFunctions_2_1_GlAreTexturesResident(QOpenGLFunctions_2_1* self, int32_t n, const uint32_t* textures, unsigned char* residences);
void QOpenGLFunctions_2_1_GlVertexPointer(QOpenGLFunctions_2_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlTexCoordPointer(QOpenGLFunctions_2_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlNormalPointer(QOpenGLFunctions_2_1* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlInterleavedArrays(QOpenGLFunctions_2_1* self, uint32_t format, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlIndexPointer(QOpenGLFunctions_2_1* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlEnableClientState(QOpenGLFunctions_2_1* self, uint32_t array);
void QOpenGLFunctions_2_1_GlEdgeFlagPointer(QOpenGLFunctions_2_1* self, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlDisableClientState(QOpenGLFunctions_2_1* self, uint32_t array);
void QOpenGLFunctions_2_1_GlColorPointer(QOpenGLFunctions_2_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlArrayElement(QOpenGLFunctions_2_1* self, int32_t i);
void QOpenGLFunctions_2_1_GlResetMinmax(QOpenGLFunctions_2_1* self, uint32_t target);
void QOpenGLFunctions_2_1_GlResetHistogram(QOpenGLFunctions_2_1* self, uint32_t target);
void QOpenGLFunctions_2_1_GlMinmax(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_2_1_GlHistogram(QOpenGLFunctions_2_1* self, uint32_t target, int32_t width, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_2_1_GlGetMinmaxParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetMinmaxParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetMinmax(QOpenGLFunctions_2_1* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_2_1_GlGetHistogramParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetHistogramParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetHistogram(QOpenGLFunctions_2_1* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_2_1_GlSeparableFilter2D(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* row, const void* column);
void QOpenGLFunctions_2_1_GlGetSeparableFilter(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t format, uint32_t typeVal, void* row, void* column, void* span);
void QOpenGLFunctions_2_1_GlGetConvolutionParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetConvolutionParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetConvolutionFilter(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t format, uint32_t typeVal, void* image);
void QOpenGLFunctions_2_1_GlCopyConvolutionFilter2D(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_2_1_GlCopyConvolutionFilter1D(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_2_1_GlConvolutionParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlConvolutionParameteri(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t params);
void QOpenGLFunctions_2_1_GlConvolutionParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlConvolutionParameterf(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float params);
void QOpenGLFunctions_2_1_GlConvolutionFilter2D(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_2_1_GlConvolutionFilter1D(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_2_1_GlCopyColorSubTable(QOpenGLFunctions_2_1* self, uint32_t target, int32_t start, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_2_1_GlColorSubTable(QOpenGLFunctions_2_1* self, uint32_t target, int32_t start, int32_t count, uint32_t format, uint32_t typeVal, const void* data);
void QOpenGLFunctions_2_1_GlGetColorTableParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_2_1_GlGetColorTableParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_2_1_GlGetColorTable(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t format, uint32_t typeVal, void* table);
void QOpenGLFunctions_2_1_GlCopyColorTable(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_2_1_GlColorTableParameteriv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_2_1_GlColorTableParameterfv(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_2_1_GlColorTable(QOpenGLFunctions_2_1* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* table);
void QOpenGLFunctions_2_1_GlMultTransposeMatrixd(QOpenGLFunctions_2_1* self, const double* m);
void QOpenGLFunctions_2_1_GlMultTransposeMatrixf(QOpenGLFunctions_2_1* self, const float* m);
void QOpenGLFunctions_2_1_GlLoadTransposeMatrixd(QOpenGLFunctions_2_1* self, const double* m);
void QOpenGLFunctions_2_1_GlLoadTransposeMatrixf(QOpenGLFunctions_2_1* self, const float* m);
void QOpenGLFunctions_2_1_GlMultiTexCoord4sv(QOpenGLFunctions_2_1* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord4s(QOpenGLFunctions_2_1* self, uint32_t target, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_2_1_GlMultiTexCoord4iv(QOpenGLFunctions_2_1* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord4i(QOpenGLFunctions_2_1* self, uint32_t target, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_2_1_GlMultiTexCoord4fv(QOpenGLFunctions_2_1* self, uint32_t target, const float* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord4f(QOpenGLFunctions_2_1* self, uint32_t target, float s, float t, float r, float q);
void QOpenGLFunctions_2_1_GlMultiTexCoord4dv(QOpenGLFunctions_2_1* self, uint32_t target, const double* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord4d(QOpenGLFunctions_2_1* self, uint32_t target, double s, double t, double r, double q);
void QOpenGLFunctions_2_1_GlMultiTexCoord3sv(QOpenGLFunctions_2_1* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord3s(QOpenGLFunctions_2_1* self, uint32_t target, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_2_1_GlMultiTexCoord3iv(QOpenGLFunctions_2_1* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord3i(QOpenGLFunctions_2_1* self, uint32_t target, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_2_1_GlMultiTexCoord3fv(QOpenGLFunctions_2_1* self, uint32_t target, const float* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord3f(QOpenGLFunctions_2_1* self, uint32_t target, float s, float t, float r);
void QOpenGLFunctions_2_1_GlMultiTexCoord3dv(QOpenGLFunctions_2_1* self, uint32_t target, const double* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord3d(QOpenGLFunctions_2_1* self, uint32_t target, double s, double t, double r);
void QOpenGLFunctions_2_1_GlMultiTexCoord2sv(QOpenGLFunctions_2_1* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord2s(QOpenGLFunctions_2_1* self, uint32_t target, int16_t s, int16_t t);
void QOpenGLFunctions_2_1_GlMultiTexCoord2iv(QOpenGLFunctions_2_1* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord2i(QOpenGLFunctions_2_1* self, uint32_t target, int32_t s, int32_t t);
void QOpenGLFunctions_2_1_GlMultiTexCoord2fv(QOpenGLFunctions_2_1* self, uint32_t target, const float* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord2f(QOpenGLFunctions_2_1* self, uint32_t target, float s, float t);
void QOpenGLFunctions_2_1_GlMultiTexCoord2dv(QOpenGLFunctions_2_1* self, uint32_t target, const double* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord2d(QOpenGLFunctions_2_1* self, uint32_t target, double s, double t);
void QOpenGLFunctions_2_1_GlMultiTexCoord1sv(QOpenGLFunctions_2_1* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord1s(QOpenGLFunctions_2_1* self, uint32_t target, int16_t s);
void QOpenGLFunctions_2_1_GlMultiTexCoord1iv(QOpenGLFunctions_2_1* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord1i(QOpenGLFunctions_2_1* self, uint32_t target, int32_t s);
void QOpenGLFunctions_2_1_GlMultiTexCoord1fv(QOpenGLFunctions_2_1* self, uint32_t target, const float* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord1f(QOpenGLFunctions_2_1* self, uint32_t target, float s);
void QOpenGLFunctions_2_1_GlMultiTexCoord1dv(QOpenGLFunctions_2_1* self, uint32_t target, const double* v);
void QOpenGLFunctions_2_1_GlMultiTexCoord1d(QOpenGLFunctions_2_1* self, uint32_t target, double s);
void QOpenGLFunctions_2_1_GlClientActiveTexture(QOpenGLFunctions_2_1* self, uint32_t texture);
void QOpenGLFunctions_2_1_GlWindowPos3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlWindowPos3s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_2_1_GlWindowPos3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlWindowPos3i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_2_1_GlWindowPos3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlWindowPos3f(QOpenGLFunctions_2_1* self, float x, float y, float z);
void QOpenGLFunctions_2_1_GlWindowPos3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlWindowPos3d(QOpenGLFunctions_2_1* self, double x, double y, double z);
void QOpenGLFunctions_2_1_GlWindowPos2sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlWindowPos2s(QOpenGLFunctions_2_1* self, int16_t x, int16_t y);
void QOpenGLFunctions_2_1_GlWindowPos2iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlWindowPos2i(QOpenGLFunctions_2_1* self, int32_t x, int32_t y);
void QOpenGLFunctions_2_1_GlWindowPos2fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlWindowPos2f(QOpenGLFunctions_2_1* self, float x, float y);
void QOpenGLFunctions_2_1_GlWindowPos2dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlWindowPos2d(QOpenGLFunctions_2_1* self, double x, double y);
void QOpenGLFunctions_2_1_GlSecondaryColorPointer(QOpenGLFunctions_2_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlSecondaryColor3usv(QOpenGLFunctions_2_1* self, const uint16_t* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3us(QOpenGLFunctions_2_1* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3uiv(QOpenGLFunctions_2_1* self, const uint32_t* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3ui(QOpenGLFunctions_2_1* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3ubv(QOpenGLFunctions_2_1* self, const uint8_t* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3ub(QOpenGLFunctions_2_1* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3sv(QOpenGLFunctions_2_1* self, const int16_t* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3s(QOpenGLFunctions_2_1* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3iv(QOpenGLFunctions_2_1* self, const int32_t* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3i(QOpenGLFunctions_2_1* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3fv(QOpenGLFunctions_2_1* self, const float* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3f(QOpenGLFunctions_2_1* self, float red, float green, float blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3dv(QOpenGLFunctions_2_1* self, const double* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3d(QOpenGLFunctions_2_1* self, double red, double green, double blue);
void QOpenGLFunctions_2_1_GlSecondaryColor3bv(QOpenGLFunctions_2_1* self, const signed char* v);
void QOpenGLFunctions_2_1_GlSecondaryColor3b(QOpenGLFunctions_2_1* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_2_1_GlFogCoordPointer(QOpenGLFunctions_2_1* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_2_1_GlFogCoorddv(QOpenGLFunctions_2_1* self, const double* coord);
void QOpenGLFunctions_2_1_GlFogCoordd(QOpenGLFunctions_2_1* self, double coord);
void QOpenGLFunctions_2_1_GlFogCoordfv(QOpenGLFunctions_2_1* self, const float* coord);
void QOpenGLFunctions_2_1_GlFogCoordf(QOpenGLFunctions_2_1* self, float coord);
void QOpenGLFunctions_2_1_GlVertexAttrib4usv(QOpenGLFunctions_2_1* self, uint32_t index, const uint16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4uiv(QOpenGLFunctions_2_1* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4ubv(QOpenGLFunctions_2_1* self, uint32_t index, const uint8_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4sv(QOpenGLFunctions_2_1* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4s(QOpenGLFunctions_2_1* self, uint32_t index, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_2_1_GlVertexAttrib4iv(QOpenGLFunctions_2_1* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4fv(QOpenGLFunctions_2_1* self, uint32_t index, const float* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4f(QOpenGLFunctions_2_1* self, uint32_t index, float x, float y, float z, float w);
void QOpenGLFunctions_2_1_GlVertexAttrib4dv(QOpenGLFunctions_2_1* self, uint32_t index, const double* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4d(QOpenGLFunctions_2_1* self, uint32_t index, double x, double y, double z, double w);
void QOpenGLFunctions_2_1_GlVertexAttrib4bv(QOpenGLFunctions_2_1* self, uint32_t index, const signed char* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4Nusv(QOpenGLFunctions_2_1* self, uint32_t index, const uint16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4Nuiv(QOpenGLFunctions_2_1* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4Nubv(QOpenGLFunctions_2_1* self, uint32_t index, const uint8_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4Nub(QOpenGLFunctions_2_1* self, uint32_t index, uint8_t x, uint8_t y, uint8_t z, uint8_t w);
void QOpenGLFunctions_2_1_GlVertexAttrib4Nsv(QOpenGLFunctions_2_1* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4Niv(QOpenGLFunctions_2_1* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib4Nbv(QOpenGLFunctions_2_1* self, uint32_t index, const signed char* v);
void QOpenGLFunctions_2_1_GlVertexAttrib3sv(QOpenGLFunctions_2_1* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib3s(QOpenGLFunctions_2_1* self, uint32_t index, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_2_1_GlVertexAttrib3fv(QOpenGLFunctions_2_1* self, uint32_t index, const float* v);
void QOpenGLFunctions_2_1_GlVertexAttrib3f(QOpenGLFunctions_2_1* self, uint32_t index, float x, float y, float z);
void QOpenGLFunctions_2_1_GlVertexAttrib3dv(QOpenGLFunctions_2_1* self, uint32_t index, const double* v);
void QOpenGLFunctions_2_1_GlVertexAttrib3d(QOpenGLFunctions_2_1* self, uint32_t index, double x, double y, double z);
void QOpenGLFunctions_2_1_GlVertexAttrib2sv(QOpenGLFunctions_2_1* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib2s(QOpenGLFunctions_2_1* self, uint32_t index, int16_t x, int16_t y);
void QOpenGLFunctions_2_1_GlVertexAttrib2fv(QOpenGLFunctions_2_1* self, uint32_t index, const float* v);
void QOpenGLFunctions_2_1_GlVertexAttrib2f(QOpenGLFunctions_2_1* self, uint32_t index, float x, float y);
void QOpenGLFunctions_2_1_GlVertexAttrib2dv(QOpenGLFunctions_2_1* self, uint32_t index, const double* v);
void QOpenGLFunctions_2_1_GlVertexAttrib2d(QOpenGLFunctions_2_1* self, uint32_t index, double x, double y);
void QOpenGLFunctions_2_1_GlVertexAttrib1sv(QOpenGLFunctions_2_1* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_2_1_GlVertexAttrib1s(QOpenGLFunctions_2_1* self, uint32_t index, int16_t x);
void QOpenGLFunctions_2_1_GlVertexAttrib1fv(QOpenGLFunctions_2_1* self, uint32_t index, const float* v);
void QOpenGLFunctions_2_1_GlVertexAttrib1f(QOpenGLFunctions_2_1* self, uint32_t index, float x);
void QOpenGLFunctions_2_1_GlVertexAttrib1dv(QOpenGLFunctions_2_1* self, uint32_t index, const double* v);
void QOpenGLFunctions_2_1_GlVertexAttrib1d(QOpenGLFunctions_2_1* self, uint32_t index, double x);
void QOpenGLFunctions_2_1_OnInitializeOpenGLFunctions(QOpenGLFunctions_2_1* self, intptr_t slot);
bool QOpenGLFunctions_2_1_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_2_1* self);
void QOpenGLFunctions_2_1_Delete(QOpenGLFunctions_2_1* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
