#pragma once
#ifndef QOPENGLFUNCTIONS_1_1_H_C_LIB
#define QOPENGLFUNCTIONS_1_1_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_1_1 QOpenGLFunctions_1_1;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_1_1* QOpenGLFunctions_1_1_new();
bool QOpenGLFunctions_1_1_InitializeOpenGLFunctions(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlViewport(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_1_GlDepthRange(QOpenGLFunctions_1_1* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_1_1_GlIsEnabled(QOpenGLFunctions_1_1* self, uint32_t cap);
void QOpenGLFunctions_1_1_GlGetTexLevelParameteriv(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetTexLevelParameterfv(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_1_1_GlGetTexParameteriv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetTexParameterfv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_1_GlGetTexImage(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_1_1_GlGetString(QOpenGLFunctions_1_1* self, uint32_t name);
void QOpenGLFunctions_1_1_GlGetIntegerv(QOpenGLFunctions_1_1* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetFloatv(QOpenGLFunctions_1_1* self, uint32_t pname, float* params);
GL QOpenGLFunctions_1_1_GlGetError(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlGetDoublev(QOpenGLFunctions_1_1* self, uint32_t pname, double* params);
void QOpenGLFunctions_1_1_GlGetBooleanv(QOpenGLFunctions_1_1* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_1_1_GlReadPixels(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_1_1_GlReadBuffer(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlPixelStorei(QOpenGLFunctions_1_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlPixelStoref(QOpenGLFunctions_1_1* self, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlDepthFunc(QOpenGLFunctions_1_1* self, uint32_t func);
void QOpenGLFunctions_1_1_GlStencilOp(QOpenGLFunctions_1_1* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_1_1_GlStencilFunc(QOpenGLFunctions_1_1* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_1_1_GlLogicOp(QOpenGLFunctions_1_1* self, uint32_t opcode);
void QOpenGLFunctions_1_1_GlBlendFunc(QOpenGLFunctions_1_1* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_1_1_GlFlush(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlFinish(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlEnable(QOpenGLFunctions_1_1* self, uint32_t cap);
void QOpenGLFunctions_1_1_GlDisable(QOpenGLFunctions_1_1* self, uint32_t cap);
void QOpenGLFunctions_1_1_GlDepthMask(QOpenGLFunctions_1_1* self, unsigned char flag);
void QOpenGLFunctions_1_1_GlColorMask(QOpenGLFunctions_1_1* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_1_1_GlStencilMask(QOpenGLFunctions_1_1* self, uint32_t mask);
void QOpenGLFunctions_1_1_GlClearDepth(QOpenGLFunctions_1_1* self, double depth);
void QOpenGLFunctions_1_1_GlClearStencil(QOpenGLFunctions_1_1* self, int32_t s);
void QOpenGLFunctions_1_1_GlClearColor(QOpenGLFunctions_1_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_1_GlClear(QOpenGLFunctions_1_1* self, uint32_t mask);
void QOpenGLFunctions_1_1_GlDrawBuffer(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlTexImage2D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_1_GlTexImage1D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_1_GlTexParameteriv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlTexParameteri(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlTexParameterfv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlTexParameterf(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlScissor(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_1_GlPolygonMode(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_1_GlPointSize(QOpenGLFunctions_1_1* self, float size);
void QOpenGLFunctions_1_1_GlLineWidth(QOpenGLFunctions_1_1* self, float width);
void QOpenGLFunctions_1_1_GlHint(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_1_1_GlFrontFace(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlCullFace(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlIndexubv(QOpenGLFunctions_1_1* self, const uint8_t* c);
void QOpenGLFunctions_1_1_GlIndexub(QOpenGLFunctions_1_1* self, uint8_t c);
unsigned char QOpenGLFunctions_1_1_GlIsTexture(QOpenGLFunctions_1_1* self, uint32_t texture);
void QOpenGLFunctions_1_1_GlGenTextures(QOpenGLFunctions_1_1* self, int32_t n, uint32_t* textures);
void QOpenGLFunctions_1_1_GlDeleteTextures(QOpenGLFunctions_1_1* self, int32_t n, const uint32_t* textures);
void QOpenGLFunctions_1_1_GlBindTexture(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t texture);
void QOpenGLFunctions_1_1_GlTexSubImage2D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_1_GlTexSubImage1D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_1_GlCopyTexSubImage2D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_1_1_GlCopyTexSubImage1D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, int32_t xoffset, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_1_1_GlCopyTexImage2D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border);
void QOpenGLFunctions_1_1_GlCopyTexImage1D(QOpenGLFunctions_1_1* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t border);
void QOpenGLFunctions_1_1_GlPolygonOffset(QOpenGLFunctions_1_1* self, float factor, float units);
void QOpenGLFunctions_1_1_GlGetPointerv(QOpenGLFunctions_1_1* self, uint32_t pname, void** params);
void QOpenGLFunctions_1_1_GlDrawElements(QOpenGLFunctions_1_1* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_1_1_GlDrawArrays(QOpenGLFunctions_1_1* self, uint32_t mode, int32_t first, int32_t count);
void QOpenGLFunctions_1_1_GlTranslatef(QOpenGLFunctions_1_1* self, float x, float y, float z);
void QOpenGLFunctions_1_1_GlTranslated(QOpenGLFunctions_1_1* self, double x, double y, double z);
void QOpenGLFunctions_1_1_GlScalef(QOpenGLFunctions_1_1* self, float x, float y, float z);
void QOpenGLFunctions_1_1_GlScaled(QOpenGLFunctions_1_1* self, double x, double y, double z);
void QOpenGLFunctions_1_1_GlRotatef(QOpenGLFunctions_1_1* self, float angle, float x, float y, float z);
void QOpenGLFunctions_1_1_GlRotated(QOpenGLFunctions_1_1* self, double angle, double x, double y, double z);
void QOpenGLFunctions_1_1_GlPushMatrix(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlPopMatrix(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlOrtho(QOpenGLFunctions_1_1* self, double left, double right, double bottom, double top, double zNear, double zFar);
void QOpenGLFunctions_1_1_GlMultMatrixd(QOpenGLFunctions_1_1* self, const double* m);
void QOpenGLFunctions_1_1_GlMultMatrixf(QOpenGLFunctions_1_1* self, const float* m);
void QOpenGLFunctions_1_1_GlMatrixMode(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlLoadMatrixd(QOpenGLFunctions_1_1* self, const double* m);
void QOpenGLFunctions_1_1_GlLoadMatrixf(QOpenGLFunctions_1_1* self, const float* m);
void QOpenGLFunctions_1_1_GlLoadIdentity(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlFrustum(QOpenGLFunctions_1_1* self, double left, double right, double bottom, double top, double zNear, double zFar);
unsigned char QOpenGLFunctions_1_1_GlIsList(QOpenGLFunctions_1_1* self, uint32_t list);
void QOpenGLFunctions_1_1_GlGetTexGeniv(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetTexGenfv(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, float* params);
void QOpenGLFunctions_1_1_GlGetTexGendv(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, double* params);
void QOpenGLFunctions_1_1_GlGetTexEnviv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetTexEnvfv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_1_1_GlGetPolygonStipple(QOpenGLFunctions_1_1* self, uint8_t* mask);
void QOpenGLFunctions_1_1_GlGetPixelMapusv(QOpenGLFunctions_1_1* self, uint32_t mapVal, uint16_t* values);
void QOpenGLFunctions_1_1_GlGetPixelMapuiv(QOpenGLFunctions_1_1* self, uint32_t mapVal, uint32_t* values);
void QOpenGLFunctions_1_1_GlGetPixelMapfv(QOpenGLFunctions_1_1* self, uint32_t mapVal, float* values);
void QOpenGLFunctions_1_1_GlGetMaterialiv(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetMaterialfv(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t pname, float* params);
void QOpenGLFunctions_1_1_GlGetMapiv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t query, int32_t* v);
void QOpenGLFunctions_1_1_GlGetMapfv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t query, float* v);
void QOpenGLFunctions_1_1_GlGetMapdv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t query, double* v);
void QOpenGLFunctions_1_1_GlGetLightiv(QOpenGLFunctions_1_1* self, uint32_t light, uint32_t pname, int32_t* params);
void QOpenGLFunctions_1_1_GlGetLightfv(QOpenGLFunctions_1_1* self, uint32_t light, uint32_t pname, float* params);
void QOpenGLFunctions_1_1_GlGetClipPlane(QOpenGLFunctions_1_1* self, uint32_t plane, double* equation);
void QOpenGLFunctions_1_1_GlDrawPixels(QOpenGLFunctions_1_1* self, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_1_1_GlCopyPixels(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t typeVal);
void QOpenGLFunctions_1_1_GlPixelMapusv(QOpenGLFunctions_1_1* self, uint32_t mapVal, int32_t mapsize, const uint16_t* values);
void QOpenGLFunctions_1_1_GlPixelMapuiv(QOpenGLFunctions_1_1* self, uint32_t mapVal, int32_t mapsize, const uint32_t* values);
void QOpenGLFunctions_1_1_GlPixelMapfv(QOpenGLFunctions_1_1* self, uint32_t mapVal, int32_t mapsize, const float* values);
void QOpenGLFunctions_1_1_GlPixelTransferi(QOpenGLFunctions_1_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlPixelTransferf(QOpenGLFunctions_1_1* self, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlPixelZoom(QOpenGLFunctions_1_1* self, float xfactor, float yfactor);
void QOpenGLFunctions_1_1_GlAlphaFunc(QOpenGLFunctions_1_1* self, uint32_t func, float ref);
void QOpenGLFunctions_1_1_GlEvalPoint2(QOpenGLFunctions_1_1* self, int32_t i, int32_t j);
void QOpenGLFunctions_1_1_GlEvalMesh2(QOpenGLFunctions_1_1* self, uint32_t mode, int32_t i1Val, int32_t i2Val, int32_t j1, int32_t j2);
void QOpenGLFunctions_1_1_GlEvalPoint1(QOpenGLFunctions_1_1* self, int32_t i);
void QOpenGLFunctions_1_1_GlEvalMesh1(QOpenGLFunctions_1_1* self, uint32_t mode, int32_t i1Val, int32_t i2Val);
void QOpenGLFunctions_1_1_GlEvalCoord2fv(QOpenGLFunctions_1_1* self, const float* u);
void QOpenGLFunctions_1_1_GlEvalCoord2f(QOpenGLFunctions_1_1* self, float u, float v);
void QOpenGLFunctions_1_1_GlEvalCoord2dv(QOpenGLFunctions_1_1* self, const double* u);
void QOpenGLFunctions_1_1_GlEvalCoord2d(QOpenGLFunctions_1_1* self, double u, double v);
void QOpenGLFunctions_1_1_GlEvalCoord1fv(QOpenGLFunctions_1_1* self, const float* u);
void QOpenGLFunctions_1_1_GlEvalCoord1f(QOpenGLFunctions_1_1* self, float u);
void QOpenGLFunctions_1_1_GlEvalCoord1dv(QOpenGLFunctions_1_1* self, const double* u);
void QOpenGLFunctions_1_1_GlEvalCoord1d(QOpenGLFunctions_1_1* self, double u);
void QOpenGLFunctions_1_1_GlMapGrid2f(QOpenGLFunctions_1_1* self, int32_t un, float u1Val, float u2Val, int32_t vn, float v1, float v2);
void QOpenGLFunctions_1_1_GlMapGrid2d(QOpenGLFunctions_1_1* self, int32_t un, double u1Val, double u2Val, int32_t vn, double v1, double v2);
void QOpenGLFunctions_1_1_GlMapGrid1f(QOpenGLFunctions_1_1* self, int32_t un, float u1Val, float u2Val);
void QOpenGLFunctions_1_1_GlMapGrid1d(QOpenGLFunctions_1_1* self, int32_t un, double u1Val, double u2Val);
void QOpenGLFunctions_1_1_GlMap2f(QOpenGLFunctions_1_1* self, uint32_t target, float u1Val, float u2Val, int32_t ustride, int32_t uorder, float v1, float v2, int32_t vstride, int32_t vorder, const float* points);
void QOpenGLFunctions_1_1_GlMap2d(QOpenGLFunctions_1_1* self, uint32_t target, double u1Val, double u2Val, int32_t ustride, int32_t uorder, double v1, double v2, int32_t vstride, int32_t vorder, const double* points);
void QOpenGLFunctions_1_1_GlMap1f(QOpenGLFunctions_1_1* self, uint32_t target, float u1Val, float u2Val, int32_t stride, int32_t order, const float* points);
void QOpenGLFunctions_1_1_GlMap1d(QOpenGLFunctions_1_1* self, uint32_t target, double u1Val, double u2Val, int32_t stride, int32_t order, const double* points);
void QOpenGLFunctions_1_1_GlPushAttrib(QOpenGLFunctions_1_1* self, uint32_t mask);
void QOpenGLFunctions_1_1_GlPopAttrib(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlAccum(QOpenGLFunctions_1_1* self, uint32_t op, float value);
void QOpenGLFunctions_1_1_GlIndexMask(QOpenGLFunctions_1_1* self, uint32_t mask);
void QOpenGLFunctions_1_1_GlClearIndex(QOpenGLFunctions_1_1* self, float c);
void QOpenGLFunctions_1_1_GlClearAccum(QOpenGLFunctions_1_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_1_GlPushName(QOpenGLFunctions_1_1* self, uint32_t name);
void QOpenGLFunctions_1_1_GlPopName(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlPassThrough(QOpenGLFunctions_1_1* self, float token);
void QOpenGLFunctions_1_1_GlLoadName(QOpenGLFunctions_1_1* self, uint32_t name);
void QOpenGLFunctions_1_1_GlInitNames(QOpenGLFunctions_1_1* self);
int32_t QOpenGLFunctions_1_1_GlRenderMode(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlSelectBuffer(QOpenGLFunctions_1_1* self, int32_t size, uint32_t* buffer);
void QOpenGLFunctions_1_1_GlFeedbackBuffer(QOpenGLFunctions_1_1* self, int32_t size, uint32_t typeVal, float* buffer);
void QOpenGLFunctions_1_1_GlTexGeniv(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlTexGeni(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlTexGenfv(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlTexGenf(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlTexGendv(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, const double* params);
void QOpenGLFunctions_1_1_GlTexGend(QOpenGLFunctions_1_1* self, uint32_t coord, uint32_t pname, double param);
void QOpenGLFunctions_1_1_GlTexEnviv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlTexEnvi(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlTexEnvfv(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlTexEnvf(QOpenGLFunctions_1_1* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlShadeModel(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlPolygonStipple(QOpenGLFunctions_1_1* self, const uint8_t* mask);
void QOpenGLFunctions_1_1_GlMaterialiv(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlMateriali(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlMaterialfv(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlMaterialf(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlLineStipple(QOpenGLFunctions_1_1* self, int32_t factor, uint16_t pattern);
void QOpenGLFunctions_1_1_GlLightModeliv(QOpenGLFunctions_1_1* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlLightModeli(QOpenGLFunctions_1_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlLightModelfv(QOpenGLFunctions_1_1* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlLightModelf(QOpenGLFunctions_1_1* self, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlLightiv(QOpenGLFunctions_1_1* self, uint32_t light, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlLighti(QOpenGLFunctions_1_1* self, uint32_t light, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlLightfv(QOpenGLFunctions_1_1* self, uint32_t light, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlLightf(QOpenGLFunctions_1_1* self, uint32_t light, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlFogiv(QOpenGLFunctions_1_1* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_1_1_GlFogi(QOpenGLFunctions_1_1* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_1_1_GlFogfv(QOpenGLFunctions_1_1* self, uint32_t pname, const float* params);
void QOpenGLFunctions_1_1_GlFogf(QOpenGLFunctions_1_1* self, uint32_t pname, float param);
void QOpenGLFunctions_1_1_GlColorMaterial(QOpenGLFunctions_1_1* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_1_1_GlClipPlane(QOpenGLFunctions_1_1* self, uint32_t plane, const double* equation);
void QOpenGLFunctions_1_1_GlVertex4sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlVertex4s(QOpenGLFunctions_1_1* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_1_GlVertex4iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlVertex4i(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_1_GlVertex4fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlVertex4f(QOpenGLFunctions_1_1* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_1_GlVertex4dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlVertex4d(QOpenGLFunctions_1_1* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_1_GlVertex3sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlVertex3s(QOpenGLFunctions_1_1* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_1_GlVertex3iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlVertex3i(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_1_GlVertex3fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlVertex3f(QOpenGLFunctions_1_1* self, float x, float y, float z);
void QOpenGLFunctions_1_1_GlVertex3dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlVertex3d(QOpenGLFunctions_1_1* self, double x, double y, double z);
void QOpenGLFunctions_1_1_GlVertex2sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlVertex2s(QOpenGLFunctions_1_1* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_1_GlVertex2iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlVertex2i(QOpenGLFunctions_1_1* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_1_GlVertex2fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlVertex2f(QOpenGLFunctions_1_1* self, float x, float y);
void QOpenGLFunctions_1_1_GlVertex2dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlVertex2d(QOpenGLFunctions_1_1* self, double x, double y);
void QOpenGLFunctions_1_1_GlTexCoord4sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlTexCoord4s(QOpenGLFunctions_1_1* self, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_1_1_GlTexCoord4iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlTexCoord4i(QOpenGLFunctions_1_1* self, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_1_1_GlTexCoord4fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlTexCoord4f(QOpenGLFunctions_1_1* self, float s, float t, float r, float q);
void QOpenGLFunctions_1_1_GlTexCoord4dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlTexCoord4d(QOpenGLFunctions_1_1* self, double s, double t, double r, double q);
void QOpenGLFunctions_1_1_GlTexCoord3sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlTexCoord3s(QOpenGLFunctions_1_1* self, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_1_1_GlTexCoord3iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlTexCoord3i(QOpenGLFunctions_1_1* self, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_1_1_GlTexCoord3fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlTexCoord3f(QOpenGLFunctions_1_1* self, float s, float t, float r);
void QOpenGLFunctions_1_1_GlTexCoord3dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlTexCoord3d(QOpenGLFunctions_1_1* self, double s, double t, double r);
void QOpenGLFunctions_1_1_GlTexCoord2sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlTexCoord2s(QOpenGLFunctions_1_1* self, int16_t s, int16_t t);
void QOpenGLFunctions_1_1_GlTexCoord2iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlTexCoord2i(QOpenGLFunctions_1_1* self, int32_t s, int32_t t);
void QOpenGLFunctions_1_1_GlTexCoord2fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlTexCoord2f(QOpenGLFunctions_1_1* self, float s, float t);
void QOpenGLFunctions_1_1_GlTexCoord2dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlTexCoord2d(QOpenGLFunctions_1_1* self, double s, double t);
void QOpenGLFunctions_1_1_GlTexCoord1sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlTexCoord1s(QOpenGLFunctions_1_1* self, int16_t s);
void QOpenGLFunctions_1_1_GlTexCoord1iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlTexCoord1i(QOpenGLFunctions_1_1* self, int32_t s);
void QOpenGLFunctions_1_1_GlTexCoord1fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlTexCoord1f(QOpenGLFunctions_1_1* self, float s);
void QOpenGLFunctions_1_1_GlTexCoord1dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlTexCoord1d(QOpenGLFunctions_1_1* self, double s);
void QOpenGLFunctions_1_1_GlRectsv(QOpenGLFunctions_1_1* self, const int16_t* v1, const int16_t* v2);
void QOpenGLFunctions_1_1_GlRects(QOpenGLFunctions_1_1* self, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void QOpenGLFunctions_1_1_GlRectiv(QOpenGLFunctions_1_1* self, const int32_t* v1, const int32_t* v2);
void QOpenGLFunctions_1_1_GlRecti(QOpenGLFunctions_1_1* self, int32_t x1, int32_t y1, int32_t x2, int32_t y2);
void QOpenGLFunctions_1_1_GlRectfv(QOpenGLFunctions_1_1* self, const float* v1, const float* v2);
void QOpenGLFunctions_1_1_GlRectf(QOpenGLFunctions_1_1* self, float x1, float y1, float x2, float y2);
void QOpenGLFunctions_1_1_GlRectdv(QOpenGLFunctions_1_1* self, const double* v1, const double* v2);
void QOpenGLFunctions_1_1_GlRectd(QOpenGLFunctions_1_1* self, double x1, double y1, double x2, double y2);
void QOpenGLFunctions_1_1_GlRasterPos4sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlRasterPos4s(QOpenGLFunctions_1_1* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_1_1_GlRasterPos4iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlRasterPos4i(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_1_1_GlRasterPos4fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlRasterPos4f(QOpenGLFunctions_1_1* self, float x, float y, float z, float w);
void QOpenGLFunctions_1_1_GlRasterPos4dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlRasterPos4d(QOpenGLFunctions_1_1* self, double x, double y, double z, double w);
void QOpenGLFunctions_1_1_GlRasterPos3sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlRasterPos3s(QOpenGLFunctions_1_1* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_1_1_GlRasterPos3iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlRasterPos3i(QOpenGLFunctions_1_1* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_1_1_GlRasterPos3fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlRasterPos3f(QOpenGLFunctions_1_1* self, float x, float y, float z);
void QOpenGLFunctions_1_1_GlRasterPos3dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlRasterPos3d(QOpenGLFunctions_1_1* self, double x, double y, double z);
void QOpenGLFunctions_1_1_GlRasterPos2sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlRasterPos2s(QOpenGLFunctions_1_1* self, int16_t x, int16_t y);
void QOpenGLFunctions_1_1_GlRasterPos2iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlRasterPos2i(QOpenGLFunctions_1_1* self, int32_t x, int32_t y);
void QOpenGLFunctions_1_1_GlRasterPos2fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlRasterPos2f(QOpenGLFunctions_1_1* self, float x, float y);
void QOpenGLFunctions_1_1_GlRasterPos2dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlRasterPos2d(QOpenGLFunctions_1_1* self, double x, double y);
void QOpenGLFunctions_1_1_GlNormal3sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlNormal3s(QOpenGLFunctions_1_1* self, int16_t nx, int16_t ny, int16_t nz);
void QOpenGLFunctions_1_1_GlNormal3iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlNormal3i(QOpenGLFunctions_1_1* self, int32_t nx, int32_t ny, int32_t nz);
void QOpenGLFunctions_1_1_GlNormal3fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlNormal3f(QOpenGLFunctions_1_1* self, float nx, float ny, float nz);
void QOpenGLFunctions_1_1_GlNormal3dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlNormal3d(QOpenGLFunctions_1_1* self, double nx, double ny, double nz);
void QOpenGLFunctions_1_1_GlNormal3bv(QOpenGLFunctions_1_1* self, const signed char* v);
void QOpenGLFunctions_1_1_GlNormal3b(QOpenGLFunctions_1_1* self, signed char nx, signed char ny, signed char nz);
void QOpenGLFunctions_1_1_GlIndexsv(QOpenGLFunctions_1_1* self, const int16_t* c);
void QOpenGLFunctions_1_1_GlIndexs(QOpenGLFunctions_1_1* self, int16_t c);
void QOpenGLFunctions_1_1_GlIndexiv(QOpenGLFunctions_1_1* self, const int32_t* c);
void QOpenGLFunctions_1_1_GlIndexi(QOpenGLFunctions_1_1* self, int32_t c);
void QOpenGLFunctions_1_1_GlIndexfv(QOpenGLFunctions_1_1* self, const float* c);
void QOpenGLFunctions_1_1_GlIndexf(QOpenGLFunctions_1_1* self, float c);
void QOpenGLFunctions_1_1_GlIndexdv(QOpenGLFunctions_1_1* self, const double* c);
void QOpenGLFunctions_1_1_GlIndexd(QOpenGLFunctions_1_1* self, double c);
void QOpenGLFunctions_1_1_GlEnd(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlEdgeFlagv(QOpenGLFunctions_1_1* self, const unsigned char* flag);
void QOpenGLFunctions_1_1_GlEdgeFlag(QOpenGLFunctions_1_1* self, unsigned char flag);
void QOpenGLFunctions_1_1_GlColor4usv(QOpenGLFunctions_1_1* self, const uint16_t* v);
void QOpenGLFunctions_1_1_GlColor4us(QOpenGLFunctions_1_1* self, uint16_t red, uint16_t green, uint16_t blue, uint16_t alpha);
void QOpenGLFunctions_1_1_GlColor4uiv(QOpenGLFunctions_1_1* self, const uint32_t* v);
void QOpenGLFunctions_1_1_GlColor4ui(QOpenGLFunctions_1_1* self, uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha);
void QOpenGLFunctions_1_1_GlColor4ubv(QOpenGLFunctions_1_1* self, const uint8_t* v);
void QOpenGLFunctions_1_1_GlColor4ub(QOpenGLFunctions_1_1* self, uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha);
void QOpenGLFunctions_1_1_GlColor4sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlColor4s(QOpenGLFunctions_1_1* self, int16_t red, int16_t green, int16_t blue, int16_t alpha);
void QOpenGLFunctions_1_1_GlColor4iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlColor4i(QOpenGLFunctions_1_1* self, int32_t red, int32_t green, int32_t blue, int32_t alpha);
void QOpenGLFunctions_1_1_GlColor4fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlColor4f(QOpenGLFunctions_1_1* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_1_1_GlColor4dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlColor4d(QOpenGLFunctions_1_1* self, double red, double green, double blue, double alpha);
void QOpenGLFunctions_1_1_GlColor4bv(QOpenGLFunctions_1_1* self, const signed char* v);
void QOpenGLFunctions_1_1_GlColor4b(QOpenGLFunctions_1_1* self, signed char red, signed char green, signed char blue, signed char alpha);
void QOpenGLFunctions_1_1_GlColor3usv(QOpenGLFunctions_1_1* self, const uint16_t* v);
void QOpenGLFunctions_1_1_GlColor3us(QOpenGLFunctions_1_1* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_1_1_GlColor3uiv(QOpenGLFunctions_1_1* self, const uint32_t* v);
void QOpenGLFunctions_1_1_GlColor3ui(QOpenGLFunctions_1_1* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_1_1_GlColor3ubv(QOpenGLFunctions_1_1* self, const uint8_t* v);
void QOpenGLFunctions_1_1_GlColor3ub(QOpenGLFunctions_1_1* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_1_1_GlColor3sv(QOpenGLFunctions_1_1* self, const int16_t* v);
void QOpenGLFunctions_1_1_GlColor3s(QOpenGLFunctions_1_1* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_1_1_GlColor3iv(QOpenGLFunctions_1_1* self, const int32_t* v);
void QOpenGLFunctions_1_1_GlColor3i(QOpenGLFunctions_1_1* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_1_1_GlColor3fv(QOpenGLFunctions_1_1* self, const float* v);
void QOpenGLFunctions_1_1_GlColor3f(QOpenGLFunctions_1_1* self, float red, float green, float blue);
void QOpenGLFunctions_1_1_GlColor3dv(QOpenGLFunctions_1_1* self, const double* v);
void QOpenGLFunctions_1_1_GlColor3d(QOpenGLFunctions_1_1* self, double red, double green, double blue);
void QOpenGLFunctions_1_1_GlColor3bv(QOpenGLFunctions_1_1* self, const signed char* v);
void QOpenGLFunctions_1_1_GlColor3b(QOpenGLFunctions_1_1* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_1_1_GlBitmap(QOpenGLFunctions_1_1* self, int32_t width, int32_t height, float xorig, float yorig, float xmove, float ymove, const uint8_t* bitmap);
void QOpenGLFunctions_1_1_GlBegin(QOpenGLFunctions_1_1* self, uint32_t mode);
void QOpenGLFunctions_1_1_GlListBase(QOpenGLFunctions_1_1* self, uint32_t base);
uint32_t QOpenGLFunctions_1_1_GlGenLists(QOpenGLFunctions_1_1* self, int32_t range);
void QOpenGLFunctions_1_1_GlDeleteLists(QOpenGLFunctions_1_1* self, uint32_t list, int32_t range);
void QOpenGLFunctions_1_1_GlCallLists(QOpenGLFunctions_1_1* self, int32_t n, uint32_t typeVal, const void* lists);
void QOpenGLFunctions_1_1_GlCallList(QOpenGLFunctions_1_1* self, uint32_t list);
void QOpenGLFunctions_1_1_GlEndList(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlNewList(QOpenGLFunctions_1_1* self, uint32_t list, uint32_t mode);
void QOpenGLFunctions_1_1_GlPushClientAttrib(QOpenGLFunctions_1_1* self, uint32_t mask);
void QOpenGLFunctions_1_1_GlPopClientAttrib(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_GlPrioritizeTextures(QOpenGLFunctions_1_1* self, int32_t n, const uint32_t* textures, const float* priorities);
unsigned char QOpenGLFunctions_1_1_GlAreTexturesResident(QOpenGLFunctions_1_1* self, int32_t n, const uint32_t* textures, unsigned char* residences);
void QOpenGLFunctions_1_1_GlVertexPointer(QOpenGLFunctions_1_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlTexCoordPointer(QOpenGLFunctions_1_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlNormalPointer(QOpenGLFunctions_1_1* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlInterleavedArrays(QOpenGLFunctions_1_1* self, uint32_t format, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlIndexPointer(QOpenGLFunctions_1_1* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlEnableClientState(QOpenGLFunctions_1_1* self, uint32_t array);
void QOpenGLFunctions_1_1_GlEdgeFlagPointer(QOpenGLFunctions_1_1* self, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlDisableClientState(QOpenGLFunctions_1_1* self, uint32_t array);
void QOpenGLFunctions_1_1_GlColorPointer(QOpenGLFunctions_1_1* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_1_1_GlArrayElement(QOpenGLFunctions_1_1* self, int32_t i);
void QOpenGLFunctions_1_1_OnInitializeOpenGLFunctions(QOpenGLFunctions_1_1* self, intptr_t slot);
bool QOpenGLFunctions_1_1_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_1_1* self);
void QOpenGLFunctions_1_1_Delete(QOpenGLFunctions_1_1* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
