#pragma once
#ifndef QOPENGLFUNCTIONS_3_0_H_C_LIB
#define QOPENGLFUNCTIONS_3_0_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef char GLchar;
typedef float GLclampf;
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLFunctions_3_0 QOpenGLFunctions_3_0;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLFunctions_3_0* QOpenGLFunctions_3_0_new();
bool QOpenGLFunctions_3_0_InitializeOpenGLFunctions(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlViewport(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlDepthRange(QOpenGLFunctions_3_0* self, double nearVal, double farVal);
unsigned char QOpenGLFunctions_3_0_GlIsEnabled(QOpenGLFunctions_3_0* self, uint32_t cap);
void QOpenGLFunctions_3_0_GlGetTexLevelParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetTexLevelParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetTexParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetTexParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetTexImage(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t format, uint32_t typeVal, void* pixels);
const uint8_t* QOpenGLFunctions_3_0_GlGetString(QOpenGLFunctions_3_0* self, uint32_t name);
void QOpenGLFunctions_3_0_GlGetIntegerv(QOpenGLFunctions_3_0* self, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetFloatv(QOpenGLFunctions_3_0* self, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetDoublev(QOpenGLFunctions_3_0* self, uint32_t pname, double* params);
void QOpenGLFunctions_3_0_GlGetBooleanv(QOpenGLFunctions_3_0* self, uint32_t pname, unsigned char* params);
void QOpenGLFunctions_3_0_GlReadPixels(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, void* pixels);
void QOpenGLFunctions_3_0_GlReadBuffer(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlPixelStorei(QOpenGLFunctions_3_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlPixelStoref(QOpenGLFunctions_3_0* self, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlDepthFunc(QOpenGLFunctions_3_0* self, uint32_t func);
void QOpenGLFunctions_3_0_GlStencilOp(QOpenGLFunctions_3_0* self, uint32_t fail, uint32_t zfail, uint32_t zpass);
void QOpenGLFunctions_3_0_GlStencilFunc(QOpenGLFunctions_3_0* self, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_3_0_GlLogicOp(QOpenGLFunctions_3_0* self, uint32_t opcode);
void QOpenGLFunctions_3_0_GlBlendFunc(QOpenGLFunctions_3_0* self, uint32_t sfactor, uint32_t dfactor);
void QOpenGLFunctions_3_0_GlFlush(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlFinish(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlEnable(QOpenGLFunctions_3_0* self, uint32_t cap);
void QOpenGLFunctions_3_0_GlDisable(QOpenGLFunctions_3_0* self, uint32_t cap);
void QOpenGLFunctions_3_0_GlDepthMask(QOpenGLFunctions_3_0* self, unsigned char flag);
void QOpenGLFunctions_3_0_GlColorMask(QOpenGLFunctions_3_0* self, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void QOpenGLFunctions_3_0_GlStencilMask(QOpenGLFunctions_3_0* self, uint32_t mask);
void QOpenGLFunctions_3_0_GlClearDepth(QOpenGLFunctions_3_0* self, double depth);
void QOpenGLFunctions_3_0_GlClearStencil(QOpenGLFunctions_3_0* self, int32_t s);
void QOpenGLFunctions_3_0_GlClearColor(QOpenGLFunctions_3_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_3_0_GlClear(QOpenGLFunctions_3_0* self, uint32_t mask);
void QOpenGLFunctions_3_0_GlDrawBuffer(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlTexImage2D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlTexImage1D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlTexParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlTexParameteri(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlTexParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlTexParameterf(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlScissor(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlPolygonMode(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_3_0_GlPointSize(QOpenGLFunctions_3_0* self, float size);
void QOpenGLFunctions_3_0_GlLineWidth(QOpenGLFunctions_3_0* self, float width);
void QOpenGLFunctions_3_0_GlHint(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t mode);
void QOpenGLFunctions_3_0_GlFrontFace(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlCullFace(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlIndexubv(QOpenGLFunctions_3_0* self, const uint8_t* c);
void QOpenGLFunctions_3_0_GlIndexub(QOpenGLFunctions_3_0* self, uint8_t c);
unsigned char QOpenGLFunctions_3_0_GlIsTexture(QOpenGLFunctions_3_0* self, uint32_t texture);
void QOpenGLFunctions_3_0_GlGenTextures(QOpenGLFunctions_3_0* self, int32_t n, uint32_t* textures);
void QOpenGLFunctions_3_0_GlDeleteTextures(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* textures);
void QOpenGLFunctions_3_0_GlBindTexture(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t texture);
void QOpenGLFunctions_3_0_GlTexSubImage2D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlTexSubImage1D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlCopyTexSubImage2D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlCopyTexSubImage1D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_3_0_GlCopyTexImage2D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border);
void QOpenGLFunctions_3_0_GlCopyTexImage1D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t border);
void QOpenGLFunctions_3_0_GlPolygonOffset(QOpenGLFunctions_3_0* self, float factor, float units);
void QOpenGLFunctions_3_0_GlGetPointerv(QOpenGLFunctions_3_0* self, uint32_t pname, void** params);
void QOpenGLFunctions_3_0_GlDrawElements(QOpenGLFunctions_3_0* self, uint32_t mode, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_3_0_GlDrawArrays(QOpenGLFunctions_3_0* self, uint32_t mode, int32_t first, int32_t count);
void QOpenGLFunctions_3_0_GlCopyTexSubImage3D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlTexSubImage3D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlTexImage3D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlDrawRangeElements(QOpenGLFunctions_3_0* self, uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t typeVal, const void* indices);
void QOpenGLFunctions_3_0_GlBlendEquation(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlBlendColor(QOpenGLFunctions_3_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_3_0_GlGetCompressedTexImage(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, void* img);
void QOpenGLFunctions_3_0_GlCompressedTexSubImage1D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t width, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_3_0_GlCompressedTexSubImage2D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_3_0_GlCompressedTexSubImage3D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, int32_t imageSize, const void* data);
void QOpenGLFunctions_3_0_GlCompressedTexImage1D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_3_0_GlCompressedTexImage2D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_3_0_GlCompressedTexImage3D(QOpenGLFunctions_3_0* self, uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, int32_t imageSize, const void* data);
void QOpenGLFunctions_3_0_GlSampleCoverage(QOpenGLFunctions_3_0* self, float value, unsigned char invert);
void QOpenGLFunctions_3_0_GlActiveTexture(QOpenGLFunctions_3_0* self, uint32_t texture);
void QOpenGLFunctions_3_0_GlPointParameteriv(QOpenGLFunctions_3_0* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlPointParameteri(QOpenGLFunctions_3_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlPointParameterfv(QOpenGLFunctions_3_0* self, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlPointParameterf(QOpenGLFunctions_3_0* self, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlMultiDrawElements(QOpenGLFunctions_3_0* self, uint32_t mode, const int32_t* count, uint32_t typeVal, const void** indices, int32_t drawcount);
void QOpenGLFunctions_3_0_GlMultiDrawArrays(QOpenGLFunctions_3_0* self, uint32_t mode, const int32_t* first, const int32_t* count, int32_t drawcount);
void QOpenGLFunctions_3_0_GlBlendFuncSeparate(QOpenGLFunctions_3_0* self, uint32_t sfactorRGB, uint32_t dfactorRGB, uint32_t sfactorAlpha, uint32_t dfactorAlpha);
void QOpenGLFunctions_3_0_GlGetBufferPointerv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, void** params);
void QOpenGLFunctions_3_0_GlGetBufferParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
unsigned char QOpenGLFunctions_3_0_GlUnmapBuffer(QOpenGLFunctions_3_0* self, uint32_t target);
void* QOpenGLFunctions_3_0_GlMapBuffer(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t access);
void QOpenGLFunctions_3_0_GlGetBufferSubData(QOpenGLFunctions_3_0* self, uint32_t target, int64_t offset, int64_t size, void* data);
void QOpenGLFunctions_3_0_GlBufferSubData(QOpenGLFunctions_3_0* self, uint32_t target, int64_t offset, int64_t size, const void* data);
void QOpenGLFunctions_3_0_GlBufferData(QOpenGLFunctions_3_0* self, uint32_t target, int64_t size, const void* data, uint32_t usage);
unsigned char QOpenGLFunctions_3_0_GlIsBuffer(QOpenGLFunctions_3_0* self, uint32_t buffer);
void QOpenGLFunctions_3_0_GlGenBuffers(QOpenGLFunctions_3_0* self, int32_t n, uint32_t* buffers);
void QOpenGLFunctions_3_0_GlDeleteBuffers(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* buffers);
void QOpenGLFunctions_3_0_GlBindBuffer(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t buffer);
void QOpenGLFunctions_3_0_GlGetQueryObjectuiv(QOpenGLFunctions_3_0* self, uint32_t id, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_3_0_GlGetQueryObjectiv(QOpenGLFunctions_3_0* self, uint32_t id, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetQueryiv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlEndQuery(QOpenGLFunctions_3_0* self, uint32_t target);
void QOpenGLFunctions_3_0_GlBeginQuery(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t id);
unsigned char QOpenGLFunctions_3_0_GlIsQuery(QOpenGLFunctions_3_0* self, uint32_t id);
void QOpenGLFunctions_3_0_GlDeleteQueries(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* ids);
void QOpenGLFunctions_3_0_GlGenQueries(QOpenGLFunctions_3_0* self, int32_t n, uint32_t* ids);
void QOpenGLFunctions_3_0_GlVertexAttribPointer(QOpenGLFunctions_3_0* self, uint32_t index, int32_t size, uint32_t typeVal, unsigned char normalized, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlValidateProgram(QOpenGLFunctions_3_0* self, uint32_t program);
void QOpenGLFunctions_3_0_GlUniformMatrix4fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix3fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix2fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniform4iv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_3_0_GlUniform3iv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_3_0_GlUniform2iv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_3_0_GlUniform1iv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const int32_t* value);
void QOpenGLFunctions_3_0_GlUniform4fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_3_0_GlUniform3fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_3_0_GlUniform2fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_3_0_GlUniform1fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const float* value);
void QOpenGLFunctions_3_0_GlUniform4i(QOpenGLFunctions_3_0* self, int32_t location, int32_t v0, int32_t v1, int32_t v2, int32_t v3);
void QOpenGLFunctions_3_0_GlUniform3i(QOpenGLFunctions_3_0* self, int32_t location, int32_t v0, int32_t v1, int32_t v2);
void QOpenGLFunctions_3_0_GlUniform2i(QOpenGLFunctions_3_0* self, int32_t location, int32_t v0, int32_t v1);
void QOpenGLFunctions_3_0_GlUniform1i(QOpenGLFunctions_3_0* self, int32_t location, int32_t v0);
void QOpenGLFunctions_3_0_GlUniform4f(QOpenGLFunctions_3_0* self, int32_t location, float v0, float v1, float v2, float v3);
void QOpenGLFunctions_3_0_GlUniform3f(QOpenGLFunctions_3_0* self, int32_t location, float v0, float v1, float v2);
void QOpenGLFunctions_3_0_GlUniform2f(QOpenGLFunctions_3_0* self, int32_t location, float v0, float v1);
void QOpenGLFunctions_3_0_GlUniform1f(QOpenGLFunctions_3_0* self, int32_t location, float v0);
void QOpenGLFunctions_3_0_GlUseProgram(QOpenGLFunctions_3_0* self, uint32_t program);
void QOpenGLFunctions_3_0_GlShaderSource(QOpenGLFunctions_3_0* self, uint32_t shader, int32_t count, const GLchar** stringVal, const int32_t* length);
void QOpenGLFunctions_3_0_GlLinkProgram(QOpenGLFunctions_3_0* self, uint32_t program);
unsigned char QOpenGLFunctions_3_0_GlIsShader(QOpenGLFunctions_3_0* self, uint32_t shader);
unsigned char QOpenGLFunctions_3_0_GlIsProgram(QOpenGLFunctions_3_0* self, uint32_t program);
void QOpenGLFunctions_3_0_GlGetVertexAttribPointerv(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t pname, void** pointer);
void QOpenGLFunctions_3_0_GlGetVertexAttribiv(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetVertexAttribfv(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetVertexAttribdv(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t pname, double* params);
void QOpenGLFunctions_3_0_GlGetUniformiv(QOpenGLFunctions_3_0* self, uint32_t program, int32_t location, int32_t* params);
void QOpenGLFunctions_3_0_GlGetUniformfv(QOpenGLFunctions_3_0* self, uint32_t program, int32_t location, float* params);
int32_t QOpenGLFunctions_3_0_GlGetUniformLocation(QOpenGLFunctions_3_0* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_3_0_GlGetShaderSource(QOpenGLFunctions_3_0* self, uint32_t shader, int32_t bufSize, int32_t* length, GLchar* source);
void QOpenGLFunctions_3_0_GlGetShaderInfoLog(QOpenGLFunctions_3_0* self, uint32_t shader, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_3_0_GlGetShaderiv(QOpenGLFunctions_3_0* self, uint32_t shader, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetProgramInfoLog(QOpenGLFunctions_3_0* self, uint32_t program, int32_t bufSize, int32_t* length, GLchar* infoLog);
void QOpenGLFunctions_3_0_GlGetProgramiv(QOpenGLFunctions_3_0* self, uint32_t program, uint32_t pname, int32_t* params);
int32_t QOpenGLFunctions_3_0_GlGetAttribLocation(QOpenGLFunctions_3_0* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_3_0_GlGetAttachedShaders(QOpenGLFunctions_3_0* self, uint32_t program, int32_t maxCount, int32_t* count, uint32_t* obj);
void QOpenGLFunctions_3_0_GlEnableVertexAttribArray(QOpenGLFunctions_3_0* self, uint32_t index);
void QOpenGLFunctions_3_0_GlDisableVertexAttribArray(QOpenGLFunctions_3_0* self, uint32_t index);
void QOpenGLFunctions_3_0_GlDetachShader(QOpenGLFunctions_3_0* self, uint32_t program, uint32_t shader);
void QOpenGLFunctions_3_0_GlDeleteShader(QOpenGLFunctions_3_0* self, uint32_t shader);
void QOpenGLFunctions_3_0_GlDeleteProgram(QOpenGLFunctions_3_0* self, uint32_t program);
uint32_t QOpenGLFunctions_3_0_GlCreateShader(QOpenGLFunctions_3_0* self, uint32_t typeVal);
uint32_t QOpenGLFunctions_3_0_GlCreateProgram(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlCompileShader(QOpenGLFunctions_3_0* self, uint32_t shader);
void QOpenGLFunctions_3_0_GlBindAttribLocation(QOpenGLFunctions_3_0* self, uint32_t program, uint32_t index, const GLchar* name);
void QOpenGLFunctions_3_0_GlAttachShader(QOpenGLFunctions_3_0* self, uint32_t program, uint32_t shader);
void QOpenGLFunctions_3_0_GlStencilMaskSeparate(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t mask);
void QOpenGLFunctions_3_0_GlStencilFuncSeparate(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t func, int32_t ref, uint32_t mask);
void QOpenGLFunctions_3_0_GlStencilOpSeparate(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t sfail, uint32_t dpfail, uint32_t dppass);
void QOpenGLFunctions_3_0_GlBlendEquationSeparate(QOpenGLFunctions_3_0* self, uint32_t modeRGB, uint32_t modeAlpha);
void QOpenGLFunctions_3_0_GlUniformMatrix4x3fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix3x4fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix4x2fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix2x4fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix3x2fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
void QOpenGLFunctions_3_0_GlUniformMatrix2x3fv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, unsigned char transpose, const float* value);
unsigned char QOpenGLFunctions_3_0_GlIsVertexArray(QOpenGLFunctions_3_0* self, uint32_t array);
void QOpenGLFunctions_3_0_GlGenVertexArrays(QOpenGLFunctions_3_0* self, int32_t n, uint32_t* arrays);
void QOpenGLFunctions_3_0_GlDeleteVertexArrays(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* arrays);
void QOpenGLFunctions_3_0_GlBindVertexArray(QOpenGLFunctions_3_0* self, uint32_t array);
void QOpenGLFunctions_3_0_GlFlushMappedBufferRange(QOpenGLFunctions_3_0* self, uint32_t target, int64_t offset, int64_t length);
void* QOpenGLFunctions_3_0_GlMapBufferRange(QOpenGLFunctions_3_0* self, uint32_t target, int64_t offset, int64_t length, uint32_t access);
void QOpenGLFunctions_3_0_GlFramebufferTextureLayer(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t attachment, uint32_t texture, int32_t level, int32_t layer);
void QOpenGLFunctions_3_0_GlRenderbufferStorageMultisample(QOpenGLFunctions_3_0* self, uint32_t target, int32_t samples, uint32_t internalformat, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlBlitFramebuffer(QOpenGLFunctions_3_0* self, int32_t srcX0, int32_t srcY0, int32_t srcX1, int32_t srcY1, int32_t dstX0, int32_t dstY0, int32_t dstX1, int32_t dstY1, uint32_t mask, uint32_t filter);
void QOpenGLFunctions_3_0_GlGenerateMipmap(QOpenGLFunctions_3_0* self, uint32_t target);
void QOpenGLFunctions_3_0_GlGetFramebufferAttachmentParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t attachment, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlFramebufferRenderbuffer(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t attachment, uint32_t renderbuffertarget, uint32_t renderbuffer);
void QOpenGLFunctions_3_0_GlFramebufferTexture3D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level, int32_t zoffset);
void QOpenGLFunctions_3_0_GlFramebufferTexture2D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level);
void QOpenGLFunctions_3_0_GlFramebufferTexture1D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level);
void QOpenGLFunctions_3_0_GlGenFramebuffers(QOpenGLFunctions_3_0* self, int32_t n, uint32_t* framebuffers);
void QOpenGLFunctions_3_0_GlDeleteFramebuffers(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* framebuffers);
void QOpenGLFunctions_3_0_GlBindFramebuffer(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t framebuffer);
unsigned char QOpenGLFunctions_3_0_GlIsFramebuffer(QOpenGLFunctions_3_0* self, uint32_t framebuffer);
void QOpenGLFunctions_3_0_GlGetRenderbufferParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlRenderbufferStorage(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlGenRenderbuffers(QOpenGLFunctions_3_0* self, int32_t n, uint32_t* renderbuffers);
void QOpenGLFunctions_3_0_GlDeleteRenderbuffers(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* renderbuffers);
void QOpenGLFunctions_3_0_GlBindRenderbuffer(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t renderbuffer);
unsigned char QOpenGLFunctions_3_0_GlIsRenderbuffer(QOpenGLFunctions_3_0* self, uint32_t renderbuffer);
const uint8_t* QOpenGLFunctions_3_0_GlGetStringi(QOpenGLFunctions_3_0* self, uint32_t name, uint32_t index);
void QOpenGLFunctions_3_0_GlClearBufferfi(QOpenGLFunctions_3_0* self, uint32_t buffer, int32_t drawbuffer, float depth, int32_t stencil);
void QOpenGLFunctions_3_0_GlClearBufferfv(QOpenGLFunctions_3_0* self, uint32_t buffer, int32_t drawbuffer, const float* value);
void QOpenGLFunctions_3_0_GlClearBufferuiv(QOpenGLFunctions_3_0* self, uint32_t buffer, int32_t drawbuffer, const uint32_t* value);
void QOpenGLFunctions_3_0_GlClearBufferiv(QOpenGLFunctions_3_0* self, uint32_t buffer, int32_t drawbuffer, const int32_t* value);
void QOpenGLFunctions_3_0_GlGetTexParameterIuiv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_3_0_GlGetTexParameterIiv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlTexParameterIuiv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const uint32_t* params);
void QOpenGLFunctions_3_0_GlTexParameterIiv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlUniform4uiv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_3_0_GlUniform3uiv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_3_0_GlUniform2uiv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_3_0_GlUniform1uiv(QOpenGLFunctions_3_0* self, int32_t location, int32_t count, const uint32_t* value);
void QOpenGLFunctions_3_0_GlUniform4ui(QOpenGLFunctions_3_0* self, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3);
void QOpenGLFunctions_3_0_GlUniform3ui(QOpenGLFunctions_3_0* self, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2);
void QOpenGLFunctions_3_0_GlUniform2ui(QOpenGLFunctions_3_0* self, int32_t location, uint32_t v0, uint32_t v1);
void QOpenGLFunctions_3_0_GlUniform1ui(QOpenGLFunctions_3_0* self, int32_t location, uint32_t v0);
int32_t QOpenGLFunctions_3_0_GlGetFragDataLocation(QOpenGLFunctions_3_0* self, uint32_t program, const GLchar* name);
void QOpenGLFunctions_3_0_GlBindFragDataLocation(QOpenGLFunctions_3_0* self, uint32_t program, uint32_t color, const GLchar* name);
void QOpenGLFunctions_3_0_GlGetUniformuiv(QOpenGLFunctions_3_0* self, uint32_t program, int32_t location, uint32_t* params);
void QOpenGLFunctions_3_0_GlGetVertexAttribIuiv(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t pname, uint32_t* params);
void QOpenGLFunctions_3_0_GlGetVertexAttribIiv(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlVertexAttribIPointer(QOpenGLFunctions_3_0* self, uint32_t index, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlEndConditionalRender(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlBeginConditionalRender(QOpenGLFunctions_3_0* self, uint32_t id, uint32_t mode);
void QOpenGLFunctions_3_0_GlClampColor(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t clamp);
void QOpenGLFunctions_3_0_GlTransformFeedbackVaryings(QOpenGLFunctions_3_0* self, uint32_t program, int32_t count, const GLchar** varyings, uint32_t bufferMode);
void QOpenGLFunctions_3_0_GlBindBufferBase(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index, uint32_t buffer);
void QOpenGLFunctions_3_0_GlBindBufferRange(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index, uint32_t buffer, int64_t offset, int64_t size);
void QOpenGLFunctions_3_0_GlEndTransformFeedback(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlBeginTransformFeedback(QOpenGLFunctions_3_0* self, uint32_t primitiveMode);
unsigned char QOpenGLFunctions_3_0_GlIsEnabledi(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_3_0_GlDisablei(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_3_0_GlEnablei(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index);
void QOpenGLFunctions_3_0_GlGetIntegeriV(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index, int32_t* data);
void QOpenGLFunctions_3_0_GlGetBooleaniV(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t index, unsigned char* data);
void QOpenGLFunctions_3_0_GlColorMaski(QOpenGLFunctions_3_0* self, uint32_t index, unsigned char r, unsigned char g, unsigned char b, unsigned char a);
void QOpenGLFunctions_3_0_GlTranslatef(QOpenGLFunctions_3_0* self, float x, float y, float z);
void QOpenGLFunctions_3_0_GlTranslated(QOpenGLFunctions_3_0* self, double x, double y, double z);
void QOpenGLFunctions_3_0_GlScalef(QOpenGLFunctions_3_0* self, float x, float y, float z);
void QOpenGLFunctions_3_0_GlScaled(QOpenGLFunctions_3_0* self, double x, double y, double z);
void QOpenGLFunctions_3_0_GlRotatef(QOpenGLFunctions_3_0* self, float angle, float x, float y, float z);
void QOpenGLFunctions_3_0_GlRotated(QOpenGLFunctions_3_0* self, double angle, double x, double y, double z);
void QOpenGLFunctions_3_0_GlPushMatrix(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlPopMatrix(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlOrtho(QOpenGLFunctions_3_0* self, double left, double right, double bottom, double top, double zNear, double zFar);
void QOpenGLFunctions_3_0_GlMultMatrixd(QOpenGLFunctions_3_0* self, const double* m);
void QOpenGLFunctions_3_0_GlMultMatrixf(QOpenGLFunctions_3_0* self, const float* m);
void QOpenGLFunctions_3_0_GlMatrixMode(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlLoadMatrixd(QOpenGLFunctions_3_0* self, const double* m);
void QOpenGLFunctions_3_0_GlLoadMatrixf(QOpenGLFunctions_3_0* self, const float* m);
void QOpenGLFunctions_3_0_GlLoadIdentity(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlFrustum(QOpenGLFunctions_3_0* self, double left, double right, double bottom, double top, double zNear, double zFar);
unsigned char QOpenGLFunctions_3_0_GlIsList(QOpenGLFunctions_3_0* self, uint32_t list);
void QOpenGLFunctions_3_0_GlGetTexGeniv(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetTexGenfv(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetTexGendv(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, double* params);
void QOpenGLFunctions_3_0_GlGetTexEnviv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetTexEnvfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetPolygonStipple(QOpenGLFunctions_3_0* self, uint8_t* mask);
void QOpenGLFunctions_3_0_GlGetPixelMapusv(QOpenGLFunctions_3_0* self, uint32_t mapVal, uint16_t* values);
void QOpenGLFunctions_3_0_GlGetPixelMapuiv(QOpenGLFunctions_3_0* self, uint32_t mapVal, uint32_t* values);
void QOpenGLFunctions_3_0_GlGetPixelMapfv(QOpenGLFunctions_3_0* self, uint32_t mapVal, float* values);
void QOpenGLFunctions_3_0_GlGetMaterialiv(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetMaterialfv(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetMapiv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t query, int32_t* v);
void QOpenGLFunctions_3_0_GlGetMapfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t query, float* v);
void QOpenGLFunctions_3_0_GlGetMapdv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t query, double* v);
void QOpenGLFunctions_3_0_GlGetLightiv(QOpenGLFunctions_3_0* self, uint32_t light, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetLightfv(QOpenGLFunctions_3_0* self, uint32_t light, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetClipPlane(QOpenGLFunctions_3_0* self, uint32_t plane, double* equation);
void QOpenGLFunctions_3_0_GlDrawPixels(QOpenGLFunctions_3_0* self, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* pixels);
void QOpenGLFunctions_3_0_GlCopyPixels(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t width, int32_t height, uint32_t typeVal);
void QOpenGLFunctions_3_0_GlPixelMapusv(QOpenGLFunctions_3_0* self, uint32_t mapVal, int32_t mapsize, const uint16_t* values);
void QOpenGLFunctions_3_0_GlPixelMapuiv(QOpenGLFunctions_3_0* self, uint32_t mapVal, int32_t mapsize, const uint32_t* values);
void QOpenGLFunctions_3_0_GlPixelMapfv(QOpenGLFunctions_3_0* self, uint32_t mapVal, int32_t mapsize, const float* values);
void QOpenGLFunctions_3_0_GlPixelTransferi(QOpenGLFunctions_3_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlPixelTransferf(QOpenGLFunctions_3_0* self, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlPixelZoom(QOpenGLFunctions_3_0* self, float xfactor, float yfactor);
void QOpenGLFunctions_3_0_GlAlphaFunc(QOpenGLFunctions_3_0* self, uint32_t func, float ref);
void QOpenGLFunctions_3_0_GlEvalPoint2(QOpenGLFunctions_3_0* self, int32_t i, int32_t j);
void QOpenGLFunctions_3_0_GlEvalMesh2(QOpenGLFunctions_3_0* self, uint32_t mode, int32_t i1Val, int32_t i2Val, int32_t j1, int32_t j2);
void QOpenGLFunctions_3_0_GlEvalPoint1(QOpenGLFunctions_3_0* self, int32_t i);
void QOpenGLFunctions_3_0_GlEvalMesh1(QOpenGLFunctions_3_0* self, uint32_t mode, int32_t i1Val, int32_t i2Val);
void QOpenGLFunctions_3_0_GlEvalCoord2fv(QOpenGLFunctions_3_0* self, const float* u);
void QOpenGLFunctions_3_0_GlEvalCoord2f(QOpenGLFunctions_3_0* self, float u, float v);
void QOpenGLFunctions_3_0_GlEvalCoord2dv(QOpenGLFunctions_3_0* self, const double* u);
void QOpenGLFunctions_3_0_GlEvalCoord2d(QOpenGLFunctions_3_0* self, double u, double v);
void QOpenGLFunctions_3_0_GlEvalCoord1fv(QOpenGLFunctions_3_0* self, const float* u);
void QOpenGLFunctions_3_0_GlEvalCoord1f(QOpenGLFunctions_3_0* self, float u);
void QOpenGLFunctions_3_0_GlEvalCoord1dv(QOpenGLFunctions_3_0* self, const double* u);
void QOpenGLFunctions_3_0_GlEvalCoord1d(QOpenGLFunctions_3_0* self, double u);
void QOpenGLFunctions_3_0_GlMapGrid2f(QOpenGLFunctions_3_0* self, int32_t un, float u1Val, float u2Val, int32_t vn, float v1, float v2);
void QOpenGLFunctions_3_0_GlMapGrid2d(QOpenGLFunctions_3_0* self, int32_t un, double u1Val, double u2Val, int32_t vn, double v1, double v2);
void QOpenGLFunctions_3_0_GlMapGrid1f(QOpenGLFunctions_3_0* self, int32_t un, float u1Val, float u2Val);
void QOpenGLFunctions_3_0_GlMapGrid1d(QOpenGLFunctions_3_0* self, int32_t un, double u1Val, double u2Val);
void QOpenGLFunctions_3_0_GlMap2f(QOpenGLFunctions_3_0* self, uint32_t target, float u1Val, float u2Val, int32_t ustride, int32_t uorder, float v1, float v2, int32_t vstride, int32_t vorder, const float* points);
void QOpenGLFunctions_3_0_GlMap2d(QOpenGLFunctions_3_0* self, uint32_t target, double u1Val, double u2Val, int32_t ustride, int32_t uorder, double v1, double v2, int32_t vstride, int32_t vorder, const double* points);
void QOpenGLFunctions_3_0_GlMap1f(QOpenGLFunctions_3_0* self, uint32_t target, float u1Val, float u2Val, int32_t stride, int32_t order, const float* points);
void QOpenGLFunctions_3_0_GlMap1d(QOpenGLFunctions_3_0* self, uint32_t target, double u1Val, double u2Val, int32_t stride, int32_t order, const double* points);
void QOpenGLFunctions_3_0_GlPushAttrib(QOpenGLFunctions_3_0* self, uint32_t mask);
void QOpenGLFunctions_3_0_GlPopAttrib(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlAccum(QOpenGLFunctions_3_0* self, uint32_t op, float value);
void QOpenGLFunctions_3_0_GlIndexMask(QOpenGLFunctions_3_0* self, uint32_t mask);
void QOpenGLFunctions_3_0_GlClearIndex(QOpenGLFunctions_3_0* self, float c);
void QOpenGLFunctions_3_0_GlClearAccum(QOpenGLFunctions_3_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_3_0_GlPushName(QOpenGLFunctions_3_0* self, uint32_t name);
void QOpenGLFunctions_3_0_GlPopName(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlPassThrough(QOpenGLFunctions_3_0* self, float token);
void QOpenGLFunctions_3_0_GlLoadName(QOpenGLFunctions_3_0* self, uint32_t name);
void QOpenGLFunctions_3_0_GlInitNames(QOpenGLFunctions_3_0* self);
int32_t QOpenGLFunctions_3_0_GlRenderMode(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlSelectBuffer(QOpenGLFunctions_3_0* self, int32_t size, uint32_t* buffer);
void QOpenGLFunctions_3_0_GlFeedbackBuffer(QOpenGLFunctions_3_0* self, int32_t size, uint32_t typeVal, float* buffer);
void QOpenGLFunctions_3_0_GlTexGeniv(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlTexGeni(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlTexGenfv(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlTexGenf(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlTexGendv(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, const double* params);
void QOpenGLFunctions_3_0_GlTexGend(QOpenGLFunctions_3_0* self, uint32_t coord, uint32_t pname, double param);
void QOpenGLFunctions_3_0_GlTexEnviv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlTexEnvi(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlTexEnvfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlTexEnvf(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlShadeModel(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlPolygonStipple(QOpenGLFunctions_3_0* self, const uint8_t* mask);
void QOpenGLFunctions_3_0_GlMaterialiv(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlMateriali(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlMaterialfv(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlMaterialf(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlLineStipple(QOpenGLFunctions_3_0* self, int32_t factor, uint16_t pattern);
void QOpenGLFunctions_3_0_GlLightModeliv(QOpenGLFunctions_3_0* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlLightModeli(QOpenGLFunctions_3_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlLightModelfv(QOpenGLFunctions_3_0* self, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlLightModelf(QOpenGLFunctions_3_0* self, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlLightiv(QOpenGLFunctions_3_0* self, uint32_t light, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlLighti(QOpenGLFunctions_3_0* self, uint32_t light, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlLightfv(QOpenGLFunctions_3_0* self, uint32_t light, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlLightf(QOpenGLFunctions_3_0* self, uint32_t light, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlFogiv(QOpenGLFunctions_3_0* self, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlFogi(QOpenGLFunctions_3_0* self, uint32_t pname, int32_t param);
void QOpenGLFunctions_3_0_GlFogfv(QOpenGLFunctions_3_0* self, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlFogf(QOpenGLFunctions_3_0* self, uint32_t pname, float param);
void QOpenGLFunctions_3_0_GlColorMaterial(QOpenGLFunctions_3_0* self, uint32_t face, uint32_t mode);
void QOpenGLFunctions_3_0_GlClipPlane(QOpenGLFunctions_3_0* self, uint32_t plane, const double* equation);
void QOpenGLFunctions_3_0_GlVertex4sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertex4s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_3_0_GlVertex4iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertex4i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_3_0_GlVertex4fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlVertex4f(QOpenGLFunctions_3_0* self, float x, float y, float z, float w);
void QOpenGLFunctions_3_0_GlVertex4dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlVertex4d(QOpenGLFunctions_3_0* self, double x, double y, double z, double w);
void QOpenGLFunctions_3_0_GlVertex3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertex3s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_3_0_GlVertex3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertex3i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_3_0_GlVertex3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlVertex3f(QOpenGLFunctions_3_0* self, float x, float y, float z);
void QOpenGLFunctions_3_0_GlVertex3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlVertex3d(QOpenGLFunctions_3_0* self, double x, double y, double z);
void QOpenGLFunctions_3_0_GlVertex2sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertex2s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y);
void QOpenGLFunctions_3_0_GlVertex2iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertex2i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y);
void QOpenGLFunctions_3_0_GlVertex2fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlVertex2f(QOpenGLFunctions_3_0* self, float x, float y);
void QOpenGLFunctions_3_0_GlVertex2dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlVertex2d(QOpenGLFunctions_3_0* self, double x, double y);
void QOpenGLFunctions_3_0_GlTexCoord4sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlTexCoord4s(QOpenGLFunctions_3_0* self, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_3_0_GlTexCoord4iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlTexCoord4i(QOpenGLFunctions_3_0* self, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_3_0_GlTexCoord4fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlTexCoord4f(QOpenGLFunctions_3_0* self, float s, float t, float r, float q);
void QOpenGLFunctions_3_0_GlTexCoord4dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlTexCoord4d(QOpenGLFunctions_3_0* self, double s, double t, double r, double q);
void QOpenGLFunctions_3_0_GlTexCoord3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlTexCoord3s(QOpenGLFunctions_3_0* self, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_3_0_GlTexCoord3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlTexCoord3i(QOpenGLFunctions_3_0* self, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_3_0_GlTexCoord3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlTexCoord3f(QOpenGLFunctions_3_0* self, float s, float t, float r);
void QOpenGLFunctions_3_0_GlTexCoord3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlTexCoord3d(QOpenGLFunctions_3_0* self, double s, double t, double r);
void QOpenGLFunctions_3_0_GlTexCoord2sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlTexCoord2s(QOpenGLFunctions_3_0* self, int16_t s, int16_t t);
void QOpenGLFunctions_3_0_GlTexCoord2iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlTexCoord2i(QOpenGLFunctions_3_0* self, int32_t s, int32_t t);
void QOpenGLFunctions_3_0_GlTexCoord2fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlTexCoord2f(QOpenGLFunctions_3_0* self, float s, float t);
void QOpenGLFunctions_3_0_GlTexCoord2dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlTexCoord2d(QOpenGLFunctions_3_0* self, double s, double t);
void QOpenGLFunctions_3_0_GlTexCoord1sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlTexCoord1s(QOpenGLFunctions_3_0* self, int16_t s);
void QOpenGLFunctions_3_0_GlTexCoord1iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlTexCoord1i(QOpenGLFunctions_3_0* self, int32_t s);
void QOpenGLFunctions_3_0_GlTexCoord1fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlTexCoord1f(QOpenGLFunctions_3_0* self, float s);
void QOpenGLFunctions_3_0_GlTexCoord1dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlTexCoord1d(QOpenGLFunctions_3_0* self, double s);
void QOpenGLFunctions_3_0_GlRectsv(QOpenGLFunctions_3_0* self, const int16_t* v1, const int16_t* v2);
void QOpenGLFunctions_3_0_GlRects(QOpenGLFunctions_3_0* self, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void QOpenGLFunctions_3_0_GlRectiv(QOpenGLFunctions_3_0* self, const int32_t* v1, const int32_t* v2);
void QOpenGLFunctions_3_0_GlRecti(QOpenGLFunctions_3_0* self, int32_t x1, int32_t y1, int32_t x2, int32_t y2);
void QOpenGLFunctions_3_0_GlRectfv(QOpenGLFunctions_3_0* self, const float* v1, const float* v2);
void QOpenGLFunctions_3_0_GlRectf(QOpenGLFunctions_3_0* self, float x1, float y1, float x2, float y2);
void QOpenGLFunctions_3_0_GlRectdv(QOpenGLFunctions_3_0* self, const double* v1, const double* v2);
void QOpenGLFunctions_3_0_GlRectd(QOpenGLFunctions_3_0* self, double x1, double y1, double x2, double y2);
void QOpenGLFunctions_3_0_GlRasterPos4sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlRasterPos4s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_3_0_GlRasterPos4iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlRasterPos4i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_3_0_GlRasterPos4fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlRasterPos4f(QOpenGLFunctions_3_0* self, float x, float y, float z, float w);
void QOpenGLFunctions_3_0_GlRasterPos4dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlRasterPos4d(QOpenGLFunctions_3_0* self, double x, double y, double z, double w);
void QOpenGLFunctions_3_0_GlRasterPos3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlRasterPos3s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_3_0_GlRasterPos3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlRasterPos3i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_3_0_GlRasterPos3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlRasterPos3f(QOpenGLFunctions_3_0* self, float x, float y, float z);
void QOpenGLFunctions_3_0_GlRasterPos3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlRasterPos3d(QOpenGLFunctions_3_0* self, double x, double y, double z);
void QOpenGLFunctions_3_0_GlRasterPos2sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlRasterPos2s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y);
void QOpenGLFunctions_3_0_GlRasterPos2iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlRasterPos2i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y);
void QOpenGLFunctions_3_0_GlRasterPos2fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlRasterPos2f(QOpenGLFunctions_3_0* self, float x, float y);
void QOpenGLFunctions_3_0_GlRasterPos2dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlRasterPos2d(QOpenGLFunctions_3_0* self, double x, double y);
void QOpenGLFunctions_3_0_GlNormal3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlNormal3s(QOpenGLFunctions_3_0* self, int16_t nx, int16_t ny, int16_t nz);
void QOpenGLFunctions_3_0_GlNormal3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlNormal3i(QOpenGLFunctions_3_0* self, int32_t nx, int32_t ny, int32_t nz);
void QOpenGLFunctions_3_0_GlNormal3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlNormal3f(QOpenGLFunctions_3_0* self, float nx, float ny, float nz);
void QOpenGLFunctions_3_0_GlNormal3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlNormal3d(QOpenGLFunctions_3_0* self, double nx, double ny, double nz);
void QOpenGLFunctions_3_0_GlNormal3bv(QOpenGLFunctions_3_0* self, const signed char* v);
void QOpenGLFunctions_3_0_GlNormal3b(QOpenGLFunctions_3_0* self, signed char nx, signed char ny, signed char nz);
void QOpenGLFunctions_3_0_GlIndexsv(QOpenGLFunctions_3_0* self, const int16_t* c);
void QOpenGLFunctions_3_0_GlIndexs(QOpenGLFunctions_3_0* self, int16_t c);
void QOpenGLFunctions_3_0_GlIndexiv(QOpenGLFunctions_3_0* self, const int32_t* c);
void QOpenGLFunctions_3_0_GlIndexi(QOpenGLFunctions_3_0* self, int32_t c);
void QOpenGLFunctions_3_0_GlIndexfv(QOpenGLFunctions_3_0* self, const float* c);
void QOpenGLFunctions_3_0_GlIndexf(QOpenGLFunctions_3_0* self, float c);
void QOpenGLFunctions_3_0_GlIndexdv(QOpenGLFunctions_3_0* self, const double* c);
void QOpenGLFunctions_3_0_GlIndexd(QOpenGLFunctions_3_0* self, double c);
void QOpenGLFunctions_3_0_GlEnd(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlEdgeFlagv(QOpenGLFunctions_3_0* self, const unsigned char* flag);
void QOpenGLFunctions_3_0_GlEdgeFlag(QOpenGLFunctions_3_0* self, unsigned char flag);
void QOpenGLFunctions_3_0_GlColor4usv(QOpenGLFunctions_3_0* self, const uint16_t* v);
void QOpenGLFunctions_3_0_GlColor4us(QOpenGLFunctions_3_0* self, uint16_t red, uint16_t green, uint16_t blue, uint16_t alpha);
void QOpenGLFunctions_3_0_GlColor4uiv(QOpenGLFunctions_3_0* self, const uint32_t* v);
void QOpenGLFunctions_3_0_GlColor4ui(QOpenGLFunctions_3_0* self, uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha);
void QOpenGLFunctions_3_0_GlColor4ubv(QOpenGLFunctions_3_0* self, const uint8_t* v);
void QOpenGLFunctions_3_0_GlColor4ub(QOpenGLFunctions_3_0* self, uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha);
void QOpenGLFunctions_3_0_GlColor4sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlColor4s(QOpenGLFunctions_3_0* self, int16_t red, int16_t green, int16_t blue, int16_t alpha);
void QOpenGLFunctions_3_0_GlColor4iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlColor4i(QOpenGLFunctions_3_0* self, int32_t red, int32_t green, int32_t blue, int32_t alpha);
void QOpenGLFunctions_3_0_GlColor4fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlColor4f(QOpenGLFunctions_3_0* self, float red, float green, float blue, float alpha);
void QOpenGLFunctions_3_0_GlColor4dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlColor4d(QOpenGLFunctions_3_0* self, double red, double green, double blue, double alpha);
void QOpenGLFunctions_3_0_GlColor4bv(QOpenGLFunctions_3_0* self, const signed char* v);
void QOpenGLFunctions_3_0_GlColor4b(QOpenGLFunctions_3_0* self, signed char red, signed char green, signed char blue, signed char alpha);
void QOpenGLFunctions_3_0_GlColor3usv(QOpenGLFunctions_3_0* self, const uint16_t* v);
void QOpenGLFunctions_3_0_GlColor3us(QOpenGLFunctions_3_0* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_3_0_GlColor3uiv(QOpenGLFunctions_3_0* self, const uint32_t* v);
void QOpenGLFunctions_3_0_GlColor3ui(QOpenGLFunctions_3_0* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_3_0_GlColor3ubv(QOpenGLFunctions_3_0* self, const uint8_t* v);
void QOpenGLFunctions_3_0_GlColor3ub(QOpenGLFunctions_3_0* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_3_0_GlColor3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlColor3s(QOpenGLFunctions_3_0* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_3_0_GlColor3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlColor3i(QOpenGLFunctions_3_0* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_3_0_GlColor3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlColor3f(QOpenGLFunctions_3_0* self, float red, float green, float blue);
void QOpenGLFunctions_3_0_GlColor3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlColor3d(QOpenGLFunctions_3_0* self, double red, double green, double blue);
void QOpenGLFunctions_3_0_GlColor3bv(QOpenGLFunctions_3_0* self, const signed char* v);
void QOpenGLFunctions_3_0_GlColor3b(QOpenGLFunctions_3_0* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_3_0_GlBitmap(QOpenGLFunctions_3_0* self, int32_t width, int32_t height, float xorig, float yorig, float xmove, float ymove, const uint8_t* bitmap);
void QOpenGLFunctions_3_0_GlBegin(QOpenGLFunctions_3_0* self, uint32_t mode);
void QOpenGLFunctions_3_0_GlListBase(QOpenGLFunctions_3_0* self, uint32_t base);
uint32_t QOpenGLFunctions_3_0_GlGenLists(QOpenGLFunctions_3_0* self, int32_t range);
void QOpenGLFunctions_3_0_GlDeleteLists(QOpenGLFunctions_3_0* self, uint32_t list, int32_t range);
void QOpenGLFunctions_3_0_GlCallLists(QOpenGLFunctions_3_0* self, int32_t n, uint32_t typeVal, const void* lists);
void QOpenGLFunctions_3_0_GlCallList(QOpenGLFunctions_3_0* self, uint32_t list);
void QOpenGLFunctions_3_0_GlEndList(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlNewList(QOpenGLFunctions_3_0* self, uint32_t list, uint32_t mode);
void QOpenGLFunctions_3_0_GlPushClientAttrib(QOpenGLFunctions_3_0* self, uint32_t mask);
void QOpenGLFunctions_3_0_GlPopClientAttrib(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_GlPrioritizeTextures(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* textures, const float* priorities);
unsigned char QOpenGLFunctions_3_0_GlAreTexturesResident(QOpenGLFunctions_3_0* self, int32_t n, const uint32_t* textures, unsigned char* residences);
void QOpenGLFunctions_3_0_GlVertexPointer(QOpenGLFunctions_3_0* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlTexCoordPointer(QOpenGLFunctions_3_0* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlNormalPointer(QOpenGLFunctions_3_0* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlInterleavedArrays(QOpenGLFunctions_3_0* self, uint32_t format, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlIndexPointer(QOpenGLFunctions_3_0* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlEnableClientState(QOpenGLFunctions_3_0* self, uint32_t array);
void QOpenGLFunctions_3_0_GlEdgeFlagPointer(QOpenGLFunctions_3_0* self, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlDisableClientState(QOpenGLFunctions_3_0* self, uint32_t array);
void QOpenGLFunctions_3_0_GlColorPointer(QOpenGLFunctions_3_0* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlArrayElement(QOpenGLFunctions_3_0* self, int32_t i);
void QOpenGLFunctions_3_0_GlResetMinmax(QOpenGLFunctions_3_0* self, uint32_t target);
void QOpenGLFunctions_3_0_GlResetHistogram(QOpenGLFunctions_3_0* self, uint32_t target);
void QOpenGLFunctions_3_0_GlMinmax(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_3_0_GlHistogram(QOpenGLFunctions_3_0* self, uint32_t target, int32_t width, uint32_t internalformat, unsigned char sink);
void QOpenGLFunctions_3_0_GlGetMinmaxParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetMinmaxParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetMinmax(QOpenGLFunctions_3_0* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_3_0_GlGetHistogramParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetHistogramParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetHistogram(QOpenGLFunctions_3_0* self, uint32_t target, unsigned char reset, uint32_t format, uint32_t typeVal, void* values);
void QOpenGLFunctions_3_0_GlSeparableFilter2D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* row, const void* column);
void QOpenGLFunctions_3_0_GlGetSeparableFilter(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t format, uint32_t typeVal, void* row, void* column, void* span);
void QOpenGLFunctions_3_0_GlGetConvolutionParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetConvolutionParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetConvolutionFilter(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t format, uint32_t typeVal, void* image);
void QOpenGLFunctions_3_0_GlCopyConvolutionFilter2D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height);
void QOpenGLFunctions_3_0_GlCopyConvolutionFilter1D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_3_0_GlConvolutionParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlConvolutionParameteri(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t params);
void QOpenGLFunctions_3_0_GlConvolutionParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlConvolutionParameterf(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float params);
void QOpenGLFunctions_3_0_GlConvolutionFilter2D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t width, int32_t height, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_3_0_GlConvolutionFilter1D(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* image);
void QOpenGLFunctions_3_0_GlCopyColorSubTable(QOpenGLFunctions_3_0* self, uint32_t target, int32_t start, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_3_0_GlColorSubTable(QOpenGLFunctions_3_0* self, uint32_t target, int32_t start, int32_t count, uint32_t format, uint32_t typeVal, const void* data);
void QOpenGLFunctions_3_0_GlGetColorTableParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, int32_t* params);
void QOpenGLFunctions_3_0_GlGetColorTableParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, float* params);
void QOpenGLFunctions_3_0_GlGetColorTable(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t format, uint32_t typeVal, void* table);
void QOpenGLFunctions_3_0_GlCopyColorTable(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t x, int32_t y, int32_t width);
void QOpenGLFunctions_3_0_GlColorTableParameteriv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const int32_t* params);
void QOpenGLFunctions_3_0_GlColorTableParameterfv(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t pname, const float* params);
void QOpenGLFunctions_3_0_GlColorTable(QOpenGLFunctions_3_0* self, uint32_t target, uint32_t internalformat, int32_t width, uint32_t format, uint32_t typeVal, const void* table);
void QOpenGLFunctions_3_0_GlMultTransposeMatrixd(QOpenGLFunctions_3_0* self, const double* m);
void QOpenGLFunctions_3_0_GlMultTransposeMatrixf(QOpenGLFunctions_3_0* self, const float* m);
void QOpenGLFunctions_3_0_GlLoadTransposeMatrixd(QOpenGLFunctions_3_0* self, const double* m);
void QOpenGLFunctions_3_0_GlLoadTransposeMatrixf(QOpenGLFunctions_3_0* self, const float* m);
void QOpenGLFunctions_3_0_GlMultiTexCoord4sv(QOpenGLFunctions_3_0* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord4s(QOpenGLFunctions_3_0* self, uint32_t target, int16_t s, int16_t t, int16_t r, int16_t q);
void QOpenGLFunctions_3_0_GlMultiTexCoord4iv(QOpenGLFunctions_3_0* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord4i(QOpenGLFunctions_3_0* self, uint32_t target, int32_t s, int32_t t, int32_t r, int32_t q);
void QOpenGLFunctions_3_0_GlMultiTexCoord4fv(QOpenGLFunctions_3_0* self, uint32_t target, const float* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord4f(QOpenGLFunctions_3_0* self, uint32_t target, float s, float t, float r, float q);
void QOpenGLFunctions_3_0_GlMultiTexCoord4dv(QOpenGLFunctions_3_0* self, uint32_t target, const double* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord4d(QOpenGLFunctions_3_0* self, uint32_t target, double s, double t, double r, double q);
void QOpenGLFunctions_3_0_GlMultiTexCoord3sv(QOpenGLFunctions_3_0* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord3s(QOpenGLFunctions_3_0* self, uint32_t target, int16_t s, int16_t t, int16_t r);
void QOpenGLFunctions_3_0_GlMultiTexCoord3iv(QOpenGLFunctions_3_0* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord3i(QOpenGLFunctions_3_0* self, uint32_t target, int32_t s, int32_t t, int32_t r);
void QOpenGLFunctions_3_0_GlMultiTexCoord3fv(QOpenGLFunctions_3_0* self, uint32_t target, const float* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord3f(QOpenGLFunctions_3_0* self, uint32_t target, float s, float t, float r);
void QOpenGLFunctions_3_0_GlMultiTexCoord3dv(QOpenGLFunctions_3_0* self, uint32_t target, const double* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord3d(QOpenGLFunctions_3_0* self, uint32_t target, double s, double t, double r);
void QOpenGLFunctions_3_0_GlMultiTexCoord2sv(QOpenGLFunctions_3_0* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord2s(QOpenGLFunctions_3_0* self, uint32_t target, int16_t s, int16_t t);
void QOpenGLFunctions_3_0_GlMultiTexCoord2iv(QOpenGLFunctions_3_0* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord2i(QOpenGLFunctions_3_0* self, uint32_t target, int32_t s, int32_t t);
void QOpenGLFunctions_3_0_GlMultiTexCoord2fv(QOpenGLFunctions_3_0* self, uint32_t target, const float* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord2f(QOpenGLFunctions_3_0* self, uint32_t target, float s, float t);
void QOpenGLFunctions_3_0_GlMultiTexCoord2dv(QOpenGLFunctions_3_0* self, uint32_t target, const double* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord2d(QOpenGLFunctions_3_0* self, uint32_t target, double s, double t);
void QOpenGLFunctions_3_0_GlMultiTexCoord1sv(QOpenGLFunctions_3_0* self, uint32_t target, const int16_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord1s(QOpenGLFunctions_3_0* self, uint32_t target, int16_t s);
void QOpenGLFunctions_3_0_GlMultiTexCoord1iv(QOpenGLFunctions_3_0* self, uint32_t target, const int32_t* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord1i(QOpenGLFunctions_3_0* self, uint32_t target, int32_t s);
void QOpenGLFunctions_3_0_GlMultiTexCoord1fv(QOpenGLFunctions_3_0* self, uint32_t target, const float* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord1f(QOpenGLFunctions_3_0* self, uint32_t target, float s);
void QOpenGLFunctions_3_0_GlMultiTexCoord1dv(QOpenGLFunctions_3_0* self, uint32_t target, const double* v);
void QOpenGLFunctions_3_0_GlMultiTexCoord1d(QOpenGLFunctions_3_0* self, uint32_t target, double s);
void QOpenGLFunctions_3_0_GlClientActiveTexture(QOpenGLFunctions_3_0* self, uint32_t texture);
void QOpenGLFunctions_3_0_GlWindowPos3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlWindowPos3s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_3_0_GlWindowPos3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlWindowPos3i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_3_0_GlWindowPos3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlWindowPos3f(QOpenGLFunctions_3_0* self, float x, float y, float z);
void QOpenGLFunctions_3_0_GlWindowPos3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlWindowPos3d(QOpenGLFunctions_3_0* self, double x, double y, double z);
void QOpenGLFunctions_3_0_GlWindowPos2sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlWindowPos2s(QOpenGLFunctions_3_0* self, int16_t x, int16_t y);
void QOpenGLFunctions_3_0_GlWindowPos2iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlWindowPos2i(QOpenGLFunctions_3_0* self, int32_t x, int32_t y);
void QOpenGLFunctions_3_0_GlWindowPos2fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlWindowPos2f(QOpenGLFunctions_3_0* self, float x, float y);
void QOpenGLFunctions_3_0_GlWindowPos2dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlWindowPos2d(QOpenGLFunctions_3_0* self, double x, double y);
void QOpenGLFunctions_3_0_GlSecondaryColorPointer(QOpenGLFunctions_3_0* self, int32_t size, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlSecondaryColor3usv(QOpenGLFunctions_3_0* self, const uint16_t* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3us(QOpenGLFunctions_3_0* self, uint16_t red, uint16_t green, uint16_t blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3uiv(QOpenGLFunctions_3_0* self, const uint32_t* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3ui(QOpenGLFunctions_3_0* self, uint32_t red, uint32_t green, uint32_t blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3ubv(QOpenGLFunctions_3_0* self, const uint8_t* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3ub(QOpenGLFunctions_3_0* self, uint8_t red, uint8_t green, uint8_t blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3sv(QOpenGLFunctions_3_0* self, const int16_t* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3s(QOpenGLFunctions_3_0* self, int16_t red, int16_t green, int16_t blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3iv(QOpenGLFunctions_3_0* self, const int32_t* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3i(QOpenGLFunctions_3_0* self, int32_t red, int32_t green, int32_t blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3fv(QOpenGLFunctions_3_0* self, const float* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3f(QOpenGLFunctions_3_0* self, float red, float green, float blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3dv(QOpenGLFunctions_3_0* self, const double* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3d(QOpenGLFunctions_3_0* self, double red, double green, double blue);
void QOpenGLFunctions_3_0_GlSecondaryColor3bv(QOpenGLFunctions_3_0* self, const signed char* v);
void QOpenGLFunctions_3_0_GlSecondaryColor3b(QOpenGLFunctions_3_0* self, signed char red, signed char green, signed char blue);
void QOpenGLFunctions_3_0_GlFogCoordPointer(QOpenGLFunctions_3_0* self, uint32_t typeVal, int32_t stride, const void* pointer);
void QOpenGLFunctions_3_0_GlFogCoorddv(QOpenGLFunctions_3_0* self, const double* coord);
void QOpenGLFunctions_3_0_GlFogCoordd(QOpenGLFunctions_3_0* self, double coord);
void QOpenGLFunctions_3_0_GlFogCoordfv(QOpenGLFunctions_3_0* self, const float* coord);
void QOpenGLFunctions_3_0_GlFogCoordf(QOpenGLFunctions_3_0* self, float coord);
void QOpenGLFunctions_3_0_GlVertexAttrib4usv(QOpenGLFunctions_3_0* self, uint32_t index, const uint16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4uiv(QOpenGLFunctions_3_0* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4ubv(QOpenGLFunctions_3_0* self, uint32_t index, const uint8_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4sv(QOpenGLFunctions_3_0* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4s(QOpenGLFunctions_3_0* self, uint32_t index, int16_t x, int16_t y, int16_t z, int16_t w);
void QOpenGLFunctions_3_0_GlVertexAttrib4iv(QOpenGLFunctions_3_0* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4fv(QOpenGLFunctions_3_0* self, uint32_t index, const float* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4f(QOpenGLFunctions_3_0* self, uint32_t index, float x, float y, float z, float w);
void QOpenGLFunctions_3_0_GlVertexAttrib4dv(QOpenGLFunctions_3_0* self, uint32_t index, const double* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4d(QOpenGLFunctions_3_0* self, uint32_t index, double x, double y, double z, double w);
void QOpenGLFunctions_3_0_GlVertexAttrib4bv(QOpenGLFunctions_3_0* self, uint32_t index, const signed char* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4Nusv(QOpenGLFunctions_3_0* self, uint32_t index, const uint16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4Nuiv(QOpenGLFunctions_3_0* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4Nubv(QOpenGLFunctions_3_0* self, uint32_t index, const uint8_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4Nub(QOpenGLFunctions_3_0* self, uint32_t index, uint8_t x, uint8_t y, uint8_t z, uint8_t w);
void QOpenGLFunctions_3_0_GlVertexAttrib4Nsv(QOpenGLFunctions_3_0* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4Niv(QOpenGLFunctions_3_0* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib4Nbv(QOpenGLFunctions_3_0* self, uint32_t index, const signed char* v);
void QOpenGLFunctions_3_0_GlVertexAttrib3sv(QOpenGLFunctions_3_0* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib3s(QOpenGLFunctions_3_0* self, uint32_t index, int16_t x, int16_t y, int16_t z);
void QOpenGLFunctions_3_0_GlVertexAttrib3fv(QOpenGLFunctions_3_0* self, uint32_t index, const float* v);
void QOpenGLFunctions_3_0_GlVertexAttrib3f(QOpenGLFunctions_3_0* self, uint32_t index, float x, float y, float z);
void QOpenGLFunctions_3_0_GlVertexAttrib3dv(QOpenGLFunctions_3_0* self, uint32_t index, const double* v);
void QOpenGLFunctions_3_0_GlVertexAttrib3d(QOpenGLFunctions_3_0* self, uint32_t index, double x, double y, double z);
void QOpenGLFunctions_3_0_GlVertexAttrib2sv(QOpenGLFunctions_3_0* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib2s(QOpenGLFunctions_3_0* self, uint32_t index, int16_t x, int16_t y);
void QOpenGLFunctions_3_0_GlVertexAttrib2fv(QOpenGLFunctions_3_0* self, uint32_t index, const float* v);
void QOpenGLFunctions_3_0_GlVertexAttrib2f(QOpenGLFunctions_3_0* self, uint32_t index, float x, float y);
void QOpenGLFunctions_3_0_GlVertexAttrib2dv(QOpenGLFunctions_3_0* self, uint32_t index, const double* v);
void QOpenGLFunctions_3_0_GlVertexAttrib2d(QOpenGLFunctions_3_0* self, uint32_t index, double x, double y);
void QOpenGLFunctions_3_0_GlVertexAttrib1sv(QOpenGLFunctions_3_0* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttrib1s(QOpenGLFunctions_3_0* self, uint32_t index, int16_t x);
void QOpenGLFunctions_3_0_GlVertexAttrib1fv(QOpenGLFunctions_3_0* self, uint32_t index, const float* v);
void QOpenGLFunctions_3_0_GlVertexAttrib1f(QOpenGLFunctions_3_0* self, uint32_t index, float x);
void QOpenGLFunctions_3_0_GlVertexAttrib1dv(QOpenGLFunctions_3_0* self, uint32_t index, const double* v);
void QOpenGLFunctions_3_0_GlVertexAttrib1d(QOpenGLFunctions_3_0* self, uint32_t index, double x);
void QOpenGLFunctions_3_0_GlVertexAttribI4usv(QOpenGLFunctions_3_0* self, uint32_t index, const uint16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI4ubv(QOpenGLFunctions_3_0* self, uint32_t index, const uint8_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI4sv(QOpenGLFunctions_3_0* self, uint32_t index, const int16_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI4bv(QOpenGLFunctions_3_0* self, uint32_t index, const signed char* v);
void QOpenGLFunctions_3_0_GlVertexAttribI4uiv(QOpenGLFunctions_3_0* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI3uiv(QOpenGLFunctions_3_0* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI2uiv(QOpenGLFunctions_3_0* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI1uiv(QOpenGLFunctions_3_0* self, uint32_t index, const uint32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI4iv(QOpenGLFunctions_3_0* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI3iv(QOpenGLFunctions_3_0* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI2iv(QOpenGLFunctions_3_0* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI1iv(QOpenGLFunctions_3_0* self, uint32_t index, const int32_t* v);
void QOpenGLFunctions_3_0_GlVertexAttribI4ui(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t x, uint32_t y, uint32_t z, uint32_t w);
void QOpenGLFunctions_3_0_GlVertexAttribI3ui(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t x, uint32_t y, uint32_t z);
void QOpenGLFunctions_3_0_GlVertexAttribI2ui(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t x, uint32_t y);
void QOpenGLFunctions_3_0_GlVertexAttribI1ui(QOpenGLFunctions_3_0* self, uint32_t index, uint32_t x);
void QOpenGLFunctions_3_0_GlVertexAttribI4i(QOpenGLFunctions_3_0* self, uint32_t index, int32_t x, int32_t y, int32_t z, int32_t w);
void QOpenGLFunctions_3_0_GlVertexAttribI3i(QOpenGLFunctions_3_0* self, uint32_t index, int32_t x, int32_t y, int32_t z);
void QOpenGLFunctions_3_0_GlVertexAttribI2i(QOpenGLFunctions_3_0* self, uint32_t index, int32_t x, int32_t y);
void QOpenGLFunctions_3_0_GlVertexAttribI1i(QOpenGLFunctions_3_0* self, uint32_t index, int32_t x);
void QOpenGLFunctions_3_0_OnInitializeOpenGLFunctions(QOpenGLFunctions_3_0* self, intptr_t slot);
bool QOpenGLFunctions_3_0_QBaseInitializeOpenGLFunctions(QOpenGLFunctions_3_0* self);
void QOpenGLFunctions_3_0_Delete(QOpenGLFunctions_3_0* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
