#pragma once
#ifndef QOPENGLVERSIONFUNCTIONS_H_C_LIB
#define QOPENGLVERSIONFUNCTIONS_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_0_CoreBackend__Functions)
typedef QOpenGLFunctions_1_0_CoreBackend::Functions QOpenGLFunctions_1_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_0_DeprecatedBackend::Functions QOpenGLFunctions_1_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_1_CoreBackend__Functions)
typedef QOpenGLFunctions_1_1_CoreBackend::Functions QOpenGLFunctions_1_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_1_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_1_DeprecatedBackend::Functions QOpenGLFunctions_1_1_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_2_CoreBackend__Functions)
typedef QOpenGLFunctions_1_2_CoreBackend::Functions QOpenGLFunctions_1_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_2_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_2_DeprecatedBackend::Functions QOpenGLFunctions_1_2_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_3_CoreBackend__Functions)
typedef QOpenGLFunctions_1_3_CoreBackend::Functions QOpenGLFunctions_1_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_3_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_3_DeprecatedBackend::Functions QOpenGLFunctions_1_3_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_4_CoreBackend__Functions)
typedef QOpenGLFunctions_1_4_CoreBackend::Functions QOpenGLFunctions_1_4_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_4_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_4_DeprecatedBackend::Functions QOpenGLFunctions_1_4_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_5_CoreBackend__Functions)
typedef QOpenGLFunctions_1_5_CoreBackend::Functions QOpenGLFunctions_1_5_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_0_CoreBackend__Functions)
typedef QOpenGLFunctions_2_0_CoreBackend::Functions QOpenGLFunctions_2_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_2_0_DeprecatedBackend::Functions QOpenGLFunctions_2_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_1_CoreBackend__Functions)
typedef QOpenGLFunctions_2_1_CoreBackend::Functions QOpenGLFunctions_2_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_0_CoreBackend__Functions)
typedef QOpenGLFunctions_3_0_CoreBackend::Functions QOpenGLFunctions_3_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_3_0_DeprecatedBackend::Functions QOpenGLFunctions_3_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_1_CoreBackend__Functions)
typedef QOpenGLFunctions_3_1_CoreBackend::Functions QOpenGLFunctions_3_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_2_CoreBackend__Functions)
typedef QOpenGLFunctions_3_2_CoreBackend::Functions QOpenGLFunctions_3_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_3_CoreBackend__Functions)
typedef QOpenGLFunctions_3_3_CoreBackend::Functions QOpenGLFunctions_3_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_3_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_3_3_DeprecatedBackend::Functions QOpenGLFunctions_3_3_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_0_CoreBackend__Functions)
typedef QOpenGLFunctions_4_0_CoreBackend::Functions QOpenGLFunctions_4_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_1_CoreBackend__Functions)
typedef QOpenGLFunctions_4_1_CoreBackend::Functions QOpenGLFunctions_4_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_2_CoreBackend__Functions)
typedef QOpenGLFunctions_4_2_CoreBackend::Functions QOpenGLFunctions_4_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_3_CoreBackend__Functions)
typedef QOpenGLFunctions_4_3_CoreBackend::Functions QOpenGLFunctions_4_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_4_CoreBackend__Functions)
typedef QOpenGLFunctions_4_4_CoreBackend::Functions QOpenGLFunctions_4_4_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_5_CoreBackend__Functions)
typedef QOpenGLFunctions_4_5_CoreBackend::Functions QOpenGLFunctions_4_5_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_5_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_4_5_DeprecatedBackend::Functions QOpenGLFunctions_4_5_DeprecatedBackend__Functions;
#endif
#else
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QAtomicInt QAtomicInt;
typedef struct QOpenGLContext QOpenGLContext;
typedef struct QOpenGLFunctions_1_0_CoreBackend QOpenGLFunctions_1_0_CoreBackend;
typedef struct QOpenGLFunctions_1_0_CoreBackend__Functions QOpenGLFunctions_1_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_0_DeprecatedBackend QOpenGLFunctions_1_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_0_DeprecatedBackend__Functions QOpenGLFunctions_1_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_1_CoreBackend QOpenGLFunctions_1_1_CoreBackend;
typedef struct QOpenGLFunctions_1_1_CoreBackend__Functions QOpenGLFunctions_1_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_1_DeprecatedBackend QOpenGLFunctions_1_1_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_1_DeprecatedBackend__Functions QOpenGLFunctions_1_1_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_2_CoreBackend QOpenGLFunctions_1_2_CoreBackend;
typedef struct QOpenGLFunctions_1_2_CoreBackend__Functions QOpenGLFunctions_1_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_2_DeprecatedBackend QOpenGLFunctions_1_2_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_2_DeprecatedBackend__Functions QOpenGLFunctions_1_2_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_3_CoreBackend QOpenGLFunctions_1_3_CoreBackend;
typedef struct QOpenGLFunctions_1_3_CoreBackend__Functions QOpenGLFunctions_1_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_3_DeprecatedBackend QOpenGLFunctions_1_3_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_3_DeprecatedBackend__Functions QOpenGLFunctions_1_3_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_4_CoreBackend QOpenGLFunctions_1_4_CoreBackend;
typedef struct QOpenGLFunctions_1_4_CoreBackend__Functions QOpenGLFunctions_1_4_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_4_DeprecatedBackend QOpenGLFunctions_1_4_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_4_DeprecatedBackend__Functions QOpenGLFunctions_1_4_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_5_CoreBackend QOpenGLFunctions_1_5_CoreBackend;
typedef struct QOpenGLFunctions_1_5_CoreBackend__Functions QOpenGLFunctions_1_5_CoreBackend__Functions;
typedef struct QOpenGLFunctions_2_0_CoreBackend QOpenGLFunctions_2_0_CoreBackend;
typedef struct QOpenGLFunctions_2_0_CoreBackend__Functions QOpenGLFunctions_2_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_2_0_DeprecatedBackend QOpenGLFunctions_2_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_2_0_DeprecatedBackend__Functions QOpenGLFunctions_2_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_2_1_CoreBackend QOpenGLFunctions_2_1_CoreBackend;
typedef struct QOpenGLFunctions_2_1_CoreBackend__Functions QOpenGLFunctions_2_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_0_CoreBackend QOpenGLFunctions_3_0_CoreBackend;
typedef struct QOpenGLFunctions_3_0_CoreBackend__Functions QOpenGLFunctions_3_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_0_DeprecatedBackend QOpenGLFunctions_3_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_3_0_DeprecatedBackend__Functions QOpenGLFunctions_3_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_3_1_CoreBackend QOpenGLFunctions_3_1_CoreBackend;
typedef struct QOpenGLFunctions_3_1_CoreBackend__Functions QOpenGLFunctions_3_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_2_CoreBackend QOpenGLFunctions_3_2_CoreBackend;
typedef struct QOpenGLFunctions_3_2_CoreBackend__Functions QOpenGLFunctions_3_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_3_CoreBackend QOpenGLFunctions_3_3_CoreBackend;
typedef struct QOpenGLFunctions_3_3_CoreBackend__Functions QOpenGLFunctions_3_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_3_DeprecatedBackend QOpenGLFunctions_3_3_DeprecatedBackend;
typedef struct QOpenGLFunctions_3_3_DeprecatedBackend__Functions QOpenGLFunctions_3_3_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_4_0_CoreBackend QOpenGLFunctions_4_0_CoreBackend;
typedef struct QOpenGLFunctions_4_0_CoreBackend__Functions QOpenGLFunctions_4_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_1_CoreBackend QOpenGLFunctions_4_1_CoreBackend;
typedef struct QOpenGLFunctions_4_1_CoreBackend__Functions QOpenGLFunctions_4_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_2_CoreBackend QOpenGLFunctions_4_2_CoreBackend;
typedef struct QOpenGLFunctions_4_2_CoreBackend__Functions QOpenGLFunctions_4_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_3_CoreBackend QOpenGLFunctions_4_3_CoreBackend;
typedef struct QOpenGLFunctions_4_3_CoreBackend__Functions QOpenGLFunctions_4_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_4_CoreBackend QOpenGLFunctions_4_4_CoreBackend;
typedef struct QOpenGLFunctions_4_4_CoreBackend__Functions QOpenGLFunctions_4_4_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_5_CoreBackend QOpenGLFunctions_4_5_CoreBackend;
typedef struct QOpenGLFunctions_4_5_CoreBackend__Functions QOpenGLFunctions_4_5_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_5_DeprecatedBackend QOpenGLFunctions_4_5_DeprecatedBackend;
typedef struct QOpenGLFunctions_4_5_DeprecatedBackend__Functions QOpenGLFunctions_4_5_DeprecatedBackend__Functions;
typedef struct QOpenGLVersionFunctionsBackend QOpenGLVersionFunctionsBackend;
typedef struct QOpenGLVersionFunctionsStorage QOpenGLVersionFunctionsStorage;
typedef struct QOpenGLVersionStatus QOpenGLVersionStatus;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QOpenGLVersionStatus* QOpenGLVersionStatus_new(const QOpenGLVersionStatus* other);
QOpenGLVersionStatus* QOpenGLVersionStatus_new2(QOpenGLVersionStatus* other);
QOpenGLVersionStatus* QOpenGLVersionStatus_new3();
QOpenGLVersionStatus* QOpenGLVersionStatus_new4(int majorVersion, int minorVersion, int functionStatus);
QOpenGLVersionStatus* QOpenGLVersionStatus_new5(const QOpenGLVersionStatus* param1);
libqt_pair QOpenGLVersionStatus_Version(const QOpenGLVersionStatus* self);
void QOpenGLVersionStatus_SetVersion(QOpenGLVersionStatus* self, libqt_pair version);
int QOpenGLVersionStatus_Status(const QOpenGLVersionStatus* self);
void QOpenGLVersionStatus_SetStatus(QOpenGLVersionStatus* self, int status);
void QOpenGLVersionStatus_OperatorAssign(QOpenGLVersionStatus* self, const QOpenGLVersionStatus* param1);
void QOpenGLVersionStatus_Delete(QOpenGLVersionStatus* self);

QOpenGLVersionFunctionsBackend* QOpenGLVersionFunctionsBackend_new(QOpenGLContext* ctx);
QOpenGLVersionFunctionsBackend* QOpenGLVersionFunctionsBackend_new2(const QOpenGLVersionFunctionsBackend* param1);
QOpenGLContext* QOpenGLVersionFunctionsBackend_Context(const QOpenGLVersionFunctionsBackend* self);
void QOpenGLVersionFunctionsBackend_SetContext(QOpenGLVersionFunctionsBackend* self, QOpenGLContext* context);
QAtomicInt* QOpenGLVersionFunctionsBackend_Refs(const QOpenGLVersionFunctionsBackend* self);
void QOpenGLVersionFunctionsBackend_SetRefs(QOpenGLVersionFunctionsBackend* self, QAtomicInt* refs);
void QOpenGLVersionFunctionsBackend_Delete(QOpenGLVersionFunctionsBackend* self);

QOpenGLVersionFunctionsStorage* QOpenGLVersionFunctionsStorage_new(const QOpenGLVersionFunctionsStorage* other);
QOpenGLVersionFunctionsStorage* QOpenGLVersionFunctionsStorage_new2();
void QOpenGLVersionFunctionsStorage_CopyAssign(QOpenGLVersionFunctionsStorage* self, QOpenGLVersionFunctionsStorage* other);
QOpenGLVersionFunctionsBackend* QOpenGLVersionFunctionsStorage_Backend(QOpenGLVersionFunctionsStorage* self, QOpenGLContext* context, int v);
QOpenGLVersionFunctionsBackend** QOpenGLVersionFunctionsStorage_Backends(const QOpenGLVersionFunctionsStorage* self);
void QOpenGLVersionFunctionsStorage_SetBackends(QOpenGLVersionFunctionsStorage* self, QOpenGLVersionFunctionsBackend** backends);
void QOpenGLVersionFunctionsStorage_Delete(QOpenGLVersionFunctionsStorage* self);

bool QAbstractOpenGLFunctions_InitializeOpenGLFunctions(QAbstractOpenGLFunctions* self);
QAbstractOpenGLFunctionsPrivate* QAbstractOpenGLFunctions_DFunc(QAbstractOpenGLFunctions* self);
const QAbstractOpenGLFunctionsPrivate* QAbstractOpenGLFunctions_DFunc2(const QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_OnInitializeOpenGLFunctions(QAbstractOpenGLFunctions* self, intptr_t slot);
bool QAbstractOpenGLFunctions_QBaseInitializeOpenGLFunctions(QAbstractOpenGLFunctions* self);
bool QAbstractOpenGLFunctions_IsInitialized(const QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_OnIsInitialized(const QAbstractOpenGLFunctions* self, intptr_t slot);
bool QAbstractOpenGLFunctions_QBaseIsInitialized(const QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_SetOwningContext(QAbstractOpenGLFunctions* self, const QOpenGLContext* context);
void QAbstractOpenGLFunctions_OnSetOwningContext(QAbstractOpenGLFunctions* self, intptr_t slot);
void QAbstractOpenGLFunctions_QBaseSetOwningContext(QAbstractOpenGLFunctions* self, const QOpenGLContext* context);
QOpenGLContext* QAbstractOpenGLFunctions_OwningContext(const QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_OnOwningContext(const QAbstractOpenGLFunctions* self, intptr_t slot);
QOpenGLContext* QAbstractOpenGLFunctions_QBaseOwningContext(const QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_Delete(QAbstractOpenGLFunctions* self);

QOpenGLFunctions_1_0_CoreBackend* QOpenGLFunctions_1_0_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_0_CoreBackend_VersionStatus();
void QOpenGLFunctions_1_0_CoreBackend_Delete(QOpenGLFunctions_1_0_CoreBackend* self);

QOpenGLFunctions_1_1_CoreBackend* QOpenGLFunctions_1_1_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_1_CoreBackend_VersionStatus();
void QOpenGLFunctions_1_1_CoreBackend_Delete(QOpenGLFunctions_1_1_CoreBackend* self);

QOpenGLFunctions_1_2_CoreBackend* QOpenGLFunctions_1_2_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_2_CoreBackend_VersionStatus();
void QOpenGLFunctions_1_2_CoreBackend_Delete(QOpenGLFunctions_1_2_CoreBackend* self);

QOpenGLFunctions_1_3_CoreBackend* QOpenGLFunctions_1_3_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_3_CoreBackend_VersionStatus();
void QOpenGLFunctions_1_3_CoreBackend_Delete(QOpenGLFunctions_1_3_CoreBackend* self);

QOpenGLFunctions_1_4_CoreBackend* QOpenGLFunctions_1_4_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_4_CoreBackend_VersionStatus();
void QOpenGLFunctions_1_4_CoreBackend_Delete(QOpenGLFunctions_1_4_CoreBackend* self);

QOpenGLFunctions_1_5_CoreBackend* QOpenGLFunctions_1_5_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_5_CoreBackend_VersionStatus();
void QOpenGLFunctions_1_5_CoreBackend_Delete(QOpenGLFunctions_1_5_CoreBackend* self);

QOpenGLFunctions_2_0_CoreBackend* QOpenGLFunctions_2_0_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_2_0_CoreBackend_VersionStatus();
void QOpenGLFunctions_2_0_CoreBackend_Delete(QOpenGLFunctions_2_0_CoreBackend* self);

QOpenGLFunctions_2_1_CoreBackend* QOpenGLFunctions_2_1_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_2_1_CoreBackend_VersionStatus();
void QOpenGLFunctions_2_1_CoreBackend_Delete(QOpenGLFunctions_2_1_CoreBackend* self);

QOpenGLFunctions_3_0_CoreBackend* QOpenGLFunctions_3_0_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_3_0_CoreBackend_VersionStatus();
void QOpenGLFunctions_3_0_CoreBackend_Delete(QOpenGLFunctions_3_0_CoreBackend* self);

QOpenGLFunctions_3_1_CoreBackend* QOpenGLFunctions_3_1_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_3_1_CoreBackend_VersionStatus();
void QOpenGLFunctions_3_1_CoreBackend_Delete(QOpenGLFunctions_3_1_CoreBackend* self);

QOpenGLFunctions_3_2_CoreBackend* QOpenGLFunctions_3_2_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_3_2_CoreBackend_VersionStatus();
void QOpenGLFunctions_3_2_CoreBackend_Delete(QOpenGLFunctions_3_2_CoreBackend* self);

QOpenGLFunctions_3_3_CoreBackend* QOpenGLFunctions_3_3_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_3_3_CoreBackend_VersionStatus();
void QOpenGLFunctions_3_3_CoreBackend_Delete(QOpenGLFunctions_3_3_CoreBackend* self);

QOpenGLFunctions_4_0_CoreBackend* QOpenGLFunctions_4_0_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_0_CoreBackend_VersionStatus();
void QOpenGLFunctions_4_0_CoreBackend_Delete(QOpenGLFunctions_4_0_CoreBackend* self);

QOpenGLFunctions_4_1_CoreBackend* QOpenGLFunctions_4_1_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_1_CoreBackend_VersionStatus();
void QOpenGLFunctions_4_1_CoreBackend_Delete(QOpenGLFunctions_4_1_CoreBackend* self);

QOpenGLFunctions_4_2_CoreBackend* QOpenGLFunctions_4_2_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_2_CoreBackend_VersionStatus();
void QOpenGLFunctions_4_2_CoreBackend_Delete(QOpenGLFunctions_4_2_CoreBackend* self);

QOpenGLFunctions_4_3_CoreBackend* QOpenGLFunctions_4_3_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_3_CoreBackend_VersionStatus();
void QOpenGLFunctions_4_3_CoreBackend_Delete(QOpenGLFunctions_4_3_CoreBackend* self);

QOpenGLFunctions_4_4_CoreBackend* QOpenGLFunctions_4_4_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_4_CoreBackend_VersionStatus();
void QOpenGLFunctions_4_4_CoreBackend_Delete(QOpenGLFunctions_4_4_CoreBackend* self);

QOpenGLFunctions_4_5_CoreBackend* QOpenGLFunctions_4_5_CoreBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_5_CoreBackend_VersionStatus();
void QOpenGLFunctions_4_5_CoreBackend_Delete(QOpenGLFunctions_4_5_CoreBackend* self);

QOpenGLFunctions_1_0_DeprecatedBackend* QOpenGLFunctions_1_0_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_0_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_1_0_DeprecatedBackend_Delete(QOpenGLFunctions_1_0_DeprecatedBackend* self);

QOpenGLFunctions_1_1_DeprecatedBackend* QOpenGLFunctions_1_1_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_1_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_1_1_DeprecatedBackend_Delete(QOpenGLFunctions_1_1_DeprecatedBackend* self);

QOpenGLFunctions_1_2_DeprecatedBackend* QOpenGLFunctions_1_2_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_2_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_1_2_DeprecatedBackend_Delete(QOpenGLFunctions_1_2_DeprecatedBackend* self);

QOpenGLFunctions_1_3_DeprecatedBackend* QOpenGLFunctions_1_3_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_3_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_1_3_DeprecatedBackend_Delete(QOpenGLFunctions_1_3_DeprecatedBackend* self);

QOpenGLFunctions_1_4_DeprecatedBackend* QOpenGLFunctions_1_4_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_1_4_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_1_4_DeprecatedBackend_Delete(QOpenGLFunctions_1_4_DeprecatedBackend* self);

QOpenGLFunctions_2_0_DeprecatedBackend* QOpenGLFunctions_2_0_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_2_0_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_2_0_DeprecatedBackend_Delete(QOpenGLFunctions_2_0_DeprecatedBackend* self);

QOpenGLFunctions_3_0_DeprecatedBackend* QOpenGLFunctions_3_0_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_3_0_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_3_0_DeprecatedBackend_Delete(QOpenGLFunctions_3_0_DeprecatedBackend* self);

QOpenGLFunctions_3_3_DeprecatedBackend* QOpenGLFunctions_3_3_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_3_3_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_3_3_DeprecatedBackend_Delete(QOpenGLFunctions_3_3_DeprecatedBackend* self);

QOpenGLFunctions_4_5_DeprecatedBackend* QOpenGLFunctions_4_5_DeprecatedBackend_new(QOpenGLContext* c);
int QOpenGLFunctions_4_5_DeprecatedBackend_VersionStatus();
void QOpenGLFunctions_4_5_DeprecatedBackend_Delete(QOpenGLFunctions_4_5_DeprecatedBackend* self);




























#ifdef __cplusplus
} /* extern C */
#endif

#endif
