#pragma once
#ifndef SRCC_LIBQTABLEWIDGET_H
#define SRCC_LIBQTABLEWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDataStream QDataStream;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTableView QTableView;
typedef struct QTableWidget QTableWidget;
typedef struct QTableWidgetItem QTableWidgetItem;
typedef struct QTableWidgetSelectionRange QTableWidgetSelectionRange;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QTableWidgetSelectionRange* QTableWidgetSelectionRange_new(const QTableWidgetSelectionRange* other);
QTableWidgetSelectionRange* QTableWidgetSelectionRange_new2(QTableWidgetSelectionRange* other);
QTableWidgetSelectionRange* QTableWidgetSelectionRange_new3();
QTableWidgetSelectionRange* QTableWidgetSelectionRange_new4(int top, int left, int bottom, int right);
void QTableWidgetSelectionRange_CopyAssign(QTableWidgetSelectionRange* self, QTableWidgetSelectionRange* other);
void QTableWidgetSelectionRange_MoveAssign(QTableWidgetSelectionRange* self, QTableWidgetSelectionRange* other);
int QTableWidgetSelectionRange_TopRow(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_BottomRow(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_LeftColumn(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_RightColumn(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_RowCount(const QTableWidgetSelectionRange* self);
int QTableWidgetSelectionRange_ColumnCount(const QTableWidgetSelectionRange* self);
void QTableWidgetSelectionRange_Delete(QTableWidgetSelectionRange* self);

QTableWidgetItem* QTableWidgetItem_new();
QTableWidgetItem* QTableWidgetItem_new2(const libqt_string text);
QTableWidgetItem* QTableWidgetItem_new3(const QIcon* icon, const libqt_string text);
QTableWidgetItem* QTableWidgetItem_new4(const QTableWidgetItem* other);
QTableWidgetItem* QTableWidgetItem_new5(int typeVal);
QTableWidgetItem* QTableWidgetItem_new6(const libqt_string text, int typeVal);
QTableWidgetItem* QTableWidgetItem_new7(const QIcon* icon, const libqt_string text, int typeVal);
QTableWidgetItem* QTableWidgetItem_Clone(const QTableWidgetItem* self);
QTableWidget* QTableWidgetItem_TableWidget(const QTableWidgetItem* self);
int QTableWidgetItem_Row(const QTableWidgetItem* self);
int QTableWidgetItem_Column(const QTableWidgetItem* self);
void QTableWidgetItem_SetSelected(QTableWidgetItem* self, bool selectVal);
bool QTableWidgetItem_IsSelected(const QTableWidgetItem* self);
int QTableWidgetItem_Flags(const QTableWidgetItem* self);
void QTableWidgetItem_SetFlags(QTableWidgetItem* self, int flags);
libqt_string QTableWidgetItem_Text(const QTableWidgetItem* self);
void QTableWidgetItem_SetText(QTableWidgetItem* self, const libqt_string text);
QIcon* QTableWidgetItem_Icon(const QTableWidgetItem* self);
void QTableWidgetItem_SetIcon(QTableWidgetItem* self, const QIcon* icon);
libqt_string QTableWidgetItem_StatusTip(const QTableWidgetItem* self);
void QTableWidgetItem_SetStatusTip(QTableWidgetItem* self, const libqt_string statusTip);
libqt_string QTableWidgetItem_ToolTip(const QTableWidgetItem* self);
void QTableWidgetItem_SetToolTip(QTableWidgetItem* self, const libqt_string toolTip);
libqt_string QTableWidgetItem_WhatsThis(const QTableWidgetItem* self);
void QTableWidgetItem_SetWhatsThis(QTableWidgetItem* self, const libqt_string whatsThis);
QFont* QTableWidgetItem_Font(const QTableWidgetItem* self);
void QTableWidgetItem_SetFont(QTableWidgetItem* self, const QFont* font);
int QTableWidgetItem_TextAlignment(const QTableWidgetItem* self);
void QTableWidgetItem_SetTextAlignment(QTableWidgetItem* self, int alignment);
void QTableWidgetItem_SetTextAlignment2(QTableWidgetItem* self, int alignment);
void QTableWidgetItem_SetTextAlignment3(QTableWidgetItem* self, int alignment);
QBrush* QTableWidgetItem_Background(const QTableWidgetItem* self);
void QTableWidgetItem_SetBackground(QTableWidgetItem* self, const QBrush* brush);
QBrush* QTableWidgetItem_Foreground(const QTableWidgetItem* self);
void QTableWidgetItem_SetForeground(QTableWidgetItem* self, const QBrush* brush);
int QTableWidgetItem_CheckState(const QTableWidgetItem* self);
void QTableWidgetItem_SetCheckState(QTableWidgetItem* self, int state);
QSize* QTableWidgetItem_SizeHint(const QTableWidgetItem* self);
void QTableWidgetItem_SetSizeHint(QTableWidgetItem* self, const QSize* size);
QVariant* QTableWidgetItem_Data(const QTableWidgetItem* self, int role);
void QTableWidgetItem_SetData(QTableWidgetItem* self, int role, const QVariant* value);
bool QTableWidgetItem_OperatorLesser(const QTableWidgetItem* self, const QTableWidgetItem* other);
void QTableWidgetItem_Read(QTableWidgetItem* self, QDataStream* in);
void QTableWidgetItem_Write(const QTableWidgetItem* self, QDataStream* out);
void QTableWidgetItem_OperatorAssign(QTableWidgetItem* self, const QTableWidgetItem* other);
int QTableWidgetItem_Type(const QTableWidgetItem* self);
void QTableWidgetItem_OnClone(const QTableWidgetItem* self, intptr_t slot);
QTableWidgetItem* QTableWidgetItem_QBaseClone(const QTableWidgetItem* self);
void QTableWidgetItem_OnData(const QTableWidgetItem* self, intptr_t slot);
QVariant* QTableWidgetItem_QBaseData(const QTableWidgetItem* self, int role);
void QTableWidgetItem_OnSetData(QTableWidgetItem* self, intptr_t slot);
void QTableWidgetItem_QBaseSetData(QTableWidgetItem* self, int role, const QVariant* value);
void QTableWidgetItem_OnOperatorLesser(const QTableWidgetItem* self, intptr_t slot);
bool QTableWidgetItem_QBaseOperatorLesser(const QTableWidgetItem* self, const QTableWidgetItem* other);
void QTableWidgetItem_OnRead(QTableWidgetItem* self, intptr_t slot);
void QTableWidgetItem_QBaseRead(QTableWidgetItem* self, QDataStream* in);
void QTableWidgetItem_OnWrite(const QTableWidgetItem* self, intptr_t slot);
void QTableWidgetItem_QBaseWrite(const QTableWidgetItem* self, QDataStream* out);
void QTableWidgetItem_Delete(QTableWidgetItem* self);

QTableWidget* QTableWidget_new(QWidget* parent);
QTableWidget* QTableWidget_new2();
QTableWidget* QTableWidget_new3(int rows, int columns);
QTableWidget* QTableWidget_new4(int rows, int columns, QWidget* parent);
QMetaObject* QTableWidget_MetaObject(const QTableWidget* self);
void* QTableWidget_Metacast(QTableWidget* self, const char* param1);
int QTableWidget_Metacall(QTableWidget* self, int param1, int param2, void** param3);
libqt_string QTableWidget_Tr(const char* s);
void QTableWidget_SetRowCount(QTableWidget* self, int rows);
int QTableWidget_RowCount(const QTableWidget* self);
void QTableWidget_SetColumnCount(QTableWidget* self, int columns);
int QTableWidget_ColumnCount(const QTableWidget* self);
int QTableWidget_Row(const QTableWidget* self, const QTableWidgetItem* item);
int QTableWidget_Column(const QTableWidget* self, const QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_Item(const QTableWidget* self, int row, int column);
void QTableWidget_SetItem(QTableWidget* self, int row, int column, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_TakeItem(QTableWidget* self, int row, int column);
libqt_list /* of QTableWidgetItem* */ QTableWidget_Items(const QTableWidget* self, const QMimeData* data);
QModelIndex* QTableWidget_IndexFromItem(const QTableWidget* self, const QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_ItemFromIndex(const QTableWidget* self, const QModelIndex* index);
QTableWidgetItem* QTableWidget_VerticalHeaderItem(const QTableWidget* self, int row);
void QTableWidget_SetVerticalHeaderItem(QTableWidget* self, int row, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_TakeVerticalHeaderItem(QTableWidget* self, int row);
QTableWidgetItem* QTableWidget_HorizontalHeaderItem(const QTableWidget* self, int column);
void QTableWidget_SetHorizontalHeaderItem(QTableWidget* self, int column, QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_TakeHorizontalHeaderItem(QTableWidget* self, int column);
void QTableWidget_SetVerticalHeaderLabels(QTableWidget* self, const libqt_list /* of libqt_string */ labels);
void QTableWidget_SetHorizontalHeaderLabels(QTableWidget* self, const libqt_list /* of libqt_string */ labels);
int QTableWidget_CurrentRow(const QTableWidget* self);
int QTableWidget_CurrentColumn(const QTableWidget* self);
QTableWidgetItem* QTableWidget_CurrentItem(const QTableWidget* self);
void QTableWidget_SetCurrentItem(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_SetCurrentItem2(QTableWidget* self, QTableWidgetItem* item, int command);
void QTableWidget_SetCurrentCell(QTableWidget* self, int row, int column);
void QTableWidget_SetCurrentCell2(QTableWidget* self, int row, int column, int command);
void QTableWidget_SortItems(QTableWidget* self, int column);
void QTableWidget_SetSortingEnabled(QTableWidget* self, bool enable);
bool QTableWidget_IsSortingEnabled(const QTableWidget* self);
void QTableWidget_EditItem(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_OpenPersistentEditor(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_ClosePersistentEditor(QTableWidget* self, QTableWidgetItem* item);
bool QTableWidget_IsPersistentEditorOpen(const QTableWidget* self, QTableWidgetItem* item);
QWidget* QTableWidget_CellWidget(const QTableWidget* self, int row, int column);
void QTableWidget_SetCellWidget(QTableWidget* self, int row, int column, QWidget* widget);
void QTableWidget_RemoveCellWidget(QTableWidget* self, int row, int column);
void QTableWidget_SetRangeSelected(QTableWidget* self, const QTableWidgetSelectionRange* range, bool selectVal);
libqt_list /* of QTableWidgetSelectionRange* */ QTableWidget_SelectedRanges(const QTableWidget* self);
libqt_list /* of QTableWidgetItem* */ QTableWidget_SelectedItems(const QTableWidget* self);
libqt_list /* of QTableWidgetItem* */ QTableWidget_FindItems(const QTableWidget* self, const libqt_string text, int flags);
int QTableWidget_VisualRow(const QTableWidget* self, int logicalRow);
int QTableWidget_VisualColumn(const QTableWidget* self, int logicalColumn);
QTableWidgetItem* QTableWidget_ItemAt(const QTableWidget* self, const QPoint* p);
QTableWidgetItem* QTableWidget_ItemAt2(const QTableWidget* self, int x, int y);
QRect* QTableWidget_VisualItemRect(const QTableWidget* self, const QTableWidgetItem* item);
QTableWidgetItem* QTableWidget_ItemPrototype(const QTableWidget* self);
void QTableWidget_SetItemPrototype(QTableWidget* self, const QTableWidgetItem* item);
void QTableWidget_ScrollToItem(QTableWidget* self, const QTableWidgetItem* item);
void QTableWidget_InsertRow(QTableWidget* self, int row);
void QTableWidget_InsertColumn(QTableWidget* self, int column);
void QTableWidget_RemoveRow(QTableWidget* self, int row);
void QTableWidget_RemoveColumn(QTableWidget* self, int column);
void QTableWidget_Clear(QTableWidget* self);
void QTableWidget_ClearContents(QTableWidget* self);
void QTableWidget_ItemPressed(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_Connect_ItemPressed(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemClicked(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_Connect_ItemClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemDoubleClicked(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_Connect_ItemDoubleClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemActivated(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_Connect_ItemActivated(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemEntered(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_Connect_ItemEntered(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemChanged(QTableWidget* self, QTableWidgetItem* item);
void QTableWidget_Connect_ItemChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_CurrentItemChanged(QTableWidget* self, QTableWidgetItem* current, QTableWidgetItem* previous);
void QTableWidget_Connect_CurrentItemChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_ItemSelectionChanged(QTableWidget* self);
void QTableWidget_Connect_ItemSelectionChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_CellPressed(QTableWidget* self, int row, int column);
void QTableWidget_Connect_CellPressed(QTableWidget* self, intptr_t slot);
void QTableWidget_CellClicked(QTableWidget* self, int row, int column);
void QTableWidget_Connect_CellClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_CellDoubleClicked(QTableWidget* self, int row, int column);
void QTableWidget_Connect_CellDoubleClicked(QTableWidget* self, intptr_t slot);
void QTableWidget_CellActivated(QTableWidget* self, int row, int column);
void QTableWidget_Connect_CellActivated(QTableWidget* self, intptr_t slot);
void QTableWidget_CellEntered(QTableWidget* self, int row, int column);
void QTableWidget_Connect_CellEntered(QTableWidget* self, intptr_t slot);
void QTableWidget_CellChanged(QTableWidget* self, int row, int column);
void QTableWidget_Connect_CellChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_CurrentCellChanged(QTableWidget* self, int currentRow, int currentColumn, int previousRow, int previousColumn);
void QTableWidget_Connect_CurrentCellChanged(QTableWidget* self, intptr_t slot);
bool QTableWidget_Event(QTableWidget* self, QEvent* e);
libqt_list /* of libqt_string */ QTableWidget_MimeTypes(const QTableWidget* self);
QMimeData* QTableWidget_MimeData(const QTableWidget* self, const libqt_list /* of QTableWidgetItem* */ items);
bool QTableWidget_DropMimeData(QTableWidget* self, int row, int column, const QMimeData* data, int action);
int QTableWidget_SupportedDropActions(const QTableWidget* self);
void QTableWidget_DropEvent(QTableWidget* self, QDropEvent* event);
libqt_string QTableWidget_Tr2(const char* s, const char* c);
libqt_string QTableWidget_Tr3(const char* s, const char* c, int n);
void QTableWidget_SortItems2(QTableWidget* self, int column, int order);
void QTableWidget_ScrollToItem2(QTableWidget* self, const QTableWidgetItem* item, int hint);
void QTableWidget_OnMetacall(QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseMetacall(QTableWidget* self, int param1, int param2, void** param3);
void QTableWidget_OnEvent(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseEvent(QTableWidget* self, QEvent* e);
void QTableWidget_OnMimeTypes(const QTableWidget* self, intptr_t slot);
libqt_list /* of libqt_string */ QTableWidget_QBaseMimeTypes(const QTableWidget* self);
void QTableWidget_OnMimeData(const QTableWidget* self, intptr_t slot);
QMimeData* QTableWidget_QBaseMimeData(const QTableWidget* self, const libqt_list /* of QTableWidgetItem* */ items);
void QTableWidget_OnDropMimeData(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseDropMimeData(QTableWidget* self, int row, int column, const QMimeData* data, int action);
void QTableWidget_OnSupportedDropActions(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseSupportedDropActions(const QTableWidget* self);
void QTableWidget_OnDropEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDropEvent(QTableWidget* self, QDropEvent* event);
void QTableWidget_SetRootIndex(QTableWidget* self, const QModelIndex* index);
void QTableWidget_OnSetRootIndex(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetRootIndex(QTableWidget* self, const QModelIndex* index);
void QTableWidget_SetSelectionModel(QTableWidget* self, QItemSelectionModel* selectionModel);
void QTableWidget_OnSetSelectionModel(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetSelectionModel(QTableWidget* self, QItemSelectionModel* selectionModel);
void QTableWidget_DoItemsLayout(QTableWidget* self);
void QTableWidget_OnDoItemsLayout(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDoItemsLayout(QTableWidget* self);
QRect* QTableWidget_VisualRect(const QTableWidget* self, const QModelIndex* index);
void QTableWidget_OnVisualRect(const QTableWidget* self, intptr_t slot);
QRect* QTableWidget_QBaseVisualRect(const QTableWidget* self, const QModelIndex* index);
void QTableWidget_ScrollTo(QTableWidget* self, const QModelIndex* index, int hint);
void QTableWidget_OnScrollTo(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseScrollTo(QTableWidget* self, const QModelIndex* index, int hint);
QModelIndex* QTableWidget_IndexAt(const QTableWidget* self, const QPoint* p);
void QTableWidget_OnIndexAt(const QTableWidget* self, intptr_t slot);
QModelIndex* QTableWidget_QBaseIndexAt(const QTableWidget* self, const QPoint* p);
void QTableWidget_ScrollContentsBy(QTableWidget* self, int dx, int dy);
void QTableWidget_OnScrollContentsBy(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseScrollContentsBy(QTableWidget* self, int dx, int dy);
void QTableWidget_InitViewItemOption(const QTableWidget* self, QStyleOptionViewItem* option);
void QTableWidget_OnInitViewItemOption(const QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseInitViewItemOption(const QTableWidget* self, QStyleOptionViewItem* option);
void QTableWidget_PaintEvent(QTableWidget* self, QPaintEvent* e);
void QTableWidget_OnPaintEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBasePaintEvent(QTableWidget* self, QPaintEvent* e);
void QTableWidget_TimerEvent(QTableWidget* self, QTimerEvent* event);
void QTableWidget_OnTimerEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseTimerEvent(QTableWidget* self, QTimerEvent* event);
int QTableWidget_HorizontalOffset(const QTableWidget* self);
void QTableWidget_OnHorizontalOffset(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseHorizontalOffset(const QTableWidget* self);
int QTableWidget_VerticalOffset(const QTableWidget* self);
void QTableWidget_OnVerticalOffset(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseVerticalOffset(const QTableWidget* self);
QModelIndex* QTableWidget_MoveCursor(QTableWidget* self, int cursorAction, int modifiers);
void QTableWidget_OnMoveCursor(QTableWidget* self, intptr_t slot);
QModelIndex* QTableWidget_QBaseMoveCursor(QTableWidget* self, int cursorAction, int modifiers);
void QTableWidget_SetSelection(QTableWidget* self, const QRect* rect, int command);
void QTableWidget_OnSetSelection(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetSelection(QTableWidget* self, const QRect* rect, int command);
QRegion* QTableWidget_VisualRegionForSelection(const QTableWidget* self, const QItemSelection* selection);
void QTableWidget_OnVisualRegionForSelection(const QTableWidget* self, intptr_t slot);
QRegion* QTableWidget_QBaseVisualRegionForSelection(const QTableWidget* self, const QItemSelection* selection);
libqt_list /* of QModelIndex* */ QTableWidget_SelectedIndexes(const QTableWidget* self);
void QTableWidget_OnSelectedIndexes(const QTableWidget* self, intptr_t slot);
libqt_list /* of QModelIndex* */ QTableWidget_QBaseSelectedIndexes(const QTableWidget* self);
void QTableWidget_UpdateGeometries(QTableWidget* self);
void QTableWidget_OnUpdateGeometries(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseUpdateGeometries(QTableWidget* self);
QSize* QTableWidget_ViewportSizeHint(const QTableWidget* self);
void QTableWidget_OnViewportSizeHint(const QTableWidget* self, intptr_t slot);
QSize* QTableWidget_QBaseViewportSizeHint(const QTableWidget* self);
int QTableWidget_SizeHintForRow(const QTableWidget* self, int row);
void QTableWidget_OnSizeHintForRow(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseSizeHintForRow(const QTableWidget* self, int row);
int QTableWidget_SizeHintForColumn(const QTableWidget* self, int column);
void QTableWidget_OnSizeHintForColumn(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseSizeHintForColumn(const QTableWidget* self, int column);
void QTableWidget_VerticalScrollbarAction(QTableWidget* self, int action);
void QTableWidget_OnVerticalScrollbarAction(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseVerticalScrollbarAction(QTableWidget* self, int action);
void QTableWidget_HorizontalScrollbarAction(QTableWidget* self, int action);
void QTableWidget_OnHorizontalScrollbarAction(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseHorizontalScrollbarAction(QTableWidget* self, int action);
bool QTableWidget_IsIndexHidden(const QTableWidget* self, const QModelIndex* index);
void QTableWidget_OnIsIndexHidden(const QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseIsIndexHidden(const QTableWidget* self, const QModelIndex* index);
void QTableWidget_SelectionChanged(QTableWidget* self, const QItemSelection* selected, const QItemSelection* deselected);
void QTableWidget_OnSelectionChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSelectionChanged(QTableWidget* self, const QItemSelection* selected, const QItemSelection* deselected);
void QTableWidget_CurrentChanged(QTableWidget* self, const QModelIndex* current, const QModelIndex* previous);
void QTableWidget_OnCurrentChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseCurrentChanged(QTableWidget* self, const QModelIndex* current, const QModelIndex* previous);
void QTableWidget_KeyboardSearch(QTableWidget* self, const libqt_string search);
void QTableWidget_OnKeyboardSearch(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseKeyboardSearch(QTableWidget* self, const libqt_string search);
QAbstractItemDelegate* QTableWidget_ItemDelegateForIndex(const QTableWidget* self, const QModelIndex* index);
void QTableWidget_OnItemDelegateForIndex(const QTableWidget* self, intptr_t slot);
QAbstractItemDelegate* QTableWidget_QBaseItemDelegateForIndex(const QTableWidget* self, const QModelIndex* index);
QVariant* QTableWidget_InputMethodQuery(const QTableWidget* self, int query);
void QTableWidget_OnInputMethodQuery(const QTableWidget* self, intptr_t slot);
QVariant* QTableWidget_QBaseInputMethodQuery(const QTableWidget* self, int query);
void QTableWidget_Reset(QTableWidget* self);
void QTableWidget_OnReset(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseReset(QTableWidget* self);
void QTableWidget_SelectAll(QTableWidget* self);
void QTableWidget_OnSelectAll(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSelectAll(QTableWidget* self);
void QTableWidget_DataChanged(QTableWidget* self, const QModelIndex* topLeft, const QModelIndex* bottomRight, const libqt_list /* of int */ roles);
void QTableWidget_OnDataChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDataChanged(QTableWidget* self, const QModelIndex* topLeft, const QModelIndex* bottomRight, const libqt_list /* of int */ roles);
void QTableWidget_RowsInserted(QTableWidget* self, const QModelIndex* parent, int start, int end);
void QTableWidget_OnRowsInserted(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseRowsInserted(QTableWidget* self, const QModelIndex* parent, int start, int end);
void QTableWidget_RowsAboutToBeRemoved(QTableWidget* self, const QModelIndex* parent, int start, int end);
void QTableWidget_OnRowsAboutToBeRemoved(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseRowsAboutToBeRemoved(QTableWidget* self, const QModelIndex* parent, int start, int end);
void QTableWidget_UpdateEditorData(QTableWidget* self);
void QTableWidget_OnUpdateEditorData(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseUpdateEditorData(QTableWidget* self);
void QTableWidget_UpdateEditorGeometries(QTableWidget* self);
void QTableWidget_OnUpdateEditorGeometries(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseUpdateEditorGeometries(QTableWidget* self);
void QTableWidget_VerticalScrollbarValueChanged(QTableWidget* self, int value);
void QTableWidget_OnVerticalScrollbarValueChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseVerticalScrollbarValueChanged(QTableWidget* self, int value);
void QTableWidget_HorizontalScrollbarValueChanged(QTableWidget* self, int value);
void QTableWidget_OnHorizontalScrollbarValueChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseHorizontalScrollbarValueChanged(QTableWidget* self, int value);
void QTableWidget_CloseEditor(QTableWidget* self, QWidget* editor, int hint);
void QTableWidget_OnCloseEditor(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseCloseEditor(QTableWidget* self, QWidget* editor, int hint);
void QTableWidget_CommitData(QTableWidget* self, QWidget* editor);
void QTableWidget_OnCommitData(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseCommitData(QTableWidget* self, QWidget* editor);
void QTableWidget_EditorDestroyed(QTableWidget* self, QObject* editor);
void QTableWidget_OnEditorDestroyed(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseEditorDestroyed(QTableWidget* self, QObject* editor);
bool QTableWidget_Edit2(QTableWidget* self, const QModelIndex* index, int trigger, QEvent* event);
void QTableWidget_OnEdit2(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseEdit2(QTableWidget* self, const QModelIndex* index, int trigger, QEvent* event);
int QTableWidget_SelectionCommand(const QTableWidget* self, const QModelIndex* index, const QEvent* event);
void QTableWidget_OnSelectionCommand(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseSelectionCommand(const QTableWidget* self, const QModelIndex* index, const QEvent* event);
void QTableWidget_StartDrag(QTableWidget* self, int supportedActions);
void QTableWidget_OnStartDrag(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseStartDrag(QTableWidget* self, int supportedActions);
bool QTableWidget_FocusNextPrevChild(QTableWidget* self, bool next);
void QTableWidget_OnFocusNextPrevChild(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseFocusNextPrevChild(QTableWidget* self, bool next);
bool QTableWidget_ViewportEvent(QTableWidget* self, QEvent* event);
void QTableWidget_OnViewportEvent(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseViewportEvent(QTableWidget* self, QEvent* event);
void QTableWidget_MousePressEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_OnMousePressEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseMousePressEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_MouseMoveEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_OnMouseMoveEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseMouseMoveEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_MouseReleaseEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_OnMouseReleaseEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseMouseReleaseEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_MouseDoubleClickEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_OnMouseDoubleClickEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseMouseDoubleClickEvent(QTableWidget* self, QMouseEvent* event);
void QTableWidget_DragEnterEvent(QTableWidget* self, QDragEnterEvent* event);
void QTableWidget_OnDragEnterEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDragEnterEvent(QTableWidget* self, QDragEnterEvent* event);
void QTableWidget_DragMoveEvent(QTableWidget* self, QDragMoveEvent* event);
void QTableWidget_OnDragMoveEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDragMoveEvent(QTableWidget* self, QDragMoveEvent* event);
void QTableWidget_DragLeaveEvent(QTableWidget* self, QDragLeaveEvent* event);
void QTableWidget_OnDragLeaveEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDragLeaveEvent(QTableWidget* self, QDragLeaveEvent* event);
void QTableWidget_FocusInEvent(QTableWidget* self, QFocusEvent* event);
void QTableWidget_OnFocusInEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseFocusInEvent(QTableWidget* self, QFocusEvent* event);
void QTableWidget_FocusOutEvent(QTableWidget* self, QFocusEvent* event);
void QTableWidget_OnFocusOutEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseFocusOutEvent(QTableWidget* self, QFocusEvent* event);
void QTableWidget_KeyPressEvent(QTableWidget* self, QKeyEvent* event);
void QTableWidget_OnKeyPressEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseKeyPressEvent(QTableWidget* self, QKeyEvent* event);
void QTableWidget_ResizeEvent(QTableWidget* self, QResizeEvent* event);
void QTableWidget_OnResizeEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseResizeEvent(QTableWidget* self, QResizeEvent* event);
void QTableWidget_InputMethodEvent(QTableWidget* self, QInputMethodEvent* event);
void QTableWidget_OnInputMethodEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseInputMethodEvent(QTableWidget* self, QInputMethodEvent* event);
bool QTableWidget_EventFilter(QTableWidget* self, QObject* object, QEvent* event);
void QTableWidget_OnEventFilter(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseEventFilter(QTableWidget* self, QObject* object, QEvent* event);
QSize* QTableWidget_MinimumSizeHint(const QTableWidget* self);
void QTableWidget_OnMinimumSizeHint(const QTableWidget* self, intptr_t slot);
QSize* QTableWidget_QBaseMinimumSizeHint(const QTableWidget* self);
QSize* QTableWidget_SizeHint(const QTableWidget* self);
void QTableWidget_OnSizeHint(const QTableWidget* self, intptr_t slot);
QSize* QTableWidget_QBaseSizeHint(const QTableWidget* self);
void QTableWidget_SetupViewport(QTableWidget* self, QWidget* viewport);
void QTableWidget_OnSetupViewport(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetupViewport(QTableWidget* self, QWidget* viewport);
void QTableWidget_WheelEvent(QTableWidget* self, QWheelEvent* param1);
void QTableWidget_OnWheelEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseWheelEvent(QTableWidget* self, QWheelEvent* param1);
void QTableWidget_ContextMenuEvent(QTableWidget* self, QContextMenuEvent* param1);
void QTableWidget_OnContextMenuEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseContextMenuEvent(QTableWidget* self, QContextMenuEvent* param1);
void QTableWidget_ChangeEvent(QTableWidget* self, QEvent* param1);
void QTableWidget_OnChangeEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseChangeEvent(QTableWidget* self, QEvent* param1);
void QTableWidget_InitStyleOption(const QTableWidget* self, QStyleOptionFrame* option);
void QTableWidget_OnInitStyleOption(const QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseInitStyleOption(const QTableWidget* self, QStyleOptionFrame* option);
int QTableWidget_DevType(const QTableWidget* self);
void QTableWidget_OnDevType(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseDevType(const QTableWidget* self);
void QTableWidget_SetVisible(QTableWidget* self, bool visible);
void QTableWidget_OnSetVisible(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetVisible(QTableWidget* self, bool visible);
int QTableWidget_HeightForWidth(const QTableWidget* self, int param1);
void QTableWidget_OnHeightForWidth(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseHeightForWidth(const QTableWidget* self, int param1);
bool QTableWidget_HasHeightForWidth(const QTableWidget* self);
void QTableWidget_OnHasHeightForWidth(const QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseHasHeightForWidth(const QTableWidget* self);
QPaintEngine* QTableWidget_PaintEngine(const QTableWidget* self);
void QTableWidget_OnPaintEngine(const QTableWidget* self, intptr_t slot);
QPaintEngine* QTableWidget_QBasePaintEngine(const QTableWidget* self);
void QTableWidget_KeyReleaseEvent(QTableWidget* self, QKeyEvent* event);
void QTableWidget_OnKeyReleaseEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseKeyReleaseEvent(QTableWidget* self, QKeyEvent* event);
void QTableWidget_EnterEvent(QTableWidget* self, QEnterEvent* event);
void QTableWidget_OnEnterEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseEnterEvent(QTableWidget* self, QEnterEvent* event);
void QTableWidget_LeaveEvent(QTableWidget* self, QEvent* event);
void QTableWidget_OnLeaveEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseLeaveEvent(QTableWidget* self, QEvent* event);
void QTableWidget_MoveEvent(QTableWidget* self, QMoveEvent* event);
void QTableWidget_OnMoveEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseMoveEvent(QTableWidget* self, QMoveEvent* event);
void QTableWidget_CloseEvent(QTableWidget* self, QCloseEvent* event);
void QTableWidget_OnCloseEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseCloseEvent(QTableWidget* self, QCloseEvent* event);
void QTableWidget_TabletEvent(QTableWidget* self, QTabletEvent* event);
void QTableWidget_OnTabletEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseTabletEvent(QTableWidget* self, QTabletEvent* event);
void QTableWidget_ActionEvent(QTableWidget* self, QActionEvent* event);
void QTableWidget_OnActionEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseActionEvent(QTableWidget* self, QActionEvent* event);
void QTableWidget_ShowEvent(QTableWidget* self, QShowEvent* event);
void QTableWidget_OnShowEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseShowEvent(QTableWidget* self, QShowEvent* event);
void QTableWidget_HideEvent(QTableWidget* self, QHideEvent* event);
void QTableWidget_OnHideEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseHideEvent(QTableWidget* self, QHideEvent* event);
bool QTableWidget_NativeEvent(QTableWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QTableWidget_OnNativeEvent(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseNativeEvent(QTableWidget* self, const libqt_string eventType, void* message, intptr_t* result);
int QTableWidget_Metric(const QTableWidget* self, int param1);
void QTableWidget_OnMetric(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseMetric(const QTableWidget* self, int param1);
void QTableWidget_InitPainter(const QTableWidget* self, QPainter* painter);
void QTableWidget_OnInitPainter(const QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseInitPainter(const QTableWidget* self, QPainter* painter);
QPaintDevice* QTableWidget_Redirected(const QTableWidget* self, QPoint* offset);
void QTableWidget_OnRedirected(const QTableWidget* self, intptr_t slot);
QPaintDevice* QTableWidget_QBaseRedirected(const QTableWidget* self, QPoint* offset);
QPainter* QTableWidget_SharedPainter(const QTableWidget* self);
void QTableWidget_OnSharedPainter(const QTableWidget* self, intptr_t slot);
QPainter* QTableWidget_QBaseSharedPainter(const QTableWidget* self);
void QTableWidget_ChildEvent(QTableWidget* self, QChildEvent* event);
void QTableWidget_OnChildEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseChildEvent(QTableWidget* self, QChildEvent* event);
void QTableWidget_CustomEvent(QTableWidget* self, QEvent* event);
void QTableWidget_OnCustomEvent(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseCustomEvent(QTableWidget* self, QEvent* event);
void QTableWidget_ConnectNotify(QTableWidget* self, const QMetaMethod* signal);
void QTableWidget_OnConnectNotify(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseConnectNotify(QTableWidget* self, const QMetaMethod* signal);
void QTableWidget_DisconnectNotify(QTableWidget* self, const QMetaMethod* signal);
void QTableWidget_OnDisconnectNotify(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDisconnectNotify(QTableWidget* self, const QMetaMethod* signal);
void QTableWidget_RowMoved(QTableWidget* self, int row, int oldIndex, int newIndex);
void QTableWidget_OnRowMoved(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseRowMoved(QTableWidget* self, int row, int oldIndex, int newIndex);
void QTableWidget_ColumnMoved(QTableWidget* self, int column, int oldIndex, int newIndex);
void QTableWidget_OnColumnMoved(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseColumnMoved(QTableWidget* self, int column, int oldIndex, int newIndex);
void QTableWidget_RowResized(QTableWidget* self, int row, int oldHeight, int newHeight);
void QTableWidget_OnRowResized(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseRowResized(QTableWidget* self, int row, int oldHeight, int newHeight);
void QTableWidget_ColumnResized(QTableWidget* self, int column, int oldWidth, int newWidth);
void QTableWidget_OnColumnResized(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseColumnResized(QTableWidget* self, int column, int oldWidth, int newWidth);
void QTableWidget_RowCountChanged(QTableWidget* self, int oldCount, int newCount);
void QTableWidget_OnRowCountChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseRowCountChanged(QTableWidget* self, int oldCount, int newCount);
void QTableWidget_ColumnCountChanged(QTableWidget* self, int oldCount, int newCount);
void QTableWidget_OnColumnCountChanged(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseColumnCountChanged(QTableWidget* self, int oldCount, int newCount);
int QTableWidget_State(const QTableWidget* self);
void QTableWidget_OnState(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseState(const QTableWidget* self);
void QTableWidget_SetState(QTableWidget* self, int state);
void QTableWidget_OnSetState(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetState(QTableWidget* self, int state);
void QTableWidget_ScheduleDelayedItemsLayout(QTableWidget* self);
void QTableWidget_OnScheduleDelayedItemsLayout(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseScheduleDelayedItemsLayout(QTableWidget* self);
void QTableWidget_ExecuteDelayedItemsLayout(QTableWidget* self);
void QTableWidget_OnExecuteDelayedItemsLayout(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseExecuteDelayedItemsLayout(QTableWidget* self);
void QTableWidget_SetDirtyRegion(QTableWidget* self, const QRegion* region);
void QTableWidget_OnSetDirtyRegion(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetDirtyRegion(QTableWidget* self, const QRegion* region);
void QTableWidget_ScrollDirtyRegion(QTableWidget* self, int dx, int dy);
void QTableWidget_OnScrollDirtyRegion(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseScrollDirtyRegion(QTableWidget* self, int dx, int dy);
QPoint* QTableWidget_DirtyRegionOffset(const QTableWidget* self);
void QTableWidget_OnDirtyRegionOffset(const QTableWidget* self, intptr_t slot);
QPoint* QTableWidget_QBaseDirtyRegionOffset(const QTableWidget* self);
void QTableWidget_StartAutoScroll(QTableWidget* self);
void QTableWidget_OnStartAutoScroll(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseStartAutoScroll(QTableWidget* self);
void QTableWidget_StopAutoScroll(QTableWidget* self);
void QTableWidget_OnStopAutoScroll(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseStopAutoScroll(QTableWidget* self);
void QTableWidget_DoAutoScroll(QTableWidget* self);
void QTableWidget_OnDoAutoScroll(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDoAutoScroll(QTableWidget* self);
int QTableWidget_DropIndicatorPosition(const QTableWidget* self);
void QTableWidget_OnDropIndicatorPosition(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseDropIndicatorPosition(const QTableWidget* self);
void QTableWidget_SetViewportMargins(QTableWidget* self, int left, int top, int right, int bottom);
void QTableWidget_OnSetViewportMargins(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseSetViewportMargins(QTableWidget* self, int left, int top, int right, int bottom);
QMargins* QTableWidget_ViewportMargins(const QTableWidget* self);
void QTableWidget_OnViewportMargins(const QTableWidget* self, intptr_t slot);
QMargins* QTableWidget_QBaseViewportMargins(const QTableWidget* self);
void QTableWidget_DrawFrame(QTableWidget* self, QPainter* param1);
void QTableWidget_OnDrawFrame(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDrawFrame(QTableWidget* self, QPainter* param1);
void QTableWidget_UpdateMicroFocus(QTableWidget* self);
void QTableWidget_OnUpdateMicroFocus(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseUpdateMicroFocus(QTableWidget* self);
void QTableWidget_Create(QTableWidget* self);
void QTableWidget_OnCreate(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseCreate(QTableWidget* self);
void QTableWidget_Destroy(QTableWidget* self);
void QTableWidget_OnDestroy(QTableWidget* self, intptr_t slot);
void QTableWidget_QBaseDestroy(QTableWidget* self);
bool QTableWidget_FocusNextChild(QTableWidget* self);
void QTableWidget_OnFocusNextChild(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseFocusNextChild(QTableWidget* self);
bool QTableWidget_FocusPreviousChild(QTableWidget* self);
void QTableWidget_OnFocusPreviousChild(QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseFocusPreviousChild(QTableWidget* self);
QObject* QTableWidget_Sender(const QTableWidget* self);
void QTableWidget_OnSender(const QTableWidget* self, intptr_t slot);
QObject* QTableWidget_QBaseSender(const QTableWidget* self);
int QTableWidget_SenderSignalIndex(const QTableWidget* self);
void QTableWidget_OnSenderSignalIndex(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseSenderSignalIndex(const QTableWidget* self);
int QTableWidget_Receivers(const QTableWidget* self, const char* signal);
void QTableWidget_OnReceivers(const QTableWidget* self, intptr_t slot);
int QTableWidget_QBaseReceivers(const QTableWidget* self, const char* signal);
bool QTableWidget_IsSignalConnected(const QTableWidget* self, const QMetaMethod* signal);
void QTableWidget_OnIsSignalConnected(const QTableWidget* self, intptr_t slot);
bool QTableWidget_QBaseIsSignalConnected(const QTableWidget* self, const QMetaMethod* signal);
double QTableWidget_GetDecodedMetricF(const QTableWidget* self, int metricA, int metricB);
void QTableWidget_OnGetDecodedMetricF(const QTableWidget* self, intptr_t slot);
double QTableWidget_QBaseGetDecodedMetricF(const QTableWidget* self, int metricA, int metricB);
void QTableWidget_Delete(QTableWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
