#pragma once
#ifndef SRCC_LIBQSPINBOX_H
#define SRCC_LIBQSPINBOX_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractSpinBox QAbstractSpinBox;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDoubleSpinBox QDoubleSpinBox;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSpinBox QSpinBox;
typedef struct QStyleOptionSpinBox QStyleOptionSpinBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QSpinBox* QSpinBox_new(QWidget* parent);
QSpinBox* QSpinBox_new2();
QMetaObject* QSpinBox_MetaObject(const QSpinBox* self);
void* QSpinBox_Metacast(QSpinBox* self, const char* param1);
int QSpinBox_Metacall(QSpinBox* self, int param1, int param2, void** param3);
libqt_string QSpinBox_Tr(const char* s);
int QSpinBox_Value(const QSpinBox* self);
libqt_string QSpinBox_Prefix(const QSpinBox* self);
void QSpinBox_SetPrefix(QSpinBox* self, const libqt_string prefix);
libqt_string QSpinBox_Suffix(const QSpinBox* self);
void QSpinBox_SetSuffix(QSpinBox* self, const libqt_string suffix);
libqt_string QSpinBox_CleanText(const QSpinBox* self);
int QSpinBox_SingleStep(const QSpinBox* self);
void QSpinBox_SetSingleStep(QSpinBox* self, int val);
int QSpinBox_Minimum(const QSpinBox* self);
void QSpinBox_SetMinimum(QSpinBox* self, int min);
int QSpinBox_Maximum(const QSpinBox* self);
void QSpinBox_SetMaximum(QSpinBox* self, int max);
void QSpinBox_SetRange(QSpinBox* self, int min, int max);
int QSpinBox_StepType(const QSpinBox* self);
void QSpinBox_SetStepType(QSpinBox* self, int stepType);
int QSpinBox_DisplayIntegerBase(const QSpinBox* self);
void QSpinBox_SetDisplayIntegerBase(QSpinBox* self, int base);
bool QSpinBox_Event(QSpinBox* self, QEvent* event);
int QSpinBox_Validate(const QSpinBox* self, libqt_string input, int* pos);
int QSpinBox_ValueFromText(const QSpinBox* self, const libqt_string text);
libqt_string QSpinBox_TextFromValue(const QSpinBox* self, int val);
void QSpinBox_Fixup(const QSpinBox* self, libqt_string str);
void QSpinBox_SetValue(QSpinBox* self, int val);
void QSpinBox_ValueChanged(QSpinBox* self, int param1);
void QSpinBox_Connect_ValueChanged(QSpinBox* self, intptr_t slot);
void QSpinBox_TextChanged(QSpinBox* self, const libqt_string param1);
void QSpinBox_Connect_TextChanged(QSpinBox* self, intptr_t slot);
libqt_string QSpinBox_Tr2(const char* s, const char* c);
libqt_string QSpinBox_Tr3(const char* s, const char* c, int n);
void QSpinBox_OnMetacall(QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseMetacall(QSpinBox* self, int param1, int param2, void** param3);
void QSpinBox_OnEvent(QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseEvent(QSpinBox* self, QEvent* event);
void QSpinBox_OnValidate(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseValidate(const QSpinBox* self, libqt_string input, int* pos);
void QSpinBox_OnValueFromText(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseValueFromText(const QSpinBox* self, const libqt_string text);
void QSpinBox_OnTextFromValue(const QSpinBox* self, intptr_t slot);
libqt_string QSpinBox_QBaseTextFromValue(const QSpinBox* self, int val);
void QSpinBox_OnFixup(const QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseFixup(const QSpinBox* self, libqt_string str);
QSize* QSpinBox_SizeHint(const QSpinBox* self);
void QSpinBox_OnSizeHint(const QSpinBox* self, intptr_t slot);
QSize* QSpinBox_QBaseSizeHint(const QSpinBox* self);
QSize* QSpinBox_MinimumSizeHint(const QSpinBox* self);
void QSpinBox_OnMinimumSizeHint(const QSpinBox* self, intptr_t slot);
QSize* QSpinBox_QBaseMinimumSizeHint(const QSpinBox* self);
QVariant* QSpinBox_InputMethodQuery(const QSpinBox* self, int param1);
void QSpinBox_OnInputMethodQuery(const QSpinBox* self, intptr_t slot);
QVariant* QSpinBox_QBaseInputMethodQuery(const QSpinBox* self, int param1);
void QSpinBox_StepBy(QSpinBox* self, int steps);
void QSpinBox_OnStepBy(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseStepBy(QSpinBox* self, int steps);
void QSpinBox_Clear(QSpinBox* self);
void QSpinBox_OnClear(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseClear(QSpinBox* self);
void QSpinBox_ResizeEvent(QSpinBox* self, QResizeEvent* event);
void QSpinBox_OnResizeEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseResizeEvent(QSpinBox* self, QResizeEvent* event);
void QSpinBox_KeyPressEvent(QSpinBox* self, QKeyEvent* event);
void QSpinBox_OnKeyPressEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseKeyPressEvent(QSpinBox* self, QKeyEvent* event);
void QSpinBox_KeyReleaseEvent(QSpinBox* self, QKeyEvent* event);
void QSpinBox_OnKeyReleaseEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseKeyReleaseEvent(QSpinBox* self, QKeyEvent* event);
void QSpinBox_WheelEvent(QSpinBox* self, QWheelEvent* event);
void QSpinBox_OnWheelEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseWheelEvent(QSpinBox* self, QWheelEvent* event);
void QSpinBox_FocusInEvent(QSpinBox* self, QFocusEvent* event);
void QSpinBox_OnFocusInEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseFocusInEvent(QSpinBox* self, QFocusEvent* event);
void QSpinBox_FocusOutEvent(QSpinBox* self, QFocusEvent* event);
void QSpinBox_OnFocusOutEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseFocusOutEvent(QSpinBox* self, QFocusEvent* event);
void QSpinBox_ContextMenuEvent(QSpinBox* self, QContextMenuEvent* event);
void QSpinBox_OnContextMenuEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseContextMenuEvent(QSpinBox* self, QContextMenuEvent* event);
void QSpinBox_ChangeEvent(QSpinBox* self, QEvent* event);
void QSpinBox_OnChangeEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseChangeEvent(QSpinBox* self, QEvent* event);
void QSpinBox_CloseEvent(QSpinBox* self, QCloseEvent* event);
void QSpinBox_OnCloseEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseCloseEvent(QSpinBox* self, QCloseEvent* event);
void QSpinBox_HideEvent(QSpinBox* self, QHideEvent* event);
void QSpinBox_OnHideEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseHideEvent(QSpinBox* self, QHideEvent* event);
void QSpinBox_MousePressEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_OnMousePressEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseMousePressEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_MouseReleaseEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_OnMouseReleaseEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseMouseReleaseEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_MouseMoveEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_OnMouseMoveEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseMouseMoveEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_TimerEvent(QSpinBox* self, QTimerEvent* event);
void QSpinBox_OnTimerEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseTimerEvent(QSpinBox* self, QTimerEvent* event);
void QSpinBox_PaintEvent(QSpinBox* self, QPaintEvent* event);
void QSpinBox_OnPaintEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBasePaintEvent(QSpinBox* self, QPaintEvent* event);
void QSpinBox_ShowEvent(QSpinBox* self, QShowEvent* event);
void QSpinBox_OnShowEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseShowEvent(QSpinBox* self, QShowEvent* event);
void QSpinBox_InitStyleOption(const QSpinBox* self, QStyleOptionSpinBox* option);
void QSpinBox_OnInitStyleOption(const QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseInitStyleOption(const QSpinBox* self, QStyleOptionSpinBox* option);
int QSpinBox_StepEnabled(const QSpinBox* self);
void QSpinBox_OnStepEnabled(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseStepEnabled(const QSpinBox* self);
int QSpinBox_DevType(const QSpinBox* self);
void QSpinBox_OnDevType(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseDevType(const QSpinBox* self);
void QSpinBox_SetVisible(QSpinBox* self, bool visible);
void QSpinBox_OnSetVisible(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseSetVisible(QSpinBox* self, bool visible);
int QSpinBox_HeightForWidth(const QSpinBox* self, int param1);
void QSpinBox_OnHeightForWidth(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseHeightForWidth(const QSpinBox* self, int param1);
bool QSpinBox_HasHeightForWidth(const QSpinBox* self);
void QSpinBox_OnHasHeightForWidth(const QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseHasHeightForWidth(const QSpinBox* self);
QPaintEngine* QSpinBox_PaintEngine(const QSpinBox* self);
void QSpinBox_OnPaintEngine(const QSpinBox* self, intptr_t slot);
QPaintEngine* QSpinBox_QBasePaintEngine(const QSpinBox* self);
void QSpinBox_MouseDoubleClickEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_OnMouseDoubleClickEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseMouseDoubleClickEvent(QSpinBox* self, QMouseEvent* event);
void QSpinBox_EnterEvent(QSpinBox* self, QEnterEvent* event);
void QSpinBox_OnEnterEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseEnterEvent(QSpinBox* self, QEnterEvent* event);
void QSpinBox_LeaveEvent(QSpinBox* self, QEvent* event);
void QSpinBox_OnLeaveEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseLeaveEvent(QSpinBox* self, QEvent* event);
void QSpinBox_MoveEvent(QSpinBox* self, QMoveEvent* event);
void QSpinBox_OnMoveEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseMoveEvent(QSpinBox* self, QMoveEvent* event);
void QSpinBox_TabletEvent(QSpinBox* self, QTabletEvent* event);
void QSpinBox_OnTabletEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseTabletEvent(QSpinBox* self, QTabletEvent* event);
void QSpinBox_ActionEvent(QSpinBox* self, QActionEvent* event);
void QSpinBox_OnActionEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseActionEvent(QSpinBox* self, QActionEvent* event);
void QSpinBox_DragEnterEvent(QSpinBox* self, QDragEnterEvent* event);
void QSpinBox_OnDragEnterEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseDragEnterEvent(QSpinBox* self, QDragEnterEvent* event);
void QSpinBox_DragMoveEvent(QSpinBox* self, QDragMoveEvent* event);
void QSpinBox_OnDragMoveEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseDragMoveEvent(QSpinBox* self, QDragMoveEvent* event);
void QSpinBox_DragLeaveEvent(QSpinBox* self, QDragLeaveEvent* event);
void QSpinBox_OnDragLeaveEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseDragLeaveEvent(QSpinBox* self, QDragLeaveEvent* event);
void QSpinBox_DropEvent(QSpinBox* self, QDropEvent* event);
void QSpinBox_OnDropEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseDropEvent(QSpinBox* self, QDropEvent* event);
bool QSpinBox_NativeEvent(QSpinBox* self, const libqt_string eventType, void* message, intptr_t* result);
void QSpinBox_OnNativeEvent(QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseNativeEvent(QSpinBox* self, const libqt_string eventType, void* message, intptr_t* result);
int QSpinBox_Metric(const QSpinBox* self, int param1);
void QSpinBox_OnMetric(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseMetric(const QSpinBox* self, int param1);
void QSpinBox_InitPainter(const QSpinBox* self, QPainter* painter);
void QSpinBox_OnInitPainter(const QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseInitPainter(const QSpinBox* self, QPainter* painter);
QPaintDevice* QSpinBox_Redirected(const QSpinBox* self, QPoint* offset);
void QSpinBox_OnRedirected(const QSpinBox* self, intptr_t slot);
QPaintDevice* QSpinBox_QBaseRedirected(const QSpinBox* self, QPoint* offset);
QPainter* QSpinBox_SharedPainter(const QSpinBox* self);
void QSpinBox_OnSharedPainter(const QSpinBox* self, intptr_t slot);
QPainter* QSpinBox_QBaseSharedPainter(const QSpinBox* self);
void QSpinBox_InputMethodEvent(QSpinBox* self, QInputMethodEvent* param1);
void QSpinBox_OnInputMethodEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseInputMethodEvent(QSpinBox* self, QInputMethodEvent* param1);
bool QSpinBox_FocusNextPrevChild(QSpinBox* self, bool next);
void QSpinBox_OnFocusNextPrevChild(QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseFocusNextPrevChild(QSpinBox* self, bool next);
bool QSpinBox_EventFilter(QSpinBox* self, QObject* watched, QEvent* event);
void QSpinBox_OnEventFilter(QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseEventFilter(QSpinBox* self, QObject* watched, QEvent* event);
void QSpinBox_ChildEvent(QSpinBox* self, QChildEvent* event);
void QSpinBox_OnChildEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseChildEvent(QSpinBox* self, QChildEvent* event);
void QSpinBox_CustomEvent(QSpinBox* self, QEvent* event);
void QSpinBox_OnCustomEvent(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseCustomEvent(QSpinBox* self, QEvent* event);
void QSpinBox_ConnectNotify(QSpinBox* self, const QMetaMethod* signal);
void QSpinBox_OnConnectNotify(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseConnectNotify(QSpinBox* self, const QMetaMethod* signal);
void QSpinBox_DisconnectNotify(QSpinBox* self, const QMetaMethod* signal);
void QSpinBox_OnDisconnectNotify(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseDisconnectNotify(QSpinBox* self, const QMetaMethod* signal);
QLineEdit* QSpinBox_LineEdit(const QSpinBox* self);
void QSpinBox_OnLineEdit(const QSpinBox* self, intptr_t slot);
QLineEdit* QSpinBox_QBaseLineEdit(const QSpinBox* self);
void QSpinBox_SetLineEdit(QSpinBox* self, QLineEdit* edit);
void QSpinBox_OnSetLineEdit(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseSetLineEdit(QSpinBox* self, QLineEdit* edit);
void QSpinBox_UpdateMicroFocus(QSpinBox* self);
void QSpinBox_OnUpdateMicroFocus(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseUpdateMicroFocus(QSpinBox* self);
void QSpinBox_Create(QSpinBox* self);
void QSpinBox_OnCreate(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseCreate(QSpinBox* self);
void QSpinBox_Destroy(QSpinBox* self);
void QSpinBox_OnDestroy(QSpinBox* self, intptr_t slot);
void QSpinBox_QBaseDestroy(QSpinBox* self);
bool QSpinBox_FocusNextChild(QSpinBox* self);
void QSpinBox_OnFocusNextChild(QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseFocusNextChild(QSpinBox* self);
bool QSpinBox_FocusPreviousChild(QSpinBox* self);
void QSpinBox_OnFocusPreviousChild(QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseFocusPreviousChild(QSpinBox* self);
QObject* QSpinBox_Sender(const QSpinBox* self);
void QSpinBox_OnSender(const QSpinBox* self, intptr_t slot);
QObject* QSpinBox_QBaseSender(const QSpinBox* self);
int QSpinBox_SenderSignalIndex(const QSpinBox* self);
void QSpinBox_OnSenderSignalIndex(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseSenderSignalIndex(const QSpinBox* self);
int QSpinBox_Receivers(const QSpinBox* self, const char* signal);
void QSpinBox_OnReceivers(const QSpinBox* self, intptr_t slot);
int QSpinBox_QBaseReceivers(const QSpinBox* self, const char* signal);
bool QSpinBox_IsSignalConnected(const QSpinBox* self, const QMetaMethod* signal);
void QSpinBox_OnIsSignalConnected(const QSpinBox* self, intptr_t slot);
bool QSpinBox_QBaseIsSignalConnected(const QSpinBox* self, const QMetaMethod* signal);
double QSpinBox_GetDecodedMetricF(const QSpinBox* self, int metricA, int metricB);
void QSpinBox_OnGetDecodedMetricF(const QSpinBox* self, intptr_t slot);
double QSpinBox_QBaseGetDecodedMetricF(const QSpinBox* self, int metricA, int metricB);
void QSpinBox_Delete(QSpinBox* self);

QDoubleSpinBox* QDoubleSpinBox_new(QWidget* parent);
QDoubleSpinBox* QDoubleSpinBox_new2();
QMetaObject* QDoubleSpinBox_MetaObject(const QDoubleSpinBox* self);
void* QDoubleSpinBox_Metacast(QDoubleSpinBox* self, const char* param1);
int QDoubleSpinBox_Metacall(QDoubleSpinBox* self, int param1, int param2, void** param3);
libqt_string QDoubleSpinBox_Tr(const char* s);
double QDoubleSpinBox_Value(const QDoubleSpinBox* self);
libqt_string QDoubleSpinBox_Prefix(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetPrefix(QDoubleSpinBox* self, const libqt_string prefix);
libqt_string QDoubleSpinBox_Suffix(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetSuffix(QDoubleSpinBox* self, const libqt_string suffix);
libqt_string QDoubleSpinBox_CleanText(const QDoubleSpinBox* self);
double QDoubleSpinBox_SingleStep(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetSingleStep(QDoubleSpinBox* self, double val);
double QDoubleSpinBox_Minimum(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetMinimum(QDoubleSpinBox* self, double min);
double QDoubleSpinBox_Maximum(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetMaximum(QDoubleSpinBox* self, double max);
void QDoubleSpinBox_SetRange(QDoubleSpinBox* self, double min, double max);
int QDoubleSpinBox_StepType(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetStepType(QDoubleSpinBox* self, int stepType);
int QDoubleSpinBox_Decimals(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetDecimals(QDoubleSpinBox* self, int prec);
int QDoubleSpinBox_Validate(const QDoubleSpinBox* self, libqt_string input, int* pos);
double QDoubleSpinBox_ValueFromText(const QDoubleSpinBox* self, const libqt_string text);
libqt_string QDoubleSpinBox_TextFromValue(const QDoubleSpinBox* self, double val);
void QDoubleSpinBox_Fixup(const QDoubleSpinBox* self, libqt_string str);
void QDoubleSpinBox_SetValue(QDoubleSpinBox* self, double val);
void QDoubleSpinBox_ValueChanged(QDoubleSpinBox* self, double param1);
void QDoubleSpinBox_Connect_ValueChanged(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_TextChanged(QDoubleSpinBox* self, const libqt_string param1);
void QDoubleSpinBox_Connect_TextChanged(QDoubleSpinBox* self, intptr_t slot);
libqt_string QDoubleSpinBox_Tr2(const char* s, const char* c);
libqt_string QDoubleSpinBox_Tr3(const char* s, const char* c, int n);
void QDoubleSpinBox_OnMetacall(QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseMetacall(QDoubleSpinBox* self, int param1, int param2, void** param3);
void QDoubleSpinBox_OnValidate(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseValidate(const QDoubleSpinBox* self, libqt_string input, int* pos);
void QDoubleSpinBox_OnValueFromText(const QDoubleSpinBox* self, intptr_t slot);
double QDoubleSpinBox_QBaseValueFromText(const QDoubleSpinBox* self, const libqt_string text);
void QDoubleSpinBox_OnTextFromValue(const QDoubleSpinBox* self, intptr_t slot);
libqt_string QDoubleSpinBox_QBaseTextFromValue(const QDoubleSpinBox* self, double val);
void QDoubleSpinBox_OnFixup(const QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseFixup(const QDoubleSpinBox* self, libqt_string str);
QSize* QDoubleSpinBox_SizeHint(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnSizeHint(const QDoubleSpinBox* self, intptr_t slot);
QSize* QDoubleSpinBox_QBaseSizeHint(const QDoubleSpinBox* self);
QSize* QDoubleSpinBox_MinimumSizeHint(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnMinimumSizeHint(const QDoubleSpinBox* self, intptr_t slot);
QSize* QDoubleSpinBox_QBaseMinimumSizeHint(const QDoubleSpinBox* self);
bool QDoubleSpinBox_Event(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_OnEvent(QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseEvent(QDoubleSpinBox* self, QEvent* event);
QVariant* QDoubleSpinBox_InputMethodQuery(const QDoubleSpinBox* self, int param1);
void QDoubleSpinBox_OnInputMethodQuery(const QDoubleSpinBox* self, intptr_t slot);
QVariant* QDoubleSpinBox_QBaseInputMethodQuery(const QDoubleSpinBox* self, int param1);
void QDoubleSpinBox_StepBy(QDoubleSpinBox* self, int steps);
void QDoubleSpinBox_OnStepBy(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseStepBy(QDoubleSpinBox* self, int steps);
void QDoubleSpinBox_Clear(QDoubleSpinBox* self);
void QDoubleSpinBox_OnClear(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseClear(QDoubleSpinBox* self);
void QDoubleSpinBox_ResizeEvent(QDoubleSpinBox* self, QResizeEvent* event);
void QDoubleSpinBox_OnResizeEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseResizeEvent(QDoubleSpinBox* self, QResizeEvent* event);
void QDoubleSpinBox_KeyPressEvent(QDoubleSpinBox* self, QKeyEvent* event);
void QDoubleSpinBox_OnKeyPressEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseKeyPressEvent(QDoubleSpinBox* self, QKeyEvent* event);
void QDoubleSpinBox_KeyReleaseEvent(QDoubleSpinBox* self, QKeyEvent* event);
void QDoubleSpinBox_OnKeyReleaseEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseKeyReleaseEvent(QDoubleSpinBox* self, QKeyEvent* event);
void QDoubleSpinBox_WheelEvent(QDoubleSpinBox* self, QWheelEvent* event);
void QDoubleSpinBox_OnWheelEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseWheelEvent(QDoubleSpinBox* self, QWheelEvent* event);
void QDoubleSpinBox_FocusInEvent(QDoubleSpinBox* self, QFocusEvent* event);
void QDoubleSpinBox_OnFocusInEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseFocusInEvent(QDoubleSpinBox* self, QFocusEvent* event);
void QDoubleSpinBox_FocusOutEvent(QDoubleSpinBox* self, QFocusEvent* event);
void QDoubleSpinBox_OnFocusOutEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseFocusOutEvent(QDoubleSpinBox* self, QFocusEvent* event);
void QDoubleSpinBox_ContextMenuEvent(QDoubleSpinBox* self, QContextMenuEvent* event);
void QDoubleSpinBox_OnContextMenuEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseContextMenuEvent(QDoubleSpinBox* self, QContextMenuEvent* event);
void QDoubleSpinBox_ChangeEvent(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_OnChangeEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseChangeEvent(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_CloseEvent(QDoubleSpinBox* self, QCloseEvent* event);
void QDoubleSpinBox_OnCloseEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseCloseEvent(QDoubleSpinBox* self, QCloseEvent* event);
void QDoubleSpinBox_HideEvent(QDoubleSpinBox* self, QHideEvent* event);
void QDoubleSpinBox_OnHideEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseHideEvent(QDoubleSpinBox* self, QHideEvent* event);
void QDoubleSpinBox_MousePressEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_OnMousePressEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseMousePressEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_MouseReleaseEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_OnMouseReleaseEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseMouseReleaseEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_MouseMoveEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_OnMouseMoveEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseMouseMoveEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_TimerEvent(QDoubleSpinBox* self, QTimerEvent* event);
void QDoubleSpinBox_OnTimerEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseTimerEvent(QDoubleSpinBox* self, QTimerEvent* event);
void QDoubleSpinBox_PaintEvent(QDoubleSpinBox* self, QPaintEvent* event);
void QDoubleSpinBox_OnPaintEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBasePaintEvent(QDoubleSpinBox* self, QPaintEvent* event);
void QDoubleSpinBox_ShowEvent(QDoubleSpinBox* self, QShowEvent* event);
void QDoubleSpinBox_OnShowEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseShowEvent(QDoubleSpinBox* self, QShowEvent* event);
void QDoubleSpinBox_InitStyleOption(const QDoubleSpinBox* self, QStyleOptionSpinBox* option);
void QDoubleSpinBox_OnInitStyleOption(const QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseInitStyleOption(const QDoubleSpinBox* self, QStyleOptionSpinBox* option);
int QDoubleSpinBox_StepEnabled(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnStepEnabled(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseStepEnabled(const QDoubleSpinBox* self);
int QDoubleSpinBox_DevType(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnDevType(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseDevType(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetVisible(QDoubleSpinBox* self, bool visible);
void QDoubleSpinBox_OnSetVisible(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseSetVisible(QDoubleSpinBox* self, bool visible);
int QDoubleSpinBox_HeightForWidth(const QDoubleSpinBox* self, int param1);
void QDoubleSpinBox_OnHeightForWidth(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseHeightForWidth(const QDoubleSpinBox* self, int param1);
bool QDoubleSpinBox_HasHeightForWidth(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnHasHeightForWidth(const QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseHasHeightForWidth(const QDoubleSpinBox* self);
QPaintEngine* QDoubleSpinBox_PaintEngine(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnPaintEngine(const QDoubleSpinBox* self, intptr_t slot);
QPaintEngine* QDoubleSpinBox_QBasePaintEngine(const QDoubleSpinBox* self);
void QDoubleSpinBox_MouseDoubleClickEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_OnMouseDoubleClickEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseMouseDoubleClickEvent(QDoubleSpinBox* self, QMouseEvent* event);
void QDoubleSpinBox_EnterEvent(QDoubleSpinBox* self, QEnterEvent* event);
void QDoubleSpinBox_OnEnterEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseEnterEvent(QDoubleSpinBox* self, QEnterEvent* event);
void QDoubleSpinBox_LeaveEvent(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_OnLeaveEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseLeaveEvent(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_MoveEvent(QDoubleSpinBox* self, QMoveEvent* event);
void QDoubleSpinBox_OnMoveEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseMoveEvent(QDoubleSpinBox* self, QMoveEvent* event);
void QDoubleSpinBox_TabletEvent(QDoubleSpinBox* self, QTabletEvent* event);
void QDoubleSpinBox_OnTabletEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseTabletEvent(QDoubleSpinBox* self, QTabletEvent* event);
void QDoubleSpinBox_ActionEvent(QDoubleSpinBox* self, QActionEvent* event);
void QDoubleSpinBox_OnActionEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseActionEvent(QDoubleSpinBox* self, QActionEvent* event);
void QDoubleSpinBox_DragEnterEvent(QDoubleSpinBox* self, QDragEnterEvent* event);
void QDoubleSpinBox_OnDragEnterEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseDragEnterEvent(QDoubleSpinBox* self, QDragEnterEvent* event);
void QDoubleSpinBox_DragMoveEvent(QDoubleSpinBox* self, QDragMoveEvent* event);
void QDoubleSpinBox_OnDragMoveEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseDragMoveEvent(QDoubleSpinBox* self, QDragMoveEvent* event);
void QDoubleSpinBox_DragLeaveEvent(QDoubleSpinBox* self, QDragLeaveEvent* event);
void QDoubleSpinBox_OnDragLeaveEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseDragLeaveEvent(QDoubleSpinBox* self, QDragLeaveEvent* event);
void QDoubleSpinBox_DropEvent(QDoubleSpinBox* self, QDropEvent* event);
void QDoubleSpinBox_OnDropEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseDropEvent(QDoubleSpinBox* self, QDropEvent* event);
bool QDoubleSpinBox_NativeEvent(QDoubleSpinBox* self, const libqt_string eventType, void* message, intptr_t* result);
void QDoubleSpinBox_OnNativeEvent(QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseNativeEvent(QDoubleSpinBox* self, const libqt_string eventType, void* message, intptr_t* result);
int QDoubleSpinBox_Metric(const QDoubleSpinBox* self, int param1);
void QDoubleSpinBox_OnMetric(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseMetric(const QDoubleSpinBox* self, int param1);
void QDoubleSpinBox_InitPainter(const QDoubleSpinBox* self, QPainter* painter);
void QDoubleSpinBox_OnInitPainter(const QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseInitPainter(const QDoubleSpinBox* self, QPainter* painter);
QPaintDevice* QDoubleSpinBox_Redirected(const QDoubleSpinBox* self, QPoint* offset);
void QDoubleSpinBox_OnRedirected(const QDoubleSpinBox* self, intptr_t slot);
QPaintDevice* QDoubleSpinBox_QBaseRedirected(const QDoubleSpinBox* self, QPoint* offset);
QPainter* QDoubleSpinBox_SharedPainter(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnSharedPainter(const QDoubleSpinBox* self, intptr_t slot);
QPainter* QDoubleSpinBox_QBaseSharedPainter(const QDoubleSpinBox* self);
void QDoubleSpinBox_InputMethodEvent(QDoubleSpinBox* self, QInputMethodEvent* param1);
void QDoubleSpinBox_OnInputMethodEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseInputMethodEvent(QDoubleSpinBox* self, QInputMethodEvent* param1);
bool QDoubleSpinBox_FocusNextPrevChild(QDoubleSpinBox* self, bool next);
void QDoubleSpinBox_OnFocusNextPrevChild(QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseFocusNextPrevChild(QDoubleSpinBox* self, bool next);
bool QDoubleSpinBox_EventFilter(QDoubleSpinBox* self, QObject* watched, QEvent* event);
void QDoubleSpinBox_OnEventFilter(QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseEventFilter(QDoubleSpinBox* self, QObject* watched, QEvent* event);
void QDoubleSpinBox_ChildEvent(QDoubleSpinBox* self, QChildEvent* event);
void QDoubleSpinBox_OnChildEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseChildEvent(QDoubleSpinBox* self, QChildEvent* event);
void QDoubleSpinBox_CustomEvent(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_OnCustomEvent(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseCustomEvent(QDoubleSpinBox* self, QEvent* event);
void QDoubleSpinBox_ConnectNotify(QDoubleSpinBox* self, const QMetaMethod* signal);
void QDoubleSpinBox_OnConnectNotify(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseConnectNotify(QDoubleSpinBox* self, const QMetaMethod* signal);
void QDoubleSpinBox_DisconnectNotify(QDoubleSpinBox* self, const QMetaMethod* signal);
void QDoubleSpinBox_OnDisconnectNotify(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseDisconnectNotify(QDoubleSpinBox* self, const QMetaMethod* signal);
QLineEdit* QDoubleSpinBox_LineEdit(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnLineEdit(const QDoubleSpinBox* self, intptr_t slot);
QLineEdit* QDoubleSpinBox_QBaseLineEdit(const QDoubleSpinBox* self);
void QDoubleSpinBox_SetLineEdit(QDoubleSpinBox* self, QLineEdit* edit);
void QDoubleSpinBox_OnSetLineEdit(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseSetLineEdit(QDoubleSpinBox* self, QLineEdit* edit);
void QDoubleSpinBox_UpdateMicroFocus(QDoubleSpinBox* self);
void QDoubleSpinBox_OnUpdateMicroFocus(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseUpdateMicroFocus(QDoubleSpinBox* self);
void QDoubleSpinBox_Create(QDoubleSpinBox* self);
void QDoubleSpinBox_OnCreate(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseCreate(QDoubleSpinBox* self);
void QDoubleSpinBox_Destroy(QDoubleSpinBox* self);
void QDoubleSpinBox_OnDestroy(QDoubleSpinBox* self, intptr_t slot);
void QDoubleSpinBox_QBaseDestroy(QDoubleSpinBox* self);
bool QDoubleSpinBox_FocusNextChild(QDoubleSpinBox* self);
void QDoubleSpinBox_OnFocusNextChild(QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseFocusNextChild(QDoubleSpinBox* self);
bool QDoubleSpinBox_FocusPreviousChild(QDoubleSpinBox* self);
void QDoubleSpinBox_OnFocusPreviousChild(QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseFocusPreviousChild(QDoubleSpinBox* self);
QObject* QDoubleSpinBox_Sender(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnSender(const QDoubleSpinBox* self, intptr_t slot);
QObject* QDoubleSpinBox_QBaseSender(const QDoubleSpinBox* self);
int QDoubleSpinBox_SenderSignalIndex(const QDoubleSpinBox* self);
void QDoubleSpinBox_OnSenderSignalIndex(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseSenderSignalIndex(const QDoubleSpinBox* self);
int QDoubleSpinBox_Receivers(const QDoubleSpinBox* self, const char* signal);
void QDoubleSpinBox_OnReceivers(const QDoubleSpinBox* self, intptr_t slot);
int QDoubleSpinBox_QBaseReceivers(const QDoubleSpinBox* self, const char* signal);
bool QDoubleSpinBox_IsSignalConnected(const QDoubleSpinBox* self, const QMetaMethod* signal);
void QDoubleSpinBox_OnIsSignalConnected(const QDoubleSpinBox* self, intptr_t slot);
bool QDoubleSpinBox_QBaseIsSignalConnected(const QDoubleSpinBox* self, const QMetaMethod* signal);
double QDoubleSpinBox_GetDecodedMetricF(const QDoubleSpinBox* self, int metricA, int metricB);
void QDoubleSpinBox_OnGetDecodedMetricF(const QDoubleSpinBox* self, intptr_t slot);
double QDoubleSpinBox_QBaseGetDecodedMetricF(const QDoubleSpinBox* self, int metricA, int metricB);
void QDoubleSpinBox_Delete(QDoubleSpinBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
