#pragma once
#ifndef SRCC_LIBQWIDGET_H
#define SRCC_LIBQWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QBackingStore QBackingStore;
typedef struct QBitmap QBitmap;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QCursor QCursor;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QFontInfo QFontInfo;
typedef struct QFontMetrics QFontMetrics;
typedef struct QGraphicsEffect QGraphicsEffect;
typedef struct QGraphicsProxyWidget QGraphicsProxyWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QKeySequence QKeySequence;
typedef struct QLayout QLayout;
typedef struct QLocale QLocale;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPalette QPalette;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QScreen QScreen;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSizePolicy QSizePolicy;
typedef struct QStyle QStyle;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QWidgetData QWidgetData;
typedef struct QWindow QWindow;
#endif

QWidgetData* QWidgetData_new(const QWidgetData* param1);
unsigned long long QWidgetData_Winid(const QWidgetData* self);
void QWidgetData_SetWinid(QWidgetData* self, unsigned long long winid);
unsigned int QWidgetData_WidgetAttributes(const QWidgetData* self);
void QWidgetData_SetWidgetAttributes(QWidgetData* self, unsigned int widget_attributes);
int QWidgetData_WindowFlags(const QWidgetData* self);
void QWidgetData_SetWindowFlags(QWidgetData* self, int window_flags);
unsigned int QWidgetData_WindowState(const QWidgetData* self);
void QWidgetData_SetWindowState(QWidgetData* self, unsigned int window_state);
unsigned int QWidgetData_FocusPolicy(const QWidgetData* self);
void QWidgetData_SetFocusPolicy(QWidgetData* self, unsigned int focus_policy);
unsigned int QWidgetData_SizehintForced(const QWidgetData* self);
void QWidgetData_SetSizehintForced(QWidgetData* self, unsigned int sizehint_forced);
unsigned int QWidgetData_IsClosing(const QWidgetData* self);
void QWidgetData_SetIsClosing(QWidgetData* self, unsigned int is_closing);
unsigned int QWidgetData_InShow(const QWidgetData* self);
void QWidgetData_SetInShow(QWidgetData* self, unsigned int in_show);
unsigned int QWidgetData_InSetWindowState(const QWidgetData* self);
void QWidgetData_SetInSetWindowState(QWidgetData* self, unsigned int in_set_window_state);
unsigned int QWidgetData_FstrutDirty(const QWidgetData* self);
void QWidgetData_SetFstrutDirty(QWidgetData* self, unsigned int fstrut_dirty);
unsigned int QWidgetData_ContextMenuPolicy(const QWidgetData* self);
void QWidgetData_SetContextMenuPolicy(QWidgetData* self, unsigned int context_menu_policy);
unsigned int QWidgetData_WindowModality(const QWidgetData* self);
void QWidgetData_SetWindowModality(QWidgetData* self, unsigned int window_modality);
unsigned int QWidgetData_InDestructor(const QWidgetData* self);
void QWidgetData_SetInDestructor(QWidgetData* self, unsigned int in_destructor);
unsigned int QWidgetData_Unused(const QWidgetData* self);
void QWidgetData_SetUnused(QWidgetData* self, unsigned int unused);
QRect* QWidgetData_Crect(const QWidgetData* self);
void QWidgetData_SetCrect(QWidgetData* self, QRect* crect);
QPalette* QWidgetData_Pal(const QWidgetData* self);
void QWidgetData_SetPal(QWidgetData* self, QPalette* pal);
QFont* QWidgetData_Fnt(const QWidgetData* self);
void QWidgetData_SetFnt(QWidgetData* self, QFont* fnt);
QRect* QWidgetData_Wrect(const QWidgetData* self);
void QWidgetData_SetWrect(QWidgetData* self, QRect* wrect);
void QWidgetData_OperatorAssign(QWidgetData* self, const QWidgetData* param1);
void QWidgetData_Delete(QWidgetData* self);

QWidget* QWidget_new(QWidget* parent);
QWidget* QWidget_new2();
QWidget* QWidget_new3(QWidget* parent, int f);
QMetaObject* QWidget_MetaObject(const QWidget* self);
void* QWidget_Metacast(QWidget* self, const char* param1);
int QWidget_Metacall(QWidget* self, int param1, int param2, void** param3);
libqt_string QWidget_Tr(const char* s);
int QWidget_DevType(const QWidget* self);
uintptr_t QWidget_WinId(const QWidget* self);
void QWidget_CreateWinId(QWidget* self);
uintptr_t QWidget_InternalWinId(const QWidget* self);
uintptr_t QWidget_EffectiveWinId(const QWidget* self);
QStyle* QWidget_Style(const QWidget* self);
void QWidget_SetStyle(QWidget* self, QStyle* style);
bool QWidget_IsTopLevel(const QWidget* self);
bool QWidget_IsWindow(const QWidget* self);
bool QWidget_IsModal(const QWidget* self);
int QWidget_WindowModality(const QWidget* self);
void QWidget_SetWindowModality(QWidget* self, int windowModality);
bool QWidget_IsEnabled(const QWidget* self);
bool QWidget_IsEnabledTo(const QWidget* self, const QWidget* param1);
void QWidget_SetEnabled(QWidget* self, bool enabled);
void QWidget_SetDisabled(QWidget* self, bool disabled);
void QWidget_SetWindowModified(QWidget* self, bool windowModified);
QRect* QWidget_FrameGeometry(const QWidget* self);
QRect* QWidget_Geometry(const QWidget* self);
QRect* QWidget_NormalGeometry(const QWidget* self);
int QWidget_X(const QWidget* self);
int QWidget_Y(const QWidget* self);
QPoint* QWidget_Pos(const QWidget* self);
QSize* QWidget_FrameSize(const QWidget* self);
QSize* QWidget_Size(const QWidget* self);
int QWidget_Width(const QWidget* self);
int QWidget_Height(const QWidget* self);
QRect* QWidget_Rect(const QWidget* self);
QRect* QWidget_ChildrenRect(const QWidget* self);
QRegion* QWidget_ChildrenRegion(const QWidget* self);
QSize* QWidget_MinimumSize(const QWidget* self);
QSize* QWidget_MaximumSize(const QWidget* self);
int QWidget_MinimumWidth(const QWidget* self);
int QWidget_MinimumHeight(const QWidget* self);
int QWidget_MaximumWidth(const QWidget* self);
int QWidget_MaximumHeight(const QWidget* self);
void QWidget_SetMinimumSize(QWidget* self, const QSize* minimumSize);
void QWidget_SetMinimumSize2(QWidget* self, int minw, int minh);
void QWidget_SetMaximumSize(QWidget* self, const QSize* maximumSize);
void QWidget_SetMaximumSize2(QWidget* self, int maxw, int maxh);
void QWidget_SetMinimumWidth(QWidget* self, int minw);
void QWidget_SetMinimumHeight(QWidget* self, int minh);
void QWidget_SetMaximumWidth(QWidget* self, int maxw);
void QWidget_SetMaximumHeight(QWidget* self, int maxh);
QSize* QWidget_SizeIncrement(const QWidget* self);
void QWidget_SetSizeIncrement(QWidget* self, const QSize* sizeIncrement);
void QWidget_SetSizeIncrement2(QWidget* self, int w, int h);
QSize* QWidget_BaseSize(const QWidget* self);
void QWidget_SetBaseSize(QWidget* self, const QSize* baseSize);
void QWidget_SetBaseSize2(QWidget* self, int basew, int baseh);
void QWidget_SetFixedSize(QWidget* self, const QSize* fixedSize);
void QWidget_SetFixedSize2(QWidget* self, int w, int h);
void QWidget_SetFixedWidth(QWidget* self, int w);
void QWidget_SetFixedHeight(QWidget* self, int h);
QPointF* QWidget_MapToGlobal(const QWidget* self, const QPointF* param1);
QPoint* QWidget_MapToGlobal2(const QWidget* self, const QPoint* param1);
QPointF* QWidget_MapFromGlobal(const QWidget* self, const QPointF* param1);
QPoint* QWidget_MapFromGlobal2(const QWidget* self, const QPoint* param1);
QPointF* QWidget_MapToParent(const QWidget* self, const QPointF* param1);
QPoint* QWidget_MapToParent2(const QWidget* self, const QPoint* param1);
QPointF* QWidget_MapFromParent(const QWidget* self, const QPointF* param1);
QPoint* QWidget_MapFromParent2(const QWidget* self, const QPoint* param1);
QPointF* QWidget_MapTo(const QWidget* self, const QWidget* param1, const QPointF* param2);
QPoint* QWidget_MapTo2(const QWidget* self, const QWidget* param1, const QPoint* param2);
QPointF* QWidget_MapFrom(const QWidget* self, const QWidget* param1, const QPointF* param2);
QPoint* QWidget_MapFrom2(const QWidget* self, const QWidget* param1, const QPoint* param2);
QWidget* QWidget_Window(const QWidget* self);
QWidget* QWidget_NativeParentWidget(const QWidget* self);
QWidget* QWidget_TopLevelWidget(const QWidget* self);
QPalette* QWidget_Palette(const QWidget* self);
void QWidget_SetPalette(QWidget* self, const QPalette* palette);
void QWidget_SetBackgroundRole(QWidget* self, int backgroundRole);
int QWidget_BackgroundRole(const QWidget* self);
void QWidget_SetForegroundRole(QWidget* self, int foregroundRole);
int QWidget_ForegroundRole(const QWidget* self);
QFont* QWidget_Font(const QWidget* self);
void QWidget_SetFont(QWidget* self, const QFont* font);
QFontMetrics* QWidget_FontMetrics(const QWidget* self);
QFontInfo* QWidget_FontInfo(const QWidget* self);
QCursor* QWidget_Cursor(const QWidget* self);
void QWidget_SetCursor(QWidget* self, const QCursor* cursor);
void QWidget_UnsetCursor(QWidget* self);
void QWidget_SetMouseTracking(QWidget* self, bool enable);
bool QWidget_HasMouseTracking(const QWidget* self);
bool QWidget_UnderMouse(const QWidget* self);
void QWidget_SetTabletTracking(QWidget* self, bool enable);
bool QWidget_HasTabletTracking(const QWidget* self);
void QWidget_SetMask(QWidget* self, const QBitmap* mask);
void QWidget_SetMask2(QWidget* self, const QRegion* mask);
QRegion* QWidget_Mask(const QWidget* self);
void QWidget_ClearMask(QWidget* self);
void QWidget_Render(QWidget* self, QPaintDevice* target);
void QWidget_Render2(QWidget* self, QPainter* painter);
QPixmap* QWidget_Grab(QWidget* self);
QGraphicsEffect* QWidget_GraphicsEffect(const QWidget* self);
void QWidget_SetGraphicsEffect(QWidget* self, QGraphicsEffect* effect);
void QWidget_GrabGesture(QWidget* self, int typeVal);
void QWidget_UngrabGesture(QWidget* self, int typeVal);
void QWidget_SetWindowTitle(QWidget* self, const libqt_string windowTitle);
void QWidget_SetStyleSheet(QWidget* self, const libqt_string styleSheet);
libqt_string QWidget_StyleSheet(const QWidget* self);
libqt_string QWidget_WindowTitle(const QWidget* self);
void QWidget_SetWindowIcon(QWidget* self, const QIcon* icon);
QIcon* QWidget_WindowIcon(const QWidget* self);
void QWidget_SetWindowIconText(QWidget* self, const libqt_string windowIconText);
libqt_string QWidget_WindowIconText(const QWidget* self);
void QWidget_SetWindowRole(QWidget* self, const libqt_string windowRole);
libqt_string QWidget_WindowRole(const QWidget* self);
void QWidget_SetWindowFilePath(QWidget* self, const libqt_string filePath);
libqt_string QWidget_WindowFilePath(const QWidget* self);
void QWidget_SetWindowOpacity(QWidget* self, double level);
double QWidget_WindowOpacity(const QWidget* self);
bool QWidget_IsWindowModified(const QWidget* self);
void QWidget_SetToolTip(QWidget* self, const libqt_string toolTip);
libqt_string QWidget_ToolTip(const QWidget* self);
void QWidget_SetToolTipDuration(QWidget* self, int msec);
int QWidget_ToolTipDuration(const QWidget* self);
void QWidget_SetStatusTip(QWidget* self, const libqt_string statusTip);
libqt_string QWidget_StatusTip(const QWidget* self);
void QWidget_SetWhatsThis(QWidget* self, const libqt_string whatsThis);
libqt_string QWidget_WhatsThis(const QWidget* self);
libqt_string QWidget_AccessibleName(const QWidget* self);
void QWidget_SetAccessibleName(QWidget* self, const libqt_string name);
libqt_string QWidget_AccessibleDescription(const QWidget* self);
void QWidget_SetAccessibleDescription(QWidget* self, const libqt_string description);
void QWidget_SetLayoutDirection(QWidget* self, int direction);
int QWidget_LayoutDirection(const QWidget* self);
void QWidget_UnsetLayoutDirection(QWidget* self);
void QWidget_SetLocale(QWidget* self, const QLocale* locale);
QLocale* QWidget_Locale(const QWidget* self);
void QWidget_UnsetLocale(QWidget* self);
bool QWidget_IsRightToLeft(const QWidget* self);
bool QWidget_IsLeftToRight(const QWidget* self);
void QWidget_SetFocus(QWidget* self);
bool QWidget_IsActiveWindow(const QWidget* self);
void QWidget_ActivateWindow(QWidget* self);
void QWidget_ClearFocus(QWidget* self);
void QWidget_SetFocus2(QWidget* self, int reason);
int QWidget_FocusPolicy(const QWidget* self);
void QWidget_SetFocusPolicy(QWidget* self, int policy);
bool QWidget_HasFocus(const QWidget* self);
void QWidget_SetTabOrder(QWidget* param1, QWidget* param2);
void QWidget_SetFocusProxy(QWidget* self, QWidget* focusProxy);
QWidget* QWidget_FocusProxy(const QWidget* self);
int QWidget_ContextMenuPolicy(const QWidget* self);
void QWidget_SetContextMenuPolicy(QWidget* self, int policy);
void QWidget_GrabMouse(QWidget* self);
void QWidget_GrabMouse2(QWidget* self, const QCursor* param1);
void QWidget_ReleaseMouse(QWidget* self);
void QWidget_GrabKeyboard(QWidget* self);
void QWidget_ReleaseKeyboard(QWidget* self);
int QWidget_GrabShortcut(QWidget* self, const QKeySequence* key);
void QWidget_ReleaseShortcut(QWidget* self, int id);
void QWidget_SetShortcutEnabled(QWidget* self, int id);
void QWidget_SetShortcutAutoRepeat(QWidget* self, int id);
QWidget* QWidget_MouseGrabber();
QWidget* QWidget_KeyboardGrabber();
bool QWidget_UpdatesEnabled(const QWidget* self);
void QWidget_SetUpdatesEnabled(QWidget* self, bool enable);
QGraphicsProxyWidget* QWidget_GraphicsProxyWidget(const QWidget* self);
void QWidget_Update(QWidget* self);
void QWidget_Repaint(QWidget* self);
void QWidget_Update2(QWidget* self, int x, int y, int w, int h);
void QWidget_Update3(QWidget* self, const QRect* param1);
void QWidget_Update4(QWidget* self, const QRegion* param1);
void QWidget_Repaint2(QWidget* self, int x, int y, int w, int h);
void QWidget_Repaint3(QWidget* self, const QRect* param1);
void QWidget_Repaint4(QWidget* self, const QRegion* param1);
void QWidget_SetVisible(QWidget* self, bool visible);
void QWidget_SetHidden(QWidget* self, bool hidden);
void QWidget_Show(QWidget* self);
void QWidget_Hide(QWidget* self);
void QWidget_ShowMinimized(QWidget* self);
void QWidget_ShowMaximized(QWidget* self);
void QWidget_ShowFullScreen(QWidget* self);
void QWidget_ShowNormal(QWidget* self);
bool QWidget_Close(QWidget* self);
void QWidget_Raise(QWidget* self);
void QWidget_Lower(QWidget* self);
void QWidget_StackUnder(QWidget* self, QWidget* param1);
void QWidget_Move(QWidget* self, int x, int y);
void QWidget_Move2(QWidget* self, const QPoint* param1);
void QWidget_Resize(QWidget* self, int w, int h);
void QWidget_Resize2(QWidget* self, const QSize* param1);
void QWidget_SetGeometry(QWidget* self, int x, int y, int w, int h);
void QWidget_SetGeometry2(QWidget* self, const QRect* geometry);
libqt_string QWidget_SaveGeometry(const QWidget* self);
bool QWidget_RestoreGeometry(QWidget* self, const libqt_string geometry);
void QWidget_AdjustSize(QWidget* self);
bool QWidget_IsVisible(const QWidget* self);
bool QWidget_IsVisibleTo(const QWidget* self, const QWidget* param1);
bool QWidget_IsHidden(const QWidget* self);
bool QWidget_IsMinimized(const QWidget* self);
bool QWidget_IsMaximized(const QWidget* self);
bool QWidget_IsFullScreen(const QWidget* self);
int QWidget_WindowState(const QWidget* self);
void QWidget_SetWindowState(QWidget* self, int state);
void QWidget_OverrideWindowState(QWidget* self, int state);
QSize* QWidget_SizeHint(const QWidget* self);
QSize* QWidget_MinimumSizeHint(const QWidget* self);
QSizePolicy* QWidget_SizePolicy(const QWidget* self);
void QWidget_SetSizePolicy(QWidget* self, QSizePolicy* sizePolicy);
void QWidget_SetSizePolicy2(QWidget* self, int horizontal, int vertical);
int QWidget_HeightForWidth(const QWidget* self, int param1);
bool QWidget_HasHeightForWidth(const QWidget* self);
QRegion* QWidget_VisibleRegion(const QWidget* self);
void QWidget_SetContentsMargins(QWidget* self, int left, int top, int right, int bottom);
void QWidget_SetContentsMargins2(QWidget* self, const QMargins* margins);
QMargins* QWidget_ContentsMargins(const QWidget* self);
QRect* QWidget_ContentsRect(const QWidget* self);
QLayout* QWidget_Layout(const QWidget* self);
void QWidget_SetLayout(QWidget* self, QLayout* layout);
void QWidget_UpdateGeometry(QWidget* self);
void QWidget_SetParent(QWidget* self, QWidget* parent);
void QWidget_SetParent2(QWidget* self, QWidget* parent, int f);
void QWidget_Scroll(QWidget* self, int dx, int dy);
void QWidget_Scroll2(QWidget* self, int dx, int dy, const QRect* param3);
QWidget* QWidget_FocusWidget(const QWidget* self);
QWidget* QWidget_NextInFocusChain(const QWidget* self);
QWidget* QWidget_PreviousInFocusChain(const QWidget* self);
bool QWidget_AcceptDrops(const QWidget* self);
void QWidget_SetAcceptDrops(QWidget* self, bool on);
void QWidget_AddAction(QWidget* self, QAction* action);
void QWidget_AddActions(QWidget* self, const libqt_list /* of QAction* */ actions);
void QWidget_InsertActions(QWidget* self, QAction* before, const libqt_list /* of QAction* */ actions);
void QWidget_InsertAction(QWidget* self, QAction* before, QAction* action);
void QWidget_RemoveAction(QWidget* self, QAction* action);
libqt_list /* of QAction* */ QWidget_Actions(const QWidget* self);
QAction* QWidget_AddAction2(QWidget* self, const libqt_string text);
QAction* QWidget_AddAction3(QWidget* self, const QIcon* icon, const libqt_string text);
QAction* QWidget_AddAction4(QWidget* self, const libqt_string text, const QKeySequence* shortcut);
QAction* QWidget_AddAction5(QWidget* self, const QIcon* icon, const libqt_string text, const QKeySequence* shortcut);
QWidget* QWidget_ParentWidget(const QWidget* self);
void QWidget_SetWindowFlags(QWidget* self, int typeVal);
int QWidget_WindowFlags(const QWidget* self);
void QWidget_SetWindowFlag(QWidget* self, int param1);
void QWidget_OverrideWindowFlags(QWidget* self, int typeVal);
int QWidget_WindowType(const QWidget* self);
QWidget* QWidget_Find(unsigned long long param1);
QWidget* QWidget_ChildAt(const QWidget* self, int x, int y);
QWidget* QWidget_ChildAt2(const QWidget* self, const QPoint* p);
QWidget* QWidget_ChildAt3(const QWidget* self, const QPointF* p);
void QWidget_SetAttribute(QWidget* self, int param1);
bool QWidget_TestAttribute(const QWidget* self, int param1);
QPaintEngine* QWidget_PaintEngine(const QWidget* self);
void QWidget_EnsurePolished(const QWidget* self);
bool QWidget_IsAncestorOf(const QWidget* self, const QWidget* child);
bool QWidget_AutoFillBackground(const QWidget* self);
void QWidget_SetAutoFillBackground(QWidget* self, bool enabled);
QBackingStore* QWidget_BackingStore(const QWidget* self);
QWindow* QWidget_WindowHandle(const QWidget* self);
QScreen* QWidget_Screen(const QWidget* self);
void QWidget_SetScreen(QWidget* self, QScreen* screen);
QWidget* QWidget_CreateWindowContainer(QWindow* window);
void QWidget_WindowTitleChanged(QWidget* self, const libqt_string title);
void QWidget_Connect_WindowTitleChanged(QWidget* self, intptr_t slot);
void QWidget_WindowIconChanged(QWidget* self, const QIcon* icon);
void QWidget_Connect_WindowIconChanged(QWidget* self, intptr_t slot);
void QWidget_WindowIconTextChanged(QWidget* self, const libqt_string iconText);
void QWidget_Connect_WindowIconTextChanged(QWidget* self, intptr_t slot);
void QWidget_CustomContextMenuRequested(QWidget* self, const QPoint* pos);
void QWidget_Connect_CustomContextMenuRequested(QWidget* self, intptr_t slot);
bool QWidget_Event(QWidget* self, QEvent* event);
void QWidget_MousePressEvent(QWidget* self, QMouseEvent* event);
void QWidget_MouseReleaseEvent(QWidget* self, QMouseEvent* event);
void QWidget_MouseDoubleClickEvent(QWidget* self, QMouseEvent* event);
void QWidget_MouseMoveEvent(QWidget* self, QMouseEvent* event);
void QWidget_WheelEvent(QWidget* self, QWheelEvent* event);
void QWidget_KeyPressEvent(QWidget* self, QKeyEvent* event);
void QWidget_KeyReleaseEvent(QWidget* self, QKeyEvent* event);
void QWidget_FocusInEvent(QWidget* self, QFocusEvent* event);
void QWidget_FocusOutEvent(QWidget* self, QFocusEvent* event);
void QWidget_EnterEvent(QWidget* self, QEnterEvent* event);
void QWidget_LeaveEvent(QWidget* self, QEvent* event);
void QWidget_PaintEvent(QWidget* self, QPaintEvent* event);
void QWidget_MoveEvent(QWidget* self, QMoveEvent* event);
void QWidget_ResizeEvent(QWidget* self, QResizeEvent* event);
void QWidget_CloseEvent(QWidget* self, QCloseEvent* event);
void QWidget_ContextMenuEvent(QWidget* self, QContextMenuEvent* event);
void QWidget_TabletEvent(QWidget* self, QTabletEvent* event);
void QWidget_ActionEvent(QWidget* self, QActionEvent* event);
void QWidget_DragEnterEvent(QWidget* self, QDragEnterEvent* event);
void QWidget_DragMoveEvent(QWidget* self, QDragMoveEvent* event);
void QWidget_DragLeaveEvent(QWidget* self, QDragLeaveEvent* event);
void QWidget_DropEvent(QWidget* self, QDropEvent* event);
void QWidget_ShowEvent(QWidget* self, QShowEvent* event);
void QWidget_HideEvent(QWidget* self, QHideEvent* event);
bool QWidget_NativeEvent(QWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QWidget_ChangeEvent(QWidget* self, QEvent* param1);
int QWidget_Metric(const QWidget* self, int param1);
void QWidget_InitPainter(const QWidget* self, QPainter* painter);
QPaintDevice* QWidget_Redirected(const QWidget* self, QPoint* offset);
QPainter* QWidget_SharedPainter(const QWidget* self);
void QWidget_InputMethodEvent(QWidget* self, QInputMethodEvent* param1);
QVariant* QWidget_InputMethodQuery(const QWidget* self, int param1);
int QWidget_InputMethodHints(const QWidget* self);
void QWidget_SetInputMethodHints(QWidget* self, int hints);
bool QWidget_FocusNextPrevChild(QWidget* self, bool next);
libqt_string QWidget_Tr2(const char* s, const char* c);
libqt_string QWidget_Tr3(const char* s, const char* c, int n);
void QWidget_Render22(QWidget* self, QPaintDevice* target, const QPoint* targetOffset);
void QWidget_Render3(QWidget* self, QPaintDevice* target, const QPoint* targetOffset, const QRegion* sourceRegion);
void QWidget_Render4(QWidget* self, QPaintDevice* target, const QPoint* targetOffset, const QRegion* sourceRegion, int renderFlags);
void QWidget_Render23(QWidget* self, QPainter* painter, const QPoint* targetOffset);
void QWidget_Render32(QWidget* self, QPainter* painter, const QPoint* targetOffset, const QRegion* sourceRegion);
void QWidget_Render42(QWidget* self, QPainter* painter, const QPoint* targetOffset, const QRegion* sourceRegion, int renderFlags);
QPixmap* QWidget_Grab1(QWidget* self, const QRect* rectangle);
void QWidget_GrabGesture2(QWidget* self, int typeVal, int flags);
int QWidget_GrabShortcut2(QWidget* self, const QKeySequence* key, int context);
void QWidget_SetShortcutEnabled2(QWidget* self, int id, bool enable);
void QWidget_SetShortcutAutoRepeat2(QWidget* self, int id, bool enable);
void QWidget_SetWindowFlag2(QWidget* self, int param1, bool on);
void QWidget_SetAttribute2(QWidget* self, int param1, bool on);
QWidget* QWidget_CreateWindowContainer2(QWindow* window, QWidget* parent);
QWidget* QWidget_CreateWindowContainer3(QWindow* window, QWidget* parent, int flags);
void QWidget_OnMetacall(QWidget* self, intptr_t slot);
int QWidget_QBaseMetacall(QWidget* self, int param1, int param2, void** param3);
void QWidget_OnDevType(const QWidget* self, intptr_t slot);
int QWidget_QBaseDevType(const QWidget* self);
void QWidget_OnSetVisible(QWidget* self, intptr_t slot);
void QWidget_QBaseSetVisible(QWidget* self, bool visible);
void QWidget_OnSizeHint(const QWidget* self, intptr_t slot);
QSize* QWidget_QBaseSizeHint(const QWidget* self);
void QWidget_OnMinimumSizeHint(const QWidget* self, intptr_t slot);
QSize* QWidget_QBaseMinimumSizeHint(const QWidget* self);
void QWidget_OnHeightForWidth(const QWidget* self, intptr_t slot);
int QWidget_QBaseHeightForWidth(const QWidget* self, int param1);
void QWidget_OnHasHeightForWidth(const QWidget* self, intptr_t slot);
bool QWidget_QBaseHasHeightForWidth(const QWidget* self);
void QWidget_OnPaintEngine(const QWidget* self, intptr_t slot);
QPaintEngine* QWidget_QBasePaintEngine(const QWidget* self);
void QWidget_OnEvent(QWidget* self, intptr_t slot);
bool QWidget_QBaseEvent(QWidget* self, QEvent* event);
void QWidget_OnMousePressEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseMousePressEvent(QWidget* self, QMouseEvent* event);
void QWidget_OnMouseReleaseEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseMouseReleaseEvent(QWidget* self, QMouseEvent* event);
void QWidget_OnMouseDoubleClickEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseMouseDoubleClickEvent(QWidget* self, QMouseEvent* event);
void QWidget_OnMouseMoveEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseMouseMoveEvent(QWidget* self, QMouseEvent* event);
void QWidget_OnWheelEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseWheelEvent(QWidget* self, QWheelEvent* event);
void QWidget_OnKeyPressEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseKeyPressEvent(QWidget* self, QKeyEvent* event);
void QWidget_OnKeyReleaseEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseKeyReleaseEvent(QWidget* self, QKeyEvent* event);
void QWidget_OnFocusInEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseFocusInEvent(QWidget* self, QFocusEvent* event);
void QWidget_OnFocusOutEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseFocusOutEvent(QWidget* self, QFocusEvent* event);
void QWidget_OnEnterEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseEnterEvent(QWidget* self, QEnterEvent* event);
void QWidget_OnLeaveEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseLeaveEvent(QWidget* self, QEvent* event);
void QWidget_OnPaintEvent(QWidget* self, intptr_t slot);
void QWidget_QBasePaintEvent(QWidget* self, QPaintEvent* event);
void QWidget_OnMoveEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseMoveEvent(QWidget* self, QMoveEvent* event);
void QWidget_OnResizeEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseResizeEvent(QWidget* self, QResizeEvent* event);
void QWidget_OnCloseEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseCloseEvent(QWidget* self, QCloseEvent* event);
void QWidget_OnContextMenuEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseContextMenuEvent(QWidget* self, QContextMenuEvent* event);
void QWidget_OnTabletEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseTabletEvent(QWidget* self, QTabletEvent* event);
void QWidget_OnActionEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseActionEvent(QWidget* self, QActionEvent* event);
void QWidget_OnDragEnterEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseDragEnterEvent(QWidget* self, QDragEnterEvent* event);
void QWidget_OnDragMoveEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseDragMoveEvent(QWidget* self, QDragMoveEvent* event);
void QWidget_OnDragLeaveEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseDragLeaveEvent(QWidget* self, QDragLeaveEvent* event);
void QWidget_OnDropEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseDropEvent(QWidget* self, QDropEvent* event);
void QWidget_OnShowEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseShowEvent(QWidget* self, QShowEvent* event);
void QWidget_OnHideEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseHideEvent(QWidget* self, QHideEvent* event);
void QWidget_OnNativeEvent(QWidget* self, intptr_t slot);
bool QWidget_QBaseNativeEvent(QWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QWidget_OnChangeEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseChangeEvent(QWidget* self, QEvent* param1);
void QWidget_OnMetric(const QWidget* self, intptr_t slot);
int QWidget_QBaseMetric(const QWidget* self, int param1);
void QWidget_OnInitPainter(const QWidget* self, intptr_t slot);
void QWidget_QBaseInitPainter(const QWidget* self, QPainter* painter);
void QWidget_OnRedirected(const QWidget* self, intptr_t slot);
QPaintDevice* QWidget_QBaseRedirected(const QWidget* self, QPoint* offset);
void QWidget_OnSharedPainter(const QWidget* self, intptr_t slot);
QPainter* QWidget_QBaseSharedPainter(const QWidget* self);
void QWidget_OnInputMethodEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseInputMethodEvent(QWidget* self, QInputMethodEvent* param1);
void QWidget_OnInputMethodQuery(const QWidget* self, intptr_t slot);
QVariant* QWidget_QBaseInputMethodQuery(const QWidget* self, int param1);
void QWidget_OnFocusNextPrevChild(QWidget* self, intptr_t slot);
bool QWidget_QBaseFocusNextPrevChild(QWidget* self, bool next);
bool QWidget_EventFilter(QWidget* self, QObject* watched, QEvent* event);
void QWidget_OnEventFilter(QWidget* self, intptr_t slot);
bool QWidget_QBaseEventFilter(QWidget* self, QObject* watched, QEvent* event);
void QWidget_TimerEvent(QWidget* self, QTimerEvent* event);
void QWidget_OnTimerEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseTimerEvent(QWidget* self, QTimerEvent* event);
void QWidget_ChildEvent(QWidget* self, QChildEvent* event);
void QWidget_OnChildEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseChildEvent(QWidget* self, QChildEvent* event);
void QWidget_CustomEvent(QWidget* self, QEvent* event);
void QWidget_OnCustomEvent(QWidget* self, intptr_t slot);
void QWidget_QBaseCustomEvent(QWidget* self, QEvent* event);
void QWidget_ConnectNotify(QWidget* self, const QMetaMethod* signal);
void QWidget_OnConnectNotify(QWidget* self, intptr_t slot);
void QWidget_QBaseConnectNotify(QWidget* self, const QMetaMethod* signal);
void QWidget_DisconnectNotify(QWidget* self, const QMetaMethod* signal);
void QWidget_OnDisconnectNotify(QWidget* self, intptr_t slot);
void QWidget_QBaseDisconnectNotify(QWidget* self, const QMetaMethod* signal);
void QWidget_UpdateMicroFocus(QWidget* self);
void QWidget_OnUpdateMicroFocus(QWidget* self, intptr_t slot);
void QWidget_QBaseUpdateMicroFocus(QWidget* self);
void QWidget_Create(QWidget* self);
void QWidget_OnCreate(QWidget* self, intptr_t slot);
void QWidget_QBaseCreate(QWidget* self);
void QWidget_Destroy(QWidget* self);
void QWidget_OnDestroy(QWidget* self, intptr_t slot);
void QWidget_QBaseDestroy(QWidget* self);
bool QWidget_FocusNextChild(QWidget* self);
void QWidget_OnFocusNextChild(QWidget* self, intptr_t slot);
bool QWidget_QBaseFocusNextChild(QWidget* self);
bool QWidget_FocusPreviousChild(QWidget* self);
void QWidget_OnFocusPreviousChild(QWidget* self, intptr_t slot);
bool QWidget_QBaseFocusPreviousChild(QWidget* self);
void QWidget_UpdateMicroFocus1(QWidget* self, int query);
void QWidget_OnUpdateMicroFocus1(QWidget* self, intptr_t slot);
void QWidget_QBaseUpdateMicroFocus1(QWidget* self, int query);
void QWidget_Create1(QWidget* self, unsigned long long param1);
void QWidget_OnCreate1(QWidget* self, intptr_t slot);
void QWidget_QBaseCreate1(QWidget* self, unsigned long long param1);
void QWidget_Create2(QWidget* self, unsigned long long param1, bool initializeWindow);
void QWidget_OnCreate2(QWidget* self, intptr_t slot);
void QWidget_QBaseCreate2(QWidget* self, unsigned long long param1, bool initializeWindow);
void QWidget_Create3(QWidget* self, unsigned long long param1, bool initializeWindow, bool destroyOldWindow);
void QWidget_OnCreate3(QWidget* self, intptr_t slot);
void QWidget_QBaseCreate3(QWidget* self, unsigned long long param1, bool initializeWindow, bool destroyOldWindow);
void QWidget_Destroy1(QWidget* self, bool destroyWindow);
void QWidget_OnDestroy1(QWidget* self, intptr_t slot);
void QWidget_QBaseDestroy1(QWidget* self, bool destroyWindow);
void QWidget_Destroy2(QWidget* self, bool destroyWindow, bool destroySubWindows);
void QWidget_OnDestroy2(QWidget* self, intptr_t slot);
void QWidget_QBaseDestroy2(QWidget* self, bool destroyWindow, bool destroySubWindows);
QObject* QWidget_Sender(const QWidget* self);
void QWidget_OnSender(const QWidget* self, intptr_t slot);
QObject* QWidget_QBaseSender(const QWidget* self);
int QWidget_SenderSignalIndex(const QWidget* self);
void QWidget_OnSenderSignalIndex(const QWidget* self, intptr_t slot);
int QWidget_QBaseSenderSignalIndex(const QWidget* self);
int QWidget_Receivers(const QWidget* self, const char* signal);
void QWidget_OnReceivers(const QWidget* self, intptr_t slot);
int QWidget_QBaseReceivers(const QWidget* self, const char* signal);
bool QWidget_IsSignalConnected(const QWidget* self, const QMetaMethod* signal);
void QWidget_OnIsSignalConnected(const QWidget* self, intptr_t slot);
bool QWidget_QBaseIsSignalConnected(const QWidget* self, const QMetaMethod* signal);
double QWidget_GetDecodedMetricF(const QWidget* self, int metricA, int metricB);
void QWidget_OnGetDecodedMetricF(const QWidget* self, intptr_t slot);
double QWidget_QBaseGetDecodedMetricF(const QWidget* self, int metricA, int metricB);
void QWidget_Delete(QWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
