#pragma once
#ifndef QACCESSIBLE_H_C_LIB
#define QACCESSIBLE_H_C_LIB

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QAccessible__State)
typedef QAccessible::State QAccessible__State;
#endif
#else
typedef struct QAccessible__State QAccessible__State;
typedef struct QAccessibleActionInterface QAccessibleActionInterface;
typedef struct QAccessibleAnnouncementEvent QAccessibleAnnouncementEvent;
typedef struct QAccessibleAttributesInterface QAccessibleAttributesInterface;
typedef struct QAccessibleEditableTextInterface QAccessibleEditableTextInterface;
typedef struct QAccessibleEvent QAccessibleEvent;
typedef struct QAccessibleHyperlinkInterface QAccessibleHyperlinkInterface;
typedef struct QAccessibleImageInterface QAccessibleImageInterface;
typedef struct QAccessibleInterface QAccessibleInterface;
typedef struct QAccessibleSelectionInterface QAccessibleSelectionInterface;
typedef struct QAccessibleStateChangeEvent QAccessibleStateChangeEvent;
typedef struct QAccessibleTableCellInterface QAccessibleTableCellInterface;
typedef struct QAccessibleTableInterface QAccessibleTableInterface;
typedef struct QAccessibleTableModelChangeEvent QAccessibleTableModelChangeEvent;
typedef struct QAccessibleTextCursorEvent QAccessibleTextCursorEvent;
typedef struct QAccessibleTextInsertEvent QAccessibleTextInsertEvent;
typedef struct QAccessibleTextInterface QAccessibleTextInterface;
typedef struct QAccessibleTextRemoveEvent QAccessibleTextRemoveEvent;
typedef struct QAccessibleTextSelectionEvent QAccessibleTextSelectionEvent;
typedef struct QAccessibleTextUpdateEvent QAccessibleTextUpdateEvent;
typedef struct QAccessibleValueChangeEvent QAccessibleValueChangeEvent;
typedef struct QAccessibleValueInterface QAccessibleValueInterface;
typedef struct QColor QColor;
typedef struct QObject QObject;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QSize QSize;
typedef struct QVariant QVariant;
typedef struct QWindow QWindow;
typedef struct _GUID _GUID;
typedef struct type_info type_info;
#endif



QAccessibleInterface* QAccessibleInterface_new();
QAccessibleInterface* QAccessibleInterface_new2(const QAccessibleInterface* param1);
bool QAccessibleInterface_IsValid(const QAccessibleInterface* self);
QObject* QAccessibleInterface_Object(const QAccessibleInterface* self);
QWindow* QAccessibleInterface_Window(const QAccessibleInterface* self);
libqt_list QAccessibleInterface_Relations(const QAccessibleInterface* self, int match);
QAccessibleInterface* QAccessibleInterface_FocusChild(const QAccessibleInterface* self);
QAccessibleInterface* QAccessibleInterface_ChildAt(const QAccessibleInterface* self, int x, int y);
QAccessibleInterface* QAccessibleInterface_Parent(const QAccessibleInterface* self);
QAccessibleInterface* QAccessibleInterface_Child(const QAccessibleInterface* self, int index);
int QAccessibleInterface_ChildCount(const QAccessibleInterface* self);
int QAccessibleInterface_IndexOfChild(const QAccessibleInterface* self, const QAccessibleInterface* param1);
libqt_string QAccessibleInterface_Text(const QAccessibleInterface* self, int t);
void QAccessibleInterface_SetText(QAccessibleInterface* self, int t, const libqt_string text);
QRect* QAccessibleInterface_Rect(const QAccessibleInterface* self);
int QAccessibleInterface_Role(const QAccessibleInterface* self);
QAccessible__State* QAccessibleInterface_State(const QAccessibleInterface* self);
QColor* QAccessibleInterface_ForegroundColor(const QAccessibleInterface* self);
QColor* QAccessibleInterface_BackgroundColor(const QAccessibleInterface* self);
QAccessibleTextInterface* QAccessibleInterface_TextInterface(QAccessibleInterface* self);
QAccessibleEditableTextInterface* QAccessibleInterface_EditableTextInterface(QAccessibleInterface* self);
QAccessibleValueInterface* QAccessibleInterface_ValueInterface(QAccessibleInterface* self);
QAccessibleActionInterface* QAccessibleInterface_ActionInterface(QAccessibleInterface* self);
QAccessibleImageInterface* QAccessibleInterface_ImageInterface(QAccessibleInterface* self);
QAccessibleTableInterface* QAccessibleInterface_TableInterface(QAccessibleInterface* self);
QAccessibleTableCellInterface* QAccessibleInterface_TableCellInterface(QAccessibleInterface* self);
QAccessibleHyperlinkInterface* QAccessibleInterface_HyperlinkInterface(QAccessibleInterface* self);
QAccessibleSelectionInterface* QAccessibleInterface_SelectionInterface(QAccessibleInterface* self);
QAccessibleAttributesInterface* QAccessibleInterface_AttributesInterface(QAccessibleInterface* self);
void QAccessibleInterface_VirtualHook(QAccessibleInterface* self, int id, void* data);
void* QAccessibleInterface_InterfaceCast(QAccessibleInterface* self, int param1);
void QAccessibleInterface_OnIsValid(const QAccessibleInterface* self, intptr_t slot);
bool QAccessibleInterface_QBaseIsValid(const QAccessibleInterface* self);
void QAccessibleInterface_OnObject(const QAccessibleInterface* self, intptr_t slot);
QObject* QAccessibleInterface_QBaseObject(const QAccessibleInterface* self);
void QAccessibleInterface_OnWindow(const QAccessibleInterface* self, intptr_t slot);
QWindow* QAccessibleInterface_QBaseWindow(const QAccessibleInterface* self);
void QAccessibleInterface_OnRelations(const QAccessibleInterface* self, intptr_t slot);
libqt_list QAccessibleInterface_QBaseRelations(const QAccessibleInterface* self, int match);
void QAccessibleInterface_OnFocusChild(const QAccessibleInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleInterface_QBaseFocusChild(const QAccessibleInterface* self);
void QAccessibleInterface_OnChildAt(const QAccessibleInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleInterface_QBaseChildAt(const QAccessibleInterface* self, int x, int y);
void QAccessibleInterface_OnParent(const QAccessibleInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleInterface_QBaseParent(const QAccessibleInterface* self);
void QAccessibleInterface_OnChild(const QAccessibleInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleInterface_QBaseChild(const QAccessibleInterface* self, int index);
void QAccessibleInterface_OnChildCount(const QAccessibleInterface* self, intptr_t slot);
int QAccessibleInterface_QBaseChildCount(const QAccessibleInterface* self);
void QAccessibleInterface_OnIndexOfChild(const QAccessibleInterface* self, intptr_t slot);
int QAccessibleInterface_QBaseIndexOfChild(const QAccessibleInterface* self, const QAccessibleInterface* param1);
void QAccessibleInterface_OnText(const QAccessibleInterface* self, intptr_t slot);
libqt_string QAccessibleInterface_QBaseText(const QAccessibleInterface* self, int t);
void QAccessibleInterface_OnSetText(QAccessibleInterface* self, intptr_t slot);
void QAccessibleInterface_QBaseSetText(QAccessibleInterface* self, int t, const libqt_string text);
void QAccessibleInterface_OnRect(const QAccessibleInterface* self, intptr_t slot);
QRect* QAccessibleInterface_QBaseRect(const QAccessibleInterface* self);
void QAccessibleInterface_OnRole(const QAccessibleInterface* self, intptr_t slot);
int QAccessibleInterface_QBaseRole(const QAccessibleInterface* self);
void QAccessibleInterface_OnState(const QAccessibleInterface* self, intptr_t slot);
QAccessible__State* QAccessibleInterface_QBaseState(const QAccessibleInterface* self);
void QAccessibleInterface_OnForegroundColor(const QAccessibleInterface* self, intptr_t slot);
QColor* QAccessibleInterface_QBaseForegroundColor(const QAccessibleInterface* self);
void QAccessibleInterface_OnBackgroundColor(const QAccessibleInterface* self, intptr_t slot);
QColor* QAccessibleInterface_QBaseBackgroundColor(const QAccessibleInterface* self);
void QAccessibleInterface_OnVirtualHook(QAccessibleInterface* self, intptr_t slot);
void QAccessibleInterface_QBaseVirtualHook(QAccessibleInterface* self, int id, void* data);
void QAccessibleInterface_OnInterfaceCast(QAccessibleInterface* self, intptr_t slot);
void* QAccessibleInterface_QBaseInterfaceCast(QAccessibleInterface* self, int param1);
void QAccessibleInterface_OperatorAssign(QAccessibleInterface* self, const QAccessibleInterface* param1);
void QAccessibleInterface_OnOperatorAssign(QAccessibleInterface* self, intptr_t slot);
void QAccessibleInterface_QBaseOperatorAssign(QAccessibleInterface* self, const QAccessibleInterface* param1);

QAccessibleTextInterface* QAccessibleTextInterface_new();
QAccessibleTextInterface* QAccessibleTextInterface_new2(const QAccessibleTextInterface* param1);
void QAccessibleTextInterface_Selection(const QAccessibleTextInterface* self, int selectionIndex, int* startOffset, int* endOffset);
int QAccessibleTextInterface_SelectionCount(const QAccessibleTextInterface* self);
void QAccessibleTextInterface_AddSelection(QAccessibleTextInterface* self, int startOffset, int endOffset);
void QAccessibleTextInterface_RemoveSelection(QAccessibleTextInterface* self, int selectionIndex);
void QAccessibleTextInterface_SetSelection(QAccessibleTextInterface* self, int selectionIndex, int startOffset, int endOffset);
int QAccessibleTextInterface_CursorPosition(const QAccessibleTextInterface* self);
void QAccessibleTextInterface_SetCursorPosition(QAccessibleTextInterface* self, int position);
libqt_string QAccessibleTextInterface_Text(const QAccessibleTextInterface* self, int startOffset, int endOffset);
libqt_string QAccessibleTextInterface_TextBeforeOffset(const QAccessibleTextInterface* self, int offset, int boundaryType, int* startOffset, int* endOffset);
libqt_string QAccessibleTextInterface_TextAfterOffset(const QAccessibleTextInterface* self, int offset, int boundaryType, int* startOffset, int* endOffset);
libqt_string QAccessibleTextInterface_TextAtOffset(const QAccessibleTextInterface* self, int offset, int boundaryType, int* startOffset, int* endOffset);
int QAccessibleTextInterface_CharacterCount(const QAccessibleTextInterface* self);
QRect* QAccessibleTextInterface_CharacterRect(const QAccessibleTextInterface* self, int offset);
int QAccessibleTextInterface_OffsetAtPoint(const QAccessibleTextInterface* self, const QPoint* point);
void QAccessibleTextInterface_ScrollToSubstring(QAccessibleTextInterface* self, int startIndex, int endIndex);
libqt_string QAccessibleTextInterface_Attributes(const QAccessibleTextInterface* self, int offset, int* startOffset, int* endOffset);
void QAccessibleTextInterface_OperatorAssign(QAccessibleTextInterface* self, const QAccessibleTextInterface* param1);
void QAccessibleTextInterface_OnSelection(const QAccessibleTextInterface* self, intptr_t slot);
void QAccessibleTextInterface_QBaseSelection(const QAccessibleTextInterface* self, int selectionIndex, int* startOffset, int* endOffset);
void QAccessibleTextInterface_OnSelectionCount(const QAccessibleTextInterface* self, intptr_t slot);
int QAccessibleTextInterface_QBaseSelectionCount(const QAccessibleTextInterface* self);
void QAccessibleTextInterface_OnAddSelection(QAccessibleTextInterface* self, intptr_t slot);
void QAccessibleTextInterface_QBaseAddSelection(QAccessibleTextInterface* self, int startOffset, int endOffset);
void QAccessibleTextInterface_OnRemoveSelection(QAccessibleTextInterface* self, intptr_t slot);
void QAccessibleTextInterface_QBaseRemoveSelection(QAccessibleTextInterface* self, int selectionIndex);
void QAccessibleTextInterface_OnSetSelection(QAccessibleTextInterface* self, intptr_t slot);
void QAccessibleTextInterface_QBaseSetSelection(QAccessibleTextInterface* self, int selectionIndex, int startOffset, int endOffset);
void QAccessibleTextInterface_OnCursorPosition(const QAccessibleTextInterface* self, intptr_t slot);
int QAccessibleTextInterface_QBaseCursorPosition(const QAccessibleTextInterface* self);
void QAccessibleTextInterface_OnSetCursorPosition(QAccessibleTextInterface* self, intptr_t slot);
void QAccessibleTextInterface_QBaseSetCursorPosition(QAccessibleTextInterface* self, int position);
void QAccessibleTextInterface_OnText(const QAccessibleTextInterface* self, intptr_t slot);
libqt_string QAccessibleTextInterface_QBaseText(const QAccessibleTextInterface* self, int startOffset, int endOffset);
void QAccessibleTextInterface_OnTextBeforeOffset(const QAccessibleTextInterface* self, intptr_t slot);
libqt_string QAccessibleTextInterface_QBaseTextBeforeOffset(const QAccessibleTextInterface* self, int offset, int boundaryType, int* startOffset, int* endOffset);
void QAccessibleTextInterface_OnTextAfterOffset(const QAccessibleTextInterface* self, intptr_t slot);
libqt_string QAccessibleTextInterface_QBaseTextAfterOffset(const QAccessibleTextInterface* self, int offset, int boundaryType, int* startOffset, int* endOffset);
void QAccessibleTextInterface_OnTextAtOffset(const QAccessibleTextInterface* self, intptr_t slot);
libqt_string QAccessibleTextInterface_QBaseTextAtOffset(const QAccessibleTextInterface* self, int offset, int boundaryType, int* startOffset, int* endOffset);
void QAccessibleTextInterface_OnCharacterCount(const QAccessibleTextInterface* self, intptr_t slot);
int QAccessibleTextInterface_QBaseCharacterCount(const QAccessibleTextInterface* self);
void QAccessibleTextInterface_OnCharacterRect(const QAccessibleTextInterface* self, intptr_t slot);
QRect* QAccessibleTextInterface_QBaseCharacterRect(const QAccessibleTextInterface* self, int offset);
void QAccessibleTextInterface_OnOffsetAtPoint(const QAccessibleTextInterface* self, intptr_t slot);
int QAccessibleTextInterface_QBaseOffsetAtPoint(const QAccessibleTextInterface* self, const QPoint* point);
void QAccessibleTextInterface_OnScrollToSubstring(QAccessibleTextInterface* self, intptr_t slot);
void QAccessibleTextInterface_QBaseScrollToSubstring(QAccessibleTextInterface* self, int startIndex, int endIndex);
void QAccessibleTextInterface_OnAttributes(const QAccessibleTextInterface* self, intptr_t slot);
libqt_string QAccessibleTextInterface_QBaseAttributes(const QAccessibleTextInterface* self, int offset, int* startOffset, int* endOffset);
void QAccessibleTextInterface_Delete(QAccessibleTextInterface* self);

QAccessibleEditableTextInterface* QAccessibleEditableTextInterface_new();
QAccessibleEditableTextInterface* QAccessibleEditableTextInterface_new2(const QAccessibleEditableTextInterface* param1);
void QAccessibleEditableTextInterface_DeleteText(QAccessibleEditableTextInterface* self, int startOffset, int endOffset);
void QAccessibleEditableTextInterface_InsertText(QAccessibleEditableTextInterface* self, int offset, const libqt_string text);
void QAccessibleEditableTextInterface_ReplaceText(QAccessibleEditableTextInterface* self, int startOffset, int endOffset, const libqt_string text);
void QAccessibleEditableTextInterface_OperatorAssign(QAccessibleEditableTextInterface* self, const QAccessibleEditableTextInterface* param1);
void QAccessibleEditableTextInterface_OnDeleteText(QAccessibleEditableTextInterface* self, intptr_t slot);
void QAccessibleEditableTextInterface_QBaseDeleteText(QAccessibleEditableTextInterface* self, int startOffset, int endOffset);
void QAccessibleEditableTextInterface_OnInsertText(QAccessibleEditableTextInterface* self, intptr_t slot);
void QAccessibleEditableTextInterface_QBaseInsertText(QAccessibleEditableTextInterface* self, int offset, const libqt_string text);
void QAccessibleEditableTextInterface_OnReplaceText(QAccessibleEditableTextInterface* self, intptr_t slot);
void QAccessibleEditableTextInterface_QBaseReplaceText(QAccessibleEditableTextInterface* self, int startOffset, int endOffset, const libqt_string text);
void QAccessibleEditableTextInterface_Delete(QAccessibleEditableTextInterface* self);

QAccessibleValueInterface* QAccessibleValueInterface_new();
QAccessibleValueInterface* QAccessibleValueInterface_new2(const QAccessibleValueInterface* param1);
QVariant* QAccessibleValueInterface_CurrentValue(const QAccessibleValueInterface* self);
void QAccessibleValueInterface_SetCurrentValue(QAccessibleValueInterface* self, const QVariant* value);
QVariant* QAccessibleValueInterface_MaximumValue(const QAccessibleValueInterface* self);
QVariant* QAccessibleValueInterface_MinimumValue(const QAccessibleValueInterface* self);
QVariant* QAccessibleValueInterface_MinimumStepSize(const QAccessibleValueInterface* self);
void QAccessibleValueInterface_OperatorAssign(QAccessibleValueInterface* self, const QAccessibleValueInterface* param1);
void QAccessibleValueInterface_OnCurrentValue(const QAccessibleValueInterface* self, intptr_t slot);
QVariant* QAccessibleValueInterface_QBaseCurrentValue(const QAccessibleValueInterface* self);
void QAccessibleValueInterface_OnSetCurrentValue(QAccessibleValueInterface* self, intptr_t slot);
void QAccessibleValueInterface_QBaseSetCurrentValue(QAccessibleValueInterface* self, const QVariant* value);
void QAccessibleValueInterface_OnMaximumValue(const QAccessibleValueInterface* self, intptr_t slot);
QVariant* QAccessibleValueInterface_QBaseMaximumValue(const QAccessibleValueInterface* self);
void QAccessibleValueInterface_OnMinimumValue(const QAccessibleValueInterface* self, intptr_t slot);
QVariant* QAccessibleValueInterface_QBaseMinimumValue(const QAccessibleValueInterface* self);
void QAccessibleValueInterface_OnMinimumStepSize(const QAccessibleValueInterface* self, intptr_t slot);
QVariant* QAccessibleValueInterface_QBaseMinimumStepSize(const QAccessibleValueInterface* self);
void QAccessibleValueInterface_Delete(QAccessibleValueInterface* self);

QAccessibleTableCellInterface* QAccessibleTableCellInterface_new();
QAccessibleTableCellInterface* QAccessibleTableCellInterface_new2(const QAccessibleTableCellInterface* param1);
bool QAccessibleTableCellInterface_IsSelected(const QAccessibleTableCellInterface* self);
libqt_list QAccessibleTableCellInterface_ColumnHeaderCells(const QAccessibleTableCellInterface* self);
libqt_list QAccessibleTableCellInterface_RowHeaderCells(const QAccessibleTableCellInterface* self);
int QAccessibleTableCellInterface_ColumnIndex(const QAccessibleTableCellInterface* self);
int QAccessibleTableCellInterface_RowIndex(const QAccessibleTableCellInterface* self);
int QAccessibleTableCellInterface_ColumnExtent(const QAccessibleTableCellInterface* self);
int QAccessibleTableCellInterface_RowExtent(const QAccessibleTableCellInterface* self);
QAccessibleInterface* QAccessibleTableCellInterface_Table(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OperatorAssign(QAccessibleTableCellInterface* self, const QAccessibleTableCellInterface* param1);
void QAccessibleTableCellInterface_OnIsSelected(const QAccessibleTableCellInterface* self, intptr_t slot);
bool QAccessibleTableCellInterface_QBaseIsSelected(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnColumnHeaderCells(const QAccessibleTableCellInterface* self, intptr_t slot);
libqt_list QAccessibleTableCellInterface_QBaseColumnHeaderCells(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnRowHeaderCells(const QAccessibleTableCellInterface* self, intptr_t slot);
libqt_list QAccessibleTableCellInterface_QBaseRowHeaderCells(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnColumnIndex(const QAccessibleTableCellInterface* self, intptr_t slot);
int QAccessibleTableCellInterface_QBaseColumnIndex(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnRowIndex(const QAccessibleTableCellInterface* self, intptr_t slot);
int QAccessibleTableCellInterface_QBaseRowIndex(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnColumnExtent(const QAccessibleTableCellInterface* self, intptr_t slot);
int QAccessibleTableCellInterface_QBaseColumnExtent(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnRowExtent(const QAccessibleTableCellInterface* self, intptr_t slot);
int QAccessibleTableCellInterface_QBaseRowExtent(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_OnTable(const QAccessibleTableCellInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleTableCellInterface_QBaseTable(const QAccessibleTableCellInterface* self);
void QAccessibleTableCellInterface_Delete(QAccessibleTableCellInterface* self);

QAccessibleTableInterface* QAccessibleTableInterface_new();
QAccessibleTableInterface* QAccessibleTableInterface_new2(const QAccessibleTableInterface* param1);
QAccessibleInterface* QAccessibleTableInterface_Caption(const QAccessibleTableInterface* self);
QAccessibleInterface* QAccessibleTableInterface_Summary(const QAccessibleTableInterface* self);
QAccessibleInterface* QAccessibleTableInterface_CellAt(const QAccessibleTableInterface* self, int row, int column);
int QAccessibleTableInterface_SelectedCellCount(const QAccessibleTableInterface* self);
libqt_list QAccessibleTableInterface_SelectedCells(const QAccessibleTableInterface* self);
libqt_string QAccessibleTableInterface_ColumnDescription(const QAccessibleTableInterface* self, int column);
libqt_string QAccessibleTableInterface_RowDescription(const QAccessibleTableInterface* self, int row);
int QAccessibleTableInterface_SelectedColumnCount(const QAccessibleTableInterface* self);
int QAccessibleTableInterface_SelectedRowCount(const QAccessibleTableInterface* self);
int QAccessibleTableInterface_ColumnCount(const QAccessibleTableInterface* self);
int QAccessibleTableInterface_RowCount(const QAccessibleTableInterface* self);
libqt_list QAccessibleTableInterface_SelectedColumns(const QAccessibleTableInterface* self);
libqt_list QAccessibleTableInterface_SelectedRows(const QAccessibleTableInterface* self);
bool QAccessibleTableInterface_IsColumnSelected(const QAccessibleTableInterface* self, int column);
bool QAccessibleTableInterface_IsRowSelected(const QAccessibleTableInterface* self, int row);
bool QAccessibleTableInterface_SelectRow(QAccessibleTableInterface* self, int row);
bool QAccessibleTableInterface_SelectColumn(QAccessibleTableInterface* self, int column);
bool QAccessibleTableInterface_UnselectRow(QAccessibleTableInterface* self, int row);
bool QAccessibleTableInterface_UnselectColumn(QAccessibleTableInterface* self, int column);
void QAccessibleTableInterface_ModelChange(QAccessibleTableInterface* self, QAccessibleTableModelChangeEvent* event);
void QAccessibleTableInterface_OnCaption(const QAccessibleTableInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleTableInterface_QBaseCaption(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnSummary(const QAccessibleTableInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleTableInterface_QBaseSummary(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnCellAt(const QAccessibleTableInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleTableInterface_QBaseCellAt(const QAccessibleTableInterface* self, int row, int column);
void QAccessibleTableInterface_OnSelectedCellCount(const QAccessibleTableInterface* self, intptr_t slot);
int QAccessibleTableInterface_QBaseSelectedCellCount(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnSelectedCells(const QAccessibleTableInterface* self, intptr_t slot);
libqt_list QAccessibleTableInterface_QBaseSelectedCells(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnColumnDescription(const QAccessibleTableInterface* self, intptr_t slot);
libqt_string QAccessibleTableInterface_QBaseColumnDescription(const QAccessibleTableInterface* self, int column);
void QAccessibleTableInterface_OnRowDescription(const QAccessibleTableInterface* self, intptr_t slot);
libqt_string QAccessibleTableInterface_QBaseRowDescription(const QAccessibleTableInterface* self, int row);
void QAccessibleTableInterface_OnSelectedColumnCount(const QAccessibleTableInterface* self, intptr_t slot);
int QAccessibleTableInterface_QBaseSelectedColumnCount(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnSelectedRowCount(const QAccessibleTableInterface* self, intptr_t slot);
int QAccessibleTableInterface_QBaseSelectedRowCount(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnColumnCount(const QAccessibleTableInterface* self, intptr_t slot);
int QAccessibleTableInterface_QBaseColumnCount(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnRowCount(const QAccessibleTableInterface* self, intptr_t slot);
int QAccessibleTableInterface_QBaseRowCount(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnSelectedColumns(const QAccessibleTableInterface* self, intptr_t slot);
libqt_list QAccessibleTableInterface_QBaseSelectedColumns(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnSelectedRows(const QAccessibleTableInterface* self, intptr_t slot);
libqt_list QAccessibleTableInterface_QBaseSelectedRows(const QAccessibleTableInterface* self);
void QAccessibleTableInterface_OnIsColumnSelected(const QAccessibleTableInterface* self, intptr_t slot);
bool QAccessibleTableInterface_QBaseIsColumnSelected(const QAccessibleTableInterface* self, int column);
void QAccessibleTableInterface_OnIsRowSelected(const QAccessibleTableInterface* self, intptr_t slot);
bool QAccessibleTableInterface_QBaseIsRowSelected(const QAccessibleTableInterface* self, int row);
void QAccessibleTableInterface_OnSelectRow(QAccessibleTableInterface* self, intptr_t slot);
bool QAccessibleTableInterface_QBaseSelectRow(QAccessibleTableInterface* self, int row);
void QAccessibleTableInterface_OnSelectColumn(QAccessibleTableInterface* self, intptr_t slot);
bool QAccessibleTableInterface_QBaseSelectColumn(QAccessibleTableInterface* self, int column);
void QAccessibleTableInterface_OnUnselectRow(QAccessibleTableInterface* self, intptr_t slot);
bool QAccessibleTableInterface_QBaseUnselectRow(QAccessibleTableInterface* self, int row);
void QAccessibleTableInterface_OnUnselectColumn(QAccessibleTableInterface* self, intptr_t slot);
bool QAccessibleTableInterface_QBaseUnselectColumn(QAccessibleTableInterface* self, int column);
void QAccessibleTableInterface_OnModelChange(QAccessibleTableInterface* self, intptr_t slot);
void QAccessibleTableInterface_QBaseModelChange(QAccessibleTableInterface* self, QAccessibleTableModelChangeEvent* event);
void QAccessibleTableInterface_OperatorAssign(QAccessibleTableInterface* self, const QAccessibleTableInterface* param1);
void QAccessibleTableInterface_OnOperatorAssign(QAccessibleTableInterface* self, intptr_t slot);
void QAccessibleTableInterface_QBaseOperatorAssign(QAccessibleTableInterface* self, const QAccessibleTableInterface* param1);
void QAccessibleTableInterface_Delete(QAccessibleTableInterface* self);

QAccessibleActionInterface* QAccessibleActionInterface_new();
QAccessibleActionInterface* QAccessibleActionInterface_new2(const QAccessibleActionInterface* param1);
libqt_string QAccessibleActionInterface_Tr(const char* sourceText);
libqt_list QAccessibleActionInterface_ActionNames(const QAccessibleActionInterface* self);
libqt_string QAccessibleActionInterface_LocalizedActionName(const QAccessibleActionInterface* self, const libqt_string name);
libqt_string QAccessibleActionInterface_LocalizedActionDescription(const QAccessibleActionInterface* self, const libqt_string name);
void QAccessibleActionInterface_DoAction(QAccessibleActionInterface* self, const libqt_string actionName);
libqt_list QAccessibleActionInterface_KeyBindingsForAction(const QAccessibleActionInterface* self, const libqt_string actionName);
libqt_string QAccessibleActionInterface_PressAction();
libqt_string QAccessibleActionInterface_IncreaseAction();
libqt_string QAccessibleActionInterface_DecreaseAction();
libqt_string QAccessibleActionInterface_ShowMenuAction();
libqt_string QAccessibleActionInterface_SetFocusAction();
libqt_string QAccessibleActionInterface_ToggleAction();
libqt_string QAccessibleActionInterface_ScrollLeftAction();
libqt_string QAccessibleActionInterface_ScrollRightAction();
libqt_string QAccessibleActionInterface_ScrollUpAction();
libqt_string QAccessibleActionInterface_ScrollDownAction();
libqt_string QAccessibleActionInterface_NextPageAction();
libqt_string QAccessibleActionInterface_PreviousPageAction();
void QAccessibleActionInterface_OperatorAssign(QAccessibleActionInterface* self, const QAccessibleActionInterface* param1);
libqt_string QAccessibleActionInterface_Tr2(const char* sourceText, const char* disambiguation);
libqt_string QAccessibleActionInterface_Tr3(const char* sourceText, const char* disambiguation, int n);
void QAccessibleActionInterface_OnActionNames(const QAccessibleActionInterface* self, intptr_t slot);
libqt_list QAccessibleActionInterface_QBaseActionNames(const QAccessibleActionInterface* self);
void QAccessibleActionInterface_OnLocalizedActionName(const QAccessibleActionInterface* self, intptr_t slot);
libqt_string QAccessibleActionInterface_QBaseLocalizedActionName(const QAccessibleActionInterface* self, const libqt_string name);
void QAccessibleActionInterface_OnLocalizedActionDescription(const QAccessibleActionInterface* self, intptr_t slot);
libqt_string QAccessibleActionInterface_QBaseLocalizedActionDescription(const QAccessibleActionInterface* self, const libqt_string name);
void QAccessibleActionInterface_OnDoAction(QAccessibleActionInterface* self, intptr_t slot);
void QAccessibleActionInterface_QBaseDoAction(QAccessibleActionInterface* self, const libqt_string actionName);
void QAccessibleActionInterface_OnKeyBindingsForAction(const QAccessibleActionInterface* self, intptr_t slot);
libqt_list QAccessibleActionInterface_QBaseKeyBindingsForAction(const QAccessibleActionInterface* self, const libqt_string actionName);
void QAccessibleActionInterface_Delete(QAccessibleActionInterface* self);

QAccessibleImageInterface* QAccessibleImageInterface_new();
QAccessibleImageInterface* QAccessibleImageInterface_new2(const QAccessibleImageInterface* param1);
libqt_string QAccessibleImageInterface_ImageDescription(const QAccessibleImageInterface* self);
QSize* QAccessibleImageInterface_ImageSize(const QAccessibleImageInterface* self);
QPoint* QAccessibleImageInterface_ImagePosition(const QAccessibleImageInterface* self);
void QAccessibleImageInterface_OperatorAssign(QAccessibleImageInterface* self, const QAccessibleImageInterface* param1);
void QAccessibleImageInterface_OnImageDescription(const QAccessibleImageInterface* self, intptr_t slot);
libqt_string QAccessibleImageInterface_QBaseImageDescription(const QAccessibleImageInterface* self);
void QAccessibleImageInterface_OnImageSize(const QAccessibleImageInterface* self, intptr_t slot);
QSize* QAccessibleImageInterface_QBaseImageSize(const QAccessibleImageInterface* self);
void QAccessibleImageInterface_OnImagePosition(const QAccessibleImageInterface* self, intptr_t slot);
QPoint* QAccessibleImageInterface_QBaseImagePosition(const QAccessibleImageInterface* self);
void QAccessibleImageInterface_Delete(QAccessibleImageInterface* self);

QAccessibleHyperlinkInterface* QAccessibleHyperlinkInterface_new();
QAccessibleHyperlinkInterface* QAccessibleHyperlinkInterface_new2(const QAccessibleHyperlinkInterface* param1);
libqt_string QAccessibleHyperlinkInterface_Anchor(const QAccessibleHyperlinkInterface* self);
libqt_string QAccessibleHyperlinkInterface_AnchorTarget(const QAccessibleHyperlinkInterface* self);
int QAccessibleHyperlinkInterface_StartIndex(const QAccessibleHyperlinkInterface* self);
int QAccessibleHyperlinkInterface_EndIndex(const QAccessibleHyperlinkInterface* self);
bool QAccessibleHyperlinkInterface_IsValid(const QAccessibleHyperlinkInterface* self);
void QAccessibleHyperlinkInterface_OperatorAssign(QAccessibleHyperlinkInterface* self, const QAccessibleHyperlinkInterface* param1);
void QAccessibleHyperlinkInterface_OnAnchor(const QAccessibleHyperlinkInterface* self, intptr_t slot);
libqt_string QAccessibleHyperlinkInterface_QBaseAnchor(const QAccessibleHyperlinkInterface* self);
void QAccessibleHyperlinkInterface_OnAnchorTarget(const QAccessibleHyperlinkInterface* self, intptr_t slot);
libqt_string QAccessibleHyperlinkInterface_QBaseAnchorTarget(const QAccessibleHyperlinkInterface* self);
void QAccessibleHyperlinkInterface_OnStartIndex(const QAccessibleHyperlinkInterface* self, intptr_t slot);
int QAccessibleHyperlinkInterface_QBaseStartIndex(const QAccessibleHyperlinkInterface* self);
void QAccessibleHyperlinkInterface_OnEndIndex(const QAccessibleHyperlinkInterface* self, intptr_t slot);
int QAccessibleHyperlinkInterface_QBaseEndIndex(const QAccessibleHyperlinkInterface* self);
void QAccessibleHyperlinkInterface_OnIsValid(const QAccessibleHyperlinkInterface* self, intptr_t slot);
bool QAccessibleHyperlinkInterface_QBaseIsValid(const QAccessibleHyperlinkInterface* self);
void QAccessibleHyperlinkInterface_Delete(QAccessibleHyperlinkInterface* self);

QAccessibleSelectionInterface* QAccessibleSelectionInterface_new();
QAccessibleSelectionInterface* QAccessibleSelectionInterface_new2(const QAccessibleSelectionInterface* param1);
int QAccessibleSelectionInterface_SelectedItemCount(const QAccessibleSelectionInterface* self);
libqt_list QAccessibleSelectionInterface_SelectedItems(const QAccessibleSelectionInterface* self);
QAccessibleInterface* QAccessibleSelectionInterface_SelectedItem(const QAccessibleSelectionInterface* self, int selectionIndex);
bool QAccessibleSelectionInterface_IsSelected(const QAccessibleSelectionInterface* self, QAccessibleInterface* childItem);
bool QAccessibleSelectionInterface_Select(QAccessibleSelectionInterface* self, QAccessibleInterface* childItem);
bool QAccessibleSelectionInterface_Unselect(QAccessibleSelectionInterface* self, QAccessibleInterface* childItem);
bool QAccessibleSelectionInterface_SelectAll(QAccessibleSelectionInterface* self);
bool QAccessibleSelectionInterface_Clear(QAccessibleSelectionInterface* self);
void QAccessibleSelectionInterface_OperatorAssign(QAccessibleSelectionInterface* self, const QAccessibleSelectionInterface* param1);
void QAccessibleSelectionInterface_OnSelectedItemCount(const QAccessibleSelectionInterface* self, intptr_t slot);
int QAccessibleSelectionInterface_QBaseSelectedItemCount(const QAccessibleSelectionInterface* self);
void QAccessibleSelectionInterface_OnSelectedItems(const QAccessibleSelectionInterface* self, intptr_t slot);
libqt_list QAccessibleSelectionInterface_QBaseSelectedItems(const QAccessibleSelectionInterface* self);
void QAccessibleSelectionInterface_OnSelectedItem(const QAccessibleSelectionInterface* self, intptr_t slot);
QAccessibleInterface* QAccessibleSelectionInterface_QBaseSelectedItem(const QAccessibleSelectionInterface* self, int selectionIndex);
void QAccessibleSelectionInterface_OnIsSelected(const QAccessibleSelectionInterface* self, intptr_t slot);
bool QAccessibleSelectionInterface_QBaseIsSelected(const QAccessibleSelectionInterface* self, QAccessibleInterface* childItem);
void QAccessibleSelectionInterface_OnSelect(QAccessibleSelectionInterface* self, intptr_t slot);
bool QAccessibleSelectionInterface_QBaseSelect(QAccessibleSelectionInterface* self, QAccessibleInterface* childItem);
void QAccessibleSelectionInterface_OnUnselect(QAccessibleSelectionInterface* self, intptr_t slot);
bool QAccessibleSelectionInterface_QBaseUnselect(QAccessibleSelectionInterface* self, QAccessibleInterface* childItem);
void QAccessibleSelectionInterface_OnSelectAll(QAccessibleSelectionInterface* self, intptr_t slot);
bool QAccessibleSelectionInterface_QBaseSelectAll(QAccessibleSelectionInterface* self);
void QAccessibleSelectionInterface_OnClear(QAccessibleSelectionInterface* self, intptr_t slot);
bool QAccessibleSelectionInterface_QBaseClear(QAccessibleSelectionInterface* self);
void QAccessibleSelectionInterface_Delete(QAccessibleSelectionInterface* self);

QAccessibleAttributesInterface* QAccessibleAttributesInterface_new();
QAccessibleAttributesInterface* QAccessibleAttributesInterface_new2(const QAccessibleAttributesInterface* param1);
libqt_list QAccessibleAttributesInterface_AttributeKeys(const QAccessibleAttributesInterface* self);
QVariant* QAccessibleAttributesInterface_AttributeValue(const QAccessibleAttributesInterface* self, int key);
void QAccessibleAttributesInterface_OperatorAssign(QAccessibleAttributesInterface* self, const QAccessibleAttributesInterface* param1);
void QAccessibleAttributesInterface_OnAttributeKeys(const QAccessibleAttributesInterface* self, intptr_t slot);
libqt_list QAccessibleAttributesInterface_QBaseAttributeKeys(const QAccessibleAttributesInterface* self);
void QAccessibleAttributesInterface_OnAttributeValue(const QAccessibleAttributesInterface* self, intptr_t slot);
QVariant* QAccessibleAttributesInterface_QBaseAttributeValue(const QAccessibleAttributesInterface* self, int key);
void QAccessibleAttributesInterface_Delete(QAccessibleAttributesInterface* self);

QAccessibleEvent* QAccessibleEvent_new(QObject* obj, int typ);
QAccessibleEvent* QAccessibleEvent_new2(QAccessibleInterface* iface, int typ);
int QAccessibleEvent_Type(const QAccessibleEvent* self);
QObject* QAccessibleEvent_Object(const QAccessibleEvent* self);
unsigned int QAccessibleEvent_UniqueId(const QAccessibleEvent* self);
void QAccessibleEvent_SetChild(QAccessibleEvent* self, int chld);
int QAccessibleEvent_Child(const QAccessibleEvent* self);
QAccessibleInterface* QAccessibleEvent_AccessibleInterface(const QAccessibleEvent* self);
void QAccessibleEvent_OnAccessibleInterface(const QAccessibleEvent* self, intptr_t slot);
QAccessibleInterface* QAccessibleEvent_QBaseAccessibleInterface(const QAccessibleEvent* self);
void QAccessibleEvent_Delete(QAccessibleEvent* self);

QAccessibleStateChangeEvent* QAccessibleStateChangeEvent_new(QObject* obj, QAccessible__State* state);
QAccessibleStateChangeEvent* QAccessibleStateChangeEvent_new2(QAccessibleInterface* iface, QAccessible__State* state);
QAccessible__State* QAccessibleStateChangeEvent_ChangedStates(const QAccessibleStateChangeEvent* self);
void QAccessibleStateChangeEvent_Delete(QAccessibleStateChangeEvent* self);

QAccessibleTextCursorEvent* QAccessibleTextCursorEvent_new(QObject* obj, int cursorPos);
QAccessibleTextCursorEvent* QAccessibleTextCursorEvent_new2(QAccessibleInterface* iface, int cursorPos);
void QAccessibleTextCursorEvent_SetCursorPosition(QAccessibleTextCursorEvent* self, int position);
int QAccessibleTextCursorEvent_CursorPosition(const QAccessibleTextCursorEvent* self);
void QAccessibleTextCursorEvent_Delete(QAccessibleTextCursorEvent* self);

QAccessibleTextSelectionEvent* QAccessibleTextSelectionEvent_new(QObject* obj, int start, int end);
QAccessibleTextSelectionEvent* QAccessibleTextSelectionEvent_new2(QAccessibleInterface* iface, int start, int end);
void QAccessibleTextSelectionEvent_SetSelection(QAccessibleTextSelectionEvent* self, int start, int end);
int QAccessibleTextSelectionEvent_SelectionStart(const QAccessibleTextSelectionEvent* self);
int QAccessibleTextSelectionEvent_SelectionEnd(const QAccessibleTextSelectionEvent* self);
void QAccessibleTextSelectionEvent_Delete(QAccessibleTextSelectionEvent* self);

QAccessibleTextInsertEvent* QAccessibleTextInsertEvent_new(QObject* obj, int position, const libqt_string text);
QAccessibleTextInsertEvent* QAccessibleTextInsertEvent_new2(QAccessibleInterface* iface, int position, const libqt_string text);
libqt_string QAccessibleTextInsertEvent_TextInserted(const QAccessibleTextInsertEvent* self);
int QAccessibleTextInsertEvent_ChangePosition(const QAccessibleTextInsertEvent* self);
void QAccessibleTextInsertEvent_Delete(QAccessibleTextInsertEvent* self);

QAccessibleTextRemoveEvent* QAccessibleTextRemoveEvent_new(QObject* obj, int position, const libqt_string text);
QAccessibleTextRemoveEvent* QAccessibleTextRemoveEvent_new2(QAccessibleInterface* iface, int position, const libqt_string text);
libqt_string QAccessibleTextRemoveEvent_TextRemoved(const QAccessibleTextRemoveEvent* self);
int QAccessibleTextRemoveEvent_ChangePosition(const QAccessibleTextRemoveEvent* self);
void QAccessibleTextRemoveEvent_Delete(QAccessibleTextRemoveEvent* self);

QAccessibleTextUpdateEvent* QAccessibleTextUpdateEvent_new(QObject* obj, int position, const libqt_string oldText, const libqt_string text);
QAccessibleTextUpdateEvent* QAccessibleTextUpdateEvent_new2(QAccessibleInterface* iface, int position, const libqt_string oldText, const libqt_string text);
libqt_string QAccessibleTextUpdateEvent_TextRemoved(const QAccessibleTextUpdateEvent* self);
libqt_string QAccessibleTextUpdateEvent_TextInserted(const QAccessibleTextUpdateEvent* self);
int QAccessibleTextUpdateEvent_ChangePosition(const QAccessibleTextUpdateEvent* self);
void QAccessibleTextUpdateEvent_Delete(QAccessibleTextUpdateEvent* self);

QAccessibleValueChangeEvent* QAccessibleValueChangeEvent_new(QObject* obj, const QVariant* val);
QAccessibleValueChangeEvent* QAccessibleValueChangeEvent_new2(QAccessibleInterface* iface, const QVariant* val);
void QAccessibleValueChangeEvent_SetValue(QAccessibleValueChangeEvent* self, const QVariant* val);
QVariant* QAccessibleValueChangeEvent_Value(const QAccessibleValueChangeEvent* self);
void QAccessibleValueChangeEvent_Delete(QAccessibleValueChangeEvent* self);

QAccessibleTableModelChangeEvent* QAccessibleTableModelChangeEvent_new(QObject* obj, int changeType);
QAccessibleTableModelChangeEvent* QAccessibleTableModelChangeEvent_new2(QAccessibleInterface* iface, int changeType);
void QAccessibleTableModelChangeEvent_SetModelChangeType(QAccessibleTableModelChangeEvent* self, int changeType);
int QAccessibleTableModelChangeEvent_ModelChangeType(const QAccessibleTableModelChangeEvent* self);
void QAccessibleTableModelChangeEvent_SetFirstRow(QAccessibleTableModelChangeEvent* self, int row);
void QAccessibleTableModelChangeEvent_SetFirstColumn(QAccessibleTableModelChangeEvent* self, int col);
void QAccessibleTableModelChangeEvent_SetLastRow(QAccessibleTableModelChangeEvent* self, int row);
void QAccessibleTableModelChangeEvent_SetLastColumn(QAccessibleTableModelChangeEvent* self, int col);
int QAccessibleTableModelChangeEvent_FirstRow(const QAccessibleTableModelChangeEvent* self);
int QAccessibleTableModelChangeEvent_FirstColumn(const QAccessibleTableModelChangeEvent* self);
int QAccessibleTableModelChangeEvent_LastRow(const QAccessibleTableModelChangeEvent* self);
int QAccessibleTableModelChangeEvent_LastColumn(const QAccessibleTableModelChangeEvent* self);
void QAccessibleTableModelChangeEvent_Delete(QAccessibleTableModelChangeEvent* self);

QAccessibleAnnouncementEvent* QAccessibleAnnouncementEvent_new(QObject* object, const libqt_string message);
QAccessibleAnnouncementEvent* QAccessibleAnnouncementEvent_new2(QAccessibleInterface* iface, const libqt_string message);
libqt_string QAccessibleAnnouncementEvent_Message(const QAccessibleAnnouncementEvent* self);
int QAccessibleAnnouncementEvent_Politeness(const QAccessibleAnnouncementEvent* self);
void QAccessibleAnnouncementEvent_SetPoliteness(QAccessibleAnnouncementEvent* self, int politeness);
void QAccessibleAnnouncementEvent_Delete(QAccessibleAnnouncementEvent* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
