#pragma once
#ifndef SRCC_LIBQCOMBOBOX_H
#define SRCC_LIBQCOMBOBOX_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QCompleter QCompleter;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QIcon QIcon;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QValidator QValidator;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QComboBox* QComboBox_new(QWidget* parent);
QComboBox* QComboBox_new2();
QMetaObject* QComboBox_MetaObject(const QComboBox* self);
void* QComboBox_Metacast(QComboBox* self, const char* param1);
int QComboBox_Metacall(QComboBox* self, int param1, int param2, void** param3);
libqt_string QComboBox_Tr(const char* s);
int QComboBox_MaxVisibleItems(const QComboBox* self);
void QComboBox_SetMaxVisibleItems(QComboBox* self, int maxItems);
int QComboBox_Count(const QComboBox* self);
void QComboBox_SetMaxCount(QComboBox* self, int max);
int QComboBox_MaxCount(const QComboBox* self);
bool QComboBox_DuplicatesEnabled(const QComboBox* self);
void QComboBox_SetDuplicatesEnabled(QComboBox* self, bool enable);
void QComboBox_SetFrame(QComboBox* self, bool frame);
bool QComboBox_HasFrame(const QComboBox* self);
int QComboBox_FindText(const QComboBox* self, const libqt_string text);
int QComboBox_FindData(const QComboBox* self, const QVariant* data);
int QComboBox_InsertPolicy(const QComboBox* self);
void QComboBox_SetInsertPolicy(QComboBox* self, int policy);
int QComboBox_SizeAdjustPolicy(const QComboBox* self);
void QComboBox_SetSizeAdjustPolicy(QComboBox* self, int policy);
int QComboBox_MinimumContentsLength(const QComboBox* self);
void QComboBox_SetMinimumContentsLength(QComboBox* self, int characters);
QSize* QComboBox_IconSize(const QComboBox* self);
void QComboBox_SetIconSize(QComboBox* self, const QSize* size);
void QComboBox_SetPlaceholderText(QComboBox* self, const libqt_string placeholderText);
libqt_string QComboBox_PlaceholderText(const QComboBox* self);
bool QComboBox_IsEditable(const QComboBox* self);
void QComboBox_SetEditable(QComboBox* self, bool editable);
void QComboBox_SetLineEdit(QComboBox* self, QLineEdit* edit);
QLineEdit* QComboBox_LineEdit(const QComboBox* self);
void QComboBox_SetValidator(QComboBox* self, const QValidator* v);
QValidator* QComboBox_Validator(const QComboBox* self);
void QComboBox_SetCompleter(QComboBox* self, QCompleter* c);
QCompleter* QComboBox_Completer(const QComboBox* self);
QAbstractItemDelegate* QComboBox_ItemDelegate(const QComboBox* self);
void QComboBox_SetItemDelegate(QComboBox* self, QAbstractItemDelegate* delegate);
QAbstractItemModel* QComboBox_Model(const QComboBox* self);
void QComboBox_SetModel(QComboBox* self, QAbstractItemModel* model);
QModelIndex* QComboBox_RootModelIndex(const QComboBox* self);
void QComboBox_SetRootModelIndex(QComboBox* self, const QModelIndex* index);
int QComboBox_ModelColumn(const QComboBox* self);
void QComboBox_SetModelColumn(QComboBox* self, int visibleColumn);
int QComboBox_CurrentIndex(const QComboBox* self);
libqt_string QComboBox_CurrentText(const QComboBox* self);
QVariant* QComboBox_CurrentData(const QComboBox* self);
libqt_string QComboBox_ItemText(const QComboBox* self, int index);
QIcon* QComboBox_ItemIcon(const QComboBox* self, int index);
QVariant* QComboBox_ItemData(const QComboBox* self, int index);
void QComboBox_AddItem(QComboBox* self, const libqt_string text);
void QComboBox_AddItem2(QComboBox* self, const QIcon* icon, const libqt_string text);
void QComboBox_AddItems(QComboBox* self, const libqt_list /* of libqt_string */ texts);
void QComboBox_InsertItem(QComboBox* self, int index, const libqt_string text);
void QComboBox_InsertItem2(QComboBox* self, int index, const QIcon* icon, const libqt_string text);
void QComboBox_InsertItems(QComboBox* self, int index, const libqt_list /* of libqt_string */ texts);
void QComboBox_InsertSeparator(QComboBox* self, int index);
void QComboBox_RemoveItem(QComboBox* self, int index);
void QComboBox_SetItemText(QComboBox* self, int index, const libqt_string text);
void QComboBox_SetItemIcon(QComboBox* self, int index, const QIcon* icon);
void QComboBox_SetItemData(QComboBox* self, int index, const QVariant* value);
QAbstractItemView* QComboBox_View(const QComboBox* self);
void QComboBox_SetView(QComboBox* self, QAbstractItemView* itemView);
QSize* QComboBox_SizeHint(const QComboBox* self);
QSize* QComboBox_MinimumSizeHint(const QComboBox* self);
void QComboBox_ShowPopup(QComboBox* self);
void QComboBox_HidePopup(QComboBox* self);
bool QComboBox_Event(QComboBox* self, QEvent* event);
QVariant* QComboBox_InputMethodQuery(const QComboBox* self, int param1);
QVariant* QComboBox_InputMethodQuery2(const QComboBox* self, int query, const QVariant* argument);
void QComboBox_Clear(QComboBox* self);
void QComboBox_ClearEditText(QComboBox* self);
void QComboBox_SetEditText(QComboBox* self, const libqt_string text);
void QComboBox_SetCurrentIndex(QComboBox* self, int index);
void QComboBox_SetCurrentText(QComboBox* self, const libqt_string text);
void QComboBox_EditTextChanged(QComboBox* self, const libqt_string param1);
void QComboBox_Connect_EditTextChanged(QComboBox* self, intptr_t slot);
void QComboBox_Activated(QComboBox* self, int index);
void QComboBox_Connect_Activated(QComboBox* self, intptr_t slot);
void QComboBox_TextActivated(QComboBox* self, const libqt_string param1);
void QComboBox_Connect_TextActivated(QComboBox* self, intptr_t slot);
void QComboBox_Highlighted(QComboBox* self, int index);
void QComboBox_Connect_Highlighted(QComboBox* self, intptr_t slot);
void QComboBox_TextHighlighted(QComboBox* self, const libqt_string param1);
void QComboBox_Connect_TextHighlighted(QComboBox* self, intptr_t slot);
void QComboBox_CurrentIndexChanged(QComboBox* self, int index);
void QComboBox_Connect_CurrentIndexChanged(QComboBox* self, intptr_t slot);
void QComboBox_CurrentTextChanged(QComboBox* self, const libqt_string param1);
void QComboBox_Connect_CurrentTextChanged(QComboBox* self, intptr_t slot);
void QComboBox_FocusInEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_FocusOutEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_ChangeEvent(QComboBox* self, QEvent* e);
void QComboBox_ResizeEvent(QComboBox* self, QResizeEvent* e);
void QComboBox_PaintEvent(QComboBox* self, QPaintEvent* e);
void QComboBox_ShowEvent(QComboBox* self, QShowEvent* e);
void QComboBox_HideEvent(QComboBox* self, QHideEvent* e);
void QComboBox_MousePressEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_MouseReleaseEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_KeyPressEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_KeyReleaseEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_WheelEvent(QComboBox* self, QWheelEvent* e);
void QComboBox_ContextMenuEvent(QComboBox* self, QContextMenuEvent* e);
void QComboBox_InputMethodEvent(QComboBox* self, QInputMethodEvent* param1);
void QComboBox_InitStyleOption(const QComboBox* self, QStyleOptionComboBox* option);
libqt_string QComboBox_Tr2(const char* s, const char* c);
libqt_string QComboBox_Tr3(const char* s, const char* c, int n);
int QComboBox_FindText2(const QComboBox* self, const libqt_string text, int flags);
int QComboBox_FindData2(const QComboBox* self, const QVariant* data, int role);
int QComboBox_FindData3(const QComboBox* self, const QVariant* data, int role, int flags);
QVariant* QComboBox_CurrentData1(const QComboBox* self, int role);
QVariant* QComboBox_ItemData2(const QComboBox* self, int index, int role);
void QComboBox_AddItem22(QComboBox* self, const libqt_string text, const QVariant* userData);
void QComboBox_AddItem3(QComboBox* self, const QIcon* icon, const libqt_string text, const QVariant* userData);
void QComboBox_InsertItem3(QComboBox* self, int index, const libqt_string text, const QVariant* userData);
void QComboBox_InsertItem4(QComboBox* self, int index, const QIcon* icon, const libqt_string text, const QVariant* userData);
void QComboBox_SetItemData3(QComboBox* self, int index, const QVariant* value, int role);
void QComboBox_OnMetacall(QComboBox* self, intptr_t slot);
int QComboBox_QBaseMetacall(QComboBox* self, int param1, int param2, void** param3);
void QComboBox_OnSetModel(QComboBox* self, intptr_t slot);
void QComboBox_QBaseSetModel(QComboBox* self, QAbstractItemModel* model);
void QComboBox_OnSizeHint(const QComboBox* self, intptr_t slot);
QSize* QComboBox_QBaseSizeHint(const QComboBox* self);
void QComboBox_OnMinimumSizeHint(const QComboBox* self, intptr_t slot);
QSize* QComboBox_QBaseMinimumSizeHint(const QComboBox* self);
void QComboBox_OnShowPopup(QComboBox* self, intptr_t slot);
void QComboBox_QBaseShowPopup(QComboBox* self);
void QComboBox_OnHidePopup(QComboBox* self, intptr_t slot);
void QComboBox_QBaseHidePopup(QComboBox* self);
void QComboBox_OnEvent(QComboBox* self, intptr_t slot);
bool QComboBox_QBaseEvent(QComboBox* self, QEvent* event);
void QComboBox_OnInputMethodQuery(const QComboBox* self, intptr_t slot);
QVariant* QComboBox_QBaseInputMethodQuery(const QComboBox* self, int param1);
void QComboBox_OnFocusInEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseFocusInEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_OnFocusOutEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseFocusOutEvent(QComboBox* self, QFocusEvent* e);
void QComboBox_OnChangeEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseChangeEvent(QComboBox* self, QEvent* e);
void QComboBox_OnResizeEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseResizeEvent(QComboBox* self, QResizeEvent* e);
void QComboBox_OnPaintEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBasePaintEvent(QComboBox* self, QPaintEvent* e);
void QComboBox_OnShowEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseShowEvent(QComboBox* self, QShowEvent* e);
void QComboBox_OnHideEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseHideEvent(QComboBox* self, QHideEvent* e);
void QComboBox_OnMousePressEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseMousePressEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_OnMouseReleaseEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseMouseReleaseEvent(QComboBox* self, QMouseEvent* e);
void QComboBox_OnKeyPressEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseKeyPressEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_OnKeyReleaseEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseKeyReleaseEvent(QComboBox* self, QKeyEvent* e);
void QComboBox_OnWheelEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseWheelEvent(QComboBox* self, QWheelEvent* e);
void QComboBox_OnContextMenuEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseContextMenuEvent(QComboBox* self, QContextMenuEvent* e);
void QComboBox_OnInputMethodEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseInputMethodEvent(QComboBox* self, QInputMethodEvent* param1);
void QComboBox_OnInitStyleOption(const QComboBox* self, intptr_t slot);
void QComboBox_QBaseInitStyleOption(const QComboBox* self, QStyleOptionComboBox* option);
int QComboBox_DevType(const QComboBox* self);
void QComboBox_OnDevType(const QComboBox* self, intptr_t slot);
int QComboBox_QBaseDevType(const QComboBox* self);
void QComboBox_SetVisible(QComboBox* self, bool visible);
void QComboBox_OnSetVisible(QComboBox* self, intptr_t slot);
void QComboBox_QBaseSetVisible(QComboBox* self, bool visible);
int QComboBox_HeightForWidth(const QComboBox* self, int param1);
void QComboBox_OnHeightForWidth(const QComboBox* self, intptr_t slot);
int QComboBox_QBaseHeightForWidth(const QComboBox* self, int param1);
bool QComboBox_HasHeightForWidth(const QComboBox* self);
void QComboBox_OnHasHeightForWidth(const QComboBox* self, intptr_t slot);
bool QComboBox_QBaseHasHeightForWidth(const QComboBox* self);
QPaintEngine* QComboBox_PaintEngine(const QComboBox* self);
void QComboBox_OnPaintEngine(const QComboBox* self, intptr_t slot);
QPaintEngine* QComboBox_QBasePaintEngine(const QComboBox* self);
void QComboBox_MouseDoubleClickEvent(QComboBox* self, QMouseEvent* event);
void QComboBox_OnMouseDoubleClickEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseMouseDoubleClickEvent(QComboBox* self, QMouseEvent* event);
void QComboBox_MouseMoveEvent(QComboBox* self, QMouseEvent* event);
void QComboBox_OnMouseMoveEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseMouseMoveEvent(QComboBox* self, QMouseEvent* event);
void QComboBox_EnterEvent(QComboBox* self, QEnterEvent* event);
void QComboBox_OnEnterEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseEnterEvent(QComboBox* self, QEnterEvent* event);
void QComboBox_LeaveEvent(QComboBox* self, QEvent* event);
void QComboBox_OnLeaveEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseLeaveEvent(QComboBox* self, QEvent* event);
void QComboBox_MoveEvent(QComboBox* self, QMoveEvent* event);
void QComboBox_OnMoveEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseMoveEvent(QComboBox* self, QMoveEvent* event);
void QComboBox_CloseEvent(QComboBox* self, QCloseEvent* event);
void QComboBox_OnCloseEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseCloseEvent(QComboBox* self, QCloseEvent* event);
void QComboBox_TabletEvent(QComboBox* self, QTabletEvent* event);
void QComboBox_OnTabletEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseTabletEvent(QComboBox* self, QTabletEvent* event);
void QComboBox_ActionEvent(QComboBox* self, QActionEvent* event);
void QComboBox_OnActionEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseActionEvent(QComboBox* self, QActionEvent* event);
void QComboBox_DragEnterEvent(QComboBox* self, QDragEnterEvent* event);
void QComboBox_OnDragEnterEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseDragEnterEvent(QComboBox* self, QDragEnterEvent* event);
void QComboBox_DragMoveEvent(QComboBox* self, QDragMoveEvent* event);
void QComboBox_OnDragMoveEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseDragMoveEvent(QComboBox* self, QDragMoveEvent* event);
void QComboBox_DragLeaveEvent(QComboBox* self, QDragLeaveEvent* event);
void QComboBox_OnDragLeaveEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseDragLeaveEvent(QComboBox* self, QDragLeaveEvent* event);
void QComboBox_DropEvent(QComboBox* self, QDropEvent* event);
void QComboBox_OnDropEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseDropEvent(QComboBox* self, QDropEvent* event);
bool QComboBox_NativeEvent(QComboBox* self, const libqt_string eventType, void* message, intptr_t* result);
void QComboBox_OnNativeEvent(QComboBox* self, intptr_t slot);
bool QComboBox_QBaseNativeEvent(QComboBox* self, const libqt_string eventType, void* message, intptr_t* result);
int QComboBox_Metric(const QComboBox* self, int param1);
void QComboBox_OnMetric(const QComboBox* self, intptr_t slot);
int QComboBox_QBaseMetric(const QComboBox* self, int param1);
void QComboBox_InitPainter(const QComboBox* self, QPainter* painter);
void QComboBox_OnInitPainter(const QComboBox* self, intptr_t slot);
void QComboBox_QBaseInitPainter(const QComboBox* self, QPainter* painter);
QPaintDevice* QComboBox_Redirected(const QComboBox* self, QPoint* offset);
void QComboBox_OnRedirected(const QComboBox* self, intptr_t slot);
QPaintDevice* QComboBox_QBaseRedirected(const QComboBox* self, QPoint* offset);
QPainter* QComboBox_SharedPainter(const QComboBox* self);
void QComboBox_OnSharedPainter(const QComboBox* self, intptr_t slot);
QPainter* QComboBox_QBaseSharedPainter(const QComboBox* self);
bool QComboBox_FocusNextPrevChild(QComboBox* self, bool next);
void QComboBox_OnFocusNextPrevChild(QComboBox* self, intptr_t slot);
bool QComboBox_QBaseFocusNextPrevChild(QComboBox* self, bool next);
bool QComboBox_EventFilter(QComboBox* self, QObject* watched, QEvent* event);
void QComboBox_OnEventFilter(QComboBox* self, intptr_t slot);
bool QComboBox_QBaseEventFilter(QComboBox* self, QObject* watched, QEvent* event);
void QComboBox_TimerEvent(QComboBox* self, QTimerEvent* event);
void QComboBox_OnTimerEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseTimerEvent(QComboBox* self, QTimerEvent* event);
void QComboBox_ChildEvent(QComboBox* self, QChildEvent* event);
void QComboBox_OnChildEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseChildEvent(QComboBox* self, QChildEvent* event);
void QComboBox_CustomEvent(QComboBox* self, QEvent* event);
void QComboBox_OnCustomEvent(QComboBox* self, intptr_t slot);
void QComboBox_QBaseCustomEvent(QComboBox* self, QEvent* event);
void QComboBox_ConnectNotify(QComboBox* self, const QMetaMethod* signal);
void QComboBox_OnConnectNotify(QComboBox* self, intptr_t slot);
void QComboBox_QBaseConnectNotify(QComboBox* self, const QMetaMethod* signal);
void QComboBox_DisconnectNotify(QComboBox* self, const QMetaMethod* signal);
void QComboBox_OnDisconnectNotify(QComboBox* self, intptr_t slot);
void QComboBox_QBaseDisconnectNotify(QComboBox* self, const QMetaMethod* signal);
void QComboBox_UpdateMicroFocus(QComboBox* self);
void QComboBox_OnUpdateMicroFocus(QComboBox* self, intptr_t slot);
void QComboBox_QBaseUpdateMicroFocus(QComboBox* self);
void QComboBox_Create(QComboBox* self);
void QComboBox_OnCreate(QComboBox* self, intptr_t slot);
void QComboBox_QBaseCreate(QComboBox* self);
void QComboBox_Destroy(QComboBox* self);
void QComboBox_OnDestroy(QComboBox* self, intptr_t slot);
void QComboBox_QBaseDestroy(QComboBox* self);
bool QComboBox_FocusNextChild(QComboBox* self);
void QComboBox_OnFocusNextChild(QComboBox* self, intptr_t slot);
bool QComboBox_QBaseFocusNextChild(QComboBox* self);
bool QComboBox_FocusPreviousChild(QComboBox* self);
void QComboBox_OnFocusPreviousChild(QComboBox* self, intptr_t slot);
bool QComboBox_QBaseFocusPreviousChild(QComboBox* self);
QObject* QComboBox_Sender(const QComboBox* self);
void QComboBox_OnSender(const QComboBox* self, intptr_t slot);
QObject* QComboBox_QBaseSender(const QComboBox* self);
int QComboBox_SenderSignalIndex(const QComboBox* self);
void QComboBox_OnSenderSignalIndex(const QComboBox* self, intptr_t slot);
int QComboBox_QBaseSenderSignalIndex(const QComboBox* self);
int QComboBox_Receivers(const QComboBox* self, const char* signal);
void QComboBox_OnReceivers(const QComboBox* self, intptr_t slot);
int QComboBox_QBaseReceivers(const QComboBox* self, const char* signal);
bool QComboBox_IsSignalConnected(const QComboBox* self, const QMetaMethod* signal);
void QComboBox_OnIsSignalConnected(const QComboBox* self, intptr_t slot);
bool QComboBox_QBaseIsSignalConnected(const QComboBox* self, const QMetaMethod* signal);
double QComboBox_GetDecodedMetricF(const QComboBox* self, int metricA, int metricB);
void QComboBox_OnGetDecodedMetricF(const QComboBox* self, intptr_t slot);
double QComboBox_QBaseGetDecodedMetricF(const QComboBox* self, int metricA, int metricB);
void QComboBox_Delete(QComboBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
